### ISSUE TITLE
Graphical summary of population models

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1]
A graphical summary plotting the size of the population as specified by the population models would be useful.

**Comment by champost** [comment]
do check out http://www.mabs.at/ewing/msms/popplanner.shtml, if I understand correctly it is somewhat in line with what you aim to do

**Comment by jeromekelleher** [comment]
Interesting, thanks @champost.

**Comment by jeromekelleher** [comment]
Version 0.3.0 makes a start on this issue by at least providing a textual debug output. However, graphical summaries would still be useful.

**Comment by jeromekelleher** [comment]
Comment from @agladstein over at the tzviz repo:

> As it sounds - create a figure of a demographic model. (e.g. like in momi https://momi2.readthedocs.io/en/latest/tutorial.html#Plotting-a-demography)

**Comment by jeromekelleher** [comment]
Going to close this - work is ongoing upstream to do this more generally.
