### ISSUE TITLE
[Docs] Add initial table of functions/classes to Python API section

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1003]
Inspired by the [Python docs](https://docs.python.org/3.5/library/functions.html), make some sort of table, short subsection listing the various functions and classes by usage. For example, all the Demographic events should be grouped together, and all the different simulation model classes grouped together.

Not sure how these can be best displayed, but the idea is to provide a single place where the user can see all the available functions and classes and where they can click on a link to get the precise documentation.

**Comment by jeromekelleher** [comment]
This should be closed by the new [quickref](https://tskit-dev.github.io/msprime-docs/main/quickref.html) section. Any objections?

**Comment by agladstein** [comment]
I think this can be closed. I think the table looks good.
But, will all the functions be linked in the docs? Some of them are linked now and some aren't. I assume that's just because not all the docs are complete yet.

**Comment by jeromekelleher** [comment]
OK, thanks @agladstein.

All the documented functions will be in the docs - not everything is part of the public API that we want to support. The top-level summary table should contain all the functions though, I think.

Closing this for now anyway, as the high-level point has been fixed.
