### ISSUE TITLE
Binary wheels

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1004]
Infrastructure for building binary wheels automatically is in the pipeline (https://github.com/tskit-dev/kastore/pull/118). I'm making this issue to track the progress here for msprime.

The extra complexity here is whether we can pull in GSL as part of the wheel (there's no real point in having the wheel if we can't). I'm hoping that we can use the version of GSL that's available in the manylinux Docker image (i.e., we ``yum install gsl-devel`` in there) and it'll all just work. It doesn't matter what version of GSL it is, anything should work unless it's truly prehistoric.

Assuming we can, how much of GSL do we bring in (i.e., is the software doing something clever and just pulling out the bits of libgsl that we're using, or is it just copying in libgsl and libgslcblas), and how big does this make our wheel?

**Comment by jeromekelleher** [comment]
I don't think we should bother trying to make binary wheels on Windows - it's not worth the effort since Windows users are almost certainly going to be using conda anyway.

OSX is pretty marginal whether it's worth bothering with. I would lean towards "no",  but if it's easy to do then there's no point in not doing it.

**Comment by grahamgower** [comment]
> Assuming we can, how much of GSL do we bring in (i.e., is the software doing something clever and just pulling out the bits of libgsl that we're using, or is it just copying in libgsl and libgslcblas), and how big does this make our wheel?

If you static link, it should bring in only what's used.

**Comment by castedo** [comment]
I'm getting ready to do a draft PR. I've done my first commit
https://github.com/castedo/msprime/commit/0b42c0e7e816113eaa55373d4eda6744161964e3
I have another commit to move container instructions from development.rst over into installation.rst.
And I plan to practice doing a rebase/squash for the first time before un-drafting the PR.

While doing all this, I couldn't help but ponder some high level questions.
Perhaps answering these questions and recording them into the wiki could be
useful in planning and making trade-offs and explaining decisions.

The question that came to my mind is:

How are msprime users split in terms of installation needs?

1) "Desktop User":
- using msprime in research
- running on Windows, Mac or Linux
- "research code" is _NOT_ tested/used on platforms other than the user's desktop
- ? likely running research code in a Jupyter notebook
- ? circa 2020, not knowledgable in running VMs or containers to run Linux software on Windows or Mac (but maybe in 2021/2020)

2) "Software Developer"
- software written by "developer" _IS_ tested/used on multiple platforms
- ? developers on Windows are not a target profile to support?
- ? can Mac developers be expected to developing within Linux containers?
- "developer" further trisected into
  a) "msprime developers" (changing msprime)
  b) "Python-only developers"
       - building on top of msprime and other Python packages
       - ? likely pip is preferred Python package manager ?
  c) "Multi-language developers"
      - building on top of msprime and other non-Python dependencies
      - ? likely system package managers are preferred (i.e. yum, apt-get)?

3) "Server Admin":
- running msprime on servers, say HPC
- ? happy for msprime to run within a container?

Let me know if you think consensus answers to these questions in this break down would be useful to be the wiki (or other planning area).

And I'm kind of curious to some answers regardless of whether or not they get recorded elsewhere.

**Comment by castedo** [comment]
Sorry! I commented in the wrong browser window! I meant to comment in #994! (I've moved the comment now)
