### ISSUE TITLE
[Docs] HTML demographydebugger formatting?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime#1008]
I wonder if someone could make the DemographyDebugger output in a Jupyter Notebook use html tables etc via _html_repr_, like @benjeffery did for tskit tables (https://github.com/tskit-dev/tskit/pull/514). It would make the demography docs look *much* nicer, and I guess it wouldn't be much work for someone who knows the expected DemographyDebugger output well (I don't, otherwise I might do this!)

**Comment by jeromekelleher** [comment]
Duplicate of #385.
