### ISSUE TITLE
Update Demography API to use tskit metadata schemas.

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime#1017]
I would like to be able to get the `species_name` for a population without having to use `json.loads`. I'm not sure how one passes a metadata schema into the `PopulationConfiguration` class, though? At the moment it's being called with `metadata={"species_name": node.name.strip()}`:

https://github.com/tskit-dev/msprime/blob/70961b716b0a6c379296c8cdf335f4252f1ab5ed/msprime/species_trees.py#L225

**Comment by jeromekelleher** [comment]
That's the plan all right. I'm going to use msprime as the first application of the schemas. We need to get tskit 0.3 released first though.

**Comment by jeromekelleher** [comment]
Depends on #1114
