### ISSUE TITLE
Add HKY mutation model

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1019]
Add a new mutation model to ``msprime.mutations`` to correspond to SeqGen's HKY model. I guess it should look  something like this:
```
class HKYModel(MutationModel):
    def __init__(self, ts_tv_ratio=1, base_frequencies=None):
        if base_frequences is None:
            # ACGT order
            base_frequencies = [0.25, 0.25, 0.25, 0.25]
         super( some parameters)
```

But, maybe class structure isn't the right way to do this and we should use static functions instead, like
```
class MutationModel:
     # stuff
     @classmethod
      def hky_model(cls, ts_tv_ratio=1, base_frequencies=None)
           # Do some stuff
```

We can use classes initially anyway and decide what the right structure is afterwards when we have a number of examples.

**Comment by GertjanBisschop** [comment]
Closed by #1032 .
