### ISSUE TITLE
Refactor verification.py script

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1026]
The ``verification.py`` has gotten very bloated and badly factored after years of piecemeal additions, and needs a thorough refactoring. Here's some ways it might be improved:

- currently there's no way to group tests. We'd like to be able to run the "ms" tests (ones where we call add_ms_instance), or dtwf_vs_coalescent tests separately, as each group of tests can take quite a long time now.

- The mechanism for adding registering tests is *very* clumsy. We should reduce the amount of boilerplate we have here and simplify how it's done.

- There's a lot of duplicated code for creating the base directory for outputs - we should have a mechanism to do this automatically.

- It would be **really** nice to be able to run these checks in parallel using concurrent.futures

- Also a good thing would be to have (perhaps) is an optional progress bar using tqdm (but see    run_dtwf_slim_comparison - this is a progress bar for just one simulation).

**Comment by jeromekelleher** [comment]
I think @saunack is having a look at this?

**Comment by saunack** [comment]
Issues #1056 and #1074 have covered all the requirements. #1035 , #1055 , #1068 and #1078  cover the changes made.

**Comment by jeromekelleher** [comment]
Looks good, @saunack. I'm going to make a final pass through to tidy up a few things and then close it.

You've done a great job here, thanks for your help! I've added your name to the author list over in https://github.com/tskit-dev/msprime-1.0-paper/issues/2
