### ISSUE TITLE
Is ``PopulationConfiguration.num_samples`` significant in DemographyDebugger?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1027]
Currently, the demography debugger has some quirky workarounds in the constructor to make sure that we can create a simulator instance, given the various different patterns of inputs. I think this can be simplified a bit, but want to check first.

Should sample sizes be seen as significant to the DemographyDebugger **at initialisation**, or should the ``num_samples`` arguments be ignored entirely (which seem the right thing, to me)? Methods like ``possible_lineage_locations`` take samples as input, which seems right.

@petrelharp, @apragsdale?

**Comment by petrelharp** [comment]
I'm not sure what you mean by 'ignored'? But everything I use the demography debugger for doesn't need num_samples. It could be a default to eg [coal rate trajectory](https://msprime.readthedocs.io/en/stable/api.html#msprime.DemographyDebugger.coalescence_rate_trajectory) but isn't.

**Comment by jeromekelleher** [comment]
I mean when a user provides ``PopulationConfiguration`` instances as input, it has a ``sample_size`` attribute, which has to be fiddled a little so we can create a simulator instance. The values are not (I think) used anywhere else in the debugger - where we need sample sizes, they are provided as input.

**Comment by petrelharp** [comment]
I think that's right, yes.

**Comment by jeromekelleher** [comment]
OK, I'll formalise this.

**Comment by jeromekelleher** [comment]
In #1025 this was formally moved to being ignored. The Demography object decouples sampling from description. Any methods that need samples, take them as a parameter.
