### ISSUE TITLE
Make "fake" release to fix OOA model on read the docs?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1034]
The [faulty OOA model](https://github.com/jeromekelleher/msprime-model-errors) is still live on the stable branch of [readthedocs](https://msprime.readthedocs.io/en/stable/tutorial.html#demography). We should fix it.

Readthedocs is quite singleminded about things, and I've learned it's easiest to just go with how it does things. The easiest way to get this model fixed, I think, is to

1. Create a ``hotfix`` branch off the previous release, and put in a commit fixing the model and adding the note. (Probably including a link to the repo above as well.)
2. Tag a release targetting the hotfix branch on GitHub, but make clear it's just a docs hotfix. Don't upload any artefacts to pypi.

If we do this, RTD *should* pick up the 0.7.5 tag and update the ``stable`` docs. Then, at least the docs will be correct until stable is replaced with 1.0, and our much-revamped docs.

Anyone object to this?

**Comment by benjeffery** [comment]
I'm almost certain you don't need to make a github release, just the tag.

**Comment by benjeffery** [comment]
Also, don't need a hotfix branch - just add an additional tag to the last release commit.

**Comment by jeromekelleher** [comment]
We need to add another commit though - this has to happen on a branch, right?

**Comment by benjeffery** [comment]
Yeah, I typed too fast.

**Comment by jeromekelleher** [comment]
Fixed.
