### ISSUE TITLE
SimpleBottleneck breaking change between 0.7.4 and current master

### ISSUE THREAD

**Issue by grahamgower** [tskit-dev/msprime#1040]
Stdpopsim uses SimpleBottleneck in a couple of unit tests, despite its undocumented status. One unit test now breaks when using git master, because the population parameter is not explicitly provided. Previously SimpleBottleneck had a `population=None` default, but this has been removed in the transition to being an attr class.

0.7.4
```
class SimpleBottleneck(DemographicEvent):
    # This is an unsupported/undocumented demographic event.
    def __init__(self, time, population=None, proportion=1.0, population_id=None)
        ...
```

current
```
# This is an unsupported/undocumented demographic event.
@attr.s
class SimpleBottleneck(DemographicEvent):
    population = attr.ib()
    proportion = attr.ib(default=1.0)
    ...
```

**Comment by jeromekelleher** [comment]
Thanks @grahamgower - we should fix this, unless the old semantics are obviously wrong and need to be changed.

**Comment by grahamgower** [comment]
I didn't take a close look at how stdpopsim unit tests are using this, but I daresay it's non-essential and could/should be removed from there anyway.

**Comment by grahamgower** [comment]
This will be fixed in stdpopsim.

It's also not clear to me that having a default population is a sensible thing at all. Defaulting to a bottleneck in all populations seems like a bad idea, because this is such an uncommon use case I reckon it will be more often used in error.
