### ISSUE TITLE
clarify recombination docs

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/msprime#1041]
@ndukler points out that the documentation about recombination rates talks about two columns, but the examples have four? A few more sentencs might help?

**Comment by mufernando** [comment]
One way to specify variable recombination rates is by reading HapMap files, which have four columns. The [docs](https://msprime.readthedocs.io/en/latest/api.html#msprime.RecombinationMap.read_hapmap) seem clear enough to me, as it specifies that only the second and third columns are used (starting positions and rate).

**Comment by petrelharp** [comment]
I agree! It looks good. I can't find anywhere else that talks about two columns in the documentation. Thanks, @mufernando!
