### ISSUE TITLE
[Demography] Export Demography description to "demography" format?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1047]
The [demography package](https://github.com/apragsdale/demography) is an incredibly useful debugging tool. Can we export our demography descriptions in a format that interoperates? It looks like demography uses networkx, so perhaps we could export a description in a low-level dict-of-dicts format that networkx could read in? I don't think we should have a dependency on networkx here, but exporting to a format that networkx can read would be no problem.

Is this feasible @apragsdale? This would be part of the larger refactor of the larger project to refactor the demography API (https://github.com/tskit-dev/msprime/projects/10), for which there's a few half finished PRs lying around (see #1028, #1025, #970)

**Comment by grahamgower** [comment]
I had a go at this already, but ended up just confusing myself. https://github.com/apragsdale/demography/pull/44

**Comment by jeromekelleher** [comment]
Very cool @grahamgower! It'd be really nice if we could extract some of the logic there and make it into an export function. Let's see what @apragsdale says - presumably he's done some of this already?

**Comment by apragsdale** [comment]
I'm not sure exactly what you mean, Jerome. Certainly with the upcoming demography API changes, I'm going to have to do some work to make the demography package compatible with the new ways of specifying splits and mass migrations.

Graham put in a bunch of really great work to take msprime demographic_events lists and turn them into the demography objects. I think there were some fundamental differences between how msprime specifies demography and how my networkx -> msprime functions translates the graphical demographies to msprime inputs, and that was hindering the progress on checking equivalency between models. But now I think those differences might be solved with the upcoming API differentiating between population splits and mass migration events. I'll have to think about it a bit more, but I'm more optimistic of clearing those hurdles now with the new API. What do you think, @grahamgower?

**Comment by grahamgower** [comment]
I reckon the code I wrote needs to be rewritten to use the demography debugger. That ought to be far simpler, and be compatible with both the existing and new APIs.

**Comment by apragsdale** [comment]
Things will need some reworking to also take into account the new PopulationSplit event, but I'm not sure what you mean by using the demography debugger. The debugger just contains the demographic events, population configurations, and a few other things needed to run the simulation. Do you mean the printed output? We'd want to avoid parsing text I think

**Comment by grahamgower** [comment]
See the `epochs` attribute of the DemographyDebugger class. It's a list of epochs, in which demographic parameters are fixed. This is what makes the printed output possible.
https://github.com/tskit-dev/msprime/blob/master/msprime/demography.py#L482

**Comment by apragsdale** [comment]
Right, that makes sense - I see what you mean.

All in all, I think the new PopulationSplit event will really help us here. Although we don't get around the difference that msprime reuses population indexes/labels, while the graph considers a parental population as distinct from the child populations. As you found, going from msprime -> networkx demography -> msprime loses the reuse of populations.

**Comment by grahamgower** [comment]
Yeah, it's hard to see how a one-to-one mapping could be constructed between the two formats.

**Comment by apragsdale** [comment]
It would take some refactoring on the `demography` side of things to allow A to split into A&B instead of always setting A into B and C, even if B is some continuation of A. It's certainly doable, but I'd want to see if we think it would be worthwhile before diving into that.

**Comment by grahamgower** [comment]
I guess you could do that by using an extra node attribute to signify the "continuation set" to which a node belongs?

**Comment by grahamgower** [comment]
Well I've had a lot more success using `msprime.DemographyDebugger` than trying to roll my own. See example dot graphs below. So, assuming this is the intended direction, how much goes into `msprime`, and how much into `demography`? (I haven't done the `demography` yet).

``` python3
import sys
import operator
import itertools
import collections

import numpy as np
import attr
import msprime
import networkx as nx
import stdpopsim


def attrs_equal(attr1, attr2):
    for key in ("start_size", "end_size", "growth_rate"):
        if not np.isclose(attr1[key], attr2[key]):
            return False
    for key in ("M_in", "M_out"):
        if not np.allclose(attr1[key], attr2[key]):
            return False
    return True


def get_descendent(node_attrs, node):
    epoch_j, pop_k = node
    a = epoch_j - 1
    while a >= 0:
        descendent = (a, pop_k)
        if descendent in node_attrs:
            break
        a -= 1
    if a < 0:
        descendent = None
    return descendent


def ddb_to_graph(ddb):
    """
    Convert ``ddb``, a DemographyDebugger instance, into a dict-of-dicts graph,
    compatible with networkx. Each node in the graph represents a single
    population over a time span in which the population's size and migration
    parameters do not change. Multiple nodes may exist for a given population,
    reflecting different demographic parameters in different time periods. Nodes
    are represented as (epoch_id, population_id) tuples, where epoch_id is an
    index into the ddb.epochs array.

    Returns a tuple of ``(dict_graph, node_attr)``, where ``dict_graph`` is a
    dict-of-dicts graph, and ``node_attr`` is a dict of node attributes.
    Node attributes reflect the population parameters in a
    given epoch: start_time, end_time, start_size, end_size, growth_rate,
                 M_in and M_out.
    If it exists, the demographic_event edge attribute is the MassMigration event
    corresponding to the edge.
    """
    graph = collections.defaultdict(dict)
    node_attrs = dict()
    merged_pops = set()
    for j, epoch in enumerate(ddb.epochs):
        for de in epoch.demographic_events:
            if isinstance(de, msprime.MassMigration):
                if de.proportion == 1:
                    merged_pops.add(de.source)
                source = get_descendent(node_attrs, (j, de.source))
                assert source is not None
                graph[(j, de.dest)].update({source: dict(demographic_event=de)})
        for k, pop in enumerate(epoch.populations):
            if k not in merged_pops:
                node = (j, k)
                node_attr = attr.asdict(pop)
                node_attr.update(
                        start_time=epoch.start_time, end_time=epoch.end_time,
                        M_in=epoch.migration_matrix[k, :],
                        M_out=epoch.migration_matrix[:, k])
                if j == 0:
                    node_attrs[node] = node_attr
                    continue
                descendent = get_descendent(node_attrs, node)
                if (descendent is not None and
                   (node in graph or
                       not attrs_equal(node_attr, node_attrs[descendent]))):
                    node_attrs[node] = node_attr
                    graph[node].update({descendent: {}})
                    # Extend the descendent's end_time up to the current node.
                    node_attrs[descendent].update(end_time=node_attr["start_time"])

        # TODO: Put something like this into the DemographyDebugger?
        for k in merged_pops:
            M_in = epoch.migration_matrix[k, :]
            M_out = epoch.migration_matrix[:, k]
            if not (all(M_in == 0) and all(M_out == 0)):
                raise RuntimeError(
                        f"Migrations exist for merged population {k}. "
                        "This is most likely an error in the demographic model.")

    return graph, node_attrs


def add_graphviz_attributes(dict_graph, node_attrs, population_labels):
    """
    Add attributes to a dict-of-dicts graph ``(dict_graph, node_attr)`` that
    are useful for visualising the graph using the graphviz dot format.
    """
    for node, node_attr in node_attrs.items():
        epoch_j, pop_k = node
        label = population_labels[pop_k]
        start_time = round(node_attr["start_time"])
        end_time = node_attr["end_time"]
        try:
            end_time = round(end_time)
        except OverflowError:
            pass
        growth_rate = node_attr["growth_rate"]
        start_size = round(node_attr["start_size"])
        end_size = round(node_attr["end_size"])
        M_in = {p: m for p, m in zip(population_labels, node_attr["M_in"]) if m > 0}
        M_out = {p: m for p, m in zip(population_labels, node_attr["M_out"]) if m > 0}

        label += f"\nt = ({start_time}, {end_time})"
        if growth_rate != 0:
            label += f"\nN(r={growth_rate:.3e}) = ({start_size}, {end_size})"
        else:
            label += f"\nN = ({start_size}, {end_size})"
        if len(M_in) > 0:
            label += f"\nM_in={M_in}"
        if len(M_out) > 0:
            label += f"\nM_out={M_out}"
        node_attr["label"] = label

    for from_node, to_dict in dict_graph.items():
        for to_node, edge_attr in to_dict.items():
            de = edge_attr.get("demographic_event")
            if de is not None:
                if isinstance(de, msprime.DemographicEvent) and de.proportion < 1:
                    edge_attr.update(
                            style="dotted", color="red",
                            label=f"{de.proportion:.3g}")


def ddb_graph_to_nx_graph(dict_graph, node_attrs):
    """
    Import a dict-of-dicts graph ``(dict_graph, node_attr)`` into networkx.
    """
    G = nx.DiGraph(dict_graph)
    assert nx.is_directed_acyclic_graph(G)
    for node, node_attr in node_attrs.items():
        G.nodes[node].update(**node_attr)
    return G


def print_dot(ddb, population_labels, file_=sys.stdout):
    """
    Print a graphviz dot file corresponding to the demography debugger ``ddb``.

    TODO: Write out the dot file ourselves, instead of depending on networkx.
    """
    dict_graph, node_attrs = ddb_to_graph(ddb)
    add_graphviz_attributes(dict_graph, node_attrs, population_labels)
    G = ddb_graph_to_nx_graph(dict_graph, node_attrs)
    A = nx.nx_agraph.to_agraph(G)
    # Place all nodes for a given epoch at the same height.
    for epoch_j, nodes in itertools.groupby(G.nodes, operator.itemgetter(0)):
        A.add_subgraph(list(nodes), rank="same")
    A.write(file_)


# mid = "OutOfAfrica_3G09"
mid = "AncientEurasia_9K19"
# mid = "PapuansOutOfAfrica_10J19"
model = stdpopsim.get_species("HomSap").get_demographic_model(mid)
ddb = model.get_demography_debugger()
population_labels = [pop.id for pop in model.populations]
print_dot(ddb, population_labels)
```

OutOfAfrica_3G09
![OutOfAfrica_3G09](https://user-images.githubusercontent.com/8665077/83357099-a8ad1e00-a36a-11ea-81e8-0577b4dfc88c.png)

AncientEurasia_9K19
![AncientEurasia_9K19](https://user-images.githubusercontent.com/8665077/83357097-a6e35a80-a36a-11ea-92e2-116393826adb.png)

PapuansOutOfAfrica_10J19
![PapuansOutOfAfrica_10J19](https://user-images.githubusercontent.com/8665077/83357100-a945b480-a36a-11ea-9957-5c3e9da1b9a3.png)

**Comment by jeromekelleher** [comment]
This looks great @grahamgower! I think the approach of using the DemographyDebugger is great - there's no point in trying to reason about this stuff again when the DDB has done it already.

A new method ``as_graph`` or ``to_graph`` that's your ``ddb_to_graph`` function above would be ideal, I think. If msprime can export a neutral graph format that other packages can understand, that would be ideal. The dict-of-dicts format seems like a good option.

**Comment by jeromekelleher** [comment]
I think we can close this, given upstream efforts @apragsdale, @grahamgower?

**Comment by grahamgower** [comment]
Yep.
