### ISSUE TITLE
Discourage population reuse in demography API?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1054]
Defining demographic models and interpreting the results is complicated by the fact that we reuse population IDs to mean different things at different times. Should we encourage users to define population models (and give an example in OOA) that explicitly defines and names all the ancestral populations? This would make interpretation of the tree sequence a lot easier later on, and I think make the models easier to interpret. This would remove a confusing asymmetry I think.

This would involve making the explicit event types require *new* populations PopulationSplit(ancestral_population, derived_populations)  - see #1013.

The extra populations would have some perf consequences in the current code, but it would be fairly easy change to get msprime to "ignore" empty populations (which it should do anyway, for large spatial models).

**Comment by jeromekelleher** [comment]
Ping @grahamgower, @apragsdale

**Comment by grahamgower** [comment]
At first glance, this seems like a good idea. But it will be more onerous to specify larger demographies. I guess there'll be on the order of 2*n population IDs for `n` extant populations.

I wonder if the nominal case should be to encourage users *not* to define models manually, but give them a tool to build a demography graphically, and have a machine readable model autogenerated. In this case it would make sense for all nodes in the demography graph to be assigned different msprime population IDs (in some nice deterministic way that makes it easy to write an inverse function).

**Comment by jeromekelleher** [comment]
Interesting idea @grahamgower.

**Comment by apragsdale** [comment]
I think I'd be more in favor of allowing the flexibility for the ancestral population to be either a new, unused population _or_ a continuation of one of the derived populations. You can imagine cases where both make sense historically (for example, in either some range expansion model or a model with island colonization from a mainland populations for the latter case).

**Comment by jeromekelleher** [comment]
I agree @apragsdale, we shouldn't be too rigid about it. But, I think PopulationSplit events should have that form ``PopulationSplit(ancestral, derived)`` where ancestral must be a new population and ``derived`` is a list that cannot contain ``ancestral``. We'll still keep the MassMigration events so it'll be fully general.

**Comment by apragsdale** [comment]
Right, we just want to makes sure we don't lose generality or flexibility in defining models. So I think as long as the MassMigration events still allow for a proportion of 1, we keep that flexibility.
