### ISSUE TITLE
API for mutation models

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1070]
We now have a number of different matrix mutation models, including amino acid models (#1065). The  current API isn't ideal, I think, and we want to review the API a little bit. This should mirror the structure used in the ancestry.py module for ancestry models as closely as possible. We should also allow for using strings for non-parametric models, same as the ``model`` argument to msprime.simulate.

**Comment by benjeffery** [comment]
Only one of the models (`GTR`) has an argument without a default (`relative_rates`) so can't be specified with a string. Is there a sensible default we can specify for that argument?

**Comment by jeromekelleher** [comment]
I think we're better off not providing a string shortcut for parametric models (same as we do for ancestry models). In this case, I think the sensible defaults would amount to one of the other models already defined, so it's a bit pointless (you'd only use this when you really want to specify your own model).
