### ISSUE TITLE
Feature request: add_mutations command for msp

### ISSUE THREAD

**Issue by winni2k** [tskit-dev/msprime#1075]
I would like to throw down N mutations randomly on a tree sequence. Is there a way I can currently do that with the tskit or msp CLI?

**Comment by jeromekelleher** [comment]
Why exactly N? Lots of people ask for this, but most of the time it's a much better idea to simulate with a given rate, and then randomly subset down to N sites (if you really do need exactly N)

**Comment by jeromekelleher** [comment]
But we can definitely add a ``msp mutate`` CLI that's an interface to the [mutate function](https://msprime.readthedocs.io/en/latest/api.html#msprime.mutate). The documentation for this is a bit out of date at the moment - we have all sorts of nice things for mutations in the pipeline.

**Comment by winni2k** [comment]
Right, downsample. That would work for me.

I can work on a PR for this if there isn't anybody to do it right now.

**Comment by winni2k** [comment]
I think the reason the exactly N question sprang into my head first is because I am trying to remain comparable with another analysis where the mutation rate was not reported, but the number of mutations was, as far as I can tell.

**Comment by jeromekelleher** [comment]
> I can work on a PR for this if there isn't anybody to do it right now.

That would be amazing, thanks Winni! FYI, this would get you on the [author list](https://github.com/tskit-dev/msprime-1.0-paper/issues/2) for the forthcoming 1.0 paper...

**Comment by winni2k** [comment]
Well, that certainly is quite some motivation. I'll see if I can budget some time over the next week then.
