### ISSUE TITLE
Add model argument to msp mutate CLI

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1077]
We added a CLI for mutate in #1076. This doesn't have any way to specify the model. Once #1070 is done as we have a way to create non-parametric models from strings like "HKY", etc, we can add a model argument here.

We should also think about whether we want to support the more complex parametric models (probably not?)

**Comment by jeromekelleher** [comment]
@winni2k, can we sign you up for this?

**Comment by winni2k** [comment]
Hehe, sure ;)

**Comment by jeromekelleher** [comment]
@winni2k, any update on when you might get to this?

**Comment by winni2k** [comment]
Thanks for the ping. I'll give it a shot this weekend.

**Comment by jeromekelleher** [comment]
@winni2k, hows this looking? We're going to feature freeze at the end of next week, so we need to get it done soon.

**Comment by winni2k** [comment]
Right-o. I'll sort this out tomorrow then.
________________________________
