### ISSUE TITLE
Script to compare performance with older versions of msprime

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1085]
We'd like to have some tooling to help spot performance regressions and tune performance. We want to make a script called ``performance.py`` that will run the same simulations on the current version of msprime and some older version(s) and plot the output. The plots should look somethink like [this one](https://github.com/tskit-dev/msprime/issues/852#issuecomment-578668968).

The way it should work is to make a venv (maybe using the [API](https://docs.python.org/3/library/venv.html#api)) for each version that we want to measure, including the current one. I guess the versions should be specified using strings that can be supplied to pip. Then, we install the version we're testing into this venv, and run the sims, recording the time and memory usage and outputting the results to a CSV file using pandas.

The interface will be split into "scenarios" using subcommands on the command line, so we'd have
```
python3 performance.py human-recombination-maps
```
which would run some [stdpopsim](https://stdpopsim.readthedocs.io/en/latest/) simulations for a human chromosome. We can add some command line options to this command to say which chromosomes we run, and what the largest sample size is, etc. (Stdpopsim uses msprime under the hood, so this is a handy way of running some large realistic simulations.

Another scenario we'd want is 
```
python3 performance.py hudson-recombination
```
which runs some large simulations with a constant recombination rate.

**Comment by benjeffery** [comment]
We've thought about doing something like this to detect performance regressions continuously. e.g. https://github.com/tskit-dev/tskit/issues/511 It would be great if this is organised so the same scenarios could be reused for that.

**Comment by jeromekelleher** [comment]
Closing this in favour of airspeed velocity (#1165)
