### ISSUE TITLE
Problems with XiGrowth test in verification.py

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1091]
There's some problems with XiGrowth test in verification.py as explained [here](https://github.com/tskit-dev/msprime/blob/master/verification.py#L2064).

@JereKoskela, I think you wrote this originally. Would you mind taking a look at seeing if it can be brought in line with the other tests please? Ideally, we'd like to split it up into qqplots for a handful of parameter combinations  - I think the big grid is overkill.

See the top of the verification.py file for details on the testing framework and how to run the tests. Any feedback on how to improve this would be appreciated, as you're the first developer to see the new framework.

**Comment by JereKoskela** [comment]
Happy to take a look. I'm sure I can shrink the number of parameter combinations significantly if I spend a little time picking out ones that give good coverage, and also tidy up the code while I'm at it.

**Comment by jeromekelleher** [comment]
Closed in #1096
