### ISSUE TITLE
Problems with DemographyDebugger verification tests

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1093]
There are two problems with the current DemographyDebugger [verification test](https://github.com/tskit-dev/msprime/blob/ef19606e2d62dd5c6601a46d584f0c3d74475b96/verification.py#L2700):

1. We're emitting a bunch of warnings. Is this because we the parameters we're putting in are bad, or we're doing division by zero in our calculations somewhere? If so, should we be catching these somewhere else?
2. The output of the test isn't particularly convincing. Why is the output banded like this? The text results don't look particularly close either.

![mean_coaltimes](https://user-images.githubusercontent.com/2664569/86611228-4917e300-bfa6-11ea-90ea-b2da054e97b6.png)

@apragsdale, did you write these originally, or was it someone else?

(The refactoring of the verification tests was done in #1086 - see the top of the file for documentation on how the tests are defined and how to run them)

**Comment by apragsdale** [comment]
This doesn't look familiar to me - pretty sure I didn't write them. But looks like the banding is because there are 8 replicates and each replicate will have a single mean calculated coalescent time? Hard to tell if it looks not that close just by chance because of running few replicates.

**Comment by jeromekelleher** [comment]
Thanks @apragsdale. Hmm, @petrelharp, do you have any idea who wrote these? Maybe I should just do the git archeology..

**Comment by petrelharp** [comment]
I haven't written anything in verification.py. It might have been Jared Galloway, who implemented the mean coaltime method, but I'm not tagging him since he's working on other things.

**Comment by petrelharp** [comment]
I'm taking a look.

**Comment by jeromekelleher** [comment]
Closed in #1094
