### ISSUE TITLE
Change to discrete coordinates by default?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1116]
Currently the discrete parameter defaults to False, which is done for compatibility reasons. However, this is probably the wrong choice for most of the models that people might specify, and will probably lead to bugs in people's code. There's really no point in specifying a JukesCantor model without specifying  ``discrete=True`` at the same time.

Perhaps this would be confusing/hard to document though? Perhaps we should default ``discrete=True``, and accept the (probably very minor) breakage that ensues? I don't imagine many people are using ``msprime.mutate`` yet and this is probably our only chance to git it sensible defaults.

**Comment by jeromekelleher** [comment]
Of course, we could argue that ``msprime.simulate`` should default to ``discrete_coordinates=True`` also (#1115). Let's see, what would break? Not a whole lot, actually, except simulations where L=1 and recombination rate != 0. This is an obvious case here discrete is wrong. A more subtle case is when L is small and recombination rate is large - the difference between the discrete and continuous cases will be very large then. I guess what we could do is see if the value of L * recombination_rate and if this is greater than some threshold **and** discrete_coordinates is left to it's default value we emit a warning. If the user explicitly sets discrete_coordinates=False, then we shut up and do what we're told, regardless.

**Comment by jeromekelleher** [comment]
The intuition here is that for a simulation like
```
ts = msprime.simulate(10, Ne=10**4, length=10**8, recombination_rate=1e-8)
```
there's basically no difference between discrete and continuous coordinates, and since most people want discrete coordinates we should use them by default.

On the other hand, if some has a simulation like
```
ts = msprime.simulate(10, length=10, recombination_rate=100)
```
then using discrete coordinates would certainly give different answers. In this case, we would emit a warning like
```
Warning! Since 1.0, msprime uses discrete coordinates by default and the simulation that you are running will have quite different results when discrete and continuous coordinates. If this is an existing simulation developed using older versions of msprime, you should set ``discrete_coordinates=False`` to ensure that that the same type of simulation is run. If you really want to run this simulation with discrete coordinates, set ``discrete_coordinates=True`` to make this warning go away.
```

**Comment by petrelharp** [comment]
Ooooo, I think this is just the right think to do (default to discrete, emit the warning). For when to warn, maybe: if length is less than 1000 and recomb rate is positive?

This means we should go through the docs and check/modify all the places that `simulate()` is used.

**Comment by jeromekelleher** [comment]
Excellent! Let's get #1115 merged so and I'll work up a proposal.

**Comment by jeromekelleher** [comment]
This has been decided: ``sim_ancestry`` simulates a discrete genome by default and ``simulate`` stays as-is.
