### ISSUE TITLE
New top-level function for 1.0

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1119]
@castedo came up with an intriguing idea for dealing with some of our most pronounced compatibility headaches: make a new top level function to use instead of ``simulate``: https://github.com/tskit-dev/msprime/pull/1117#issuecomment-672263768

The advantage is that we can then rethink a whole bunch of things that we've been constrained on because of backwards compatibility. Some thoughts:

- I think this function should *only* simulate ancestry and there should be no options for mutations. We can use the ``mutate`` function for that. Thus, I don't like the original suggestion of "sim" as this doesn't get across the idea that we're just simulating the trees. So, ``sim_trees``, ``sim_ancesty``? I would be nice if there was a natural pairing with ``mutate``, but it's not quite the same thing (that's mutating an input tree sequence, whereas this is magicing a new tree sequence topology out of thin air). Ideas welcome!

- It should simulate discrete genomes by default (#1117)

- It should have a ``ploidy`` argument and create individuals. The sample size argument should be the number of **individuals**, and ploidy should default to 1. (Thus, unless you specify a ploidy explicitly, you still get n samples in your tree sequence.)

There's basically a bunch of things we could fix by doing this, and we could then keep the ``simulate`` function backwardly compatible indefinitely. It would be a lot of work, but there's a lot of work to do anyway, so might as well do what we think will be the most useful to the most people.

**Comment by jeromekelleher** [comment]
Ping @tskit-dev/all for thoughts and opinions.

**Comment by benjeffery** [comment]
In general I like the idea. Is the idea that `simulate` would then call this new function with arguments that emulated the old behaviour? Seems to be the cleanest way that removes the need for two code paths.

**Comment by castedo** [comment]
Regarding function name ideas @jeromekelleher ...

If one likes to coin words (it's so much fun!), I can suggest `arborate`. It looks like an English word, suggests a pronunciation, and most readers will intuit the meaning based on the root 'arbor', I think.

Technically, it _is_ an existing word ... in Italian: the conjugation of
https://en.wiktionary.org/wiki/arborare
which means 'to plant with trees' in Italian. The related Italian adjective
https://en.wiktionary.org/wiki/arborato
means 'planted/lined with trees'.

`arborate` also has a certain aesthetically pleasing symmetry with 'mutate' and `simulate`.  It can optionally be extended to 'arboration' to say things like the 'Arboration API' that pairs with the 'Mutation API'.

If one wants to not coin words, there are possibilities
* `farm`
* `sprout`
* `forestate`
* `germinate`
but those sound way more boring that to *arborate*!

**Comment by jeromekelleher** [comment]
Haha, these are *great* ideas for words to conjure up tree-making @castedo, I love it!

After thinking about it a bit, another approach we might take is to make a new version of ``mutate`` as well so that we can have a nice symmetric pair of top-level functions. Some possibilities:
- ``sim_trees`` and ``sim_mutations``
- ``sim_ancestry`` and ``sim_mutations``

I think I like the ``sim_ancestry`` and ``sim_mutations`` pair. It's very clear what the two functions *do* then, and they're not a lot more typing. This would lead to two very clear documentation sections too (#996) - "Simulating ancestry" and "Simulating mutations".

**Comment by hyanwong** [comment]
I like `sim_ancestry` and `sim_mutations` too. However, I do think many people might like to do both in one go, as they do currently with `simulate`. Would we keep `simulate` as the recommended way of doing this, and e.g. keep it in the docs, or just leave it in for backwards-compatibility (and coin a new `sim_ancestry_plus_mutations` function)?

**Comment by jeromekelleher** [comment]
> I do think many people might like to do both in one go, as they do currently with simulate. Would we keep simulate as the recommended way of doing this, and e.g. keep it in the docs, or just leave it in for backwards-compatibility (and coin a new sim_ancestry_plus_mutations function)?

Well, I kinda like the way that it emphasises these are two distinct tasks. It's not so bad to type:
```python
ts = msprime.sim_mutations(
     msprime.sim_ancestry(10, length=1000),
     rate=1)
```
It's a fair point, though.

I guess people can always use ``simulate`` for this, if they want to. It will exist indefinitely.

**Comment by hyanwong** [comment]
Also, we presumably would like to know whether the ancestry that was simulated via `sim_ancestry` was done in continuous coordinate space, and if so, by default put the mutations in continuous space too. And likewise for discontinuous ("finite sites") space. So we need to [distinguish](https://github.com/tskit-dev/tskit/issues/146#issuecomment-527195817) somehow between a finite_recombination_position tree sequence, and a continuous one.

**Comment by jeromekelleher** [comment]
> Also, we presumably would like to know whether the ancestry that was simulated via sim_ancestry was done in continuous coordinate space, and if so, by default put the mutations in continuous space too. And likewise for discontinuous ("finite sites") space. So we need to distinguish somehow between a finite_recombination_position tree sequence, and a continuous one.

I disagree with this. We shouldn't infer what we think people might want to do based on the input tree sequence for ``sim_mutations``. The default will be to have discrete genomes in both cases, and with continuous being an option. There really isn't any good use for continuous coordinates, it's arguable whether we should even offer it for the new functions.

**Comment by hyanwong** [comment]
> The default will be to have discrete genomes in both cases, and with continuous being an option. 

Yes, on second thoughts, I think if the default for both is discrete, I think that would be fine. I brought it up because I thought that we had decided to make the "continuous_genome" function operate on both recombination *and* mutation, when they were in one function, so this seems like a slight change from the behaviour we had decided upon previously.

**Comment by hyanwong** [comment]
Also, I would prefer the argument to `sim_mutations` to be `mutation_rate` rather than just `rate`, which would reflect the (presumable) parameter for `sim_ancestry(recombination_rate=XXX)`. If we just use `rate` as the parameter name, then in a combined call like @jeromekelleher describes above, it would be a bit too easy to get mixed up as to which parameter applies to which function.

It also matches the params to the current `simulate()` method, which is helpful, IMO.

**Comment by hyanwong** [comment]
> I guess people can always use `simulate` for this, if they want to. It will exist indefinitely.

>  There really isn't any good use for continuous coordinates, it's arguable whether we should even offer it for the new functions.

So would we keep backwards compatibility by leaving `simulate()` as defaulting to continuous genomic coordinates, and only have discrete as the default for the new functions? Or break backwards compatibility and allow `simulate()` with no defaults to be used as a shorthand for `sim_ancestry + sim_mutations` in discrete coords?

**Comment by jeromekelleher** [comment]
Good points, thanks @hyanwong. One thing to note - if we do decide to do this, we should roll the interface for ``simulate`` back to what it was for 0.7.4, so there's less for us to maintain going forward.

**Comment by molpopgen** [comment]
> > Also, we presumably would like to know whether the ancestry that was simulated via sim_ancestry was done in continuous coordinate space, and if so, by default put the mutations in continuous space too. And likewise for discontinuous ("finite sites") space. So we need to distinguish somehow between a finite_recombination_position tree sequence, and a continuous one.
> 
> I disagree with this. We shouldn't infer what we think people might want to do based on the input tree sequence for ``sim_mutations``. The default will be to have discrete genomes in both cases, and with continuous being an option. There really isn't any good use for continuous coordinates, it's arguable whether we should even offer it for the new functions.

Continuous coordinates for mutations are very useful for applications using infinite alleles models.  Taking advantage of multiple mutations in the "same site", you can do things like generate very complex microsatellite mutation models.

**Comment by bhaller** [comment]
> Continuous coordinates for mutations are very useful for applications using infinite alleles models. Taking advantage of multiple mutations in the "same site", you can do things like generate very complex microsatellite mutation models.

This can be done with "stacked" mutations at discrete coordinates, too, of course, as SLiM does.  No doubt there are tradeoffs and advantages/disadvantages to both approaches.  :->

**Comment by petrelharp** [comment]
I think it would be a shame to deprecate `simulate`, since it's the natural place for a new user sho is looking to "simulate" to start. And, by default, `simulate` does the standard coalescent with infinite-sites mutation, which is a fine thing to start playing around with. A note saying "For finer control, and to simulate more realistic genomes, use sim_ancestry and mutate (or whatever)" would suffice.

I'm kinda liking `sim_ancestry` and `sim_mutations` (although "arborate/mutate" is pretty great).

**Comment by jeromekelleher** [comment]
I like @petrelharp's thinking here. It'll be a little bit confusing as the defaults for ``sim_ancestry`` and ``simulate`` will be different, but hey, nothing's perfect. So, we have three functions - ``simulate`` which does a bit of everything with simple defaults, and ``sim_ancestry`` and ``sim_mutations`` which give more functionality.

I think we *can* deprecate ``mutate`` though, and encourage users to move over the ``sim_mutations``, as they'll basically be the same and I don't think very many people are using ``mutate`` anyhow.

**Comment by agladstein** [comment]
> I think we can deprecate `mutate` though, and encourage users to move over the `sim_mutations`

so, would you be able to use `simulate` and then `sim_mutations` on top of that tree?

**Comment by petrelharp** [comment]
> so, would you be able to use simulate and then sim_mutations on top of that tree?

Yes, I think - `simulate` would stay as-is, and `sim_mutations` would be (basically) `mutate`.

**Comment by jeromekelleher** [comment]
This can be closed now as we've made the basic decision(s).
