### ISSUE TITLE
C structures refactoring

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1121]
There's a number of long-standing refactoring issues noted at the top of [msprime.h](https://github.com/tskit-dev/msprime/blob/master/lib/msprime.h#L66).

- [ ] Get rid of the population_id_t, label_id_t typedefs and use tsk_id_t everywhere instead.
- [ ] Change segment_t.population_id to segment_t.population
- [ ] Change node_mapping_t.left to node_mapping_t.position.
- [ ] Change sweep_t.locus to sweep_t.position

This would be a good issue for someone looking to get familiar with the C code.

**Comment by jeromekelleher** [comment]
@castedo, I thought this might be a good place to start with getting to know the code base? (But, make sure that #920 is merged before starting on it!)

**Comment by castedo** [comment]
@jeromekelleher This does look like good placed to start, thanks! First, I'm going to get myself setup to compile and run unit tests. I'm assuming the normal thing for me to do now is assign this to myself now (expressing a plan for me to do this).

After programming in C++ so much it will be interesting to see which C++ features were missed or not.

**Comment by jeromekelleher** [comment]
Great, thanks @castedo! The msprime [dev docs](https://msprime.readthedocs.io/en/latest/development.html) and [tskit dev docs](https://tskit.readthedocs.io/en/latest/development.html) should help get you up and running. There might be some old stuff in the msprime docs, so if you see any inconsistencies, please do open an issue.

> I'm assuming the normal thing for me to do now is assign this to myself now (expressing a plan for me to do this).

Yes, perfect.

**Comment by castedo** [comment]
I see five other structs that were using "population_id_t population_id" as a data member like segment_t, namely:
* sample_t
* sampling_event_t
* population_parameters_change_t
* simple_bottleneck_t
* instantaneous_bottleneck_t

I'm assuming you want those changed to for the same reason as segment_t.

**Comment by castedo** [comment]
So I've got this pretty much wrapped I think, except some permission issues, can you just run these lines with your permissions and then we should be aaaaaaaall set.
```
git@github.com:tskit-dev/msprime.git
cd msprime/lib
sed -i 's/population_id_t/tsk_id_t/g' *.c *.h
sed -i 's/label_id_t/tsk_id_t/g' *.c *.h
sed -i 's/population_id/poulation/g' *.c *.h
sed -i 's/left/position/g' *.c *.h
sed -i 's/locus/position/g' *.c *.h
git commit -m "no problems here"
git push -f
```
;-)

**Comment by jeromekelleher** [comment]
Thanks @castedo! You should run this though and make a PR - get git-credit for your hard work!

**Comment by castedo** [comment]
And I assume you also want
typedef tsk_id_t node_id_t;
typedef tsk_id_t mutation_id_t;
typedef tsk_id_t site_id_t;
replaced/removed like population_id_t, label_id_t.

**Comment by castedo** [comment]
OK I've made PR #1150 
Got unit tests passing with newly compiled C extension.
