### ISSUE TITLE
Split up C unit tests

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1122]
The C unit tests are all currently in one file. Split this up into (say) three files, ``test_likelihood``, ``test_ancestry``, and ``test_mutations``. We can copy some of the code from tskit's [test_main.c](https://github.com/tskit-dev/tskit/blob/master/c/tests/testlib.c) to avoid repeating all the CUnit boilerplate in each file.

This is a good introduction to the C code (see also #1211 and #1084)

**Comment by castedo** [comment]
msprime/docs/development.rst needs updating to reflect the recent new improvement by @nspope (splitting up the C unit tests). The dev docs still reference running `./build/tests` and `./build/tests test_fenwick` so those lines are now out of date. This is in the section C Library > Unit Tests.
Perhaps we still want a simple script `./build/tests` that runs all the tests?

**Comment by jeromekelleher** [comment]
Good spot, thanks @castedo.

> Perhaps we still want a simple script ./build/tests that runs all the tests?

Running ``ninja -C build test`` does this, so we'd be better off documenting this useful trick.

**Comment by castedo** [comment]
or `find ./build/test_* -type f -executable | bash` ;-)
