### ISSUE TITLE
Odd behaviour when all samples historic

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime#1123]
When I run an msprime simulation with *all* historical samples, I get no edges:

```
samples = [msprime.Sample(population=0, time=t) for t in (1e-6, 1e-6, 1e-6, 1e-7)]
ts = msprime.simulate(samples=samples, recombination_rate=4, mutation_rate=10, random_seed=123)
ts.num_edges
> 0
```

This seems pretty counterintuitive to me. Is this a bug?

**Comment by petrelharp** [comment]
Good spotting! I saw it first, though: this is #983. ;)

**Comment by hyanwong** [comment]
Oops - should have checked first, sorry!

**Comment by petrelharp** [comment]
hah, np - I had a vague memory that *someone* had reported this... no wonder I remembered, since that someone was me.

**Comment by hyanwong** [comment]
Yeah, I do that all the time: something needs reporting, I'll go and look it up, and find that I already reported it 6 months ago, and forgot.
