### ISSUE TITLE
population sizes can't be zero, so positive sizes are used where they don't make sense

### ISSUE THREAD

**Issue by grahamgower** [tskit-dev/msprime#1125]
Consider a three population model, `(0, (1, 2))`, where `0` is the ancestor of `1` and `2`. Furthermore, we have that `0` goes extinct at some time `T`, and `1` and `2` pop into existance at this time.

The typical way of describing this model is as follows.
```python
import msprime

N = 1000
T = 500
population_configurations = [
    msprime.PopulationConfiguration(initial_size=N),
    msprime.PopulationConfiguration(initial_size=N),
    msprime.PopulationConfiguration(initial_size=N),
]
demographic_events = [
    msprime.MassMigration(T, source=1, dest=0),
    msprime.MassMigration(T, source=2, dest=0),
]

ddb = msprime.DemographyDebugger(
    population_configurations=population_configurations,
    demographic_events=demographic_events,
)
ddb.print_history()
```
Which results in the following output:
```
Model =  hudson(reference_size=1)
=============================
Epoch: 0 -- 500.0 generations
=============================
     start     end      growth_rate |     0        1        2
   -------- --------       -------- | -------- -------- --------
0 |  1e+03    1e+03               0 |     0        0        0
1 |  1e+03    1e+03               0 |     0        0        0
2 |  1e+03    1e+03               0 |     0        0        0

Events @ generation 500.0
   - Mass migration: Lineages moved with probability 1.0 backwards in time with source 1 & dest 0
                     (equivalent to migration from 0 to 1 forwards in time)
   - Mass migration: Lineages moved with probability 1.0 backwards in time with source 2 & dest 0
                     (equivalent to migration from 0 to 2 forwards in time)
===============================
Epoch: 500.0 -- inf generations
===============================
     start     end      growth_rate |     0        1        2
   -------- --------       -------- | -------- -------- --------
0 |  1e+03    1e+03               0 |     0        0        0
1 |  1e+03    1e+03               0 |     0        0        0
2 |  1e+03    1e+03               0 |     0        0        0
```

But I would argue that the population sizes should be zero outside the epochs where the populations exist. This would be a more accurate representation of the demograpy (but neither `PopulationConfiguration` nor `PopulationParametersChange` permit `initial_size=0`):
```
N = 1000
T = 500
population_configurations = [
    msprime.PopulationConfiguration(initial_size=0),
    msprime.PopulationConfiguration(initial_size=N),
    msprime.PopulationConfiguration(initial_size=N),
]
demographic_events = [
    msprime.PopulationParametersChange(T, initial_size=N, population_id=0),
    msprime.MassMigration(T, source=1, dest=0),
    msprime.MassMigration(T, source=2, dest=0),
    msprime.PopulationParametersChange(T, initial_size=0, population_id=1),
    msprime.PopulationParametersChange(T, initial_size=0, population_id=2),
]
```

A possible simpler alternative would be to have `PopulationConfiguration` and `PopulationParametersChange` accept an `enable` parameter that defaults to `True`?

**Comment by jeromekelleher** [comment]
We could easily allow PopulationConfiguration and PopulationParametersChange accept 0 as input - I think it's just a filter to try and prevent errors. I'd be surprised if this was more than just making a few checks less stringent.

I can't imagine it breaking anyone's code if we allow zero population sizes now - would people really depend on ValueErrors being raised for a zero population size? Since it's 1.0, I think we can make this change.

**Comment by jeromekelleher** [comment]
Unless anyone objects?

**Comment by petrelharp** [comment]
Sounds good. This could help catch errors (like not turning off migration), since if a lineage is in a zero-size population that it's not supposed to be in, it will produce an error. But it might be hard to make those errors be very interpretable...

**Comment by grahamgower** [comment]
There are only a few checks that prevent `initial_size=0`, so I disabled them (will submit a pr after #920 goes in). Calling simulate() seems to work (at least, it gives a result without error---I didn't look at the trees to see if they're reliable). If I try to sample from a population with zero size, a not unreasonable error is produced:

> _msprime.LibraryError: The simulation model supplied resulted in a parent node having a time value <= to its child. This can occur either as a result of multiple bottlenecks happening at the same time or because of numerical imprecision with very small population sizes.

Unfortunately, asking for migration to or from a population with zero size doesn't produce an error. But presumably this has no practical side effect, as no sample will have ancestry in the population while its size is zero.

**Comment by petrelharp** [comment]
> Unfortunately, asking for migration to or from a population with zero size doesn't produce an error. But presumably this has no practical side effect, as no sample will have ancestry in the population while its size is zero.

Gee, I thought at least if there were two or more lineages in a population of zero size, there'd be an error due to the infinite coalescence rate?

**Comment by grahamgower** [comment]
I suppose the lineages don't get created? Probably you could provoke some issues by "turning off" a population without merging it though!

**Comment by jeromekelleher** [comment]
Sound good, thanks @grahamgower, looking forward to the PR.
