### ISSUE TITLE
Document ploidy values for multiple merger models

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1132]
#1128 added support for different ploidy levels to the multiple merger models. Document the differences between them - I think the main difference is between ploidy=1 and ploidy>1. Ping @TPPSellinger and @JereKoskela

**Comment by JereKoskela** [comment]
Thanks @jeromekelleher. I'll sort this out and update the multiple merger tutorial once we have the `sim_ancestry` interface.

**Comment by TPPSellinger** [comment]
Talking about Multiple merger tutorial, should we put the command lines showing how to use and compare the three model (Kingman, Dirac and Beta) ? I mean Kingman with Ne=10^4 equivalent to dirac with Ne=200  and c=0 which tends to Beta (with alpha close to 2) with Ne=4*complex_formula(Ne_Kingman, alpha) ?

**Comment by JereKoskela** [comment]
I'm resigned to the fact that I'll never remember to include this in the PR directly.

Closed in #1151.
