### ISSUE TITLE
Add verification code for varying ploidy levels in multiple merger models.

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1137]
See also #1132 

In #1128 we added support for ploidy levels in multiple merger models. These need verification tests.

Ping @JereKoskela, @TPPSellinger

**Comment by JereKoskela** [comment]
@TPPSellinger, are you happy to try to put together an SFS test for haploid models now that we have access to the `sim_ancestry` function with its `ploidy` argument as per #1134?

I'll update all of the other multiple merger tests (Mutation vs Recombination, Dirac vs Hudson, and the growth rate tests) in verification.py to cover the haploid case in the mean time. That won't be much different to the minor tweaks I already made when building the multiple merger ploidy infrastructure.

Once everything demonstrably works, we can look at documentation.

**Comment by TPPSellinger** [comment]
Yes sure I will try to implement the test (today if possible). Thanks for updating all the other tests and putting this together @JereKoskela

**Comment by TPPSellinger** [comment]
I  the simulator of Bjarki and have the SFS for the beta, I will do PR tomorrow morning. But we have a small problem. For the dirac there seem to be no c parameter, which means no kingman component according to him. I'm not quite sure on how to understand this, he explained me it should be equivalent to c=0 in msprime. But it's not so intuitive for me. Any insight about this @JereKoskela ?

**Comment by JereKoskela** [comment]
> I have the simulator of Bjarki and have the SFS for the beta, I will do PR tomorrow morning. But we have a small problem. For the dirac there seem to be no c parameter, which means no kingman component according to him. I'm not quite sure on how to understand this, he explained me it should be equivalent to c=0 in msprime.

I haven't looked at his code, but from the description, it sounds like he has no Kingman component, and a Dirac component with weight 1. We have a Kingman component with weight 1, and a Dirac component with weight `c`. If that's right, then the two should have the same normalised SFS when our `c` goes to infinity.

Could you try plugging in a few very large values of `c` and check if that looks plausible? If not, I can try to do some digging too.

**Comment by TPPSellinger** [comment]
Okay, I will plug very high value of c and let you know what results look like.

**Comment by TPPSellinger** [comment]
All results looks good. I will do PR now. Thanks for all the help @JereKoskela .

**Comment by JereKoskela** [comment]
I'll close this in light of #1141 and #1148. We can reopen if we need further testing at some point.
