### ISSUE TITLE
requirements/readthedocs.txt missing sphinx_rtd_theme

### ISSUE THREAD

**Issue by castedo** [tskit-dev/msprime#1145]
In building a minimal container image that can make the msprime docs, I call
```
pip3 install -r requirements/readthedocs.txt
```
but results in:
```
(ubuntu-18.04-pip)castedo@fire:~/shr/src/msprime/docs$ make
python3 -m sphinx -b html -d _build/doctrees  -W . _build/html
Running Sphinx v3.2.1
loading pickled environment... failed
failed: build environment version not current

Theme error:
sphinx_rtd_theme is no longer a hard dependency since version 1.4.0. Please install it manually.(pip install sphinx_rtd_theme)
Makefile:52: recipe for target 'html' failed
make: *** [html] Error 2
```
I'm in the process of committing the full Dockerfile to `tskit-dev/containers` that shows all the details.

Adding `sphinx_rtd_theme` to `requirements/readthedocs.txt` fixes the problem.

Feel free to assign to me to fix.

**Comment by jeromekelleher** [comment]
sounds good, thanks @castedo. The reason we left it out is because it's included automatically on read the docs, but I'd imagine there's no harm in specifying it as part of the requirements there.
