### ISSUE TITLE
Unexpected behaviour of msprime.mutate() when specifying start and end time

### ISSUE THREAD

**Issue by simonhmartin** [tskit-dev/msprime#1154]
Hi Jerome et al.
I've encountered an odd behaviour using `mutate()` when `start_time` and/or `end_time` are given.

Using the same `random_seed`, I would expect that you would always get a subset of all possible mutations if you constrain the time intervals. But that is not what I see:

```
>>> ts = msprime.simulate(2, random_seed=1)
>>> 
>>> ts1 = msprime.mutate(ts, rate=2, random_seed = 1)
>>> [v.position for v in ts1.variants()]
[0.12812444777227938, 0.23608897626399994, 0.39658072614111006, 0.3967674686573446, 0.5388167318888009, 0.9990405153948814]
>>> 
>>> ts2 = msprime.mutate(ts, rate=2, start_time=0, end_time=1, random_seed = 1)
>>> [v.position for v in ts2.variants()]
[0.12812444777227938, 0.23608897626399994, 0.39658072614111006, 0.66974604036659, 0.9990405153948814]
```
Here, the second last vaiant in `ts2` is not present in `ts1`.

If I constrain the intervals eve further, things get stranger:
```
>>> ts3 = msprime.mutate(ts, rate=2, start_time=0, end_time=0.5, random_seed = 1)
>>> [v.position for v in ts3.variants()]
[0.12812444777227938, 0.23608897626399994, 0.9325573612004519]
>>> 
>>> ts4 = msprime.mutate(ts, rate=2, start_time=0.5, end_time=1, random_seed = 1)
>>> [v.position for v in ts4.variants()]
[0.12812444777227938, 0.23608897626399994, 0.9325573612004519]
```
Here using two non-overlapping intervals both result in the same three mutations.

Am I missing something or is this a bug?

Thanks!
Simon

**Comment by jeromekelleher** [comment]
Sorry for the slow reply Simon, I didn't see this until just now. So, to be clear, are you imagining the semantics here to be that ``msprime.mutate`` returns something like (psuedocode):
```
all_mutations = msprime.mutate(...) # call without start_time and end_time
# Now filter out all the mutations that aren't in the window
mutations = [mutation for mutation in all_mutations start_time <= mutation.time < end_time]
```

If so, then that's not how it works I'm afraid - we don't actually simulate the stuff outside the required bounds and so we end up on a different random trajectory.

**Comment by simonhmartin** [comment]
Thanks for the explanation. Is there any way to achieve what your pseudocode is doing?

**Comment by jeromekelleher** [comment]
Not right now I'm afraid @simonhmartin as we don't have a ``time`` attribute on mutations (yet - see #977). You could do something  similar by filtering out based on node times in the tree, but it wouldn't be very precise.

What are you trying to do here?

**Comment by simonhmartin** [comment]
Ok, thanks.
What I'm trying to do is compare the full sfs to one in which mutations are restricted to the past. I am able to do so, but when I do  `SFS_full - SFS_restricted`, some of the values can end up negative, due to stochastic noise, which I would ideally like to avoid. Does that make sense?

**Comment by jeromekelleher** [comment]
Hmm, not sure we can do this without having mutation times.

**Comment by simonhmartin** [comment]
No worries. At least visually the noise can be minimised by just increasing the number of reps.
