### ISSUE TITLE
dependency requirements

### ISSUE THREAD

**Issue by castedo** [tskit-dev/msprime#1157]
After fixing polydistrotest
(https://github.com/castedo/containers/tree/polydistro/polydistro)
it now hits the same issue that @bhaller hit today where msprime doesn't load due to a dependency not satisfied by attrs 19.1. @molpopgen says he see attr.s(eq=False) work ok in attrs 19.2.

I attach the log spew from a test run on a clean Fedora 31 container that installed 19.1 and then pip install msprime doesn't not trigger an upgrade.
[](url)

**Comment by castedo** [comment]
[fedora-31.txt](https://github.com/tskit-dev/msprime/files/5184763/fedora-31.txt)

**Comment by castedo** [comment]
[centos-8.txt](https://github.com/tskit-dev/msprime/files/5184775/centos-8.txt)

and here's the other dependency issue. I don't as many details as the attrs case. But Centos 8 repositories install install jsonschema 2.6.0 and then pip installing msprime does not request a newer version and the msprime doesn't load. Error message in the attach log spew.

**Comment by jeromekelleher** [comment]
Thanks for tracking these details down @castedo. Looks like we need to pin these in setup.py:

```
attrs>=19.2
jsonschema>=2.6.0
```

**Comment by castedo** [comment]
jsonschema 2.6.0 seems to be missing something that msprime (maybe indirectly) wants. Fedora 31, which is the pentultimate stable version, packages jsonschema version 3.2 (which is also the latest on pip I think). I haven't seen any version in between. 

But 2.6.0 is too old. Maybe doing "jsonschema >= 3.0" is a good guess.

**Comment by benjeffery** [comment]
This is now fixed in tskit.
