### ISSUE TITLE
Add LRU cache rate_map_position_to_mass

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1159]
The [rate_map_position_to_mass](https://github.com/tskit-dev/msprime/blob/master/lib/rate_map.c#L149) function gets called a vast number of times during large simulations, and the binary search lookups that it incurs are a significant fraction of the time taken on the [time_human_chr22](https://github.com/tskit-dev/msprime/blob/master/benchmarks/benchmarks.py#L98) benchmark. I think we can significantly improve on this by having a small (say, 3-5 value) LRU cache for this lookup.

I guess the way to do this is to have a small ``lru_cache`` class which we put in its own file and write a few unit tests for. The API would look something like:
```c
int lru_cache_alloc(lru_cache_t *self, size_t size);
int lru_cach_free(lru_cache_t *self);
bool lru_cache_get(lru_cache_t *self, double key, double *value); // returns true for a hit
void lru_cache_put(lru_cache_t *self, double key, double value); // put at the front of the queue and evict LRU value
```

Maybe we'd want ``lru_cache_put`` to return an int just in case we need to return an error, I'm not sure. The only error condition I can think of is putting in a duplicate key, though, and this seems fairly harmless.

@castedo - this seems right up your street, any interest?

**Comment by castedo** [comment]
Ooooooo, fraction of time on a benchmark! Sounds like fun! I'll take it.

**Comment by castedo** [comment]
After looking over the code and observing a few benchmark scenarios with kcachegrind, here is my current thinking. Let me know if you see any issues. In a certain way, you could say what I am thinking is to let the CPU do the LRU caching with the L2/L3 caches.

What is kind of analogous to the `lru_cache_t` above is this structure:
```c
typedef struct {
    size_t num_bounds;
    struct { size_t lo; size_t hi; } bounds[];
} fast_search_lookup_t;
```

We can call this the `fast_search_lookup_t` plan. There are number of extra benefits I see to this plan:

1. can probably boost the performance of most all calls to `tsk_search_sorted` and `msp_binary_interval_search`.

2. existing unit tests for `msp_binary_interval_search`/`tsk_search_sorted` can be reused.

3. the performance benefit is not lost across simulations; new never-recently-used chromosome position queries still get perf boost

The core of the idea is that the actual bits inside the query, the `double`, contains bits with a great deal of information about which memory index should be used in the arrays of chromosome positions and cumulative masses.  This extra information I believe can drastically "turbo boost" the `tsk_search_sorted` & `msp_binary_interval_search` functions by letting those functions start searching from a drastically more narrow pair of bounds. In some cases, the bounds will be equal and no searching is needed at all.

So this lookup table is passed to a performance enhanced versions of `tsk_search_sorted` & `msp_binary_interval_search`, something like this:
```c
msp_fast_search_sorted(const double *restrict array, size_t n_values, double query,
                       const fast_search_lookup_t *restrict lookup_table)
```

This `fast_search_lookup_t` struct is allocated and initialized when `rate_map_alloc` runs. So the this overhead only happens once and the perf boost gets re-used across all random simulations.

Obviously there are many more details of interest which I'll try and make available in a branch soon. Feel free to chat with me about it synchronously.

**Comment by castedo** [comment]
@ivan-krukov thank you for all those unit tests for `msp_binary_interval_search` that I think you wrote. I think they are going to be very useful in the `fast_search_lookup_t` plan above. If you see any issues please feel free to share.

**Comment by jeromekelleher** [comment]
Sounds very interesting @castedo - if we can speed up the binary search used in looking up the chromosome positions then that will be a big bonus. I'm intrigued to see what you've come up with!
