### ISSUE TITLE
GC is not being simulated correctly for long tracklengths

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1161]
Since #1138, the GC code has been updated to remove the ``gc_left`` event type. The idea was to replace this (for now) with a single class of gc event, where we compensated for gc events which start to the left of the first segment by letting the first segment span back to the start of the sequence. However, this doesn't seem to work:

![breakpoints](https://user-images.githubusercontent.com/2664569/92504822-12a35200-f1fb-11ea-9e68-d020a38122de.png)

This is a pretty extreme example with a very long track length, where we're clearly biasing towards the end of the sequence for breakpoints.

We'll probably fix this by putting in a fenwick tree to track the gc_left process like discussed in #1138 and elsewhere.

GC is working fine for short track lengths, though.

**Comment by jeromekelleher** [comment]
See also the gc_correlation_between_trees test:

![prob_first](https://user-images.githubusercontent.com/2664569/92507284-a1659e00-f1fe-11ea-9022-d4b0fcb5d7f3.png)

**Comment by fbaumdicker** [comment]
Ok, this looks indeed like the gcleft part is misbehaving. I will try to look into this issue.
@jeromekelleher: Are the otherfigures for the middle and last positions in the gc_correlation_between_trees test closer to the prediction?

**Comment by jeromekelleher** [comment]
Thanks @fbaumdicker - I'm actually working on it at the moment. Hold off a little bit and I'll update with a proposal.

**Comment by fbaumdicker** [comment]
Great! Looking forward to see your proposal.

**Comment by jeromekelleher** [comment]
I've reinstated the old way of doing things in #1168, if you want to take a look @fbaumdicker  - I'll probably tidy that up a little bit and merge before trying to make it more efficient in a follow up.

**Comment by fbaumdicker** [comment]
I think there might be an easy way to fix it in this new version without gc_left here. 
I didn't look at the code yet but did you add a weight of mean_gc_rate * track_length to the leftmost position in the gc_map? The distribution looks like this is missing and might cause the error.

**Comment by jeromekelleher** [comment]
> I didn't look at the code yet but did you add a weight of mean_gc_rate * track_length to the leftmost position in the gc_map? The distribution looks like this is missing and might cause the error.

No, I just had a standard weight of ``gc_rate`` according to the map. That was probably the issue. There's still the problem of generating too many events then, though, isn't there?

**Comment by fbaumdicker** [comment]
> There's still the problem of generating too many events then, though, isn't there?
The graph above shows the relative frequency of events, correct? In this case, if we add events at the left side of the genome, the relative frequency of events on the right side should drop.

**Comment by jeromekelleher** [comment]
I was thinking more in terms of the performance @fbaumdicker - will we be able to simulate human chromosomes if we have all these GC non-events happening? I guess the simplest thing is to try it out.

**Comment by jeromekelleher** [comment]
Quick question for you @fbaumdicker - what's a reasonable track length for humans?

**Comment by fbaumdicker** [comment]
Something between 50 and 900 bp.
