### ISSUE TITLE
GC is currently ignored by sweeps code

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1162]
The selective sweep model currently allows there to be a non-zero GC rate but ignores the value (as in, it doesn't attempt to simulate gene conversion). This may lead to problems.

Should we simply raise an error if we start to simulate a sweep and there's a non-zero GC rate?

ping @andrewkern, @gbinux

**Comment by gbinux** [comment]
I think that makes sense. It seems `msms` does not have GC parameter either. I am thinking we can add an assertion in `msp_run_sweep function`. Do we need to update this python code as well? @jeromekelleher @andrewkern

**Comment by jeromekelleher** [comment]
It makes sense to raise an error or to continue ignoring the gc rate @gbinux? I think it's probably simpler/safer to raise an error. (We can do this in the C code, in the same way as we do for raising an error in DTWF when there's a non-zero GC rate).
