### ISSUE TITLE
Document running airspeed velocity benchmarks and set up site

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1165]
#1146 and #1138 added some initial benchmarks using [airspeed velocity](https://asv.readthedocs.io/en/stable/). For the record, here's what the current set look like 

![image](https://user-images.githubusercontent.com/2664569/92508796-22259980-f201-11ea-9c2b-c44e7800846a.png)

We have some basic benchmarks for Hudson and DTWF simulations. Getting these up and running and working for the problems I was working on was pretty frustrating and there's a lot of gotchas involved in running it. Hopefully these will settle down a bit now, though. One of the reasons it's so awkward is that ASV is built to accurately time short-lived functions, but we're mainly interested in things that take 10s of seconds (at least) to run.

Ideally, we'd like to run these regularly and keep a site updated with the results. The simplest way to do this is probably for us in Oxford to run the benchmarks on one of our servers on a cron job, and publish the results to github pages. We can look into having a dedicated machine at some point, but this will get us most of the way without extra faff of trying to find appropriate hardware.

@benjeffery, any thoughts here?

**Comment by benjeffery** [comment]
From my point of view the simplest option is to rent a dedicated server for $30 a month, unless an oxford machine can be found that can be configured to give consistent results. I'm not sure it is worth setting it up on a shared server as we won't trust the results.

**Comment by jeromekelleher** [comment]
It's no so much the cost I really care about @benjeffery, it's the admin overhead of setting it up (which would be many, many emails, I'm sure). Having something running all the time just to run a few benchmarks once a week (or whatever) just seems wasteful, anyway.

**Comment by benjeffery** [comment]
I've found an old laptop - hopefully can just leave it connected in my attic running benchmarks

**Comment by castedo** [comment]
This is great, especially the Monty Python's Holy Grail reference and that it is a cronjob on your old laptop poplar in your loft! :+1:

**Comment by castedo** [comment]
Question relating to the new plots:

Some of the benchmarks seem to only exist recently, like Hudson.time_human_chr22, but there is data going way back: 
https://tskit-dev.github.io/msprime-asv/#benchmarks.Hudson.time_human_chr22?branch=HEAD
In this example there is a big jump right at the time that Hudson.time_human_chr22 came into existence. Do I understand the code correctly? And if so, where are the old pre-existence numbers coming from?

**Comment by benjeffery** [comment]
I chose `poplar` as it's one of the fastest growing tree species. :D

The machine is still working it's way back in time, so we'll have to wait to see the full history.
