### ISSUE TITLE
Fill out functionality for sim_ancestry and document

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1171]
The current version of sim_ancestry is missing quite a few features. We should support everything in ``simulate``, except for

- mutation_rate 
- population_configurations
- migration_matrix
- demographic_events (these are replaced by the demography argument)
- pedigree (this isn't properly implemented yet anyway)
- mutation_generator

We should document it all as well. Most of it can be copied directly from msprime.simulate. We'll probably want to refactor the ``simulator_factory`` and other code a bit so we don't duplicate too much, but also without making divergent code paths within simulator_factor to deal with the two different front ends.

**Comment by mufernando** [comment]
Initial implementation of `sim_ancestry` in #1134

**Comment by jeromekelleher** [comment]
Another thought I had is that we should embrace input polymorphism a bit more, like we're doing with the ``recombination_rate`` now. Rather than having two arguments ``recombination_map``, and ``recombination_rate``, we just have the ``recombination_rate`` which has both behaviours by checking the type of the input.

Another place we could do this is for ``num_samples`` and ``samples``. I think the first (and only) positional argument to ``sim_ancestry`` should be ``samples``, which

- If it's an integer it's interpreted as n samples from the first population
- If it's a list of msprime.Sample objects it covers the old ``samples`` option to simulate.

Are there any other places we could reduce the number of parameters like this?

**Comment by petrelharp** [comment]
> If it's an integer it's interpreted as n samples from the first population

I think this should only work if there's only one population.
