### ISSUE TITLE
Add sim_mutations function

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1174]
As discussed in #1119, we would like to have a ``sim_mutations`` function that is basically the same msprime.mutate.

It may even be identical, in which case we should just make a simple shim like
```python
def sim_mutations(*args, **kwargs):
    return mutate(*args, **kwargs)

sim_mutations.__doc__ = mutate.__doc__
```

Is there any reason that we *can't* make ``sim_mutations`` the same thing as ``mutate``? I guess the main issue will be having ``discrete=True`` as the default.

**Comment by benjeffery** [comment]
If we aren't already I'd like to advocate for only allowing kwargs to `sim_mutations` as we are in some other places.

**Comment by jeromekelleher** [comment]
Agreed - all args after the first ``ts`` argument are keyword only.
