### ISSUE TITLE
use mutation.time to populate `origin_generation_` in slim mutation metadata

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/msprime#1188]
Once #1179 is in. Note that origin_generation_ is an *integer*, but following discussion with @bhaller, we decided it's still useful to put this in there, rounded. But it needs to be multiplied by -1, maybe offset by one, and either floor'ed or ceiling'ed. Details TBD.

Explanatory note: the "origin_generation_" entry in the metadata does *not* have to be consistent with anything in SLiM, since people can change it in the fly, use it as a tag, and other confusing things. So, we could just leave it set to 0 and nothing would break. But, we might as well put something useful in there. Note that under dtwf it will be consistent with 'time'.

**Comment by bhaller** [comment]
> Explanatory note: the "slim_time" entry in the metadata does _not_ have to be consistent with anything in SLiM, since people can change it in the fly, use it as a tag, and other confusing things.

This is now outlawed, as per https://github.com/MesserLab/SLiM/issues/103.  But still, SLiM itself doesn't use the times for anything, it just provides them to the user for their use as a property in script.  So SLiM doesn't care what the value is, and doesn't use it for anything.  (Which is why it was allowed to use it as a tag, etc., but that was indeed confusing.)

**Comment by petrelharp** [comment]
> This is now outlawed,

oh, right. phew. =)

**Comment by mufernando** [comment]
> I ran across another related TODO in the code: https://github.com/tskit-dev/msprime/blob/master/lib/mutgen.c#L307 - what we'd like to have happen here is to put 1 - time into origin_generation (check that 1).

should we also do this after #1179 goes in?

**Comment by petrelharp** [comment]
Yes - see above:

> Once #1179 is in. 

;)
