### ISSUE TITLE
keep enabling asserts by default?

### ISSUE THREAD

**Issue by castedo** [tskit-dev/msprime#1192]
As I'm improving the performance for some of these great benchmarks available, I have to ask whether enabling asserts by default should still be the case approaching v1.0.
https://github.com/tskit-dev/msprime/blob/96dc8d32528dfee218d8e7f6e53cfced9f797bdb/setup.py#L126

I usually would insert asserts often, but in some functions that should be particularly fast, i'm not putting them in. I could introduce a new C define like REALLY_DEBUG and then have a real_assert() function but that seems questionable.

What are people's thoughts? Seems to me there are two choices:

A) use NDEBUG and assert like it's usually used and define some assert() func alternative that is always enabled, say a function called kaboom() or abort_if() ...

B) keep NDEBUG undefined and keep assert running in production, but the having some other define like HARD_DEBUG and hard_assert that can be used in special cases ... like the amazyingly fast code i'm writting :)

**Comment by molpopgen** [comment]
My two cents:

If you can't measure the asserts in a profile, then leave them in.  Yes, it is a little odd to have them enabled, but they have proven useful in catching corner case bugs and annoying numerical issues.  I think it is worth occasionally crashing the interpreter if it helps to squash another bug.

Your option A doesn't solve the "never ever abort" in Python issue.  As for option B, it only matters if you can measure it.

**Comment by castedo** [comment]
Some more details to just make sure we're all on the same page:
1) there are currently two kinds of builds:
    - the "release" build, with the Python package, via msprime/Makefile, setup.py build_ext3
    - the "debug" build, via msprime/lib/meson.build, run by automated C unit tests
2) there are 174 calls to "assert()" in `msprime/lib/*.c`
3) at the moment there is no C define which allows C code to detect which of these two builds is being compiled

Just to clarify possibilities here, imagine option B with `fail_if()` defined just like `assert()` from 'assert.h', but unlike standard `assert.h` it always fails/aborts regardless of NDEBUG being defined or not.

In this scenario, @molpopgen recommendation can be "translated" (for option B) as "If you can't measure the `fail_if()` in a profile, use `fail_if()` instead of `assert()`. `fail_if()` is useful in catching corner case bugs and annoying
numerical issues."

I should share that as someone new to the code base I was slightly surprised `assert` is getting compiled into code that gets released to regular users. I imagine there is a great variety in how different programmers use `assert()` and in what situations they think the use of `assert()` is appropriate or not. I certainly have my own inclinations and opinions.

But I think the more relevant issue here is a function called `assert()` that gets pulled in by `assert.h` is usually understood to be something that does not cause code to abruptly terminate in release builds. @molpopgen makes a great point that sometimes there are good reasons to cause code to abruptly terminate in release builds. I just don't think most programmers think that's what `assert()` from 'assert.h' does.

When coding and choosing between:
a) adding an "assert" (that is enabled in release builds)
b) writing some extra code to handle the error condition properly doing goto out etc...
c) just ignore it and don't add any code
... abrupt termination of the Python process in release builds to all users is an important trade-off factor between these three options.

**Comment by molpopgen** [comment]
While I agree that it is strange to use this macro in release builds, the code base has moved a lot recently. There are multiple open issues that have only been found because these macros have been triggered. In some cases, users have reported the issues. So while it's not perfect to not exit gracefully, I think it is preferable compared to letting incorrect results happen.  

Anyways, @jeromekelleher will have a lot to say about this I imagine.

**Comment by castedo** [comment]
> There are multiple open issues that have only been found because these macros have been triggered.

I'm just making sure we're all on the same page here. The above statement by @molpopgen is true when "these macros" means "macros such as `assert` _OR_ a `fail_if` (as described earlier)". Whereas the statement is false if "these macros" means only the macro called `assert()` defined in 'assert.h' and enabled in release builds by undefining NDEBUG.

The objective of catching these bugs via abrupt termination with users does not require using the `assert()` macro defined in 'assert.h' and undefining NDEBUG in release builds. I think we all agree on this.

**Comment by jeromekelleher** [comment]
I'm pretty happy with keeping the asserts in, frankly. They have proved invaluable in tracking down bugs and they don't show up in profiles, so I see no good reason not to keep them in. There's a sort of Murphy's Law on Steroids effect with random simulation programs, in that it's incredibly hard to shake out all possible corner cases and to predict every possible parameter regime users will put in. I agree leaving asserts seems a bit weird, but experience has shown these are very useful.

So: unless the asserts show up at > 1% overall CPU time in the ``perf record`` of a simulation lasting more that (say) 10 seconds, I would see no reason to change this. There's lots of code for doing expensive "deep asserts" that's run during the C tests cases, that's run during ``msp_verify``. This might be a good model for any more expensive asserts you'd like to put in @castedo.

**Comment by castedo** [comment]
Thank you for your all's comments. I have a much better sense what you all mean when you say/write "assert" and the nature of msprime users. It's nice to have msprime users helping so much to find bugs. Perhaps in a sense one could say the broad msprime community, including all msprime users, are participating in testing and debugging, and thus are using an `-O2` optimized "debug" build.

So the resolution for this github issue will be option B.

Thanks for pointing out `msp_verify`, I had not seen that. I will keep that model in mind. If I understand this model correctly it goes into effect when explicitly enabled by a specific unit test or call, but not for every call to an internal function regardless of call path.

@jeromekelleher you used the phrase "expensive asserts" so I am thinking I will define a macro called `expensive_assert()` which is not enabled in optimized builds. The long name will discourage usage unless it's really needed. For now I'll condition the macro on the `__OPTIMIZE__` flag. Or it can be conditioned on a new flag.

Some other day I'll probably suggest another new macro as equally useful but better behaved alternative to `assert()`, but we can discuss that idea separately when the time comes.

I should finish with some closing remarks. These closing remarks don't have any immediate actions but I do think they are worth keeping in mind for the future.

<closing_remarks>
I don't find it surprising that there are conditional code checks that always trigger abrupt termination even for end users. What I find surprising is calling them 'asserts' and using the `assert()` macro from `assert.h` to do this. I would have used a macro called `fail_if` or 'panic_if` or 'abort_if` and called them panics or aborts or similar.

To make a crude analogy, imagine a piping system built with many taps that are welded open. When asked why taps are welded open, the answer is that it is very useful to have something that most people would call a 'spout'. But for some reason the builders use taps instead of spouts, weld them open and call them 'taps'.

Now that I understand what you all mean by "assert" we're all good now. But you might want to keep this in mind for future new developers. I think most C/C++ developers understand that 'assert()' is something that is enabled test/dev builds and disabled in externally released builds. If they are supposed to terminate the program always in all builds why call it "assert" and use `assert()` from `assert.h`. That is the point of what are called "asserts" and `assert.h`. That is what I find weird.
</closing_remarks>

**Comment by jeromekelleher** [comment]
I think we agree on what ``assert`` means @castedo, and these are *extremely* rare bugs we're talking about (one of them happened with probability, oh, I don't know, something excruciatingly small). So, it's not that we expect this to happen very often and we're using the user community as lab rats to find problems for us, it's more like a pragmatic acceptance that these things happen with stochastic simulations and it's better to prepare for it. 

But yeah, maybe we should call these ``bug_on`` or ``fail_if`` or something, as you say, to avoid having to turn off asserts, which does complicate the compilation a bit and avoid confusing C/C++ devs used to a crisper and more predictable universe. I'd happily accept a patch doing this.

**Comment by jeromekelleher** [comment]
Reopening this due to #1203

**Comment by castedo** [comment]
Secondary detail related to the possible elimination of `undef_macros=["NDEBUG"]` in `setup.py` so that release builds have `NDEBUG` defined. Then it will be a typical release build for Python package and debug build for C unit tests.

It will then become useful to be able to easily run `nosetests` with a debug build. Probably most simple to just continue with two kinds of builds and have `nosetests` run the debug build, though that will make it noticeably slower. Something to consider is a third in-between build of a "fast debug" build which is kind of what the current release build is, with NDEBUG undefined but all other speed optimizations turned on.

I'm not sure what will be easiest to do with the current `setup.py` but just wanted to mention that locally I would be attempting to run `nosetests` with a build that has all possible safety checks turned on.

**Comment by jeromekelleher** [comment]
Easy enough to add a "debug" target to the dev Makefile @castedo, with the required CFLAGS values.
