### ISSUE TITLE
Reinstate specific errors for old classes

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1194]
The current fall-back of looking up tskit where there's a name error in msprime leads to some confusing error messages. For example, if I write
```
>>> msprime.simlate
Traceback (most recent call last):
  File "/home/jk/work/github/msprime/msprime/__init__.py", line 61, in __getattr__
    result = getattr(tskit, name)
AttributeError: module 'tskit' has no attribute 'simlate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jk/work/github/msprime/msprime/__init__.py", line 67, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'msprime' has no attribute 'simlate'
```

This will catch people out, as they'll look at top error message first and then wonder what this has to do with tskit (it's certainly tripped me up a couple of times now).

We should explicitly list the things we expect to deprecate and keep the name resolution at the top-level straightforward.

**Comment by benjeffery** [comment]
This is due to how I did the deprecation so I should fix this! Self-assigning.

**Comment by jeromekelleher** [comment]
See also #1207, where it looks like we should change the warning type to FutureWarning.

**Comment by jeromekelleher** [comment]
@benjeffery we could do with getting this shelved away soon, any chance you could pick it up this week please?
