### ISSUE TITLE
Non-standard binary search semantics

### ISSUE THREAD

**Issue by castedo** [tskit-dev/msprime#1195]
In the msprime code there is [a TODO to call `tsk_search_sorted`](https://github.com/tskit-dev/msprime/blob/1ee8d287b15857ac8638c369b99d06bba77e235a/lib/rate_map.c#L168) instead of `msp_binary_interval_search`. In [the comments for `tsk_search_sorted`](https://github.com/tskit-dev/tskit/blob/bc50b5a92e56b578af12caea43d13a82c2008b59/c/tskit/core.c#L622) it reads 'Mirrors the semantics of numpy's searchsorted ...'.

There are two issues highlighted here. One issue is that the behavior of `msp_binary_interval_search` can not be replicated by `tsk_search_sorted` when there are repeated values.  In a sense, the loops of each are fundamentally different. One loop is searching for a strict non-equal upper bound and the other loop is searching for an upper bound that may be equal.

The other problem is that `tsk_search_sorted()` does not have the semantics of `numpy.searchsorted`. It is closest to `numpy.searchsorted(..., side='right')` which one could call "find_first_strict_upper_bound". But what `tsk_search_sorted()` actually does would be called "find_first_strict_upper_bound_or_last_match".

I'm thinking a good way to clean this up is to have functions in msprime and/or tskit that really mirror the semantics of numpy.searchsorted and equivalent standard C++ <algorithm> library functions [std::lower_bound()](https://en.cppreference.com/w/cpp/algorithm/lower_bound) and [std::upper_bound()](https://en.cppreference.com/w/cpp/algorithm/upper_bound). (just two semantics, both reflected in both libraries).

The semantics of these standard functions make a lot of sense to me and I think reflect the wisdom of decades of usage. The existing function can be derived from these two standard binary search function semantics. At some point, some of the hacky tweaks and adjustments in the code can be eliminated using these standard semantics.

One piece of feedback some people might want to provide is on naming of these two functions with standard semantics. If it weren't for the names in the C++ library, I would think good names are:

`find_first_upper_bound` and `find_first_strict_upper_bound`

but I suspect this a little confusing with the C++ library function names. I actually think the C++ library function names are more confusing than the names I suggest. :) But the C++ library function have already been named so that's tough reality.

Suggestions on naming? Other issues? Concerns?

**Comment by jeromekelleher** [comment]
Neither of these are part of the public APIs, so I'm not particularly worried about the exact semantics. They do what we need them to do within the context of the libraries. I doubt the differences in semantics between the msprime and tskit are make any difference in our applications, which probably never have repeats (IIRC, we just use binary search to find positions in a sorted list of coordinates, which cannot have repeats).

**Comment by castedo** [comment]
@jeromekelleher I see a check in rate_map_alloc to error out if there are repeats in the positions. But the rates can be zero:
https://github.com/tskit-dev/msprime/blob/1ee8d287b15857ac8638c369b99d06bba77e235a/lib/rate_map.c#L84
and thus cumulative mass can repeat so here
https://github.com/tskit-dev/msprime/blob/1ee8d287b15857ac8638c369b99d06bba77e235a/lib/rate_map.c#L191
there is a call to `msp_binary_interval_search` where `tsk_search_sorted` will return a different index.

`msp_binary_interval_search` and `tsk_search_sorted` also return diff values for queries strictly greater than the last array value. Not sure that matters in live code.

I can't tell whether these minor difference will introduce a bug **but the unit tests catch** these minor differences in test_rate_map.c. And doing an assert for equivalence in does get hit in benchmark tests. So I'm torn what's the best way to proceed.

For now I'm just focusing on improving performance. But while I'm testing and optimizing this code using `msp_binary_interval_search` I can:

A) migrate the code (and unit tests) to use standard semantics. And then at least for **non-repeating** arrays it will actually match exactly to `tsk_search_sorted`. I suspect following standard semantics will actually make some optimizations easier (but not sure yet).

As a separate future follow up item it seems like a good idea to:

B) actually make `tsk_search_sorted` match the semantics of numpy.searchsorted and the C++ algorithm library and after that have msprime can call it.

Any requests/preferences on A) or B)?

**Comment by jeromekelleher** [comment]
Path (A) sounds great, thanks @castedo. We can worry about tsk_search_sorted some other time. Particularly if we're doing perf tweaks specifically for the application in msprime, we may as well just keep the code there. The only motivation for using the tskit version was to cut down on lines-of-code.
