### ISSUE TITLE
Change gene_conversion_track_length to gene_conversion_tract_length

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1202]
I.e., change "track" to "tract".  See [here](https://github.com/tskit-dev/msprime/pull/1190#discussion_r493739431) for original comment.

Thoughts, @fbaumdicker?

**Comment by fbaumdicker** [comment]
Yeah, I think @petrelharp is right. "tract" is better. Will add a commit that switches from "track" to "tract" to the ongoing pull request #1196

**Comment by jeromekelleher** [comment]
I think it's better to hold off on this a little bit until both #1196 and #1190 have landed @fbaumdicker - we'll be dealing with a merge-mess otherwise. It's an easy change to make, anyway, so there's no rush.

**Comment by fbaumdicker** [comment]
I agree.
