### ISSUE TITLE
add clang-format to developer docs

### ISSUE THREAD

**Issue by mufernando** [tskit-dev/msprime#1208]
There currently isn't guidance on how to format the C side of msprime, even though one of the PR checks is about formatting.

If you just mindlessly `clang-format` all the C files you get some changes to `avl.c` and `mutgen.c` that are currently in `main`.

**Comment by jeromekelleher** [comment]
Yes, this isn't obvious, I'll update the docs next time I'm in there.

The ``mutgen.c`` file should be clang-formatted, though.
