### ISSUE TITLE
Add pytest config 

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1231]
We mainly need this to specify the test path and stop pytest from recursing into the submodules and trying to execute tests for tskit and kastore (which will confuse devs as well as clutter up the git status).

Docs [here](https://docs.pytest.org/en/stable/customize.html)

Ideally, we'd use a setup.cfg, and centralise some of this configutation, but maybe we're not in a position to move away from setup.py quite yet, so a ``pytest.ini`` file might be a good interim solution.

**Comment by benjeffery** [comment]
Yeah, lets do setup.cfg another time.
