### ISSUE TITLE
Upload lcov report data to codecov.io

### ISSUE THREAD

**Issue by castedo** [tskit-dev/msprime#1240]
The msprime code coverage infra, just today, help identify some needless code I wrote. It really did an awesome job making clear where there was some fishy code worth investigating.

Uploading lcov reports can make the coverage number even more useful and clear. Using lcov will make it possible to not have good error handling code lower the code coverage number, and reach 100% in many files. For example, the goto out handling for failed memory allocations. Specfically `// LCOV_EXCL_LINE` can be appended to these kinds of lines, that are not worth trying to hit from unit tests, but they do the right error handling for users.

Per https://docs.codecov.io/docs/supported-report-formats codecov.io will also accept "Lcov TXT" reports in addition to the usual gcov reports that are currently uploaded.

Using lcov I'm able to get lib/util.c to 100% coverage even though there are error handling lines for when too much memory is getting allocated.

I believe all that is needed is to do what is done today with gcov but then also run the command
```
lcov --capture --directory . --output lcov-data.txt
```
and then have `codecov` upload that data text file.

I'm running this manually and then running `genhtml` (from lcov) to generate an html file. But I think this last step is to be skipped when using codecov.io.

There is an `lcov` package on Debian.

I also tried out `gcovr` but after using both and reading online I have a strong hunch `lcov` will have less headaches at the moment... even though `gcovr` will probably be a better tool in the future.

**Comment by castedo** [comment]
@benjeffery It appears that codecov already ignores lines marked as `// LCOV_EXCL_LINE`! :open_mouth:  Either codecov changed this in the last few days or I made the erroneous assumption that it isn't supported (far more likely).

I investigated `lcov` running inside the Debian stretch container that CircleCI uses and did not see anything obviously fishy. I suspect that it is an incompatibility between `lcov` and `codecov.io`. So I recommend ditching `lcov`, it's ancient anyway.

I also tried out `gcovr` which you can see in #1242. But as shown in #1243 support for ignoring lines was already available. So it's much clear that using `gcovr` is worth adopting vs only `gcov`. I'll investigate some more and add comentary into #1242.

**Comment by castedo** [comment]
I've gone ahead and closed both PRs since the changes aren't worth the new issues introduced.

@benjeffery There is one inconsistency between the Makefile and the .circleci/config.yml that I noticed and perhaps should be fixed:
`.circleci/config.yml` has a line
https://github.com/tskit-dev/msprime/blob/88236ab8e61031fc48131ff53116f724c7230f29/.circleci/config.yml#L75
to collect coverage for C code when the Python tests are run. But the `make allchecks` recipe
https://github.com/tskit-dev/msprime/blob/88236ab8e61031fc48131ff53116f724c7230f29/Makefile#L10
does not add `--coverage` as a C flag. As a result no coverage lines are credited for C code execution resulting from the Python tests. I don't know whether that is intended or an omission.

**Comment by benjeffery** [comment]
Thanks for looking into this @castedo - I'll file issues to fix the missing coverage of `_msprimemodule.c`.
