### ISSUE TITLE
Is there any way to know how MutationGenerator() work?

### ISSUE THREAD

**Issue by leovam** [tskit-dev/msprime#1247]
Hi, thanks for such a wonderful package!

I would like to use it to simulate a model with customized mutations, so I would like to know how mutation works first and then may develop my own. However, in the ```mutations.py``` file,  I saw there are additional libraries imported by ```import _msprime```, it is a cypthon.os file in my directory and I think those functions are pre-compiled so ```mutation_generator = _msprime.MutationGenerator(...)``` can be directly used. Then I tried to locate ```MutationGenerator(...)``` and found ```_msprimemodule.c``` in Github, but inside this file, I cannot find any function or class called ```MutationGenerator()```. Could you please help me with this?

On the other hand, if I want to develop my own function to impose mutations with more customized settings, what is a good way to start with? Thanks!!

**Comment by leovam** [comment]
nvm, I just found that there is a huge update between 0.7.5 and 0.7.4 ...

**Comment by benjeffery** [comment]
Thanks for getting in touch @leovam! Yes, msprime is undergoing large changes in preparation for its 1.0 release, there won't be a 0.7.5.  Using the latest code from github is not advised unless you're comfortable with some churn and incomplete docs. 

We'd love to hear what your use case is for mutation generation though, as finding out how people are using the library informs future API design etc. msprime is also wide open for contribution if you find you need to add something that is missing or could be improved.

**Comment by petrelharp** [comment]
If you want to see what's coming up, you can look at the latest documentation, for instance [here](https://msprime.readthedocs.io/en/latest/api.html#mutation-matrix-models).

**Comment by leovam** [comment]
thanks for all information, I really appreciate it!
