### ISSUE TITLE
gene conversion tract lengths are slightly to large

### ISSUE THREAD

**Issue by fbaumdicker** [tskit-dev/msprime#1251]
For small gene conversion tract lengths the distribution of tract lengths is currently not the correct one. For example, the mean tract length is 2.54 if the tract length is set to 2. The effect vanishes for larger tract lengths. I already found the reason for this issue (switching from continuous to discrete coordinates is slightly biased) and am working on a PR that fixes this. Will give more details in the PR.

**Comment by jeromekelleher** [comment]
That's great, thanks for looking into this @fbaumdicker. Can you make sure there's a check in the verification.py for this please?

**Comment by fbaumdicker** [comment]
I can try to think of something to check this. It is not straight forward as we are currently not internally tracking the lengths of all gene conversion tract lengths. Is there an easy way to look up the actually simulated tract lengths in a table or variable?

**Comment by jeromekelleher** [comment]
> I can try to think of something to check this. It is not straight forward as we are currently not internally tracking the lengths of all gene conversion tract lengths. Is there an easy way to look up the actually simulated tract lengths in a table or variable?

Good point. No, we don't have a way to track this. We could store the cumulative tract length in a variable, I guess?

**Comment by fbaumdicker** [comment]
That would work, will add it.
