### ISSUE TITLE
Rename ``mu`` parameter in unnormalised_log_mutation_likelihood

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1262]
The unnormalised_log_mutation_likelihood is a bit inconsistent with other functions in that it uses a parameter ``mu``.  Since the ``log_arg_likelihood`` function has a parameter ``recombination_rate`` I propose we change the parameter for unnormalised_log_mutation_likelihood to ``mutation_rate``.

It's at the only positional parameter, so I doubt we'll break any code by changing the name.

Any thoughts @JereKoskela?

**Comment by JereKoskela** [comment]
Well spotted, I agree. Shall I push through a quick PR to change the name @jeromekelleher?

**Comment by jeromekelleher** [comment]
> Well spotted, I agree. Shall I push through a quick PR to change the name @jeromekelleher?

Yes please! Don't worry about the docs, I'm doing a major refactor over in #1258, so we'll need to do a quick refresh at some point.

Alternatively, you could wait until #1258 is in and make one job of it.

**Comment by JereKoskela** [comment]
I'll fix both at once when #1258 is done. I've assigned this issue to myself as a reminder.
