### ISSUE TITLE
Drop "unnormalised" from unnormalised_log_mutation_likelihood?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1263]
It's a bit long as it is, and we can probably make it clear that the quantity we're computing is unnormalised in the docs. If we ever do want a "normalised" version of this, we could always add a parameter ``normalised=False`` to make it an options.

Any objections @JereKoskela?

**Comment by JereKoskela** [comment]
Nope, fine by me. Shall I add this to my todo list along with #1262?

**Comment by jeromekelleher** [comment]
Yes please!
