### ISSUE TITLE
Port ARG example content to jupyter-sphinx

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1270]
Current content is [here](https://tskit-dev.github.io/msprime-docs/main/ancestry.html#ancestral-recombination-graph), which is a copy-paste of the old tutorial code.

This should be a straightforward update.

@JereKoskela - any chance you could take a look at this?

**Comment by JereKoskela** [comment]
Sure @jeromekelleher - I'll add it to my list. I had just about got the hang of sphinx before the refactor and have never used jupyter so there will probably be dumb questions forthcoming.
