### ISSUE TITLE
Port census events content to jupyter sphinx

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1271]
Current section [here](https://tskit-dev.github.io/msprime-docs/main/ancestry.html#census-events)

**Comment by cdquinto** [comment]
@agladstein and I can work on this issue.

**Comment by jeromekelleher** [comment]
Thanks @cdquinto! Please feel free to ping me if you have any questions. (Did you get an invite to the tskit-dev slack, btw? If not, can you email with so I can send you one please?)

**Comment by cdquinto** [comment]
Got the slack invitation, thanks!
