### ISSUE TITLE
Restructure likelihoods docs page

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1274]
The likelihoods [docs page](https://tskit-dev.github.io/msprime-docs/main/likelihoods.html) is currently a mixture of old API and tutorial content. Bring this up to date, using jupyter-sphinx for the examples.

I propose we split it into two level sections:

```
Topology
Mutations
```

The sections then contain the autodoc API docs for the relevant functions, and some examples of the functions in use (as ported from the old tutorial docs). See, e.g., [here](https://github.com/tskit-dev/msprime/blob/main/docs/ancestry.rst#discrete-or-continuous) for an example of using jupyter-sphinx.

Also update the links to documentation sections in the Python code to point to these new sections.

@JereKoskela can I sign you up for this?

**Comment by JereKoskela** [comment]
Yes, happy to take this on @jeromekelleher. Thanks for the link to the example!
