### ISSUE TITLE
Document conventions and recommendations for jupyter sphinx

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1275]
After #1258 we're using jupyter-sphinx. Some conventions like starting a new kernel for every section have been laid down there, but we should document this stuff for developers.

**Comment by agladstein** [comment]
This is related to https://github.com/tskit-dev/msprime/issues/1305

**Comment by agladstein** [comment]
Should this be closed now or is the more we want to add about Jupyter Sphinx?

**Comment by jeromekelleher** [comment]
Closing - thanks @agladstein
