### ISSUE TITLE
Update the ancestry/genome properties section

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1278]
Half-done section [here](https://tskit-dev.github.io/msprime-docs/main/ancestry.html#genome-properties).

In particular we need some discussion and help on the recombination and gene conversion sections. See todos for details.

**Comment by petrelharp** [comment]
Something that should be pointed out is that, as we figured out in #1299, with a discrete recombination map and a recombination rate of `r`, the expected number of recombinations per unit time and per unit length is `1-exp(-r)`. (And, this appears to be true in both hudson and dtwf.) This has the consequence that the total map length for a segment of length `L` and recombination rate `r` is in fact `L (1 - exp(-r))`, which is
```
Lr (1 - r/2) < L (1 - exp(-r)) < Lr
```
So, with a recombination rate of 1e-8, this would only reduce total map length by a factor of (1 - 0.5e-8); but if people are simulating bigger gaps (eg chromosomes) they should be aware of this.
