### ISSUE TITLE
Errors running tests after install following developer docs

### ISSUE THREAD

**Issue by apragsdale** [tskit-dev/msprime#1283]
I ran into a very small hiccup following the instructions under Quickstart in the Developer documentation (in a fresh environment on an ubuntu system).

At the step of running `python3 -m nose -vs` there were a few failing tests when testing logging - specifically a few errors all along the lines of `TypeError: test_debug_logging() missing 1 required positional argument: 'caplog'`.

The install worked otherwise and I had no problems running msprime, but wanted to bring it up in case it hadn't been seen before.

**Comment by benjeffery** [comment]
We recently moved to pytest. The dev docs have been updated, but if you are following the docs for the last version then you'll get that error.

**Comment by apragsdale** [comment]
Ah, ok! Sometimes hard to keep up with all the changes :)

Thanks!

**Comment by jeromekelleher** [comment]
> Ah, ok! Sometimes hard to keep up with all the changes :)

Will hopefully be settling down soon. Can't wait to get 1.0 out and move on!
