### ISSUE TITLE
Compare command line parameters of msprime with other coalescent simulators

### ISSUE THREAD

**Issue by gbinux** [tskit-dev/msprime#1286]
As many other coalescent simulators use the command line to specify parameters, maybe we could do a comparison of command-line parameters between `msprime` with other simulators, such as `macs`, `msms`, `discoal` (there are more to add to the list). I would suggest to:

1) Use several examples to show how to do a set of similar simulations with different software. I think this will make it easier for new users to switch from other software to msprime.  In the meantime, this can help transition to functionalities/models that other simulators do not have.

2) Use a table to compare definitions of parameters, such as coalescent rate, recombination rate, and time units (1, 2N, or 4N generations) used in `msprime` vs other software. I was confused every time a simulator uses a different scale factor or time units.

As @jeromekelleher suggested, this is likely to be in the quickstart page.

**Comment by jeromekelleher** [comment]
@gbinux, the 1.0 release is getting closer and there's still a lot of stuff to do. Would you like to volunteer to do this, or can I take it out of the 1.0 Milestone?

**Comment by jeromekelleher** [comment]
One place this could go is on the [notes for ms users page](https://tskit.dev/msprime/docs/latest/notes_ms_users.html) @gbinux, although we'd need to come up with a new name for the page.

**Comment by gbinux** [comment]
I was thinking about this as well. How about `Notes for users of ms and other coalescent simulators`?

**Comment by jeromekelleher** [comment]
Closed in #1624
