### ISSUE TITLE
Behavior of `end_time` when using "dtwf" model

### ISSUE THREAD

**Issue by apragsdale** [tskit-dev/msprime#1304]
I'm confused about the behavior of `end_time` when the model is set to "dtwf". When simulating using `sim_ancestry`, if I set the `end_time=1`, I figured the simulation would run for a single generation. I can see this in the "hudson" model, running `sim_ancestry` with `end_time=1` gives me multiple trees. However, simulating with "dtwf" and `end_time=1` results always in a single tree, so that nothing has occurred. Instead, specifying `end_time=2` with the "dtwf" model results in roughly the same distribution of the number of trees as with the "hudson" model and `end_time=1`.

Is this the intended behavior, or is the "dtwf" model ending a generation too early when `end_time` is specified?

Edit, as an illustration, with 2 samples, Ne=1000, a segment of 1 Morgan, with 20,000 replicates:
![num_trees](https://user-images.githubusercontent.com/33734266/99106183-72c2c580-25a9-11eb-9600-b38d808dff0f.png)

**Comment by jeromekelleher** [comment]
Looks to me like we're not running DTWF at all when ``end_time=1`` because of the strict < semantics. I don't think the definition of time is particularly well worked out here though, and it could well be that we need to fix it.

**Comment by apragsdale** [comment]
Right, so if the simulation time interval with `end_time=1` is on the half-open interval [0, 1), nothing occurs in the "dtwf" model. But we would get a generation of simulation with time on the interval [0, 1+epsilon). The confusion I see, is that if we set `end_time=1`, users probably would have expected one generation of dtwf simulation and for the tops of the trees to be at the parental generation, instead of the sampled generation.

Another related issue: if we switch models at an integer time from "dtwf" to "hudson", do we lose a whole generation of simulation? E.g. if I run `ts = msprime.sim_ancestry(2, population_size=1000, recombination_rate=rec_map, model=["dtwf", (1, "hudson")], end_time=2)`, I think we'd end up missing a whole generation of simulation, and it would be essentially equivalent to running `ts = msprime.sim_ancestry(2, population_size=1000, recombination_rate=rec_map, end_time=1)`.

**Comment by jeromekelleher** [comment]
I remember spending a long time dithering over the semantics of ``end_time`` based on the Hudson algorithm, and being able to guarantee that all times in the output tree sequence were < than end_time seemed like a good thing. It's implemented [here](https://github.com/tskit-dev/msprime/blob/main/lib/msprime.c#L4222). Strictly < makes it a bit simpler because we always put on unary edges up to the ``max_time`` at the end of an uncoalesced simulation [here](https://github.com/tskit-dev/msprime/blob/main/lib/msprime.c#L5092). We need these unary edges or else we can't do things like recapitating later (this took quite a while to figure out, too!). So, I guess we could change the definition to all nodes are <= ``end_time`` and then check for any nodes at ``end_time`` in this function?

> Another related issue: if we switch models at an integer time from "dtwf" to "hudson", do we lose a whole generation of simulation?

Yes, very possibly. As I say, I don't think we ever really thought through the exact semantics of time in the DTWF properly. We can definitely change it, if we want to.

**Comment by castedo** [comment]
I'm just throwing out an idea here, and with the caveat that I've learned the Wright-Fisher model but not Hudson's yet, and I've yet to really use the API as a user.

Perhaps a parameter name of "expiry" or "expire_time" or "stop_time" is more suggestive that nothing is simulated at that time.

It would not shock me if in the end, sometimes it works out best specifying the last time a simulation happened and sometimes it works out best specifying the first time simulation is absent. In discrete time these are different by one unit of time and in continuous time they are equal, maybe.

**Comment by jeromekelleher** [comment]
Adding this to the 1.0 milestone, but I think it's just a case of documentation. We just have to be clear that ``end_time`` is exclusive and add some warnings about what this means in DTWF

**Comment by apragsdale** [comment]
Documentation would put a band-aid on it, I suppose. This does create some very awkward and unintuitive usage that will be confusing for most users: If you want `n` generations of WF and then `m` generations of Hudson, you have to set end time first to `n+1` and then "rewind" a generation to continue the `m` generations of Hudson. I really think the behavior of integer end times should be consistent across the models, as `end_time` effectively means the number of generations simulated. Having it mean different things across the models is a bug that people could easily get tripped up on, and we should expect that not everyone will see a note in the documentation.

To me, the `<=` interpretation of `end_time` is more consistent across models in any case. Say you run any model with `end_time=0`, which does nothing. Then you have a collection of samples and their node times will be equal to zero (i.e. `<= end_time`). 

Would it break things to change to a `<=` understanding for `end_time`? In Hudson, since it's all continuous, nothing would actually change there, right?

**Comment by jeromekelleher** [comment]
> Would it break things to change to a <= understanding for end_time? In Hudson, since it's all continuous, nothing would actually change there, right?

No, probably not. I expect you're right too. 

So the proposal is to change [this line](https://github.com/tskit-dev/msprime/blob/42ed301bc4ad994c975d3ca06a0e3671bb1e5567/lib/msprime.c#L4272) and clean up any breakage in the test suite and watch out for time equality when doing uncoalesced nodes?
