### ISSUE TITLE
Simulating population split then merge (backwards in time)

### ISSUE THREAD

**Issue by trevorcousins** [tskit-dev/msprime#1311]
Hi, 

Is it possible to model a single population that (going backwards in time) at time t_1 splits into two populations, then at time t_2>t_1 reforms back into one population?

I don't think my current method is effective. I start with two populations of equal size (pop ID 0 and 1), though am only sampling form one of them (pop ID 0). 
`population_configurations = [`\
`msprime.PopulationConfiguration(sample_size=2, initial_size=1e+04, growth_rate=0),`\
`msprime.PopulationConfiguration(sample_size=0, initial_size=1e+04, growth_rate=0),`\
`]`
With MassMigration I send at time t_1 a fraction, say 0.5, of 0's lineages into 1:
`msprime.MassMigration(time=t_1, source = 0, dest=1,proportion=0.5)`
and I want to send these lineages back into 0 at time t_2, though the only command that doesn't crash msprime is:
`msprime.MassMigration(time=t_2, source=1, dest=0, proportion=1) `
(i.e. sending all lineages from 1 to 0. Setting proportion as any fraction crashes the program)
Presumably this is because if A's lineages remain separate then there is no chance of them coalescing and the program crashes. This doesn't seem the right thing to do because then all of 1's lineages are in 0 too; but does that matter - I believe if I am only sampling from population 0 then having 1's lineages in 0 won't affect the population size of 0?

What i am trying to model is an instananeous migration, which lasts for some period of time. I realise I can model continuous migration with the migration_matrix but that is not what I am trying to do.

Best wishes, 

Trevor

**Comment by trevorcousins** [comment]
Further to last comment, I think I've found a better way to do it, which is to match the size of the ghost population (ID 1) to the size of the split. Suppose ID 0 is size 1e+04 and between times t_1 and t_2 I want this to split into two populations of equal size (0.5e+04 each):
`population_configurations = [`
`msprime.PopulationConfiguration(sample_size=2, initial_size=1e+04,growth_rate=0),`
`msprime.PopulationConfiguration(sample_size=0, initial_size=0.5e+04, growth_rate=0),`
`]`
Then
`demographic_events = [`
`msprime.MassMigration(time=T_1, source = 0, dest=1,proportion=0.5),`
`msprime.MassMigration(time=T_2, source=1, dest=0, proportion=1)`
`]`

Would this be a better (correct, even) way to do it?

Best, 

T

**Comment by jeromekelleher** [comment]
Hi @trevorcousins, thanks for using msprime! Your approach in the last comment should do what you want, I think. I'd recommend using the [DemographyDebugger](https://msprime.readthedocs.io/en/latest/api.html#debugging-demographic-models) to see the effects of the mass migrations on your model. Section 2.5.2 in this [chapter](https://link.springer.com/protocol/10.1007/978-1-0716-0199-0_9) might help, as well as the [tutorial](https://msprime.readthedocs.io/en/latest/tutorial.html#mass-migrations).
