### ISSUE TITLE
python3 -m nose -vs  fails

### ISSUE THREAD

**Issue by eldonb** [tskit-dev/msprime#1317]
In case this is helpful:

python3 -m nose -vs 

returns  5 errors:

======================================================================
ERROR: tests.test_ancestry.TestSimulator.test_debug_logging
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_debug_logging() missing 1 required positional argument: 'caplog'

======================================================================
ERROR: tests.test_ancestry.TestSimulator.test_debug_logging_dtwf
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_debug_logging_dtwf() missing 1 required positional argument: 'caplog'

======================================================================
ERROR: tests.test_ancestry.TestSimulator.test_info_logging
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_info_logging() missing 1 required positional argument: 'caplog'

======================================================================
ERROR: tests.test_provenance.TestBuildObjects.test_encode_numpy_functions_and_classes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_encode_numpy_functions_and_classes() missing 1 required positional argument: 'caplog'

======================================================================
ERROR: tests.test_provenance.TestBuildObjects.test_large_provenance_warning
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_large_provenance_warning() missing 1 required positional argument: 'caplog'

----------------------------------------------------------------------
Ran 887 tests in 73.300s

FAILED (errors=5)

**Comment by apragsdale** [comment]
Thanks! I also ran into this recently. Testing was recently moved from nose to pytest. The developer docs have been updated, but the docs for the last version will still have you run tests using nose and give that error.

**Comment by benjeffery** [comment]
You can preview the 1.0 docs at https://tskit-dev.github.io/msprime-docs/main/development.html

Thanks for the report though @eldonb!
