### ISSUE TITLE
model="dtwf" in mspms?

### ISSUE THREAD

**Issue by samyeaman** [tskit-dev/msprime#1318]
Are there any plans to include the backwards Wright-Fisher model in the legacy mspms style implementation? Apologies if it's already there -- I couldn't figure it out. If not, I totally get it.

**Comment by jeromekelleher** [comment]
Unfortunately not @samyeaman, we don't have any plans to implement DTWF in the mspms interface. It's quite a complex piece of code and we don't want to make it any more complex and harder to maintain. 

Apologies - I know this isn't terribly helpful!

**Comment by samyeaman** [comment]
No problem. I should just figure out how to implement it in msprime -- have
been meaning to do so for a while anyway. Thanks!
