### ISSUE TITLE
SVG tree object not displayed

### ISSUE THREAD

**Issue by eldonb** [tskit-dev/msprime#1320]
In case this helps:  following the first  few  lines in the tutorial, the SVG tree object is not  displayed:

ipython3 
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import msprime

In [2]: 

In [2]: from IPython.display import SVG

In [3]: from IPython.display import display

In [4]: ts=msprime.sim_ancestry(3)

In [5]: SVG( ts.draw_svg())
Out[5]: <IPython.core.display.SVG object>

and the tree is not  displayed -  
am I missing  a python library ?

**Comment by jeromekelleher** [comment]
I think you need to do this in a Jupyter notebook rather than an IPython shell @eldonb.

Try ``print(ts.draw_text())`` - this works well for us CLI people!

**Comment by eldonb** [comment]
yes, works; will close this
thanks @jeromekelleher
