### ISSUE TITLE
github pages double scrollbar in chrome

### ISSUE THREAD

**Issue by grahamgower** [tskit-dev/msprime#1325]
When using chrome to view the docs hosted on github pages, I see two scrollbars for any page that is long enough to need scrolling. However, when viewing the locally-built docs, only one scrollbar is visible. The additional scrollbar is always disabled. I don't see this issue with Firefox.

Github pages, with two scrollbars (note also the version number is wrong here):
![2-bars](https://user-images.githubusercontent.com/8665077/100715583-b134ee80-33b7-11eb-8106-09e48cd76dd5.png)

Locally-built, with one scrollbar:
![1-bar](https://user-images.githubusercontent.com/8665077/100715601-b5f9a280-33b7-11eb-9067-594dbaf8eed3.png)

**Comment by jeromekelleher** [comment]
Weird.

**Comment by jeromekelleher** [comment]
@grahamgower, do you still see this now we've moved to JupyterBook? https://tskit.dev/msprime/docs/latest/

**Comment by grahamgower** [comment]
Nope, the latest site looks as it should!
