### ISSUE TITLE
'Demography' object is not iterable

### ISSUE THREAD

**Issue by eldonb** [tskit-dev/msprime#1326]
import msprime
phylogeny = msprime.parse_species_tree(tree="(popA:1.0,popB:1.0)",Ne=1000)
print(phylogeny)

Demography(populations=[Population(initial_size=1000.0, growth_rate=0.0, name='popA', description=None, temporary_hack_for_metadata=None), Population(initial_size=1000.0, growth_rate=0.0, name='popB', description=None, temporary_hack_for_metadata=None)], migration_matrix=array([[0., 0.],
       [0., 0.]]), events=[MassMigration(time=1.0, source=1, dest=0, proportion=1.0)])

for p in phylogeny:
    p.sample_size=2

TypeError                                 Traceback (most recent call last)
<ipython-input-9-4b3c75329d9a> in <module>
----> 1 for p in phylogeny:
      2     p.sample_size=2

TypeError: 'Demography' object is not iterable

**Comment by jeromekelleher** [comment]
There's some work outstanding on this API @eldonb (#1072) but it's not intended to return a *tree* as such, rather the demographic model defined by the species tree. So, if you wanted to look at the populations in the model, you'd do ``print(demography.populations)`` etc. I'm not sure what the right semantics would be to made a Demography iterable.

For what you want to do here (setting the sample size) I think you would want

```python
demography = msprime.parse_species_tree(tree="(popA:1.0,popB:1.0)",Ne=1000)
samples = demography.sample(2, 2) # Two from each leaf population
# Warning - this is diploid by default, so there'll be 8 sample nodes in the tree unless ploidy=1
ts = msprime.sim_ancestr(samples, demography=demography)
```
Does this do what you want?

This isn't documented at the moment, so it's not surprising you're hitting these problems!

**Comment by eldonb** [comment]
yes,  thanks: I was  following an old  documentation on this;
I will try to make a note on this in the documentation.
 
one thing:  setting  unequal branch lengths does not produce any  errors or warnings:
import msprime
from IPython.display import SVG
phylogeny = msprime.parse_species_tree(tree="(popA:100.0,popB:10.0)",Ne=1000)
print(phylogeny)
samples=phylogeny.sample(2,1)
print(samples)
ts=msprime.sim_ancestry(samples, demography=phylogeny)
SVG(ts.draw_svg())

will close this,  and  have a look at the code
thanks @jeromekelleher

**Comment by jeromekelleher** [comment]
> one thing: setting unequal branch lengths does not produce any errors or warnings:

Hmm, this is probably a bug. We're not dealing with the idea of sampling time very well here - presumably the interpretation here is that one population "starts" at an older time point, and so it's default sampling time should be that time?

**Comment by eldonb** [comment]
yes,  given  that  the branch lengths  are   different,  but  there is really no way to know  if that is what is meant,  or  
if it was a  mistake in the input - 
I will open a new issue for this
