### ISSUE TITLE
cli.py

### ISSUE THREAD

**Issue by jarrodhadfield** [tskit-dev/msprime#1327]
Hi Jerome,

The addition of  zlib_compression=args.compress  to tree_sequence.dump has created problems on my system (mac OS 10.15.7 & python3.9.0_2):

TypeError: dump() got an unexpected keyword argument 'zlib_compression'

Its probably a problem at my end, but I can't find a fix!

Cheers,

Jarrod

**Comment by jeromekelleher** [comment]
Hi Jarrod! Nope, this is a bug in tskit which should't have removed the option. We'll push out a bugfix asap. 

Thanks for the report!

**Comment by jeromekelleher** [comment]
A quick fix @jarrodhadfield is to downgrade your tskit version to 0.3.2: ``python3 -m pip install tskit==0.3.2``.

**Comment by jeromekelleher** [comment]
This should be fixed now @jarrodhadfield, we just released a bugfix version of tskit: https://github.com/tskit-dev/tskit/releases/tag/0.3.4

Upgrade with ``python3 -m pip install tskit --upgrade``

ps. Great to see you using msprime - let me know if you have any feature requests!
