### ISSUE TITLE
Logo ideas

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/msprime#1331]
It would be good to have consistent logos across tskit. The current ones we have are:

![tskit](https://raw.githubusercontent.com/tskit-dev/administrative/main/tskit_logo.svg)

and

![tsdate](https://raw.githubusercontent.com/tskit-dev/tsdate/master/docs/_static/tsdate_logo.svg)

**Comment by benjeffery** [comment]
Here's my idea:
![circle32](https://user-images.githubusercontent.com/8552/101000815-4837ad00-3556-11eb-8597-490e44f53f41.png)

**Comment by jeromekelleher** [comment]
Looks great, I LOVE the dice! 

I worry it's a bit too rectangular though, and won't work when it's cropped to a circle/forced into a square. We could do something around ``ms'`` (i.e., a mathematical prime symbol, which was the original idea - it's like ms, only different).

**Comment by hyanwong** [comment]
Here's my riff on @benjeffery 's theme, which is a bit squarer, I guess

![mp-hyw](https://user-images.githubusercontent.com/4699014/101016153-48d54100-3560-11eb-9428-06f4e3f2645c.png)

SVG for Ben here:

[mp-hyw.svg.zip](https://github.com/tskit-dev/msprime/files/5635935/mp-hyw.svg.zip)

**Comment by hyanwong** [comment]
Here was another idea I thought of, but only put a crappy version together: use the "m" as a tree:

![image](https://user-images.githubusercontent.com/4699014/101017044-7bcc0480-3561-11eb-91bc-a330d08b259b.png)

**Comment by jeromekelleher** [comment]
Loving the two above @hyanwong. Not so sure about the tree-as-m, though.

**Comment by hyanwong** [comment]
Yeah, I though it didn't quite work either. Here's a better version on the same theme. Still not as good as my first ones, I think:

![mp-hyw-tree-m](https://user-images.githubusercontent.com/4699014/101018510-84bdd580-3563-11eb-978f-2d06ee1877d8.png)

**Comment by hyanwong** [comment]
> Loving the two above @hyanwong.

I like having the (pair of) dice *above* the tree, as it looks like the randomness is generating the tree itself.

**Comment by petrelharp** [comment]
Damn, those look nice.

**Comment by benjeffery** [comment]
We might get a more square logo if we renamed to `tsms` but it's too late for that!

**Comment by hyanwong** [comment]
> We might get a more square logo if we renamed to `tsms` but it's too late for that!

Turkish State Meteorological Service?

https://acronyms.thefreedictionary.com/TSMS

**Comment by eldonb** [comment]
maybe rotate the tree  counterclockwise 90 degrees  and use it for the 'e' in msprime, 
sort of reading msprime as 'msprimE',  this might require modifying the tree a little

**Comment by hyanwong** [comment]
> maybe rotate the tree counterclockwise 90 degrees and use it for the 'e' in msprime,
> sort of reading msprime as 'msprimE', this might require modifying the tree a little

Nice thought @eldonb . Fancy hacking something together?! :)

**Comment by hyanwong** [comment]
> yes - happy to contribute as I can
> I suppose the source files are on github,
> and you simply use some figure processing package for this ?

Easiest to grab the SVGs or PNGs posed in this thread - there's nothing pushed to GitHub yet. But you only need to make something that is roughly what you think looks OK. No need to make a perfect final version, so you can just hack the PNG file if you like. We can always make vector versions if everyone decides they like your version most!

**Comment by eldonb** [comment]
a simple latex hack as a first try (the source code is below):

[msprimelogo.pdf](https://github.com/tskit-dev/msprime/files/5667334/msprimelogo.pdf)


\documentclass{article}
\usepackage[T1]{fontenc}
%\usepackage{lmodern}
\usepackage[utf8]{inputenc}
\usepackage{pifont}
\RequirePackage{fix-cm}
%%\usepackage{times}
%%\usepackage{tgbonum}
%%\usepackage{biblatex}
%%\usepackage{helvetica}
\usepackage{amsmath, amsfonts, amssymb, amsthm}
%%\usepackage{amsthm}
\usepackage{epsfig,graphicx,color}

\DeclareFontFamily{U}{dice3d}{}
\DeclareFontShape{U}{dice3d}{m}{n}{<-> s*[4] dice3d}{}

\begin{document}

%\Pisymbol{dice3d}{102}

%{\usefont{U}{dice3d}{m}{n}6a 2b 3d}


\begin{picture}(50,50)
\put(20,0){\textcolor{cyan}{{\usefont{U}{dice3d}{m}{n}6a}}}
\put(30,0){\rotatebox{34}{\textcolor{cyan}{{\usefont{U}{dice3d}{m}{n}2b}}}}
\put(-10,0){\scalebox{2}{\textcolor{blue}{\textbf{ms}}}}
\put(-10,-15){\scalebox{2}{\textcolor{blue}{\textbf{prim}}}}
\linethickness{1mm}%
\put(45,5){\textcolor{cyan}{\line(1,0){10}}}%
\put(45,-5){\textcolor{cyan}{\line(1,0){10}}}%
\put(45,-5){\textcolor{cyan}{\line(0,1){10}}}%
\put(40,0){\textcolor{cyan}{\line(1,0){5}}}%
%%
\put(40,-15){\textcolor{cyan}{\line(1,0){15}}}%
\put(40,-15){\textcolor{cyan}{\line(0,1){15}}}%
\end{picture}


\pagestyle{plain}\thispagestyle{empty}
\end{document}

**Comment by hyanwong** [comment]
Thanks @eldonb . For ease of reference for others, the png looks like this: 
<img width="163" alt="Screenshot 2020-12-09 at 21 27 06" src="https://user-images.githubusercontent.com/4699014/101690530-4cd3f800-3a65-11eb-8f86-87f2c02e7557.png">

**Comment by hyanwong** [comment]
Generally agreed version now at https://github.com/tskit-dev/msprime/blob/main/msprime_logo.svg
