### ISSUE TITLE
Rename/replace Demography.simple_model

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1333]
This is quite a useful method as it allows us to create simple models with varying sizes and growth rates. The name isn't very good though. One idea was to call it ``isolated``, as it creates a bunch of isolated populations? Or should we change the semantics of ``island_model`` to accept an array of population sizes and growth rates rather than the current approach?

Should be settled before alpha release, anyway.

**Comment by grahamgower** [comment]
What are the isolated populations used for? It doesn't seem so useful in practice, so is it mainly for tests?
```python
>>> import msprime
>>> d = msprime.Demography.simple_model([1,1])
>>> msprime.sim_ancestry(demography=d, samples=d.sample(1,1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/grg/src/msprime/msprime/ancestry.py", line 1160, in sim_ancestry
    return _wrap_replicates(
  File "/home/grg/src/msprime/msprime/ancestry.py", line 715, in _wrap_replicates
    deque = collections.deque(iterator, maxlen=1)
  File "/home/grg/src/msprime/msprime/ancestry.py", line 1366, in run_replicates
    self.run()
  File "/home/grg/src/msprime/msprime/ancestry.py", line 1336, in run
    self._run_until(end_time, event_chunk, debug_func)
  File "/home/grg/src/msprime/msprime/ancestry.py", line 1299, in _run_until
    while super().run(end_time, event_chunk) == _msprime.EXIT_MAX_EVENTS:
_msprime.LibraryError: Infinite waiting time until next simulation event.
```

**Comment by jeromekelleher** [comment]
Good question. I've found it useful for making a basic model that can then be elaborated on with a few extra events. But you're right, it probably is most useful for making tests.

Perhaps the thing to do is change ``island_model`` and ``stepping_stone_1d`` to have the parameter semantics that I've given ``simple_model`` here, so that rather than num_demes as the first positional parameter we have an array of population sizes. ``Demography.island_model([Ne] * num_demes)`` isn't that much more obscure than ``Demography.island_model(num_demes, Ne=Ne)`` and it's *much* more flexible.

**Comment by jeromekelleher** [comment]
Hah - we could change ``stepping_stone_1d`` to just ``stepping_stone`` and derive the number of dimensions in the model from the input array shape. So, a 1D array of population sizes gives a 1D stepping stone, 2D array 2D stepping stone, etc. Wouldn't bother actually implementing the 2D one for now, but the idea is there.
