### ISSUE TITLE
HTML output for Demography

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1344]
We'd like to have a reasonably clear output for Demography objects appear in notebooks via repr_html. 

See also #1343.

@benjeffery, you're the maestro here, I'm going to tag you for this one!

**Comment by benjeffery** [comment]
Doh sorry I didn't get to this before you!

**Comment by jeromekelleher** [comment]
No worries, I was probably the best person to take the first pass at this anyway. Feel free to jazz it up though!
