### ISSUE TITLE
Fix MsMs sweep verification tests

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1365]
I disable the MsmsSweeps tests because they were unreliable (looks like some simulations were ocassionally returning no data).

We probably just need to make these more robust.

**Comment by jeromekelleher** [comment]
What are the thoughts on the MsmsSweeps tests @gbinux @andrewkern? We need to get the stats suite robust now in the run up to release.

**Comment by andrewkern** [comment]
i don't think we need the msms tests-- we've got discoal and SLiM agreeing with the msprime implementation

**Comment by jeromekelleher** [comment]
@gbinux, any thoughts?

**Comment by gbinux** [comment]
@jeromekelleher I can spend some time on this to see whether it fits well in the comparisons. If it does, it is good to have it; if not, we can get rid of this.

**Comment by jeromekelleher** [comment]
Closed in #1561
