### ISSUE TITLE
Artefact upload to pypi failed

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1368]
Looks like there's some issue with the tokens use for uploading to pypi

https://github.com/tskit-dev/msprime/actions/runs/488371945

No problem popping out a 1.0.0a2 release, this is what alphas are for.

**Comment by benjeffery** [comment]
Upload now works - but I think it needs an alpha 2 as uploading the sdist failed as it had already been uploaded, I guess manually?

**Comment by jeromekelleher** [comment]
OK, I'll tag alpha2.

**Comment by jeromekelleher** [comment]
Fixed.
