### ISSUE TITLE
population_size parameter is not documented in sim_ancestry

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime#1384]
This is particularly confusing as it used to be called Ne, I presume. As well as adding to the doctoring, might it be an idea to allow Ne as a (deprecated) parameter, or at least if Ne is provided, to raise an error to say "use the `population_size` parameter instead"?

**Comment by jeromekelleher** [comment]
We should document it all right, but I'm against adding ``Ne`` - it caused a lot of confusion, and it's not compatible with things like the DTWF.

**Comment by hyanwong** [comment]
Can we just spit out an error that says "don't use Ne - the new way is to specify population_size"? Presumably that can't harm?

**Comment by jeromekelleher** [comment]
Doesn't do any harm, I guess, but it's added complexity for not that much gain. The signature of sim_ancestry will probably gain lots more parameters over time, and this 1.0 break is our chance to have a clean slate. If we do errors for Ne, then why not for ``population_configurations`` and for every other ``simulate`` parameter? Then, we end up with an unreadable function signature.

**Comment by hyanwong** [comment]
Fair enough. It confused me at first, though, especially as it's probably one of the most common parameters to use (I assume nearly everyone will use that). Also Ne is a pretty established terminology in population genetics, so a newbie might try this out even before reading the docs. Maybe ask on Slack what others think?

**Comment by jeromekelleher** [comment]
Do you think it's worth have ~10 extra parameters in the signature?

**Comment by hyanwong** [comment]
No, I meant that `Ne` was a special case (because it's so commonly used, and such a standard abbreviation). I wouldn't bother with any of the other ones.

**Comment by petrelharp** [comment]
I think if someone uses `Ne`, it fails (no  special error), they look at the docs, and see a parameter called `population_size`, then they'll use that, no problem.

**Comment by jeromekelleher** [comment]
Agreed. Let's not add complexity to the code to cover this.

**Comment by jeromekelleher** [comment]
Ooops, reopening because we still need to document population_size

**Comment by jeromekelleher** [comment]
Also need to mention Ne -> population_size in "upgrading from 0.x" section
