### ISSUE TITLE
Simple pedigree simulator for testing

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1391]
It would be useful to have a (very!) simple pedigree simulator for testing. This doesn't need to be realistic in any way, we just want it to produce some small pedigrees that we can use for testing.

I guess ultimately we could get the DTWF to actually store the pedigree too, but that's not something that we can do without a fair bit of work.

**Comment by petrelharp** [comment]
It's not what you're looking for here, but just so you're aware in case it's helpful: you can use [pyslim's `individual_parents`](https://pyslim.readthedocs.io/en/latest/python_api.html#pyslim.SlimTreeSequence.individual_parents) to find out who is whose parent in a SLiM simulation (you need to Remember previous generations to ensure they're still around).

**Comment by jeromekelleher** [comment]
Closed in  #1738
