### ISSUE TITLE
Update installation docs

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1393]
The [installation page](https://tskit.dev/msprime/docs/latest/installation.html) needs a refresh for 1.0

- [ ] Change references to Python 3.6 to 3.7
- [ ] Update pip installation instructions to remove requirement on GSL
- [ ] Add a subsection to the pip section "Build from source". Move the information about GSL into this section. Give it a label so that we can refer to this information about GSL from the development page, also.
- [ ] Refresh the conda section with output from a recent conda transation, and update the example to use more modern APIs (i.e., use sim_ancestry and ``ts.draw_text()``)

I'm not totally sold on the "Via" prefix to the sections here, maybe we could rename these to "Conda", "Pip" and "Containers"?

**Comment by castedo** [comment]
I'm familiar with this page. You can assign it to me if nobody else wants to pick it up.

@jeromekelleher What comes to mind when you read "Via ____"? or ... what reaction do we imagine new readers have when they read "Via ___"?

A possible downside to just having the TOC/titles reading "Conda", "Pip" "Containers" is that new readers initially mentally read those as "How to install X" or the new reader doesn't know what X is and is not sure how it even relates to msprime.

**Comment by jeromekelleher** [comment]
That'd be great, thanks @castedo - consider yourself assigned!

It's not a strong opinion on the section names, it just looks a bit strange to my eyes. It's not worth discussing further if you disagree.

**Comment by jeromekelleher** [comment]
Wait for #1935 to merge, though, as I've converted the file to markdown there.
