### ISSUE TITLE
Show version number in the  documentation.

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1396]
Need to show the version number somewhere in the docs. Preferably in the title, but wherever we can display it using JupyterBook.

**Comment by jeromekelleher** [comment]
Partial solution in #1408, which gets the version number by registering a custom sphinx module and setting the ``version`` config value in the setup. This is a bit of a hack, but there doesn't seem to be any other way to execute Python code during build, otherwise.

This means the value is only available via rst (and eval-rst blocks) which limits how we use it. In particular it means we can't get the version into a title string, and so it won't be displayed in the left sidebar.

Unless we can display in a page footer via the sphinx config or something, I think this is probably as good as we'll do, but I'm going to leave the issue open for the moment.

**Comment by benjeffery** [comment]
If the version string is somewhere (hidden on the page) it can be copied anywhere we want with a little JS snippet.

**Comment by benjeffery** [comment]
Actually, the simplest thing might be to do a search and replace after the build as part of the make file.
