### ISSUE TITLE
Set mutation times to null for 0.x APIs

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1399]
The main thing that's breaking code in tskit's test suite when using msprime 1.0.0a3 is the fact that ``simulate()`` and ``mutate()`` now return times for mutations. On the one hand, it's clearly and improvement that we now have times for mutations, but on the other since it's looking like the 0.x APIs are really just going to be kept for supporting legacy code (I can't see any good reason for recommending new users to use them; it's just too confusing from a docs perspective).

The reason the tskit code is breaking is because of a defect in the tables APIs that means we can't add entire rows to a table (https://github.com/tskit-dev/tskit/issues/1111). When we do things like 

```python
copy = tables.copy()
do_something_to_copy(copy)
assert copy == tables # Fails because copy doesn't have mutation times
```

So, in the interest of being as compatible as possible, I suggest we set the mutation times for these legacy APIs to null. If someone wants to use the times, then this is a good motivation to upgrade their code to 1.0.

Any objections? cc @petrelharp @benjeffery

**Comment by petrelharp** [comment]
Hm, I'm not so sure - would this be a problem for anything other than testing for equality in our unit tests? It's hard to imagine how providing some extra information would break anyone's code otherwise. Leaving out times would make it harder for people to, say, do minor upgrades to previous scripts to take advantage of mutation times. Maybe that's good because they get motivated to switch to 1.0 for reals, but it kinda seems like an unnecessary barrier.

A stop-gap would be to just assign the `time` column to be null before problematic asserts like that in the tskit test suite.

**Comment by jeromekelleher** [comment]
I don't think there's an obvious right or wrong answer here @petrelharp, so I'm happy to go with your take. My feeling was that we should do our best to minimise breakage though (as being more important that letting people do new things with the 0.x code). I agree it's hard to imagine how people might get caught out by this, but code breakage does tend to be unexpected.

I don't mind breaking the tskit tests, that's easy to fix, I just don't want to break other people's code, who might be doing similar things.

**Comment by petrelharp** [comment]
Well, that's still my gut feeling, but happy to go the other way.

It also seems like a confusing bit of complexity in the documentation.

**Comment by benjeffery** [comment]
This is an instance of a larger question of whether the legacy APIs are "frozen", or just a thin compatibility wrapper around the current, evolving, methods. A similar question might come up with pedigree recording for example?

I err towards the "frozen" option as it gives greatest compatibility. I guess if we hadn't made new API methods we would have had to have included the mutation times and broken things. 

I'm not following the `copy` example though - I thought that used the lwt?

**Comment by jeromekelleher** [comment]
> This is an instance of a larger question of whether the legacy APIs are "frozen", or just a thin compatibility wrapper around the current, evolving, methods. A similar question might come up with pedigree recording for example?

I'd vote strongly for "frozen". It's so much harder having to come up with two different compatible ways of doing things, **and** having to worry about the possibility of breakage of (lots of) existing code. For example, with pedigree recording, we'd have to do a lot of extra work to add support for that in simulate. Why create extra work for ourselves, and increase the probability of breaking old code? 

So, mutation times is a >= 1.0 feature, and therefore simulate()/mutate() don't have them. If someone really wants them down the line, we can always add a boolean flag ``include_mutation_times=False``.

> I'm not following the copy example though - I thought that used the lwt?

It's not the copy that's the problem, it's the ``do_something_to_copy``, which uses, say, some ``mutation_table.add_row(...)`` without specifying anything for the ``time`` column, and so this column is silently lost.

**Comment by petrelharp** [comment]
Happy to go with your intuition here!

**Comment by jeromekelleher** [comment]
I think it'll make us significantly less likely to break older versions of msprime with newer versions of tskit, if we keep the old behaviour for simualte().

**Comment by jeromekelleher** [comment]
Just to finish up the discussion here: we can't null out the column because this will break old code that uses ``mutate(...keep=True)``, which is a definitive answer I think.
