### ISSUE TITLE
Make nucleotides the default output for sim_mutations

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1403]
I don't think there's any good reason to output 0/1 any more - it causes many more problems than it solves, and the information about ancestral and derived states is maintained within the table structure.

So, we keep ``mutate()`` as it is, outputting 0/1 alleles, but we change ``sim_mutations`` to do what the vast majority of people want, by default.

(I thought there was another issue relating to this, but couldn't find it)

**Comment by petrelharp** [comment]
Sounds good.
