### ISSUE TITLE
Clean up mutations/models docs

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1410]
#1409 made a small update to the mutations part of the docs. There's a few updates that we need to make to bring the "models" section up to date:

- Make sure we use sim_mutations and sim_ancestry in all the examples
- Update the examples to use jupyter code blocks (see the ancestry.md page for examples to follow here) and delete the old images from the repo

**Comment by awohns** [comment]
Happy to address this! I happened to be working with the new mutation models this week anyway

**Comment by awohns** [comment]
The `msprime.SLiMMutationModel` example includes a parameter called `allow_ancestral`. I can't find where this is documented, does it now exist anymore?

**Comment by petrelharp** [comment]
See https://github.com/tskit-dev/msprime/issues/1206#issuecomment-768562378 for the proposal on this (and documentation).

**Comment by awohns** [comment]
Ah great, thanks @petrelharp

**Comment by awohns** [comment]
Another point, maybe I'm missing something but the SVG and the text of "Infinite Alleles Mutation Models" don't match up. My understanding is that the SVG should be labelling mutations by the derived state and showing that multiple mutations have the same derived state, but this isn't what's shown

**Comment by petrelharp** [comment]
I meant that five of the samples inherited allele 13, etcetera.

**Comment by awohns** [comment]
Don't 8 samples inherit allele 13?

**Comment by petrelharp** [comment]
Heh, this is exactly why I put that sentence in, to make the reader notice things like it being a single site. =) But, clearly it needs to say what's going on a bit more explicitly.

**Comment by awohns** [comment]
Right now the mutation models are listed twice in the mutations section: once in the "Quick reference" and once in "Models". Do we want to keep this duplication?

**Comment by jeromekelleher** [comment]
No, probably not.
