### ISSUE TITLE
CLI section refresh

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1420]
The [CLI docs](https://tskit.dev/msprime/docs/latest/cli.html) section needs a refresh and update. Some information is out of date.

@winni2k, you're the closest thing to a CLI expert here, would you be able to pick this one up at some point (not urgent)? 

The new [documentation docs](https://tskit.dev/msprime/docs/latest/development.html#documentation) should help orient you with the new way things are done.

**Comment by winni2k** [comment]
Can do!

**Comment by jeromekelleher** [comment]
Bumping this one also - any chance you can pick this up soon please @winni2k?

**Comment by winni2k** [comment]
Will sort this one out today or tomorrow as well. Cheers.
