### ISSUE TITLE
Add citation for DTWF paper to Citations

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1426]
Need to add something like "Additionally, If you use the DTWF model please cite [this paper](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1008619) to the [citing msprime](https://tskit.dev/msprime/docs/latest/CITATION.html) page.

Also, we should link to this paper in both the docstring and the example model docs, asking people to cite it there as well.

@apragsdale, you should be motivated for this one; any chance you'd pick it up?!

**Comment by apragsdale** [comment]
I can handle adding the citations, yes.
