### ISSUE TITLE
SweepGenicSelection model needs documentation

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1430]
We currently have no documentation for the SweepGenicSelection model. Assuming we are able to resolve the issues that we have with validation (#1173), we will need to have 

- Formal definitions of the model in the docstring (see the [BetaCoalescent](https://tskit.dev/msprime/docs/latest/api.html#msprime.BetaCoalescent) as what we should be aiming for)
- Some examples explaining what the model does and how to use it in the [examples section](https://tskit.dev/msprime/docs/latest/ancestry.html#selective-sweeps). Again, the lambda coalescents are showing the way here.

@andrewkern, @gbinux are either of you on for filling this in? @andrewkern, writing the formal definition might actually help you track down the scaling issue in #1173...

**Comment by gbinux** [comment]
Hi @jeromekelleher, just jumped out from the swamp of classes and qualifying exams. I would like to continue to work on the selection functionality and related documentation. I am very new to the documentation side, any tutorial on documentation (I know the quick edit way via webpage).

**Comment by andrewkern** [comment]
yup @jeromekelleher- i'm on it starting first thing tomorrow AM

**Comment by jeromekelleher** [comment]
Excellent! @gbinux, I think it would be great if you could think about illustrating the sweep code with a few simple examples in [this section](https://tskit.dev/msprime/docs/latest/ancestry.html#selective-sweeps). 

The [developer documentation](https://tskit.dev/msprime/docs/latest/development.html#documentation) will hopefully help you get started with writing docs @gbinux.

@andrewkern, I think you're best placed to write down the formal definition.
