### ISSUE TITLE
Change branch_length_units in from_species_tree and from_starbeast to time_units

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1435]
This is easier to understand, more concise and consistent with the [demes](https://popsim-consortium.github.io/demes-spec-docs/main/spec.html) specification that we'll us using soon.

Should be a simple find and replace, since we haven't released this code.

**Comment by cdquinto** [comment]
in which file should these terms be replaced?

**Comment by jeromekelleher** [comment]
In ``demography.py``, on these two functions. Running the tests should then let you mop up the rest of the breakage.

Thanks!

**Comment by cdquinto** [comment]
I'm tackling this again. I replaced **branch_length_units** to **time_units** `demography.py`. However the function `from_species_tree` and its parameters are referenced in `ancestry.md` and `demography.md`. I changed to **time_units** in those files as well, and I am getting this error:
`ESC[0;31mTypeErrorESC[0m: parse_species_tree() got an unexpected keyword argument 'time_units'
TypeError: parse_species_tree() got an unexpected keyword argument 'time_units'`. 

I tried making msprime again and running the tests with `python3 -m nose -vs` but other errors showed up.

**Comment by jeromekelleher** [comment]
Sounds good, thanks @cdquinto. If you open a PR we should be able to see how things are going and see how to fix.

ps. We're using pytest rather than nose now: you should be running ``python3 -m pytest`` to run the tests.

**Comment by jeromekelleher** [comment]
Closed in #1475
