### ISSUE TITLE
Add verification tests for adding ancestral mutations

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1441]
There are currently none.

See #1440 and #1434 for background on where we're add with adding mutations on top of existing ones.

@petrelharp, any suggestions for what we should do here? I guess doing sim_mutations twice at rate x should be the same as once at rate 2x, across all supported models is a good start?

**Comment by petrelharp** [comment]
Yup.  And that putting mutations ancestral to some time and then putting mutations since that time is equivalent to just putting down mutations. I guess that "the same as" could be measured by similarity of (a) the allele frequency spectrum, and (b) the distribution of inter-site distances.

**Comment by jeromekelleher** [comment]
Might have been premature to close this one in #1548 as the tests just look at counts of mutations. We might want something a bit more robust @petrelharp, @GertjanBisschop?
