### ISSUE TITLE
Improve HTML output structure for DemographyDebugger

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1462]
#1443 added an intitial pass at HTML output for the DemographyDebugger object. Here's an example:

![Screenshot from 2021-02-02 12-20-19](https://user-images.githubusercontent.com/2664569/106599498-0d032b80-6551-11eb-8ac9-fe7991fa14db.png)

The basic structure of a set of epochs, which each contain a table describing the current population state and the events that happen at the end of the epoch (to transform it into the next one) is good, I think. It can certainly use some refinement, though. Here are some issues:

- Its currently structured as a ``<div>`` containing a set of paragraphs, one for each epoch. The paragraph then has a ``<h3>`` for the title and two tables for the detailed info. Is this a good way to do it?
- Like the Demography object (#1461) there's no visual separation of the content from the rest of the page. Should we draw a box around it? (Also see next point)
- The visual distinction between epochs isn't strong enough. Should we structure it as a table, where each row is an epoch?

Also, the population state table isn't quite right:
- The first column should really be bolded to match the header for the populations (make them ``<th>`` elements?)
- The "migration matrix" bit should be separated more clearly from the population sizes (maybe a vline after the growth_rate col?)
- It would be nice to have a header "Migration rates" centered over the migration rates section of the table.

These updates aren't really compatible with the current ``html_table`` function, so that would need to be updated a bit.

The old text format might be helpful here, see e.g. [https://msprime.readthedocs.io/en/latest/tutorial.html#debugging-demography](here)

@benjeffery, any thoughts on what would be good here?

**Comment by benjeffery** [comment]
A some simple tweaks would be to shade the background of the matrix cells, make the column headers vertical to make the matrix square, also decode the `source` and `dest` to names if possible.

A more ambitious thing might be to draw a timeline?

Happy to have a pass at this when I'm done with the tskit C release.

**Comment by jeromekelleher** [comment]
Sounds good, assigning you. I considered using an ipython [accordion](https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html#Accordion) widget to display the info, but decided against it because we want to have all the information displayed when we're using this in the Jupyter book for docs (which is a key use case). Looks like the Accordion can only have one tab open at a time, so that rules that out.

I'm working on getting the information that we need to display down in the text version in #1464, so it's good to let this marinade for a bit while we think about it. The current display is good enough for writing docs around, anyway.

**Comment by benjeffery** [comment]
You can use html's native `<summary>` tag to achieve a similar effect. We use this in tskit metadata.

**Comment by jeromekelleher** [comment]
Went down the ``<details>`` route in #1503 - it's good enough for now.
