### ISSUE TITLE
Problems compiling docs with jupyter-book 0.10.0+

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime#1467]
The `msprime` docs compile with jupyter-book 0.9.0, but on jupyter-book 0.10.0 (which requires `myst-nb~=0.11.1` and `myst-parser~=0.13.3`), I get:

```
myst_extended_syntax is deprecated, instead specify extensions you wish to be enabled. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
===============================================================================
Running Sphinx v3.3.1
WARNING: myst configuration invalid: unhashable type: 'list'
```

And various markdown items, such as `:::{warning} Here is a warning :::` do not compile correctly.

**Comment by jeromekelleher** [comment]
We should bump our dependencies and let devs know I think. The fix will be easy, I'd say.
