### ISSUE TITLE
probable bug when passing RateMap to sim_mutations

### ISSUE THREAD

**Issue by awohns** [tskit-dev/msprime#1470]
I got unexpected behaviour when writing an example of using a ratemap with `sim_mutations`. Below I simulate 1 Mb of sequence with 1000 individuals and throw mutations down with a rate of 1e-8. I then plot the number of mutations appearing in 10 kb chunks. If I instead use a RateMap with a uniform rate of 1e-8 but 50 intervals of uniform size, we get very different results.

Seems there's something off about the way mutations are placed using a RateMap. Proposed unittest to check for correct behaviour is a statistical test that the distribution of mutations is the same when using a uniform map with 1 interval (equivalent to passing a float) and when using a ratemap with uniform rate but many intervals, as shown here. 

```python
import msprime
import numpy as np
import matplotlib.pyplot as plt
sim = msprime.sim_ancestry(1000, sequence_length=1e6, recombination_rate=1e-8, population_size=10000, random_seed=1)
sim = msprime.sim_mutations(sim, rate=1e-8, random_seed=1)
bins = np.arange(0, sim.get_sequence_length(), 1e4)
bin_counts = np.unique(np.digitize(sim.tables.sites.position, bins), return_counts=True)
plt.scatter(bins, bin_counts[1], label="using float")

pos = np.linspace(0, int(sim.get_sequence_length()), 50)
rate = np.repeat(1e-8, 49)
mut_map = msprime.RateMap(pos, rate)
sim = msprime.sim_mutations(sim, rate=mut_map, random_seed=1)
bins = np.arange(0, sim.get_sequence_length(), 1e4)
bin_counts = np.unique(np.digitize(sim.tables.sites.position, bins), return_counts=True)
plt.scatter(bins, bin_counts[1], label="using RateMap")
plt.xlabel("Position")
plt.ylabel("Mutations in 10kb bin")
plt.legend()
```
![image](https://user-images.githubusercontent.com/10664424/107108785-8a20f000-6832-11eb-9c67-4be661aed9af.png)

**Comment by jeromekelleher** [comment]
Thanks @awohns, certainly looks like a bug to me. We should add this something like this check to the ``verification`` script for mutations.

**Comment by petrelharp** [comment]
Wow, that's a bad one. I think the problem is because we [look up the mutation rate for the left end of each edge](https://github.com/tskit-dev/msprime/blob/8ff725c75bf7a62e89c1dae50a5a6c7e48caba7f/lib/mutgen.c#L1143) and fail to account for the fact that the mtuation rate may change over the edge. (I think we said early on "let's get it working for a uniform rate first" and forgot to come back to it?)

**Comment by awohns** [comment]
Hmm, I wonder if that's it though @petrelharp as it fails here even when the mutation rate does not change over the edge (as in this example)?

**Comment by petrelharp** [comment]
Whoo, glad you caught this. I can fix it up, if you like.

**Comment by awohns** [comment]
Fantastic, thanks @petrelharp!
