### ISSUE TITLE
Update DemographyDebugger numerical methods to use new events

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1480]
#1478 added the PopulationSplit event, and numerical methods in the DemographyDebugger like coalescent rate trajectories, etc, need to be updated.

Probably best to wait until we've finished shaking down the Demography API (e.g., #1479)

@apragsdale, you're pretty close to this, do you think there's much involved here?

**Comment by apragsdale** [comment]
I don't think there would be too much involved. But yes, I agree we should let all dust around the Demography API to settle first and then tackle this, which I could return to at that point.
