### ISSUE TITLE
Demographic (Legacy Version) Sample Size Parameter  Bug?

### ISSUE THREAD

**Issue by marcustutert** [tskit-dev/msprime#1495]
Hi,

I am trying to use msprime 1.0.0a4 to run some of my demographic models I used on the non-dev verison of msprime, specifically a population split some time ago t at the past which results in two descendant (split) populations.

Here is how I previously coded this up:
```
ngwas_haps         = 5000
nref_haps          = 5000
nref_replicates    = 19
total_samples      = nref_replicates * nref_haps + ngwas_haps
divergence_time    = 10

Ne_A = 10000
Ne_B = Ne_A/2 #Define the population split size (in terms of Ne's). This is the REFERENCE PANEL POP
Ne_C = Ne_A/2 #Define the population split size (in terms of Ne's). This is the GWAS PANEL POP.

population_configurations = [
      msprime.PopulationConfiguration(
          sample_size  = 0,
          initial_size = Ne_A),
      msprime.PopulationConfiguration(
          sample_size  = int(nref_haps),
          initial_size = Ne_B), #Reference panel size
      msprime.PopulationConfiguration(
          sample_size  = int(ngwas_haps),
          initial_size = Ne_C) #GWAS panel size
]
 
demographic_events = [
  msprime.MassMigration(
      time         = divergence_time,
      source       = 2,
      destination  = 0,
      proportion   = 1.0),
  msprime.MassMigration(
      time         = divergence_time,
      source       = 1,
      destination  = 0,
      proportion   = 1.0),
]
```

I would run this with msprime.simulate() and it would work as expected, and I would downstream convert to a genotype matrix then to a haplotype format (w sci kit allele) then to just a plain np array.

However, when I've tried to use this in the new verison of msprime, I run into issues. I'm trying to do this via the legacy tools provided in this new dev version

This gets converted into the msprime demography code with this:

```
demography = msprime.Demography.from_old_style(population_configurations=population_configurations,demographic_events=demographic_events)
```

However, when I try to run sim_ancestry with:

```
tree       = msprime.sim_ancestry(recombination_rate =1e-8,
                                  sequence_length =1000,
                                  demography=demography)
```

I get:

```
Traceback (most recent call last):
  File "msprime_pop_split_sim.py", line 62, in <module>
    demography=demography)
  File "/well/mcvean/mtutert/anaconda3/envs/python_3.7/lib/python3.7/site-packages/msprime/ancestry.py", line 1160, in sim_ancestry
    random_seed=random_seed,
  File "/well/mcvean/mtutert/anaconda3/envs/python_3.7/lib/python3.7/site-packages/msprime/ancestry.py", line 962, in _parse_sim_ancestry
    "Either the samples or initial_state arguments must be provided"
ValueError: Either the samples or initial_state arguments must be provided
```

I've managed to get it to work when using the 'new' version of the samples argument form and this does work! But then when I convert to my haplotype array, the sizes look all wrong (way too small for the sample size (rows), so clearly am doing something wrong:

```
tree       = msprime.sim_ancestry(recombination_rate =1e-8,
                                  sequence_length =1000,
                                  demography=demography,
                                  samples={pop_id: 1 for pop_id in range(demography.num_populations)})
mutated_ts = msprime.sim_mutations(tree, rate=2e-6, model = "binary")
#Now convert the mutated_ts to an haplotype array
haps        = np.transpose(np.asarray(allel.HaplotypeArray(mutated_ts.genotype_matrix())))
print(np.shape(haps))
(6, 77)
```

I believe this is happening because they think my populations are just the 6 diploid populations (A,B&C) and the actual sample size within the pop configs isn't getting passed properly to sim_ancestry somehow.

Could someone help me out here? 

Thanks!

**Comment by marcustutert** [comment]
I took another look and managed to get round this issue by setting samples to be this dictionary:
```
sample_sizes = {
  "pop_1": ngwas_haps,
  "pop_2": nref_haps,
}
```
This worked, but still I find it weird that you have to specify the sample size in the demographic model, and then again in the samples arguement. Although this could just be a result of translating the legacy demographic model to the current version.

Happy to close this now or can keep open if people think this is something worth pointing out/changing in docs/somewhere.
@hyanwong FYI^

**Comment by hyanwong** [comment]
It seems like we should at least raise a warning that the `sample_size` values in `msprime.PopulationConfiguration` are ignored (if present) when converting to the new format? I've not used this before though, so I could be misunderstanding the syntax.

**Comment by marcustutert** [comment]
Yes, that's basically what's happening. Seems like with sim_ancestry you *always* need to have the samples argument within the main function, so having it within pop_config doesn't do anything. I'm sure you could easily change something in the source to parse it through to create the dictionary you want automatically...if someone was keen to make that change

**Comment by jeromekelleher** [comment]
Thanks @marcustutert, this is an important corner case I missed. As you've figured out, the ``sample_size`` stuff in population configurations can only be used in ``simulate`` not ``sim_ancestry``. I think probably a warning is the right thing to do here, as you'll get an error later anyway if you don't specify any samples.
