### ISSUE TITLE
`sim_ancestry(initial_state=ts)` does not use population names

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/msprime#1528]
Right now, it looks like `sim_ancestry(initial_state=ts, demography=d, ...)` matches up the populations in the Demography object, in order, to the populations in the initial state. The population table in the output is the same as in the initial state (this is good!). However, there's the possibility for confusion here, because names are not matched. For instance:
```
t = tskit.TableCollection(sequence_length=1)
t.populations.metadata_schema = tskit.MetadataSchema({ "codec": "json" })
t.populations.add_row(metadata={'name' : 'A'})
t.populations.add_row(metadata={'name' : 'B'})
t.nodes.add_row(time=0, flags=1, population=0)
t.nodes.add_row(time=0, flags=1, population=0)
t.nodes.add_row(time=0, flags=1, population=1)
t.nodes.add_row(time=0, flags=1, population=1)

d = msprime.Demography()
d.add_population(initial_size=0.001, name='B')
d.add_population(initial_size=1e6, name='A')

ts = msprime.sim_ancestry(
        initial_state=t.tree_sequence(),
        demography=d,
        end_time=1)

print(ts.first().draw(format='unicode'))
```
shows that 0 and 1, the samples in `A`, have coalesced, and so have been assigned to what we called `B` in the Demography.
```
 5  7 6
 ┃  ┃ ┃
 4  ┃ ┃
┏┻┓ ┃ ┃
0 1 2 3
```
(and, the populations are still labeled `A` and `B`, as before).

BTW, if the demography has one more population than the tables, we get this error:
```
msprime._msprime.InputError: Input error in population configuration: Population ID out of bounds.
```
and if the tables have one more population than the demography, we get:
```
ValueError: migration matrix must be a N x N square matrix encoded as a list-of-lists or numpy array, where N is the number of populations defined in the population_configurations. The diagonal elements of this matrix must be zero. For example, a valid matrix for a 3 population system is [[0, 1, 1], [1, 0, 1], [1, 1, 0]]
```

**Comment by jeromekelleher** [comment]
Hmm, very nice @petrelharp. Let's see.

What if we had a ``Demography.from_tree_sequence()`` that returned a demography reflecting the populations in the tree sequence, which tries to recover as much as it can from the metadata? At a minimum it will have the right number of populations and if names/descriptions exist in the metadata it'll use those too.

Then, the way to do things would be 
```python
demography = msprime.Demography.from_tree_sequence(slim_ts)
# e.g.
demography["p1"].initial_size = 10000
demography["p2"].initial_size = 20000
ts = msprime.sim_ancestry(initial_state=slim_ts, demography=demography)
```
Would that be any better?

**Comment by petrelharp** [comment]
I like that idea (it would solve https://github.com/tskit-dev/pyslim/issues/106, in particular). It doesn't totally address this, though - would we then just throw an informative error message if populations don't match?

**Comment by jeromekelleher** [comment]
> It doesn't totally address this, though - would we then just throw an informative error message if populations don't match?

Yes, I think we could be stricter then about what we accept as an input demography. I guess what we'd do is 
```
demography_check = Demography.from_tree_sequence(initial_state)
if demography_check.num_populations != demography.num_populations:
    raise ValueError("Blah blah")
for check_pop, pop in zip(demography_check.populations, demography.populations):
    if check_pop.name != pop.name:
           raise ValueError("Incompatible population names")
```

So, if you follow the pattern above as a user this error should never be thrown (since both are using from_tree_sequence to derive the names), and it should catch errors otherwise.

What do you think?

**Comment by jeromekelleher** [comment]
Gives a nice way to inspect the populations in the ts too.

**Comment by petrelharp** [comment]
Sounds good!

**Comment by petrelharp** [comment]
What will populations not having any lineages in them look like in the result, btw? Can we make it clear that those won't be used?

**Comment by petrelharp** [comment]
Ah: suppose we've got a tree sequence with samples in two populations, but want to simulate them having come from a population split some time in the past. This requires adding another population that isn't in the tree sequence we've passed in, like
```
d = Demography.from_tree_sequence(initial_state)
d.add_population(initial_size=100, name='ancestral')
```
... but currently, `sim_ancestry( )` won't add populations.

**Comment by jeromekelleher** [comment]
Yeah, good point. So, we required that the first ``initial_state.num_populations`` pops are equivalent to the ones from ``initial_state``, and we add populations for any extras from the demography.

That should allow us do stuff like
```
demography = msprime.Demography.from_tree_sequence(slim_ts)
# e.g.
demography["p1"].initial_size = 10000
demography["p2"].initial_size = 20000
demography.add_population(name="ancestor", initial_size=100
demography.add_population_split(time=1000, derived=["p1", "p2"], ancestral="ancestor")
ts = msprime.sim_ancestry(initial_state=slim_ts, demography=demography)

```

> What will populations not having any lineages in them look like in the result, btw? Can we make it clear that those won't be used?

We won't know that just by inspecting the population table, we'd have to something fancy like create a simulator from the initial state and then inspect it's state. We could then mark those pops that have no lineages initially as "inactive", but it might get complicated.

Probably not necessary for a first pass though?

**Comment by petrelharp** [comment]
> Probably not necessary for a first pass though?

Totally. Sounds good.

**Comment by jeromekelleher** [comment]
OK, will do this once the current batch of docs updates is done.
