### ISSUE TITLE
Update Dockerfile for 1.0

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1530]
The Dockerfile is a bit out of date now. I just updated it quickly to use Ubuntu 20.04 so it at least works, but I think we could make it more useful:

1. Base it off one of the standard Python data science images (so it's more useful)
2. Change it so it installs the latest release rather than from github (``pip install --pre msprime``)

Because of the binary wheels now, this means that we don't need any of the GSL stuff and it should all work fine. It should literally be one line ``pip install --pre msprime``.

This should make things like Binder (#1413) work better.

@agladstein, any chance you could take a look at this?

**Comment by agladstein** [comment]
Yes, I can work on it.

**Comment by agladstein** [comment]
I vote going with https://hub.docker.com/r/jupyter/scipy-notebook as a base stack.

> jupyter/scipy-notebook includes popular packages from the scientific Python ecosystem.
Everything in jupyter/minimal-notebook and its ancestor images
dask, pandas, numexpr, matplotlib, scipy, seaborn, scikit-learn, scikit-image, sympy, cython, patsy, statsmodel, cloudpickle, dill, numba, bokeh, sqlalchemy, hdf5, vincent, beautifulsoup, protobuf, xlrd, bottleneck, and pytables packages
ipywidgets and ipympl for interactive visualizations and plots in Python notebooks
Facets for visualizing machine learning datasets
