### ISSUE TITLE
Migrate docs off RTD

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1547]
Like https://github.com/tskit-dev/tskit/issues/1214

Can I leave this with you please @benjeffery?

**Comment by benjeffery** [comment]
This should be complete now, I haven't redirected all the individual pages as the structure has changed so much with 1.0.

**Comment by jeromekelleher** [comment]
Awesome, thanks @benjeffery!

**Comment by grahamgower** [comment]
Seems to be a wrinkle. This page is still live: https://msprime.readthedocs.io/en/stable/api.html
Selecting the "latest" version gives a 404 without redirect: https://msprime.readthedocs.io/en/latest/api.html

**Comment by benjeffery** [comment]
> Seems to be a wrinkle. This page is still live: https://msprime.readthedocs.io/en/stable/api.html

Try clearing cache? Is 404 for me.

> Selecting the "latest" version gives a 404 without redirect: https://msprime.readthedocs.io/en/latest/api.html

Yes, I could set up redirects for individual pages. Didn't seem worth it as structure changes so much for 1.0.

**Comment by jeromekelleher** [comment]
Could redirect pages to the root at least, if a counterpart doesn't exist? Or will there not really be any dangling links and this isn't worth worrying about?

**Comment by grahamgower** [comment]
Ah, the stable link is a 404 for me now too.

**Comment by jeromekelleher** [comment]
How's this looking @benjeffery?

**Comment by benjeffery** [comment]
I've added in the redirects to the root.
