### ISSUE TITLE
Update mutation models to generate silent mutations and document

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1551]
As discussed here: https://github.com/tskit-dev/msprime/pull/1548#issuecomment-801305017

> I got confused for a bit trying to work out what the silent mutation rates should be. But then I realized that the silent mutations are already there - notice for instance in the docs on HKY - it explains that this is implemented at a MatrixMutationModel with P_ii set to something so the rows all sum to the same thing. This is exactly what we want - usually, HKY is not-parent independent, but if for instance pi_A = pi_C = pi_T = pi_G then it is, and with this choice for P_ii, applying HKY multiple times will be correct (and approximately correct if the pi's aren't all equal).

> So, all we have to do is to go back in to the mutation generation code and ask it to actually record the silent mutations, for instance [here](https://github.com/tskit-dev/msprime/blob/main/lib/mutgen.c#L238) and [here](https://github.com/tskit-dev/msprime/blob/6f31a5359e858c5505af136f8073e62cc86b8640/lib/mutgen.c#L1241).  And, fix up the tests to account for this change, heh. I can probably do that sufficiently soon, unless you're willing to have a go at it, @GertjanBisschop? And, I think that should be a different PR.

So, we want to
1. Update the models so that they generate silent mutations
2. Update the stats tests to take this into account and verify
3. Document the fact that we do generate silent mutations. We'd to this by making a "Silent mutations" section at the end of the page, showing an example of a silent mutation happening, explain why we do this, and reassure the reader that this is fine, nothing will explode.

Sound good @petrelharp? I could do this (well, except for 2, maybe), but I don't think I'm the best person to...

**Comment by petrelharp** [comment]
Yes! Sounds good!

**Comment by petrelharp** [comment]
Note: I'm removing the functionality that [if a transition( ) method returns a nonzero value the mutation is discarded](https://github.com/tskit-dev/msprime/blob/6f31a5359e858c5505af136f8073e62cc86b8640/lib/mutgen.c#L1241), since we were no longer using it. I'm sure we could imagine a mutation model that used this functionality, but I don't really want to make one up just to keep that code in there. But if someone can think of a really good use case, say so.

**Comment by petrelharp** [comment]
My note above about silent mutations already being there is *not* quite right - there are some silent mutations, but not as many as we'd like to make the models close to parent-independent. For instance, Jukes-Cantor had zero silent mutations, and I think we want HKY and F84 to reduce to Jukes-Cantor when kappa=1. 

So, I'm adding silent mutations to these three models, but am *not* currently adding them to the amino acid models. (There's no obstacle to that, but it'd make them harder to explain - perhaps I should?)
