### ISSUE TITLE
remove add_ancestral?

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/msprime#1553]
In #1440:

> Does this mean that we can remove the add_ancestral parameter, since we expect the output to be "right" unless someone is doing something pretty obscure?

That'd be nice! Let's see:
- the upside would be that users adding more mutations to a forwards sim with selected mutations wouldn't have to think about "add_ancestral"
- the downside is that users who mutate more than once with non-parent-independent models would be less likely to be aware that this is statistically wrong.

So, we'd be reducing cognitive burden significantly on maybe a common use case, in exchange for avoiding some very, very slight statistical wrongness. It sounds like a great trade to me: not worrying about the precise mutation model in those rare cases of multiple hits is totally the right thing to do, I think.

I guess that also `add_ancestral` helps avoid bugs where someone means to mutate only the more recent part of the tree but forgets to specify an `end_time`. Or means to only mutate a segment of the genome. But this also seems pretty rare.

**Comment by jeromekelleher** [comment]
Sounds good @petrelharp, but I'm not sure which direction you're voting for? I'm happy to go with what you think.

**Comment by petrelharp** [comment]
Sorry, I'm voting to remove it. =) But I'm a bit nervous about that.

**Comment by winni2k** [comment]
Removing it sounds reasonable to me too. Perhaps there is a warning message we could throw if someone is doing that rare but slightly wrong thing?
