### ISSUE TITLE
Bug detected in lib/msprime.c at line 960

### ISSUE THREAD

**Issue by marcustutert** [tskit-dev/msprime#1554]
Hi I have been running a msprime simulation on my cluster (rescomp2, SGE) and have come across a bug in msprime.

Here is the output log:
```
Activating conda environment: /gpfs3/well/mcvean/mtutert/thesis/conditional_ld/.snakemake/conda/5e8d8497
Activating conda environment: /gpfs3/well/mcvean/mtutert/thesis/conditional_ld/.snakemake/conda/5e8d8497
The provenance information for the resulting tree sequence is 2.67MB. This is nothing to worry about as provenance is a good thing to have, but if you want to save this memory/storage space you can disabl
e provenance recording by setting record_provenance=False
Bug detected in lib/msprime.c at line 960. If you are using tskit directly please open an issue on GitHub, ideally with a reproducible example. (https://github.com/tskit-dev/tskit/issues) If you are using
 software that uses tskit, please report an issue to that software's issue tracker, at least initially.
```

The code that I run is as follows
```

####Variables#### 
#These are the DIPLOID counts
sequence_length    = 100000
Ne_A               = 10000
Ne_B               = Ne_A/2 
peripheral_pops    = 500
pi_1               = 0.01
pi_2               = 0.1
tol                = 0.01
###################
demography = msprime.Demography()
descendant_pops = []
demography.add_population(name="ancestral_population", initial_size=Ne_A)
for i in range(0,peripheral_pops):
  name = "peripheral_%s" % i
  demography.add_population(name=name, initial_size=Ne_B)
  demography.add_mass_migration(time=divergence_time, source=name, dest="ancestral_population", proportion=1)
  descendant_pops.append("peripheral_%s" % i)
#Create the dictionary of sample sizes python
sample_sizes = { i : 500 for i in descendant_pops }

#Do a recombination map with a single recombination hotspot in the middle (ask Gil why!)
positions = range(0,sequence_length)
rate_map  = np.zeros(sequence_length-1)
#Replace 0 with hotspot in middle
rate_map[math.floor(sequence_length/2)] = 0.9

rate_map = msprime.RateMap(position = positions,
                           rate     = rate_map)

tree       = msprime.sim_ancestry(recombination_rate = rate_map, 
                                  sequence_length    = 100000-1,
                                  demography         = demography,
                                  samples            = sample_sizes,
                                  random_seed        = seed)
                                  
#Rate here refers to MUTATION rate                                
mutated_ts = msprime.sim_mutations(tree, rate=1e-7, model = "binary",random_seed = seed)

#Perform filtering based on the haplotype configuration frequency we care about
#Get list of all samples
my_arr                                   = np.zeros(mutated_ts.num_nodes, dtype=bool)
my_arr[mutated_ts.samples(population=1)] = True
sample_in_pop1                           = my_arr[mutated_ts.samples()]

#Loop through the variants to find the haplotype frequency I need
freq_results = []
for v in mutated_ts.variants():
  genos = v.genotypes[sample_in_pop1]
  freq=np.sum(genos>0)/len(genos)
  freq_results.append(freq)

#Get indexes of the frequencies  
pi_1_bounds = [abs(x - pi_1) for x in freq_results]
pi_1_index  = next(x[0] for x in enumerate(pi_1_bounds) if x[1] < tol)

pi_2_bounds = [abs(x - pi_2) for x in freq_results]
pi_2_index  = next(x[0] for x in enumerate(pi_2_bounds) if x[1] < tol)

#Now convert the mutated_ts to an haplotype array and export only filtered variants
haps        = np.transpose(np.asarray(allel.HaplotypeArray(mutated_ts.genotype_matrix())))
target      =  pd.DataFrame(haps[0:1000,[pi_1_index,pi_2_index]])

#Write out the files
for i in range(1,peripheral_pops):
  #Output the GWAS population
  gwas = pd.DataFrame(haps[i*1000:(i+1)*1000,[pi_1_index,pi_2_index]])
  gwas.to_csv("pop_split_msprime/peripheral_%s_replicate_%s_dt_%s.csv" % (i,seed,divergence_time), index = False)

target.to_csv("pop_split_msprime/target_1_replicate_%s_dt_%s.csv" % (seed,divergence_time) , index = False)
```

I will try to revisit this code and make it more of a minimum reproducible example, but just for the purpose of this issue I will include it here. The specific parameters in the model that make this fail are:
seed=1102, divergence_time=50

Let me know if anyone requires any more info
Marcus

**Comment by jeromekelleher** [comment]
Thanks @marcustutert, can you tell us what version of msprime your using? (msp --version)

**Comment by benjeffery** [comment]
Confirmed on current HEAD (e5debf904d604206a19fb842ca66fad3c67410fa).

Gist of slightly-minimised example code: https://gist.github.com/benjeffery/499cda3f2cbda715f252bb762d580ff3

Looks like your good old friend the fenwick tree.

**Comment by jeromekelleher** [comment]
Yep, confirmed. :sob:

**Comment by marcustutert** [comment]
Hi Jerome/Ben--I take it from the above you have spotted the issue/don't need anything more from me? Out of curiosity what exactly did I trip up here within the code?

**Comment by jeromekelleher** [comment]
No, you're off the hook here @marcustutert. Looks like a problem in the core recombination engine - I'll report back when I know more. Thanks for the bug report!

**Comment by jeromekelleher** [comment]
Looks like this is one of those probability of one-in-a-gazillion things, rather than a worrying bug. I'll figure it out and make a fix.

In the short term @marcustutert, this shouldn't happen if you use a different random seed.

**Comment by marcustutert** [comment]
Thanks, Jerome
I've since changed up my code a bit to implement the idea a slightly different way after meeting with Gil yesterday to do something differently, so hopefully won't run into this situation again (unless I'm super unlucky!).

Typically if problems with tree sequences do arise how would you suggest dealing with them? Ie: if I get these errors like "Bug detected in lib/msprime.c at line 960" is there a way to flag that in msprime/python itself so my code is aware that I just skip over that seed?

**Comment by jeromekelleher** [comment]
> Typically if problems with tree sequences do arise how would you suggest dealing with them? Ie: if I get these errors like "Bug detected in lib/msprime.c at line 960" is there a way to flag that in msprime/python itself so my code is aware that I just skip over that seed?

File an issue, every time. These errors should never happen - you're hitting this because the core recombination code is relatively new and hasn't been battle hardened yet.

**Comment by jeromekelleher** [comment]
Yep, this was a super obscure edge case, should be sorted now in #1560.

A couple of notes on your simulation @marcustutert 

- The way you're allocating the ratemap is inefficient, and will lead to much slower simulations than necessary. This is the way to do what you want:

```python
rate_map = msprime.RateMap(
    position=[0, sequence_length / 2 - 1, sequence_length / 2, sequence_length]
    rate=[0, 0.9, 0]
)
```
The rate map is specifying **intervals** not per-base recombination rates.

- The recombination rate is super, super, super high. That's not so much a hotspot, as a different chromosome. I don't think there can be much difference between what you're doing here and simulating the two sides of the sequence independently without any recombination.

**Comment by marcustutert** [comment]
Thanks for the tips Jerome, much appreciated.
Just quickly on your second point (and this may just be because I'm having trouble understanding the difference between rate map and recombination rate within the software, within the way I implement the code at the moment if I wanted to have human-level recombination, I would just set this to 1e-8?

**Comment by jeromekelleher** [comment]
> Just quickly on your second point (and this may just be because I'm having trouble understanding the difference between rate map and recombination rate for the software), with the way I implement the code at the moment if I wanted to have human-level recombination, I would just set this to 1e-8?

A RateMap is just the newer way of specifying a RecombinationMap (which is not deprecated). The documentation isn't great at the moment, sorry about that. It gives the rate per base, per generation. So, you're specifying a rate of 0.9 in one base pair, per generation.

1e-8 is the usual background rate we have for humans, so a hotpot would be 10 or 100 times this.
