### ISSUE TITLE
[Doc] Missing description about using a list as model param in sim_ancestry

### ISSUE THREAD

**Issue by gbinux** [tskit-dev/msprime#1559]
There seems to be a missing description about **using a list** as the `model` parameter in `sim_ancestry` documentation.

1. There is a great explanation in `_parse_model_arg`: "The model argument must be either (a) a value that can be interpreted as a simulation model or (b) **a list** in which the first element is a model description and the remaining elements are model change events. These can either be described by a (time, model) tuple or AncestryModelChange instances.", 
2. and an example from the selective sweep doc 'https://tskit.dev/msprime/docs/latest/ancestry.html#sec-ancestry-models-selective-sweeps'. 

https://github.com/tskit-dev/msprime/blob/2ecc248efb8f446772383c5c6243bfc8c09b7926/msprime/ancestry.py#L1146

**Comment by jeromekelleher** [comment]
Thanks @gbinux, I'll be making a pass through this in the next few days.

**Comment by jeromekelleher** [comment]
Closed in #1573
