### ISSUE TITLE
Tidy up external namespace

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1570]
Currently we're being very messy about what gets exported into the external namespace.

I've taken a :shrug: approach to this up to now, assuming that people will read the documentation and not delve into undocumented features. However, this might not be such a good idea any more, as IDEs and things like [ConquerOfCompletions](https://github.com/neoclide/coc.nvim) (one of my rewards for shipping 1.0 is going to be setting this up, finally) scan the namespace, making stuff we don't document much more discoverable.

So, should we lock down the namespace to just the stuff we support, going forward? 

Thoughts @benjeffery, @molpopgen, @petrelharp, @grahamgower (and anyone else)?

**Comment by grahamgower** [comment]
> So, should we lock down the namespace to just the stuff we support, going forward?

Yes. Underscores everywhere else.

**Comment by jeromekelleher** [comment]
Well, I was thinking more of using a ``__all__`` list in the top-level ``__init__.py``. Putting underscores on everything is tedious.

**Comment by grahamgower** [comment]
I guess `__all__`  is helpful for stuff at the top level, but internal methods on public classes will still be "completable".

**Comment by benjeffery** [comment]
We should def be setting `__all__`. Where it doesn't screw things up we should add underscores. Shouldn't be too tedious using refactoring tools.
