### ISSUE TITLE
Sojourn time tests broken

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1577]
The analytical tests for sweeps are currently broken. Here's what we get:

![sojourn](https://user-images.githubusercontent.com/2664569/112470085-2448e300-8d62-11eb-9e0b-e032475cf71d.png)

![sojourn](https://user-images.githubusercontent.com/2664569/112470096-2743d380-8d62-11eb-997c-1c243f4d83fd.png)

Probably something got munged through the various API updates.

@andrewkern can you have a look please?

**Comment by andrewkern** [comment]
yup will look
