### ISSUE TITLE
HTML and text rendering for RateMap

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1590]
It would be nice to have good tabular output for the RateMap class for user and docs.

@hyanwong, fancy taking a look?

**Comment by jeromekelleher** [comment]
You could use the ``core.html_table`` directly actually (see the demography module), should be very straightforward.

**Comment by hyanwong** [comment]
Yep, I could output the position and rate. I was worried about displaying huge tables, but I see that e.g. `display_html(ts.tables.nodes)` puts "... skipped XXXXX rows ..." in for large tables, so I guess that's fine. How does it do that though?!

**Comment by jeromekelleher** [comment]
Don't worry about skipping stuff for the first version, we can add that in afterwards.

**Comment by jeromekelleher** [comment]
I'll take care of this.

**Comment by hyanwong** [comment]
Just doing it now!

**Comment by hyanwong** [comment]
I'm about to PR it!
