### ISSUE TITLE
Need to clarify in docs that log_mutation_likelihood only applies to a specific model

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime#1600]
I suspect that the entire section https://tskit.dev/msprime/docs/latest/api.html#msprime.log_mutation_likelihood was written before we had flexible mutation models. I assume the single mutation rate parameter means that ~~the model is the JC69MutationModel~~ this applies to any model with a continuous genome and constant mutation rate between alleles. We should say that somewhere.

**Comment by jeromekelleher** [comment]
@JereKoskela, thoughts?

**Comment by JereKoskela** [comment]
Only the infinite sites model is supported, and only on continuous genomes. I can add a warning to that effect at the top of the docstring.

**Comment by hyanwong** [comment]
(and only the JC69MutationModel within the infinite sites model, right @JereKoskela ?)

**Comment by JereKoskela** [comment]
I think that's probably right, but I'm not very familiar with the nomenclature of the various mutation models, so I'll spell this out to avoid being confused. Since each site can mutate at most once, there are essentially only two alleles (ancestral and mutant). Only the ancestral-to-mutant mutation is permitted, and happens with constant rate.

**Comment by hyanwong** [comment]
> I think that's probably right, but I'm not very familiar with the nomenclature of the various mutation models, so I'll spell this out to avoid being confused. Since each site can mutate at most once, there are essentially only two alleles (ancestral and mutant). Only the ancestral-to-mutant mutation is permitted, and happens with constant rate.

Yep, I get that, but I assume that this applies even to models that allow a single mutation to multiple possible alleles  at a site (like the JC69MutationModel), as long as the infinite sites assumption is met (i.e. only one mutation per site). So I think that we need to avoid talking about number of alleles allowed at a site (e.g. I presume all the single base DNA mutation models allow for 4 alleles: ATCG, even in continuous genomes), and just say that this applies to genomes where only one mutation can occur per site (i.e. discrete_genome=False), with a constant mutation rate. It's just a matter of careful wording I think.

**Comment by JereKoskela** [comment]
> > I think that's probably right, but I'm not very familiar with the nomenclature of the various mutation models, so I'll spell this out to avoid being confused. Since each site can mutate at most once, there are essentially only two alleles (ancestral and mutant). Only the ancestral-to-mutant mutation is permitted, and happens with constant rate.
> 
> Yep, I get that, but I assume that this applies even to models that allow a single mutation to multiple possible alleles at a site with a constant rate (like the JC69MutationModel), as long as the infinite sites assumption is met (i.e. only one mutation per site). So I think that we need to avoid talking about number of alleles allowed at a site (e.g. I presume all the single base DNA mutation models allow for 4 alleles: ATCG, even in continuous genomes), and just say that this applies to genomes where only one mutation can occur per site (i.e. discrete_genome=False), with a constant mutation rate. It's just a matter of careful wording I think.

I think I see what you mean now, and you're right. There can be any number of alleles under the hood. Anything where they are all interchangeable and can't revert back to the ancestral state will work.

**Comment by hyanwong** [comment]
> > > I think that's probably right, but I'm not very familiar with the nomenclature of the various mutation models, so I'll spell this out to avoid being confused. Since each site can mutate at most once, there are essentially only two alleles (ancestral and mutant). Only the ancestral-to-mutant mutation is permitted, and happens with constant rate.
> > 
> > 
> > Yep, I get that, but I assume that this applies even to models that allow a single mutation to multiple possible alleles at a site with a constant rate (like the JC69MutationModel), as long as the infinite sites assumption is met (i.e. only one mutation per site). So I think that we need to avoid talking about number of alleles allowed at a site (e.g. I presume all the single base DNA mutation models allow for 4 alleles: ATCG, even in continuous genomes), and just say that this applies to genomes where only one mutation can occur per site (i.e. discrete_genome=False), with a constant mutation rate. It's just a matter of careful wording I think.
> 
> I think I see what you mean now, and you're right. There can be any number of alleles under the hood. Anything where they are all interchangeable 

Yes, exactly. 

> and can't revert back to the ancestral state will work.

A minor point: not just reversion, but any multiple mutation at a site is disallowed (e.g. parallel / convergent mutations). I'm sure that's what you meant anyway :)
