### ISSUE TITLE
Add more error messages to methods that build the Demography object

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/msprime#1601]
I'm noticing that code like the following runs fine. Notice that the populations supplied in the `add_admixture` method are different to the ones defined with `add_population` at the start.

Presumably this would eventually lead to an error when the demography object is used in `sim_ancestry`, but it might be better to produce an error or warning as soon as a non-existent population label/ID is referred to.

```
dem = msprime.Demography()
dem.add_population(
  name="Pop0",
  description="Plotted in red.",
  initial_size=500
  )
dem.add_population(
  name="Pop1",
  description="Plotted in blue.",
  initial_size=500
  )
dem.add_population(
  name="Pop2",
  description="Plotted in green.",
  initial_size=500
  )
dem.set_migration_rate(source=0, dest=1, rate=0.05)
dem.set_migration_rate(source=1, dest=0, rate=0.02)

# Specify admixture event.
dem.add_admixture(
  time=50,
  derived="AdmixedPop",
  ancestral=["AncestralPop0", "AncestralPop1"],
  proportions=[0.3, 0.7])
dem
```

**Comment by jeromekelleher** [comment]
Hah, yes, very good point @gtsambos. We should check the populations on the way in and give errors early. It's an easy fix.
