### ISSUE TITLE
Rename well known mutation models to remove "MutationModel" suffix?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1605]
Reading the docs for the mutations, I can see an inconsistency between how we're doing things for ancestry and mutations. Our ancestry models are:
```   
    BetaCoalescent,
    DiracCoalescent,
    DiscreteTimeWrightFisher,
    SmcApproxCoalescent,
    SmcPrimeApproxCoalescent,
    StandardCoalescent,
    SweepGenicSelection,
```
While our mutation models are:
```
    BinaryMutationModel,
    BLOSUM62MutationModel,
    F84MutationModel,
    GTRMutationModel,
    HKYMutationModel,
    InfiniteAllelesMutationModel,
    JC69MutationModel,
    MatrixMutationModel,
    PAMMutationModel,
    SLiMMutationModel,
```
I propose we rename these to:
```
    BinaryMutationModel,
    BLOSUM62
    F84
    GTR
    HKY
    InfiniteAlleles
    JC69
    MatrixMutationModel,
    PAM
    SLiMMutationModel,
```
So, we keep the suffix for BinaryMutationModel, and SLiMMutationModel as these would be ambiguous otherwise. MatrixMutationModel is good because it's a sort of abstract superclass. The others are concrete and unambiguous, I think?

@petrelharp?

(The ancestry models aren't brilliant either to be honest, but most of them are pre 1.0 so we're stuck with them indefinitely. Nothing stopping us with coming up with better synonyms later, but that's another issue.)

**Comment by petrelharp** [comment]
I'd be OK with this, but don't mind the reminder that they are MutationModels - "GTR" is unambiguous once you're already thinking about mutation models but maybe not otherwise. I guess I vote to leave it alone (but not strongly)?

**Comment by jeromekelleher** [comment]
OK, I don't feel strongly about it. Any thoughts anyone else? @GertjanBisschop?

**Comment by GertjanBisschop** [comment]
One argument I can think of in favour of removing the suffix is the fact that shorter code, that is still unambiguous, is easier to read and write. Given that MutationModels will always be used with `msprime.sim_mutations()`, I wonder whether there is a need to remind people that "GTR" for example is a MutationModel.

**Comment by jeromekelleher** [comment]
How about we add them as synonyms @petrelharp? We could do something like 

```python
class GTR(GTRMutationModel):
    pass
```
which should keep both camps happy? (Plus it would mean we don't have to do it immediately)

**Comment by petrelharp** [comment]
Meh, no need to clutter up the namespace. If you'd like to remove it, then I say go for it.
