### ISSUE TITLE
in some cases sim_ancestry with initial state produces unordered tables

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/msprime#1606]
I ran across this when trying to recapitate something and forgot to `keep_input_roots`.

Here is a MWE:
```
import tskit, msprime

t = tskit.TableCollection(sequence_length=2)
t.populations.add_row()
t.nodes.add_row(time=0, flags=tskit.NODE_IS_SAMPLE, population=0)
t.nodes.add_row(time=1, flags=tskit.NODE_IS_SAMPLE, population=0)
t.nodes.add_row(time=2, population=0)
t.edges.add_row(left=0, right=1, parent=2, child=0)

ts = t.tree_sequence()

msprime.sim_ancestry(initial_state=ts, population_size=1, random_seed=5)
```
produces
```
_tskit.LibraryError: Edges must be listed in (time[parent], child, left) order; time[parent] order violated
```
The error occurs *after* simulation, when trying to turn the tables that result from simulation back into a tree sequence.

**Comment by petrelharp** [comment]
The same situation (recapitating after a simplify without `keep_input_roots`) also led to in other cases:
```
 msprime._msprime.LibraryError: Attempt to sample a lineage from an inactive population
```
... I'm hoping this will be obviously the same issue.

**Comment by jeromekelleher** [comment]
Thanks @petrelharp, I can see how the first one can happen and makes sense. Should be a straightforward enough fix.

The second looks like different though, and is some interaction with demography. Can you isolate an example and open an issue please? This would happen if (say) you had a demography with three popuations A, B, C, and you said that A and B split from C, (so it's inactive before(backwards) the split) but you had some lineages in C in your initial state.
