### ISSUE TITLE
in some cases sim_ancestry with initial state does not detect segments in inactive populations

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/msprime#1608]
Here's a MWE:
```
import tskit, msprime

T = 10
times = [0, 10]
# # Other 'bad' times:
# times = [0, 11]
# times = [10, 11]
# times = [12, 11]
# times = [12, 1]
# # Times that don't produce the error:
# times = [0, 1]
# times = [0, 9]

t = tskit.TableCollection(sequence_length=1.0)
t.populations.add_row()
t.nodes.add_row(time=0, flags=1, population=0)
t.nodes.add_row(time=times[0], flags=1, population=0)
t.nodes.add_row(time=times[1], population=0)
t.edges.add_row(left=0, right=1, parent=2, child=0)
ts = t.tree_sequence()

d = msprime.Demography()
d.add_population(initial_size=1.0)
d.add_population(initial_size=1.0)
d.add_population_split(T, derived=["pop_0"], ancestral="pop_1")

msprime.sim_ancestry(initial_state=ts, demography=d)
```
This (and any of the "bad" times) produces:
```
msprime._msprime.LibraryError: Attempt to sample a lineage from an inactive population
```
Some other sets of times (e.g. `[0, 0]`) turns up the error from #1606.

**Comment by jeromekelleher** [comment]
I think this is working as expected @petrelharp: by making a population split where population 0 is derived at time T, you're definitively saying population 0 is [inactive](https://tskit.dev/msprime/docs/latest/demography.html#life-cycle) for all times >= T. So, any nodes that you have in that population with time >= T will result in this error.

If you can't make guarantees about a population really being inactive, then probably better to use mass migrations to move lineages around.

**Comment by petrelharp** [comment]
That's what I thought at first, but this does *not* produce the error:
```
T = 10
ts = msprime.sim_ancestry(2, population_size=100, end_time=T)

d = msprime.Demography()
d.add_population(initial_size=1.0)
d.add_population(initial_size=1.0)
d.add_population_split(T, derived=["pop_0"], ancestral="pop_1")
assert np.max(ts.tables.nodes.time) == 10

rts = msprime.sim_ancestry(initial_state=ts, demography=d)
```
nor does this
```
T = 10
times = [0, 10]

t = tskit.TableCollection(sequence_length=1.0)
t.populations.add_row()
t.nodes.add_row(time=0, flags=1, population=0)
t.nodes.add_row(time=times[0], flags=1, population=0)
t.nodes.add_row(time=times[1], population=0)
t.nodes.add_row(time=times[1], population=0)
t.edges.add_row(left=0, right=1, parent=2, child=0)
t.edges.add_row(left=0, right=1, parent=3, child=1)
ts = t.tree_sequence()

d = msprime.Demography()
d.add_population(initial_size=1.0)
d.add_population(initial_size=1.0)
d.add_population_split(T, derived=["pop_0"], ancestral="pop_1")

msprime.sim_ancestry(initial_state=ts, demography=d)
```

**Comment by jeromekelleher** [comment]
> So, maybe the problem is that htese other things do work?

Hmm, yes, I think that's right. Looks like we're not checking if population is inactive at time the root segments are added... I'll dig in and sort it out.

**Comment by petrelharp** [comment]
Note that this is happening *after* the bug in #1606, since if that happens it happens before this one.

**Comment by jeromekelleher** [comment]
So this is a little bit tricky, but I think it's not a big deal. What's happening is that because the root segments are < start time, they are inserted during initialisation, which is *before* any of the demographic events happen and therefore the presence of the segments in the inactive population isn't detected. It's all a bit fiddly, but I'm sure there's a solution.

Going to park this until after the beta so we can get the new functionality out there and being tested.
