### ISSUE TITLE
Move ``possible_lineage_locations`` and friends to Demography?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1610]
It's an implementation detail that we need to use the debugger to find them out, they're really methods of the Demography class.

We never released them, I think, so can just move the code?

@apragsdale, @petrelharp?

**Comment by petrelharp** [comment]
Don't see why not...

**Comment by apragsdale** [comment]
That sounds reasonable to me as well.

**Comment by jeromekelleher** [comment]
:thumbsup:

**Comment by jeromekelleher** [comment]
Actually, these aren't documented with examples yet either, so I should do that before tagging the beta. I'll do this tomorrow AM - hopefully I can get a review from you guys in your AM, and then I can cut the beta release? (assuming nothing to controversial happens)

**Comment by jeromekelleher** [comment]
I started documenting these in #1644 and actually there's no real point in moving them. Easy enough to create a debug instance, and there may be performance advantages to keeping the methods close to the source data, later on.
