### ISSUE TITLE
Examples for coalescence rates and mean times

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1615]
#1614 added some content for explaining the numerical methods on the demography debugger, and added a TODO section for the  coalescence_rate_trajectory() and mean_coalescence_time() methods. I decided I wasn't the right person to explain these.

@petrelharp, @apragsdale, would one of you be able to take this up? We can probably reuse the examples from whichever paper we used this on, right?

**Comment by petrelharp** [comment]
I'll have a go at it.

**Comment by petrelharp** [comment]
Starting [here](https://github.com/tskit-dev/msprime/pull/1614/files#diff-5ec23b83ce8afddf382b03ff5258476aded99dca85b8c21f6551ba74f86891dfR1653), right?

**Comment by jeromekelleher** [comment]
Yep - are you OK to merge that other PR first? No major hurry with this, it's no going to block the beta.
