### ISSUE TITLE
Rename Demography.epoch_times to "epoch_start_time"

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1622]
Arrays are usually singular, so nice to be consistent here. Also we should be clear whether it's the start of end time of the epochs.

It's also not entirely clear why this is needed, when ``T = [epoch.start_time for epoch in debug.epochs]`` is available? Would we be better off documenting the properties of Epochs well than providing auxiliary arrays like this?

Thoughts @petrelharp?

**Comment by petrelharp** [comment]
I don't have a strong opinion, but these are useful for a bunch of things, so it's nice to make them easily available and discoverable. Putting in `start` would make it more obvious what they are, but also it's nbd.

**Comment by jeromekelleher** [comment]
OK, I'll change it to ``epoch_start_time``. I'll also document the Epoch class, good to have this stuff available for use.
