### ISSUE TITLE
numerical issues with coalescence rate trajectories on windows

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/msprime#1629]
As observed in #1620, trying to calculate coalescence rate trajectories for the OOA model produces NAN's in Windows (only). I'm not inclined to fix this unless it actually bites someone. We could probably be smarter about solving the relevant differential equations.

(Note: maybe there's a way to do the solution analytically? But, with different populations growing at different exponential rates, we're solving a time-inhomogeneous Feynman-Kac problem; and while `u_t = a u - exp(g t) u` has a solution if a is a real number, it's not obvious how to get a solution with `a` a matrix and `g` a diagonal matrix.)

**Comment by jeromekelleher** [comment]
Is this still an issue since we switched the matrix exponential algorithm?
