### ISSUE TITLE
Give idiomatic example of replicates with mutations 

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1648]
We don't have an idiomatic way of simulating mutations and ancestry at the same time. Here's some suggested ways to do it below.

Note that we might have a simple function which combines both (#1540), but we can't have a function that gives access to the full functionality of both sim_ancestry and sim_mutations, so we do need to give some guidance on what an idiomatic and efficient way of doing this is.

## Generators

```python
def sim_replicates(sample_size, num_replicates=100):
    ancestry_reps = msprime.sim_ancestry(
        samples=sample_size,
        population_size=100, sequence_length=1_000,
        num_replicates=num_replicates)
    for ts in ancestry_reps:
        mutated_ts = msprime.sim_mutations(ts, rate=1e-6)
        yield mutated_ts

num_replicates = 100
S = np.zeros(num_replicates)
for index, ts in enumerate(sim_replicates(10, num_replicates)):
    S[index] = ts.segregating_sites()

print(S)
```

This is probably a good pattern to encourage in general: wrap all the fixed parameters in a function, and the stuff the user varies can be supplied to the ``sim_replicates`` function.

## Map and functools.partial

Another option is to use functools.partial:
```python
ancestry_reps = msprime.sim_ancestry(
    samples=10,
    population_size=100, sequence_length=1_000,
    num_replicates=num_replicates)
mutations_func = functools.partial(msprime.sim_mutations, rate=1e-6)
mutations_reps = map(mutations_func, ancestry_reps)

for index, ts in enumerate(mutations_reps):
    S[index] = ts.segregating_sites()
```
This feels a bit more obscure to me.

## Concurrent.futures

```python
def run_sim(_):
    ancestry_ts = msprime.sim_ancestry(
        samples=10,
        population_size=100, sequence_length=1_000)
    mutated_ts = msprime.sim_mutations(ts, rate=1e-6)
    return mutated_ts.segregating_sites()

with concurrent.futures.ProcessPoolExecutor(max_workers=5) as executor:
    S = executor.map(run_sim, range(num_replicates))

S = np.array(list(S))
```
Although, this only makes sense if you have large simulations.

**Comment by grahamgower** [comment]
Maybe the functools example would be less obscure using a `lambda`?
> ```python
> mutations_reps = map(lambda ts: msprime.sim_mutations(rate=1e-6), ancestry_reps)
> ```

But probably just having the generator and parallel examples are sufficient.
