### ISSUE TITLE
Population not activated by setting size

### ISSUE THREAD

**Issue by apragsdale** [tskit-dev/msprime#1657]
Working on importing demographic models from `demes`, and I ran into some behavior that I'm not quite understanding, to do with active/inactive populations. The example here is a simple "eye" model, where an ancestral population splits and then re-merges into a single population. (It's similar to this example, https://tskit.dev/msprime/docs/latest/demography.html#admixture, but the admixing populations should not be present after the admixture event).

So, populations A and B are initially inactive, but they need to be activated at the time of admixture (until they are deactivate by the population split event with ANC). I first expected that setting their size at the right time would "activate" them, but I still run into `LibraryError: All ancestral populations in admixture must already be active`.

I wonder if there should be a way to activate populations directly, maybe with a `demog.activate_population(population="A", time=10)`, or similar? Otherwise, I'm not sure how to specify this model properly with the new demography methods.

```python
# an eye model, where ANC splits into A and B, then A and B admix into C, leaving
# only population C after the admixture event

import msprime

demog = msprime.Demography()
# initialize populations
demog.add_population(name="ANC", initial_size=0, initially_active=False)
demog.add_population(name="A", initial_size=0, initially_active=False)
demog.add_population(name="B", initial_size=0, initially_active=False)
demog.add_population(name="ADMIX", initial_size=100, initially_active=True)
# add events and population size changes (to activate/deactivate)
demog.add_population_parameters_change(population="A", time=10, initial_size=100)
demog.add_population_parameters_change(population="B", time=10, initial_size=100)
demog.add_admixture(
    time=10, ancestral=["A", "B"], derived="ADMIX", proportions=[0.5, 0.5]
)
demog.add_population_split(time=20, ancestral="ANC", derived=["A", "B"])

dbg = demog.debug()
```

cc: @grahamgower

**Comment by grahamgower** [comment]
This should certainly be possible. I think the fix should be:
```diff
diff --git a/lib/msprime.c b/lib/msprime.c
index 0dc2d745..ec156d03 100644
--- a/lib/msprime.c
+++ b/lib/msprime.c
@@ -6059,8 +6059,10 @@ msp_admixture(msp_t *self, demographic_event_t *event)
     for (index = 0; index < num_ancestral; index++) {
         pop = &self->populations[ancestral[index]];
         if (pop->state != MSP_POP_STATE_ACTIVE) {
-            ret = MSP_ERR_ADMIX_ANCESTRAL_NOT_ACTIVE;
-            goto out;
+            ret = msp_activate_population(self, ancestral[index]);
+            if (ret != 0) {
+                goto out;
+            }
         }
     }
```

But then I run into #1658.

**Comment by benjeffery** [comment]
@apragsdale Would you like to work up a PR for this with @grahamgower 's fix in?

**Comment by grahamgower** [comment]
It seems like less work to have just activated teh ancestral population(s) like in the code I posted above, but instead an error was explicitly added for this case (`MSP_ERR_ADMIX_ANCESTRAL_NOT_ACTIVE` --- and there's a test for this exact behaviour). So I wonder if Jerome didn't have some good reason for making this an error?

**Comment by apragsdale** [comment]
That's what I was wondering as well - if there was a good reason to not allow admixture that also activates non-active populations. To me what you put above makes a lot of sense, @grahamgower 

It's appealing that it mirrors the behavior of a population split event in reverse, with the possibility that the ancestral populations persist in times more recent than the admixture event (looking forward in time).

**Comment by jeromekelleher** [comment]
I'm not sure what my reasoning was when doing this. My main goal was to keep the population state machine as rigorous and simple as possible, so I probably overlooked this type of example. I don't see any reason not to make the changes that are being suggested here.
