### ISSUE TITLE
Use demes hypothesis strategy for testing

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1676]
@grahamgower, ISTR you've put a lot of effort into a hypothesis strategy for demes. Would it make sense to use this for msprime? We could do some basic checks on the output demography, make sure it debugs, etc.

**Comment by grahamgower** [comment]
Yeah, absolutely. There's some design decision(s) that needs to be made in regard to how the strategy is exported by `demes`. I don't recall the details, but there's some potential awkwardness around how the downstream app (ie. msprime) will get the strategy when using pytest. So it might be worth taking a look at the hypothesis docs to see if you have an opinion: https://hypothesis.readthedocs.io/en/latest/strategies.html#registering-strategies-via-setuptools-entry-points

**Comment by jeromekelleher** [comment]
Seems like the setuptools ``entry_points`` is the way to go? I guess we'd need an updated release of demes to do this though.

So, would you prefer to
a.  figure out the hypothesis stuff and release a version of demes, then do some testing in msprime, and then release msprime 1.0.1. or
b. Release msprime 1.0.1 now with experimental demes support, and do the hypothesis testing later?

(FYI, I'm going away again from the 14th, so would like to have a version of msprime that can support demes in some form out there by then)

**Comment by grahamgower** [comment]
How about we duplicate the hypothesis strategy code from the demes repository into msprime, to check that the msprime `from_demes()` method does what it should? Then we delete the duplicated code once it's been exported in the next release of demes. We'd need to copy the 300 lines from [this file](https://github.com/popsim-consortium/demes-python/blob/main/tests/__init__.py), but it should be self contained. Example usage of the `graphs()` strategy function [here](https://github.com/popsim-consortium/demes-python/blob/main/tests/test_load_dump.py#L511-L514).

**Comment by jeromekelleher** [comment]
Leaving this open until we're using the upstream hypothesis generator: https://github.com/popsim-consortium/demes-python/issues/217
