### ISSUE TITLE
Error with MutationMap

### ISSUE THREAD

**Issue by jydu** [tskit-dev/msprime#1682]
Hi,

I am getting this error when using sim_mutations with a RateMap instead of a constant rate:
`
msprime._msprime.InputError: Input error in mutation rate map: Mutation map is not compatible with specified tables.
`
I tried to see where the error msg came from but could not figure it out. Any hint to what could cause this error? My recombination map is a priori ok (and has no missing data). The input tree sequence was generated by SLiM, where only deleterious mutations in coding regions were simulated, with a constant rate. I am now trying to add neutral mutations with a variable rate (piecewise constant rate) along the genome.

Many thanks in advance for your insights,

Julien.

**Comment by petrelharp** [comment]
Did you check if the RateMap's sequence length and the tree sequence's sequence length are the same?

**Comment by petrelharp** [comment]
That's [where the error comes from](https://github.com/tskit-dev/msprime/blob/e00cf1423b160e2edd14fcbed040829ab3ca57f8/lib/mutgen.c#L813)! I'll update the error to be more informative.

**Comment by petrelharp** [comment]
Note that the sequence_length in msprime needs to be *one more* than that in SLiM, because in SLiM a maximum position of `99` means that there's 100 bases (0, 1, ..., 99), which is a sequence length of 100.

**Comment by jydu** [comment]
Hi, thanks for the super fast answer. That was indeed the issue. I did increment the last position by one, or I thought I did... Because of a stupid copy-paste I happened to increment my recombination map instead. Fixing it solved the issue!
