### ISSUE TITLE
Add gene conversion to record_full_arg option

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1773]
We should add support for gene conversion nodes to the record full ARG option.

Should be fairly similar to recombination nodes.

If someone is interested in this functionality (and ideally helping to implement/test it), please comment here.

**Comment by JereKoskela** [comment]
At a glance, this looks like a simple case of reimplementing a slight variant `msp_store_arg_recombination`. I'm happy to take a look, though probably not before next week.
