### ISSUE TITLE
Documentation for Demes

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1784]
Now what Demes support is pretty much done (I think?), there's a number of places where we need to update the documentation to account for Demes.

Any suggestions for what we should do, and how much detail we want to get into? I guess we should give an example of importing a demes model, running it through the DemographyDebugger, and emphasising that time goes in the opposite direction?

Putting this down for the next point release milestone, unless anyone things we should bring it up.

Ping @grahamgower, @molpopgen, @apragsdale

**Comment by molpopgen** [comment]
Seems like a minimal approach would be:

1. Link to the tutorial in the demes spec as "where to find examples".
2. Encourage `demesdraw` as a way to visualize that the YAML seems to do what you wanted.
3. Then the quick example that you describe.

**Comment by grahamgower** [comment]
Another thing we could do is draw [migration events](https://tskit.dev/msprime/docs/stable/ancestry.html#migration-events) over the top of a demography that is plotted with `demedraw`.

**Comment by jeromekelleher** [comment]
I think we can close this now, unless there are specific things we should add beyond #1784 @grahamgower?

**Comment by grahamgower** [comment]
Yep, I think the biggest docs gap is now filled.
