### ISSUE TITLE
1.0.2: Improved Demes support release

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1785]
I'm preparing to put out a point release which should get the updated Demes code out there. I just want to check that we're happy to do this, @apragsdale, @grahamgower?

Are we happy with the implementation of the low-level events to activate/deactivate populations, or is there still some stuff to do there?

**Comment by grahamgower** [comment]
I think it's all been wrapped up.

**Comment by jeromekelleher** [comment]
I guess I can tag this now @grahamgower?

**Comment by grahamgower** [comment]
Yes, please do!
