### ISSUE TITLE
DemographyDebugger._repr_html_() `<details>` widget weirdness

### ISSUE THREAD

**Issue by grahamgower** [tskit-dev/msprime#1795]
Using the demography debugger in a notebook uses the html repr to put each epoch inside a `<details>` HTML widget (the little triangle thing that allows the user to expand/hide details). When there are multiple epochs, and the detail widget is "closed", the placement of the widget moves in an unintuitive manner. Identical behaviour was observed in both chrome and firefox.

The default (everything open) looks great.

![details-1](https://user-images.githubusercontent.com/8665077/127459426-a968aa20-9b9e-4460-9105-c0e0b67fecf7.png)

---

Closing the details for the middle widget (epochs[1]) moves the widget for epochs[2].

![details-2](https://user-images.githubusercontent.com/8665077/127459431-6668aa51-ea0e-45ed-94ba-e7eb01998dd9.png)

---

When all widgets are closed, all widgets appear on line line. Presumably they should be on separate lines?

![details-3](https://user-images.githubusercontent.com/8665077/127459432-34e7b21d-1d7a-4f79-bee2-90c8462d1044.png)

**Comment by grahamgower** [comment]
This is inside the jupyter-book docs, btw. I don't know if the behaviour is actually different inside a "proper" notebook.

**Comment by jeromekelleher** [comment]
This is an artefact of running in JupyterBook - it works fine when working in a normal notebook. I fiddled with it for a bit and decided that having it like this was the least bad option, and hoped that someone would fix this in JupyterBook at some point.

**Comment by grahamgower** [comment]
Ah, ok. I guess it's a stylesheet thing then?

**Comment by jeromekelleher** [comment]
No idea - I didn't investigate

**Comment by jeromekelleher** [comment]
I'm going to close this as a wontfix, unless someone wants to investigate more.
