### ISSUE TITLE
Change the model name for "wf_ped"

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1863]
After taking some folks on a tour of the simulate-through-pedigree API there was universal agreement that the name "wf_ped" is unhelpful and confusing. The "Wright-Fisher" bit got in there because under the hood the details of how recombination happens is handled by the same code as the DTWF model, but actually this doesn't really have anything to do with a Wright-Fisher process.

So, any suggestions? Here are the [existing models](https://tskit.dev/msprime/docs/latest/ancestry.html#sec-ancestry-quickref) for reference.

The simplest and most obvious is to call the ancestry model class ``Pedigree()`` with a shorthand string "pedigree", but I wonder if this will confuse people into thinking that we are simulating a pedigree rather than simulating *within* a pedigree? Perhaps this confusion would be alleviated if we documented the ``sim_pedigree()`` function as part of the public API?

**Comment by hyanwong** [comment]
`FixedPedigree` perhaps?

**Comment by jeromekelleher** [comment]
I like it!

**Comment by jeromekelleher** [comment]
``FixedPedigree`` sounds right for the class name, what should we call the short-cut string? "fixed_pedigree" is the obvious choice I guess?

**Comment by hyanwong** [comment]
> `FixedPedigree` sounds right for the class name, what should we call the short-cut string? "fixed_pedigree" is the obvious choice I guess?

Yes, make it as obvious as possible I reckon. We could also use "KnownPedigee", but I think "Fixed" is better.
