### ISSUE TITLE
Recapitating from an incomplete pedigree

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1865]
Consider the following code:
```python
import msprime
import msprime.pedigrees

N = 5
tables = msprime.pedigrees.sim_pedigree(
    population_size=N, random_seed=1234, end_time=10
)

tables.sequence_length = 100
ped_ts = msprime.sim_ancestry(
    initial_state=tables,
    model="wf_ped",
    random_seed=12345,
)
final_ts = msprime.sim_ancestry(
    initial_state=ped_ts, population_size=N, model="dtwf", random_seed=123456
)

print(final_ts.draw_text())
```
The trees we get are:

```
41.00┊                              110        ┊   
     ┊                        ┏━━━━━━┻━━━━━━┓  ┊   
10.00┊                        8             9  ┊   
     ┊                        ┃             ┃  ┊   
9.00 ┊                        ┃             ┃  ┊   
     ┊                        ┃             ┃  ┊   
8.00 ┊                        ┃             ┃  ┊   
     ┊                        ┃             ┃  ┊   
7.00 ┊                       37             ┃  ┊   
     ┊                ┏━━━━━━━┻━━━━━━━┓     ┃  ┊   
6.00 ┊                ┃               ┃     ┃  ┊   
     ┊                ┃               ┃     ┃  ┊   
5.00 ┊                ┃              50     ┃  ┊   
     ┊                ┃             ┏━┻━┓   ┃  ┊   
4.00 ┊                ┃             ┃   ┃   ┃  ┊   
     ┊                ┃             ┃   ┃   ┃  ┊   
3.00 ┊                ┃             ┃   ┃   ┃  ┊   
     ┊                ┃             ┃   ┃   ┃  ┊   
2.00 ┊               83             ┃   ┃   ┃  ┊   
     ┊      ┏━━━━━━━┳━┻━━━┳━━━━━┓   ┃   ┃   ┃  ┊   
1.00 ┊     93       ┃    98     ┃   ┃   ┃   ┃  ┊   
     ┊  ┏━━━╋━━━┓   ┃   ┏━┻━┓   ┃   ┃   ┃   ┃  ┊   
0.00 ┊ 100 107 108 101 102 104 109 105 106 103 ┊   
   0.00                                     100.00 
```

This tree is a valid sample from a Wright-Fisher process with N=5 because we've simulated the pedigree under this model, and then completed the simulation under the same model. The pedigree finished at time 10, and we had nodes 8 and 9. These were then picked up as the samples in a DTWF simulation starting from this point, and all was good.

However, as @hyanwong and @petrelharp pointed out, there's a problem when we have an incompete pedigree. Suppose we break 10% of the links in the pedigree, like this:
```python

N = 5
tables = msprime.pedigrees.sim_pedigree(
    population_size=N, random_seed=1234, end_time=10
)

parents = tables.individuals.parents
parents[0::10] = -1
tables.individuals.parents = parents

tables.sequence_length = 100
ped_ts = msprime.sim_ancestry(
    initial_state=tables,
    model="wf_ped",
    random_seed=12345,
)
print(ped_ts.draw_text())
```
the tree sequence we get out of the pedigree looks like this:
```
10.00┊          9                              ┊   
     ┊          ┃                              ┊   
9.00 ┊          ┃                              ┊   
     ┊          ┃                              ┊   
8.00 ┊          ┃                              ┊   
     ┊          ┃                              ┊   
7.00 ┊          ┃                              ┊   
     ┊          ┃                              ┊   
6.00 ┊          ┃                              ┊   
     ┊          ┃                              ┊   
5.00 ┊          ┃                 50           ┊   
     ┊          ┃            ┏━━━━━┻━━━━┓      ┊   
4.00 ┊          ┃           67          ┃      ┊   
     ┊          ┃       ┏━━━━┻━━━┓      ┃      ┊   
3.00 ┊          ┃       ┃        ┃      ┃      ┊   
     ┊          ┃       ┃        ┃      ┃      ┊   
2.00 ┊         83       ┃       85      ┃      ┊   
     ┊      ┏━━━╋━━━┓   ┃     ┏━━┻━━┓   ┃      ┊   
1.00 ┊      ┃   ┃   ┃   ┃    92     ┃   ┃  90  ┊   
     ┊      ┃   ┃   ┃   ┃   ┏━┻━┓   ┃   ┃   ┃  ┊   
0.00 ┊ 100 101 104 108 102 105 107 106 109 103 ┊   
   0.00                                     100.00 
```
So, we have nodes 100, 9, and 90 popping out of the pedigree at different times. Then, if we recapitate as before we get 
```
31.00┊                      112                ┊   
     ┊             ┏━━━━━━━━━┻━━━━━━━━━━┓      ┊   
15.00┊            111                   ┃      ┊   
     ┊    ┏━━━━━━━━┻━━━━━━━┓            ┃      ┊   
14.00┊   110               ┃            ┃      ┊   
     ┊  ┏━┻━┓              ┃            ┃      ┊   
10.00┊  ┃   ┃              ┃            9      ┊   
     ┊  ┃   ┃              ┃            ┃      ┊   
9.00 ┊  ┃   ┃              ┃            ┃      ┊   
     ┊  ┃   ┃              ┃            ┃      ┊   
8.00 ┊  ┃   ┃              ┃            ┃      ┊   
     ┊  ┃   ┃              ┃            ┃      ┊   
7.00 ┊  ┃   ┃              ┃            ┃      ┊   
     ┊  ┃   ┃              ┃            ┃      ┊   
6.00 ┊  ┃   ┃              ┃            ┃      ┊   
     ┊  ┃   ┃              ┃            ┃      ┊   
5.00 ┊  ┃   ┃             50            ┃      ┊   
     ┊  ┃   ┃        ┏━━━━━┻━━━━┓       ┃      ┊   
4.00 ┊  ┃   ┃       67          ┃       ┃      ┊   
     ┊  ┃   ┃   ┏━━━━┻━━━┓      ┃       ┃      ┊   
3.00 ┊  ┃   ┃   ┃        ┃      ┃       ┃      ┊   
     ┊  ┃   ┃   ┃        ┃      ┃       ┃      ┊   
2.00 ┊  ┃   ┃   ┃       85      ┃      83      ┊   
     ┊  ┃   ┃   ┃     ┏━━┻━━┓   ┃   ┏━━━╋━━━┓  ┊   
1.00 ┊  ┃  90   ┃    92     ┃   ┃   ┃   ┃   ┃  ┊   
     ┊  ┃   ┃   ┃   ┏━┻━┓   ┃   ┃   ┃   ┃   ┃  ┊   
0.00 ┊ 100 103 102 105 107 106 109 101 104 108 ┊   
   0.00                                     100.00 
```

We have picked up the three pedigree founders and simulated their history out to coalescence, as required. However, this is *not* a valid Wright-Fisher sample.

When we start the recapitation simulation, msprime sees that there is an sample at node 90 in generation 1, so it sets things up accordingly and starts simulating a DTWF where 90 is a sample and there is a diploid population of 5 individuals which it can descend from. However, this is **not** true, because the size of the population it's in is effectively smaller due to the existence of the pedigree individuals. 

It seems like we should be able to correct for this by reasoning about the number of lineages that are in the trees we're recapitating from at each time. This would be tricky, probably, so it would be good to get people's thoughts on what's happening here.

Pinging @sgravel @LukeAndersonTrocme @apragsdale for thoughts

**Comment by apragsdale** [comment]
In the "naive" approach, even if we were to adjust the "effective" N by subtracting the number of lineages that are in the trees at each generation in the DTWF simulation until the most ancient root of the pedigree, we'd still be imposing structure between in-pedigree vs out-of-pedigree samples and their ancestors. Unless I'm overlooking something, you should get back a valid WF sample by allowing coalescence back into the pedigree, by setting probability of picking a node within the pedigree each generation based on the number of lineages in the pedigree that generation. That does sound painful to set up, however, especially with recombination changing number of lineages at a given time in adjacent trees. We'd need to be able to remove existing branches in the tables, add intermediate nodes, and reintroduce the resulting split edges. (Or am I way off base here with what the main issue with that is?)

There's also the issue that many (most?) pedigrees we'll want to work with aren't from a random-mating WF setting, maybe with overlapping generations or non-ultrametric(?) paths through the pedigree, so trying to fill in the missing data in the pedigree with a WF simulation would result in mismatched mating assumptions for coexisting individuals from the same population. Perhaps for that reason, I'd lean toward your option 1 that you listed.

**Comment by jeromekelleher** [comment]
Sounds about right to me @apragsdale, all very tricky.

**Comment by gregorgorjanc** [comment]
Option 3 with a warning to provide a way to recapitate pedigrees? 

Option 1 would be of course the other extreme.

Why is the large N in the population, compared to what is in the pedigree, a requirement? I never understood this part of the coalescent. As to what is the situation in reality, it will vary widely.

Case A) There are closed populations where all individuals are part of one or many pedigrees (many if we would maintain dis-joint groups of individuals that never mate) - so, in those cases there are no other individuals (from that population, but there will be other populations of course). I am not fully clear about the simulation steps up the pedigree. If one would like to allow for coalescence within the pedigree for the case A, could you step back in time and every generation check if there are any nodes that don't have a parent and allow coalescence into other available parents within a pedigree?

Case B) There will be cases where we know pedigree for only a small subset of a population - in those cases we could have a large N in pop and a small N in pedigree. Use option 3 in this case?

Case C) Everything in between cases A and B.

For each case multiple dis-joint pedigrees could represent different populations - like you showed in the meeting. There is an additional choice (in addition to a choice between the case A and B) - do you allow coalescence from one pedigree into another before all nodes coalesced within each pedigree (I think this makes sense for the case A, but less for the case B).

Yeah, real cases are hard!

**Comment by gregorgorjanc** [comment]
@petrelharp while I agree with option 3, I would like to point that real pedigrees always have some missing data - the farther back in time you go, the more missingness there is. "Complete pedigrees" are very rare and actually an oxymoron, because you always run out of info about ancestors as you go back into the past;)

**Comment by jeromekelleher** [comment]
Thanks for the input all, this is very helpful. I'll chew on it for a few days and come back with a proposal.

**Comment by sgravel** [comment]
@apragsdale, 
To clarify, I'll define three models:

The "remainder" model will refer to a model with the pedigree plus a remainder population with size N_e - N_{pedigree}. To do this, you need to set up a migration rate between the two pedigree and the remainder population that are typically very high (m of order 1).  

Because setting up these migrations correctly is hard, you could also ignore these migrations. I'll call this the "remainder without migration" model. I believe that this is what you are referring to and is indeed a bad model  because of pathological increases in relatedness among the founders

The third option is the "founder" model, where each missing individual is taken to come from a distinct population of size Ne with no adjustment for size. That is the model I prefer, since 1-it works well when the genealogy corresponds to a founder population, and 2- even in the case of missing links, the errors are likely to be tolerable in most cases where genealogical simulations make sense. 

I think in practice many genealogies will have a combination of missing links due to missing data within a population and missing links due to immigration. I think that the founder model does an acceptable job at both.

**Comment by jeromekelleher** [comment]
Linking this to #2009 - we need to spell out the model here in the docs.

**Comment by jeromekelleher** [comment]
Closing this issue as I think the basic decision has been made, we just need to document it (#2009)
