### ISSUE TITLE
mspms parameter value change compared with ms

### ISSUE THREAD

**Issue by AlisaGU** [tskit-dev/msprime#1885]
Hi,
After reading the [mspms manual](https://tskit.dev/msprime/docs/stable/cli.html#sec-mspms), I think mspms parameter values are identical to those in ms except -n and -en. 
In mspms, the value of -n is size *N0. In ms, the value of -n is size.
-en is set in this way too.

Is it right?

**Comment by jeromekelleher** [comment]
The mspms interface is supposed to be identical to ms @AlisaGU, so this would be a serious bug. We compare the outputs in a bunch of statistical tests [here](https://github.com/tskit-dev/msprime/blob/e00bb3917dd65d24e2587228bfcfa836f74f6622/verification.py#L447) so I'd be surprised if this was the case (but maybe we're not trying the right parameter combos?)

Do you have an example where you think the outputs would differ? 

If there isn't a bug, it would be great if you could point out the bits of documentation for mspms that you found misleading.

**Comment by AlisaGU** [comment]
Actually, I didn't rum mspms. I just feel uncertain when I read 
```
--population-size, -n
Set the size of a specific population to size*N0.
```

**Comment by grahamgower** [comment]
> Actually, I didn't rum mspms. I just feel uncertain when I read https://tskit.dev/msprime/docs/stable/cli.html#sec-mspms
> 
> ```
> --population-size, -n
> Set the size of a specific population to size*N0.
> ```


This is the same as what ms does. E.g. paraphrasing the ms docs: `-n t x` sets the population size at time `t` to `x*N0`.

**Comment by AlisaGU** [comment]
If population size is 15000 and N0 is set to 10000, so `-n t 1.5`?

**Comment by grahamgower** [comment]
Yes, that looks right.

**Comment by AlisaGU** [comment]
Thanks for your quick and clear explaination.
Just a little suggestion, more complicated examples will help us understand the parameter value, like the last few examples in ms.

**Comment by grahamgower** [comment]
I'm sure Jerome will correct me if I'm wrong, but the mspms interface is provided for ms-compatibility purposes and is definitely not recommended if you are starting a new project! Writing ms command lines is hard work and error prone, but more importantly its no longer necessary. Msprime has an excellent Python API, which should be preferred. If you really don't want to use the Python API, an alternative that you might consider is to write your demographic model as a [Demes yaml file](https://popsim-consortium.github.io/demes-spec-docs/main/introduction.html) and pass this to the `msp ancestry` command, e.g. `msp ancestry --demography mymodel.yaml`.

**Comment by AlisaGU** [comment]
Thanks, I will try it.

**Comment by AlisaGU** [comment]
Demes yaml file is interesting and I like it. It gives me a intuitive grasp.

**Comment by jeromekelleher** [comment]
As @grahamgower says - mspms is really only intended to support people who already use ms, it's not the recommended interface to msprime.

**Comment by AlisaGU** [comment]
Thanks, I get it.

**Comment by jeromekelleher** [comment]
I'm going to close these issues - please feel free to open as a [discussion](https://github.com/tskit-dev/msprime/discussions) if you'd like to more info @AlisaGU
