### ISSUE TITLE
recombination nodes not recorded when the given recombination map has NaN values at the beginning

### ISSUE THREAD

**Issue by hyl317** [tskit-dev/msprime#1893]
Hi everyone, I found that when record_full_arg=True, the output tree sequence doesn't seem to record recombination nodes when the recombination map has NaN values in self.rate. This happens when the first row of hapmap has non-zero basepair position but zero genetic position. [here](https://doi.org/10.5281/zenodo.5656996) you can find such an example genetic map (hapmap chr5).

A small example of this from Yan Wong:
 
`
>>> rate_map = msprime.RateMap(position=[0, 10, 90, 100], rate=[np.nan, 1, np.nan])
>>> ts = msprime.simulate(10, recombination_map=rate_map, record_full_arg=True, random_seed=1)
>>> ts.num_trees
536
>>> np.any(ts.tables.nodes.flags > 1)  # should be True if any recombination nodes present
False
`

thanks!

**Comment by jeromekelleher** [comment]
Thanks for the bug report @hyl317. The issue is that the ``delete_intervals`` call used to snip out the unknown nan sections calls simplify by default, which removes all the recombination nodes. I'll add a fix.
