### ISSUE TITLE
memory leak in sim_ancestry()

### ISSUE THREAD

**Issue by grahamgower** [tskit-dev/msprime#1899]
I'm seeing a fairly rapid increase in memory use over time with the following test case.
```python
import msprime

print(msprime.__version__)
for seed in range(1, 10_001):
    msprime.sim_ancestry(samples=64, random_seed=seed)
```

I ran it under [memory-profiler](https://pypi.org/project/memory-profiler/):
```
$ time mprof run sim-sim-sim.py 
mprof: Sampling memory every 0.1s
running new process
running as a Python program...
1.0.2

real    2m0.464s
user    1m53.911s
sys     0m5.716s
```

```
$ mprof plot -o leaky.png mprofile_20211110210243.dat
```
And see this
![leaky](https://user-images.githubusercontent.com/8665077/141185629-972eefdf-af3d-4ba6-ac61-fb6e9474d422.png)

**Comment by jeromekelleher** [comment]
Hmm, thanks @grahamgower - great bug report (I learned a new tool!). I also tried this with using replicates:
```python
for _ in msprime.sim_ancestry(
        samples=64, random_seed=1, num_replicates=100000):
    pass
```

(It's a *lot* slower running one-by-one). We get:
![replicates](https://user-images.githubusercontent.com/2664569/141265186-261c0bf7-6f9a-4e7e-9c67-9dc4e6c99de6.png)

Looks like the issue is in provenance. Here's one-by-one iteration and replicates with ``record_provenance=False``:
![iter-noprov](https://user-images.githubusercontent.com/2664569/141265303-cd5eea3d-31dd-4ef6-a6a1-1a40613796b5.png)

![reps-noprov](https://user-images.githubusercontent.com/2664569/141265328-ad3509ea-c5fe-4200-894f-2d14f488c3ed.png)

**Comment by jeromekelleher** [comment]
How well do you know memory_profiler @grahamgower? I'm trying to get a line-by-line profile of the ``Simulator.run_replicates`` function but failing.

**Comment by grahamgower** [comment]
Ah, cool. That makes sense actually. The memory growth isn't unbounded (peaks ~2.5Gb on my laptop), and I've found that periodically calling `gc.collect(generation=2)` will reduce the peak memory. This points at an issue with circular references, so it makes sense that turning off the provenance fixes this.

FYI, my test case uses one-by-one simulations because my full code is altering the simulation parameters in each call (and also using multiple simulation processes, which each have memory growth).

**Comment by grahamgower** [comment]
> How well do you know memory_profiler @grahamgower? I'm trying to get a line-by-line profile of the `Simulator.run_replicates` function but failing.

This is my first time using it. :)

**Comment by jeromekelleher** [comment]
Ah yes, good call. It's probably some circular references in the provenance... I'll try and get a fix done and push out a release ASAP though, this is a big leak.

**Comment by jeromekelleher** [comment]
As far as I can tell it's something to with the calls to [inspect.getargvalues](https://github.com/tskit-dev/msprime/blob/48977225f39efa47a083a0fb570fef2b319c46b7/msprime/ancestry.py#L421)  and [inspect.currentframe](
https://github.com/tskit-dev/msprime/blob/48977225f39efa47a083a0fb570fef2b319c46b7/msprime/ancestry.py#L1141) which we use to populate the provenance parameters.

I don't have much patience for fixing this to be honest, and I think the best thing to do is just forget about storing the simulation parameters in the provenance: #1903

**Comment by grahamgower** [comment]
I don't want to wade into the debate about whether we keep the provenance or not (I think its worth will be more apparent years after the provenance info is written)... But here's the fix in case we do want to keep it.

```
diff --git a/msprime/ancestry.py b/msprime/ancestry.py
index c1b2aa5b..9feefc41 100644
--- a/msprime/ancestry.py
+++ b/msprime/ancestry.py
@@ -419,6 +419,7 @@ def _build_provenance(command, random_seed, frame):
     passed in, with a few exceptions.
     """
     argspec = inspect.getargvalues(frame)
+    del argspec.locals["frame"]
     # num_replicates is excluded as provenance is per replicate
     # replicate index is excluded as it is inserted for each replicate
     parameters = {
@@ -580,7 +581,10 @@ def simulate(
     provenance_dict = None
     if record_provenance:
         frame = inspect.currentframe()
-        provenance_dict = _build_provenance("simulate", random_seed, frame)
+        try:
+            provenance_dict = _build_provenance("simulate", random_seed, frame)
+        finally:
+            del frame
 
     if mutation_generator is not None:
         # This error was added in version 0.6.1.
@@ -1139,7 +1143,10 @@ def sim_ancestry(
     provenance_dict = None
     if record_provenance:
         frame = inspect.currentframe()
-        provenance_dict = _build_provenance("sim_ancestry", random_seed, frame)
+        try:
+            provenance_dict = _build_provenance("sim_ancestry", random_seed, frame)
+        finally:
+            del frame
     sim = _parse_sim_ancestry(
         samples=samples,
         sequence_length=sequence_length,
```

The problem is a reference cycle. The garbage collecter will collect these, but not quickly enough apparently. The [`inspect` docs](https://docs.python.org/3/library/inspect.html#the-interpreter-stack) warn about this, and suggest deleting the frame object after use (the latter part of the diff above). Our problem here, though, is that `inspect.getargvalues(frame)` returns an object with references to the local variables in the given frame, and that frame happens to have a local variable named "frame" which is the exact thing we should be cleaning up to avoid the reference cycle. So, all in all this is quite a mess!

**Comment by molpopgen** [comment]
Would forcing a garbage collection event after calling this function help?

**Comment by grahamgower** [comment]
> Would forcing a garbage collection event after calling this function help?

Yes, that works. But then if feels like you're simulating on a PDP-11.

**Comment by molpopgen** [comment]
> Yes, that works. But then if feels like you're simulating on a PDP-11.

I had to google that.

**Comment by jeromekelleher** [comment]
Thanks for looking into this @grahamgower - I fixed the problem with a good-ole non magical solution which is only slightly more code.
