### ISSUE TITLE
Drop "parameters" section from provenance records

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1903]
Trying to record the exact parameters used in making a particular simulated tree sequence is very difficult and has generated a lot of complexity in the code. 

It looks like it has lead to a massive memory leak in #1899 

Since it's unclear if there's any real value in it, I vote that we drop the parameters section from msprime API calls and just store the rest of the information.

Thoughts/objections?

**Comment by molpopgen** [comment]
I think it would be a shame to lose this feature. We get a lot of mileage out of it for forward simulations. Is the issue circular references or something worse?

**Comment by jeromekelleher** [comment]
> We get a lot of mileage out of it for forward simulations.

How do you record the parameters there? Do you hit the "this parameter is really big and complicated" problem?

> Is the issue circular references or something worse?

I'm not sure - the leak wasn't showing up in tracemalloc or any other tools, so it's hard to know. The simplest way to solve the problem would be to drop the inspect magic and encode the parameters dict by hand (well, simplest other than dropping entirely).

**Comment by molpopgen** [comment]
> > We get a lot of mileage out of it for forward simulations.
> 
> How do you record the parameters there? Do you hit the "this parameter is really big and complicated" problem?

Ultimately, everything is either a dict or has a representation as dict.  So, we store the string representation of that dict.  This hasn't led to issues for current users, but ignoring best practices could.  For example, trying to include a function rather than a callable class. So, we don't provide examples of such things in the docs.
> 
> > Is the issue circular references or something worse?
> 
> I'm not sure - the leak wasn't showing up in tracemalloc or any other tools, so it's hard to know. The simplest way to solve the problem would be to drop the inspect magic and encode the parameters dict by hand (well, simplest other than dropping entirely).

**Comment by jeromekelleher** [comment]
Actually, I take it back - it's easy to fix the memory leak and much less work than yanking out the provenance parameters: #1904
