### ISSUE TITLE
Update `from_demes()` once demes-0.1.3 is released

### ISSUE THREAD

**Issue by apragsdale** [tskit-dev/msprime#1930]
Demes 0.1.3 will introduce some breaking changes (e.g. pulses will now specify sources and proportions as lists, instead of source and proportions as single values). We're quite close there to hitting all the milestones to get 0.1.3 out the door (https://github.com/popsim-consortium/demes-python/milestone/3), so this issue is just to make sure we are on top of it. (The requirements also has "demes>=0.1.2", so demes-0.1.3 will end up not working with the current msprime version if the user has demes-0.1.3 installed.)

The changes in msprime should only require updating `Demography.from_demes()`, specifically a few simple changes in lines here: https://github.com/tskit-dev/msprime/blob/7fbaab3b031f7208cd82b79763e924260f412723/msprime/demography.py#L1984

**Comment by jeromekelleher** [comment]
Sounds good @apragsdale. I'm currently hoping to get msprime 1.1 out in a few weeks (conditioned on tskit 0.4.0 and getting the pedigree stuff wrapped up). I'll put this into the 1.1 milestone for now, so we don't forget about it (in case the demes release is out in time).

**Comment by apragsdale** [comment]
Great! Thanks @jeromekelleher. I think it's quite doable, as it's just two "small" issues over in Demes to resolve. I'll ping @grahamgower and see if we can make it in time for msprime-1.1.

**Comment by grahamgower** [comment]
Thanks @apragsdale for opening this. I think we should make the next demes-python release version 0.2.0, because of this breaking change. msprime 1.0.x already requires demes<0.2 in the setup.cfg, so the next demes release shouldn't cause big problems (fingers crossed).

**Comment by jeromekelleher** [comment]
Does this need doing now that version 0.2.0 of demes is out @apragsdale? We can push out a quick point release here with any updates?

Looks like we should just be able to wait though?

**Comment by apragsdale** [comment]
I have already started on those updates to msprime for demes 0.2 and been using them locally, so it will be quick to get a PR together for you two to have a look at. If 1.1 is close, I don't know if it's so important to rush out a point release, but it could be nice to have if 1.1 is a bit further off

**Comment by jeromekelleher** [comment]
Cool, let's see where we are after the PR goes in. Probably simplest to pop out a quick point release, it's no big deal.

**Comment by jeromekelleher** [comment]
Closed in #1936
