### ISSUE TITLE
Distinguishing autogenerated population names

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime#1932]
Although it's [not yet documented](https://github.com/tskit-dev/msprime/issues/1926), `msprime` now automatically generates names for populations, like "pop_0", "pop_1", etc, and stores them in the metadata, along with a blank description. I've found that it's useful to know, if I have 2 separately simulated tree sequences, potentially with different numbers & identities of populations, that "pop_1" in one tree sequence might not correspond to "pop_1" in the other tree sequence, unlike, for example, if the name was "GBR".

I suggest that for autogenerated names like this, we might want to put a string like "name autogenerated by msprime" in the description field of the metadata, to help us distinguish a name that has been generated for us, and which therefore might not be a unique identifier for this population across different tree sequences.

**Comment by jeromekelleher** [comment]
Yes, that seems like a reasonable thing to do. However, I'm not sure it'll be of much help downstream when trying to disambiguate - what happens if msprime changes the default string in the description a little bit? The description field is free text and just intended to communicate with users.

**Comment by hyanwong** [comment]
I was thinking of defining msprime.AUTOGENERATED_POP_DESCRIPTION = "name autogenerated by msprime" and setting it to that constant?

**Comment by hyanwong** [comment]
Any suggestions of other ways to check if names have been "autogenerated" then? It would be useful to set a precedent for an issue in tsinfer, and I do think it's a useful thing to be able to test programatically.

**Comment by hyanwong** [comment]
An alternative, although perhaps not any better, is for the autogenerated population *name* to begin with the tool that generated it, e.g. "msprime_pop_1". 🤷

**Comment by jeromekelleher** [comment]
Did we decide on any actions here @hyanwong are can we close?
