### ISSUE TITLE
Convert msprime full_arg output to version with single recombination nodes

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime#1949]
Since we [plan to switch to using a single recombination node rather than 2](https://github.com/tskit-dev/msprime/issues/1942), it would be helpful to be able to convert an msprime tree sequence with ARG nodes to the new 1-node format. I think this should do it:

```python
def convert_to_single_rec_node(ts):
    tables = ts.dump_tables()
    tables.nodes.clear()
    node_mapping = np.zeros(ts.num_nodes, dtype=tables.edges.child.dtype)
    node_id = 0
    while node_id < ts.num_nodes:
        node = ts.node(node_id)
        tables.nodes.append(node)
        node_mapping[node_id] = tables.nodes.num_rows - 1
        if (node.flags & msprime.NODE_IS_RE_EVENT):
            node_id += 1
            assert node_id < ts.num_nodes
            matching_node = ts.node(node_id)
            assert matching_node.flags & msprime.NODE_IS_RE_EVENT
            assert matching_node.time == node.time
            node_mapping[node_id] = tables.nodes.num_rows - 1
        node_id += 1
    tables.edges.parent = node_mapping[tables.edges.parent]
    tables.edges.child = node_mapping[tables.edges.child]
    tables.mutations.node = node_mapping[tables.mutations.node]
    tables.sort()
    return tables.tree_sequence()
```

The logic is that we clear the node table and loop over the nodes, adding then data back in. However, when we meet a pair of recombination nodes, we only add a single one, and keep a mapping of the old to the new nodes IDs, which we then use to update the nodes IDs in other tables.

**Comment by jeromekelleher** [comment]
LGTM - do we want this as an issue (i.e., something we can close after taking some action) or as a discussion?

**Comment by hyanwong** [comment]
I thought maybe an issue which we close when release a version with the new format? But maybe a discussion is better?

**Comment by jeromekelleher** [comment]
I see - we should choose this or #1942 as the main issue then (and close one of them).

**Comment by hyanwong** [comment]
Good point. maybe close this one. Sorry!

**Comment by hyanwong** [comment]
Also I forgot to make a new flag for these new nodes. Perhaps `tskit.NODE_IS_RECOMB`? Or should it be an msprime thing still?

**Comment by jeromekelleher** [comment]
> Or should it be an msprime thing still?

We decided to keep it as an msprime thing for now

**Comment by hyanwong** [comment]
> > Or should it be an msprime thing still?
> 
> We decided to keep it as an msprime thing for now

But we could define it in the "tskit" space: i.e. in the lowest 8 bits (I think that's what's reserved for tskit use, right?)

**Comment by jeromekelleher** [comment]
> But we could define it in the "tskit" space: i.e. in the lowest 8 bits 

That's what I was thinking all right

**Comment by hyanwong** [comment]
OK, I'll paste the code above into #1942 and close this
