### ISSUE TITLE
can't specify population names to `sim_ancestry()` when recapitating

### ISSUE THREAD

**Issue by grahamgower** [tskit-dev/msprime#1950]
I'm trying to come up with a fix for https://github.com/popsim-consortium/stdpopsim/issues/1140 that will work when SLiM 3.7 arrives, but I'm not sure that the current msprime API provides a (reasonable) way to specify the population names that will be in the `initial_state` population metadata.

* In stdpopsim, we have the name in the `PopulationConfiguration` metadata. But this is metadata, and msprime doesn't look at it.
* We can pass a `population_map` to `Demography.from_old_style()`. This is undocumented. From the source code, it looks like a list of maps---one map per epoch---which is hard to come by unless one does a deep inspection of the epochs for the demography at hand.

Is there something simple to be done here? We have the names; we can give a map from integer id to name. How do we tell msprime what the names are?

**Comment by petrelharp** [comment]
I haven't dug into the details here yet - but is the problem using `from_old_style( )`, or more general?

**Comment by grahamgower** [comment]
It's only possible to specify popuation names by passing `demography=msprime.Demography(...)` to `sim_ancestry()`. In stdpopsim, we're using `from_old_style()` to make the Demography object. In the future, we'll convert to Demes demographic models, which will include the name when converting to an `msprime.Demography` (which will probably work great). But in absense of a Demes model (e.g. outside of the future-stdpopsim world) there will be many preexisting codes that want to use `sim_ancestry()` in order to recapitate, and their only option will be via `from_old_style()` - but the population_map is undocumented and even if it get documented I don't think its a very nice path to mapping ids to names for the legacy-api recapitation use case.

So, really, this issue is about coming up with some canonical approach to match up population names when doing recaptitation if one has legacy-api code.

**Comment by grahamgower** [comment]
I think the most common case will be SLiM recapitation with a single root population that needs recaptitation. This also needs a population name or recaptitation fails, right?

**Comment by grahamgower** [comment]
PS: I've been ignoring the `pyslim` api in my recent investigations because this seems to want to convert the tree sequence to an old version upon loading. I don't know what's going on here, I kinda assumed you (@petrelharp) hadn't updated things yet (no pressure :)).

**Comment by jeromekelleher** [comment]
What if we added a ``name`` attribute to the 0.x PopulationConfiguration class @grahamgower, and used this (if set) in the [_from_old_style_simple](https://github.com/tskit-dev/msprime/blob/c034a5d24a39ad888a603a2c2042298ad0f8265f/msprime/demography.py#L1809) code path?

Stdpopsim could set the name and it should be ok then?

**Comment by grahamgower** [comment]
I think it would be simpler to pass a `population_names` parameter to `from_old_style()`, which is just a list of parameter names in the appropriate order.

**Comment by jeromekelleher** [comment]
OK, I'll do this today. I want to get a release out today, so it's a quick turnaround I'm afraid - it'd be great if I could get your review a bit later.
