### ISSUE TITLE
operations should retain the `reference_sequence` and (sometimes) `time_units`

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/msprime#1951]
Right now `sim_ancestry(from_ts= )` and `sim_mutations( )` will drop the reference sequence, if there is one:
```
ts = msprime.sim_ancestry(2, sequence_length=1)
t = ts.dump_tables()
t.reference_sequence.data = 'A'
ts = t.tree_sequence()

mts = msprime.sim_mutations(ts, rate=1)

ts.reference_sequence.data, mts.reference_sequence
# ('A', None)
```

Perhaps tskit needs a helper function that says "give me a new table collection based on this one" that passes over the reference sequence and metdata schema and things? e.g. `tsk_table_collection_empty_copy( )` to make this sort of thing easy?

**Comment by petrelharp** [comment]
Also - at least `sim_mutations( )` should retain `time_units`:
```
>>> ts = msprime.sim_ancestry(2, sequence_length=1)
>>> t.time_units = 'ticks'
>>> ts = t.tree_sequence()
>>> ts.time_units
'ticks'
>>> mts = msprime.sim_mutations(ts, rate=1)
>>> mts.time_units
'unknown'
```

**Comment by jeromekelleher** [comment]
We need to pull in tskit C_0.99.15 for this and require tskit 0.4.0. This is done in #1945. I was going to hold off for a bit on this, but actually this needs to go out ASAP, so I'll push out a patch release tomorrow to update.
