### ISSUE TITLE
Store ARG breakpoints in node metadata

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1979]
As prototyped in #1978, it would be very helpful if we stored the actual breakpoint when running ``full_arg`` simulations. We can infer *some* breakpoints from the resulting edges, but not all (they might fall in the middle of non ancestral material). The major update will be adding the metadata schema to the NodeTable, and ensuring that we set valid JSON on every node.

We can do this after #1942

**Comment by hyanwong** [comment]
It would then be trivial to output a Griffiths ARG from an msprime full arg: just take these breakpoints form the metadata and drop the right and left from the edges, right? Is it worth defining an msprime helper function to do this export? I suspect not, but thought I would mention it (note that this isn't a tskit function, because a TS can be much more general than a Griffiths ARG)

**Comment by jeromekelleher** [comment]
Yes, all quite tricky. I think the first step is to do the simplest form of this so we get things working again, and then to take a step back to see if we can refactor things a bit with an eye to generalisation. Until we have some infrastructure for converting back and forth from the Griffiths representation (tskit-dev/tskit#2098) we're going to be talking too much in the abstract and stand a good chance of forgetting about important details.

**Comment by hyanwong** [comment]
> Until we have some infrastructure for converting back and forth from the Griffiths representation ([tskit-dev/tskit#2098](https://github.com/tskit-dev/tskit/issues/2098)) we're going to be talking too much in the abstract and stand a good chance of forgetting about important details.

Absolutely. I think this is a really good way forward, so thanks for taking that on! We need to remember, however, that the Griffiths representation is only one example of a (node annotated) ARG, and I don't think we want to paint ourselves into a corner. Having said which, the idea of using the metadata means that this is kept pretty flexible for future changes.

**Comment by jeromekelleher** [comment]
I've made a start on this in  #1990 and in principle it's straightforward, but in practise a whole bunch of painful compatibility issues start cropping up when we set a metadata schema on the NodeTable. Things that were equal before are no long equal because one has a schema and the other doesn't, even though we're not actually recording any metadata. There's a real risk that we'll break a lot of code and I'm not sure the benefits outweigh the costs (a significant one being, the time it takes to figure out how significant the problems are).

We could just set a metadata schema in the ``record_arg`` case, which then shouldn't break any existing code, but the details then of storing "{}" or not in all the places we update the node table is quite tedious. I guess this would be alleviated if we had a fix for https://github.com/tskit-dev/tskit/issues/2064, but then we have to wait for a decision to be taken on that point and an update to tskit to be shipped.

Another approach would be to return a tuple ``ts, breakpoints`` from sim_ancestry when ``record_arg`` is True where breakpoints is a numpy array. This would mean we don't have to set any metadata, and would have direct access to the breakpoints array that we need for computing likelihoods, although it would mean breaking code using the likelihood function as well.

Yuck, this is all very messy. Any thoughts @hyanwong @jerekoskela?

**Comment by JereKoskela** [comment]
I'm instinctively reluctant to mess with the return types of `sim_ancestry`. I imagine something like that would raise a lot of questions and cost people time if they've e.g. used `record_arg` for early debugging or small visualisations, with a view to dropping it for a more substantial pipeline. It also just feels counterintuitive, when the data structure should be able to support both formats.

One option would be to roll back the decision to change to a single recombination node. I think that a two node structure should be able to support arbitrary patterns of recombination, gene conversion, etc, by detecting the points where ancestry jumps from one recombination node to the other. I'm aware it comes with other issues though, and don't have a clear sense of how those compare to the messiness we're talking about here.

**Comment by jeromekelleher** [comment]
Maybe what we should do is return an ARG in the form discussed https://github.com/tskit-dev/tskit/issues/2098, which we then convert into the edge annotated form?

It would be messy as we'd probably need to post-process the tables to make sure we only have one edge for every non recombination node, but that's not so bad. Recording the RE edges would be fine as we're special-casing that already.

**Comment by jeromekelleher** [comment]
> One option would be to roll back the decision to change to a single recombination node. I think that a two node structure should be able to support arbitrary patterns of recombination, gene conversion, etc, by detecting the points where ancestry jumps from one recombination node to the other. I'm aware it comes with other issues though, and don't have a clear sense of how those compare to the messiness we're talking about here.

That is an option, but we still lose the location of breakpoints in non ancestral material don't we? We want to be able to losslessly transform to a griffith's graph.

**Comment by JereKoskela** [comment]
> > One option would be to roll back the decision to change to a single recombination node. I think that a two node structure should be able to support arbitrary patterns of recombination, gene conversion, etc, by detecting the points where ancestry jumps from one recombination node to the other. I'm aware it comes with other issues though, and don't have a clear sense of how those compare to the messiness we're talking about here.
> 
> That is an option, but we still lose the location of breakpoints in non ancestral material don't we? We want to be able to losslessly transform to a griffith's graph.

Ah, yes, that is true. If we want to retain all exact breakpoints then two recombination nodes won't save us by itself.

**Comment by jeromekelleher** [comment]
I think maybe setting a metadata schema for the node table only in the case of ``record_arg`` is probably the way to go, on reflection. It's not so bad complexity wise, and it won't break people's code.

**Comment by hyanwong** [comment]
> I think maybe setting a metadata schema for the node table only in the case of `record_arg` is probably the way to go

I agree. I think that, in the long term, we want to fix https://github.com/tskit-dev/tskit/issues/2064 and so short-term breakage is OK: we could probably just comment out the tests that fail on full ARGs for this reason, and reinstate them when https://github.com/tskit-dev/tskit/issues/2064 is addressed, assuming that might be in the next month or so?

**Comment by jeromekelleher** [comment]
This turned out to be a lot of trouble, and I think that we have moved away from doing the single-node recombination in msprime, so going to close this.
