### ISSUE TITLE
Use ``ancestral_to`` field on segments instead of global lookup table.

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1993]
A fundamental part of the work in coalescent simulation is to keep track of the amount of ancestral material remaining for each interval along the genome. In msprime we currently do this using an AVL tree (S) (see [here](https://github.com/tskit-dev/msprime/blob/45fd7b88e8309e7c152ea8aadd14ac17fa4e438b/algorithms.py#L594)), and we update this structure during common ancestor events (e.g., [here](https://github.com/tskit-dev/msprime/blob/45fd7b88e8309e7c152ea8aadd14ac17fa4e438b/algorithms.py#L1755)). 

It turns out this is unnecessary and we can achieve the same thing by adding an ``ancestral_to`` field to each segment, which counts the number samples it is ancestral to. Then, when we merge segments at coalescence, we simply add the ``ancestral_to`` values.

See [this code](https://github.com/tskit-dev/what-is-an-arg-paper/blob/93e103925643ffe83d67cfad5c2df0b8d1106058/utils/args.py#L1) for how the simulation works when we track common ancestry by segment.

This should simplify the main interval overlap routines in msprime, and also result in a significant performance boost. I think a substantial fraction of the current simulation time (say, 20% for a long genome and large sample size) is taken up with AVL tree operations to maintain S.

**Comment by jeromekelleher** [comment]
I think you demonstrated that this is actually detrimental to performance @GertjanBisschop - can you comment please?

**Comment by GertjanBisschop** [comment]
Yep, that is true. The main reason was that a lot of segments cannot be squashed when keeping track of a single `ancestral_to` value per segment, as squashing can only happen for segments with identical `ancestral_to` values.

**Comment by jeromekelleher** [comment]
Closing this as "this was a bad idea" then!
