### ISSUE TITLE
Informations from the table.migrations

### ISSUE THREAD

**Issue by ChrystelleDelord** [tskit-dev/msprime#1994]
Dear all, 

This might be quite an easy question to answer: I was just wondering about which information is stored exactly within the tskit.MigrationTable?
I have been running quite simple 2-populations divergence models with varying migrations rates, but for now, the `print(mts.tables.migrations)` command always returns an empty table, even with high migrations rates, small effective sizes, and serial sampling over time. 

I just wanted to make sure this is normal feature, and that this is only due to the fact that "Migrations are performed by individual ancestors, but most likely not by an individual whose genome is tracked as a node." as explained here: https://tskit.dev/tskit/docs/stable/data-model.html#sec-migration-table-definition , so that there actually is a very small chance of having a non-empty migration table?

Many thanks and have an awesome day!
Best regards

Chrys

Code below:
```
samp_size=100
delta=10
ratio=0.20
decline_p1=math.log(ratio)/delta
decline_p2=math.log(ratio)/delta
m=0.05
N_int_p1=50000
N_int_p2=50000
N_cur_p1=ratio*N_int_p1
N_cur_p2=ratio*N_int_p2
N_before_split=N_int_p1+N_int_p2
r_anc = 0.00001
t_dec_p1=50
t_dec_p2=50
t_split=200500
t_anc_growth = 230258 

# Set demography:
demography = msprime.Demography()
demography.add_population(name="A", initial_size=ratio*N_int_p1)
demography.add_population(name="B", initial_size=ratio*N_int_p2)
demography.add_population(name="C", initial_size=N_before_split)
demography.add_population_parameters_change(time=t_dec_p1-delta, population="A", growth_rate=decline_p1)
demography.add_population_parameters_change(time=t_dec_p2-delta, population="B", growth_rate=decline_p2)
demography.add_population_parameters_change(time=t_dec_p1, population="A", growth_rate=0)
demography.add_population_parameters_change(time=t_dec_p2, population="B", growth_rate=0)
demography.add_population_split(time=t_split, derived=["A", "B"], ancestral="C") 
demography.add_population_parameters_change(time=t_split, population="C", growth_rate=r_anc) 
demography.add_population_parameters_change(time=t_split+t_anc_growth, population="C", growth_rate=0) 
demography.set_symmetric_migration_rate(populations=["A", "B"], rate=m) 

mutrate = 2.0e-08 
chromosomeSize = 1.0e06 # Very small size for first trials.
recombinationRate = 5.0e-8 

ts = msprime.sim_ancestry({"A": samp_size, "B": samp_size}, demography=demography, sequence_length=chromosomeSize, recombination_rate=recombinationRate, model=msprime.SmcApproxCoalescent(), random_seed=56)

mts = msprime.sim_mutations(ts, rate=mutrate, model=msprime.InfiniteAlleles(), random_seed=5678)
print(mts)
print(mts.tables.migrations)
```

**Comment by jeromekelleher** [comment]
Hi @ChrystelleDelord! :wave:

Recording all the migration information can become quite expensive, so it's not something that we have turned on by default in msprime. To make it work you need to provide the ``record_migrations=True`` argument to ``sim_ancestry``.  The [documentation](https://tskit.dev/msprime/docs/stable/ancestry.html#migration-events) might be helpful in getting you started as well.

Good luck!

**Comment by ChrystelleDelord** [comment]
Many thanks @jeromekelleher , I have indeed missed that information! All the best!
