### ISSUE TITLE
Coalescence trajectory for non symmetric migration

### ISSUE THREAD

**Issue by trevorcousins** [tskit-dev/msprime#2003]
I have encountered something peculiar with the debug.coalescence_rate_trajectory(), occuring when the demographic model has non symmetric migration. 

Consider two populations A and B, with a symmetric and constant migration rate. Migration happens only between times (generations) Ts_struct and Te_struct. We sample 2 lineages from A at time 0.

Let m be the rate as enetered per msprime (I think of this as the probability that a lineage migrates from some population to the other). 

If we have a constant (diploid) population size N in both A and B, then we can think of the scaled
migration rate as M = 2Nm as the expected number of lineages migrating from A to B (or vice a versa, thus the total number of migrants is 2M). 

The coalescence rates for this look how I would expect. The solid blue line is generated from msprime's debug.coalescence_rate_trajectory() and the dashed red line from my theoretical calculations. 
![image](https://user-images.githubusercontent.com/58950900/153213338-01928b4c-21c1-46dc-9eb0-680d8c7eaa83.png)
[simulated model here is N_A = 1e+04, N_B = 1e+04, m = 0.0003, Ts_struct = 1e+04, Te_struct=1.5e+04]

However, when the populations change their sizes things don't quite work as I would expect. 

Suppose now that A and B can change size, and that they are not necessarily equal. Still, m remains fixed and symmetric, but if A or B are different sizes then the expected number of migrating lineages from A to B is not the same as the expected number from B to A. Theoretically, to model this I would propose changing the scaled migration to M_AB(t)=2N_A(t)m for the rate of migrating from population A to B at time t. Similar for M_BA(t). When I calculate the coalescence rates and compare against msprime's rates, things don't come out so well:
![image](https://user-images.githubusercontent.com/58950900/153213699-9da990c8-f08d-4f99-9abb-73ba92cfa7c2.png)
[simulated model here is m = 0.0003, Ts_struct = 1e+04, Te_struct=1.5e+04, Ts_popchange=8e+03, Te_popchange=1.2e+04,
N_A(t,t<Ts_popchange or t>=Te_popchange) = 1e+04
N_B(t,t<Ts_popchange or t>=Te_popchange) = 1e+04
N_A(t,Ts_popchange<=t<Te_popchange) = 2e+04
]

I think I know why now. It seems that in msprime, no matter how you change the popuation sizes of A and B, we get a homogenous M. In other words, 
the total number of lineages migrating doesn't reflect the changes in the population's size, but seems fixed*. This seems odd to me. If I change my theory to account for homogeneous M, then things work out fine:
![image](https://user-images.githubusercontent.com/58950900/153214566-e5008dd9-72d3-42e6-a743-c84acac6c22b.png)

But this is not really what I want. So how can I can I change msprime's simulation to account for nonsymmetric migration if a population changes in size?

The alternate explanation is that something is wrong in msprime's calculation of coalescence rates, or something is wrong in my theory/code 

*It is not quite clear to me how diploid N (thus the homogeneous M=2Nm) is decided - is it the initial size in the demography.add_population parameter? Didn't seem to be. 

Code to simulate models was: 
`def mig_with_psc(N,T,Ts_struct,Te_struct,Ts_psc,Te_psc,m,intensity,pop_to_change):`
&emsp;`demography = msprime.Demography()`
&emsp;`demography.add_population(name="A", initial_size=N)`
&emsp;`demography.add_population(name="B", initial_size=N)`
&emsp;`demography.add_population_parameters_change(T[Ts_psc],initial_size=N*intensity, growth_rate=None, population=pop_to_change)`
&emsp;`demography.add_population_parameters_change(T[Te_psc], initial_size=N, growth_rate=None, population=pop_to_change)`
&emsp;`demography.add_symmetric_migration_rate_change(time=T[Ts_struct],populations=['A','B'],rate=m)`
&emsp;`demography.add_symmetric_migration_rate_change(time=T[Te_struct],populations=['A','B'],rate=0)`
&emsp;`demography.add_mass_migration(time=T[end_index_str], source="B", dest="A", proportion=1)`
&emsp;`demography.sort_events()`
&emsp;`debug = demography.debug()`
&emsp;`sim = msprime.sim_ancestry(samples={"A": 1, "B": 0},ploidy=2,demography=demography)`
&emsp;`return sim,debug`

**Comment by jeromekelleher** [comment]
Thanks @trevorcousins for the thorough report. I'm somewhat hazy on the details of this functionality,  I have to admit. @apragsdale @petrelharp any thoughts here?

**Comment by petrelharp** [comment]
I think you've correctly diagnosed what's going on, nice job.

> the total number of lineages migrating doesn't reflect the changes in the population's size, but seems fixed

Yes, this is true, it's because the "migration rate" is from the point of view of a *lineage*, looking back through time. We've tried hard to be clear on this difficult and confusing point in the documentation; if you have suggestions of how to make it better, please let us know.

We have discussed providing something to make it easy to set *forwards-time* migration rates. Unfortunately, this isn't so easy, since (as you observe) if population A is growing exponentially and population B is of fixed size, to have the same per-capita A->B migration rate, you need the "lineage migration rate" to decrease exponentially as you move further back in time, and msprime only has support for piecewise-constant-in-time migration rates. However, there is totally room for a tutorial on this issue (how to translate the natural forwards-time demographic model into a coalescent model).

**Comment by apragsdale** [comment]
The migration model in msprime, similar to many pop gen models I think, is not a "rate" in the sense of some expected number of migrants per generation, as you've found in your middle example. Instead m is the probability that an individual's parent was in a given population the generation before.

What this means in practice is that if your focal population doubles in size, each individual still has the same probability as before of picking their parent as a migrant from the other population. But with double the number of individuals picking parents, you get double the number of parents that came from that other population, so the expected number of migrating individuals is doubled. I think that's the effect you're seeing, right?

**Comment by nspope** [comment]
@trevorcousins just to chip in, one way to work around this issue in practice is to use a piece-wise-constant-in-time demographic model with a short duration for each time window. Then approximate "continuous" Ne trajectories by discretizing them (e.g. use the value of the continuous trajectory at the midpoint of each time window). Then, you can re-parameterize the migration matrix in each time window so that the expected number of immigrants/emigrants per generation is constant, regardless of their sizes. The shorter the time windows, the better the approximation to the continuous model.

**Comment by trevorcousins** [comment]
Thanks for the comments everyone. I think I am still missing something though.

I appreciate the comments from @apragsdale and @petrelharp about how m is the backwards in time probability (that a lineage in some population has a parent in another), and not the forward in time probability (that say a lineage in A migrates to B) that I had previously thought. I further appreciate that to accomodate an equal "per capita" migration rate with an exponentially growing population size, you must have a decreasing migration rate.

Responding to @apragsdale comment:
> But with double the number of individuals picking parents, you get double the number of parents that came from that other population, so the expected number of migrating individuals is doubled.

I'm not sure this is the issue though. I calculate the theoretical rate using a continuous time Markov chain (CTMC), with piecewise constant rates (just as @nspope had suggested) - I assume msprime is doing something similar (I tried looking at the source code but couldn't really decipher it). With this in mind, one has to use "rates" of either coalescing or migrating. These rates are synonymous with the "expected number" of migrations or coalescences. I give a short example.
With N_A = 1e+04, N_B = 1e+04, m = 0.0004, given two lineages in A they coalesce with rate 1, migrate out of A into B with rate 2M_AB = 4N_A*m=16 (one factor of 2 to account for diploid, the other because there are two lineages, each of which migrates independently of the other). Similarly given to lineages in B they coalesce with rate 1 and migrate out of B into A with rate 2M_BA = 16. Given one lineage in A and one in B, the rate of migrating to A is M_AB = 8 and to B is M_BA = 8. This is pretty much the same as my top figure from original post.

Curiously, if A doubles in size N_A = 2e+04, N_B = 1e+04, m = 0.0004, then the migration rates that fit msprime's curve are exactly the same, i.e. M_AB = M_BA =8, but the coalescence rate given two lineages in A is 0.5. This is my final plot in the orginal post.  The fact that here M_AB = M_BA = 8 defies my expectation and thus I don't think this is the effect "so the expected number of migrating individuals is doubled" that you mentioned @apragsdale (and @petrelharp).

Does this make sense? I feel like I am probably missing something obvious. Sorry for the long post and to ramble. Any thoughts highly appreciated!

**Comment by petrelharp** [comment]
>  I calculate the theoretical rate using a continuous time Markov chain (CTMC), with piecewise constant rates (just as @nspope had suggested) - I assume msprime is doing something similar (I tried looking at the source code but couldn't really decipher it).

This is, indeed, what the msprime code is doing - calculations with the bivariate CTMC.

Hm, let's see. So, `m` is the per-capita, forwards-time, haploid migration rate, right? So, the expected rate at which genomes appear in B that were produced by someone in A is 2 N_A m; and so the chance that a lineage in A passes through such a new migrant genome (and thus migrates) is 2 N_A m / (2 N_B); this is the msprime migration rate. The rate at which a lineage in B encounters another is 1/(2 N_B); so the ratio of migration to coalescence-within-B rates is 2 N_A m.

In your first example, N_A = N_B = 1e4, this ratio is 8 (as you say). Now, if N_A doubles, this will double the msprime migration rate from B to A, half the msprime migration rate from A to B, and half the coalescence rate within A.

I've gotten a bit turned around with your example, thanks to the factors of two and setting coalescence rates to 1. Does this agree with your math, and with what the software produces?

**Comment by trevorcousins** [comment]
> So, m is the per-capita, forwards-time, haploid migration rate, right?
In the post you were replying to, no; the m I was using was the m as used by msprime, which I understand as the backwards-in-time rate, or in other words “the probability that a lineage in some population had a parent in a different population”. Sorry for not making that clear. 

I follow your reasoning about the ratio of migrating/coalescing, but in my computations I can punch in separate rates for each and let the CTMC work it's magic. Let me describe this more fully using my previous examples. Let m_BIT be the backwards in time rate (as I said, which i believe is how msprime uses it). CTMC has 4 states, AA (two lineages in A), BB (two lineages in B), AB (one lineage in A, the other in B) and C (coalesced state). Let  N_A = N_B = 1e+4 and m_BIT = 4e-4, then the rate of leaving A (i.e. the expected number of lineages currently in A who had a parent in B the previous generation) is M_AB_BIT = 2 N_A m_BIT = 8 and similarly M_BA_BIT = 8. The rate matrix for this is then 

AA->{AA,BB,AB,C} = {., 0, 2 *M_AB_BIT,1}
BB->{AA,BB,AB,C}={0,.,2*M_BA_BIT,1}
AB->{M_AB_BIT,M_BA_BIT,.,0}
C->{0,0,0,0}

which equals:
AA->{AA,BB,AB,C} = {., 0, 16,1}
BB->{AA,BB,AB,C}={0,.,16,1}
AB->{8,8,.,0}
C->{0,0,0,0}

where . is the negative sum of other row elements and AA->AB and BB-> AB have a factor of two in front of M_{AB,BA}_BIT because there are two lineages, each of which migrates independently. This fits msprime’s coalescence rates in the top plot of my original post. 

Now let  N_A = 2e+4, N_B = 1e+4 and m_BIT = 4e-4, then the rate of leaving A is M_AB_BIT = 2 N_A m_BIT = 16 and M_BA_BIT = 8. I would have thought the rate matrix is then 
AA->{AA,BB,AB,C} = {., 0, 32,0.5}
BB->{AA,BB,AB,C}={0,.,16,1}
AB->{16,8,.,0}
C->{0,0,0,0}

But this does not fit msprime’s rates (middle plot), instead what fits it is the following matrix:
AA->{AA,BB,AB,C} = {., 0, 16,0.5}
BB->{AA,BB,AB,C}={0,.,16,1}
AB->{8,8,.,0}
C->{0,0,0,0}
Which generates the final plot. 

This leads me to my initial question: why does increasing the population size of A not increase the expected number of lineages who (BIT) have parents in B? Or equivalently FIT, why does increasing the population size of A not increase the expected number of lineages who migrate to B?

I still suspect I am missing something obvious. Any thoughts you have are highly appreciated! Best wishes, Trevor.

**Comment by petrelharp** [comment]
> Let m_BIT be the backwards in time rate (as I said, which i believe is how msprime uses it). CTMC has 4 states, AA (two lineages in A), BB (two lineages in B), AB (one lineage in A, the other in B) and C (coalesced state). Let N_A = N_B = 1e+4 and m_BIT = 4e-4, then the rate of leaving A (i.e. the expected number of lineages currently in A who had a parent in B the previous generation) is M_AB_BIT = 2 N_A m_BIT = 8 and similarly M_BA_BIT = 8. The rate matrix for this is then
> 
> ```
>     AA  BB  AB  C   
>                  
>  AA  .   0   16  1
>                  
>  BB  0   .   16  1
>                  
>  AB  8   8   .   0
>                  
>  C   0   0   0   0
> ```
> where . is the negative sum of other row elements and AA->AB and BB-> AB have a factor of two in front of M_{AB,BA}_BIT because there are two lineages, each of which migrates independently. This fits msprime’s coalescence rates in the top plot of my original post.

I agree, with one small caveat: the "rate of leaving A" is the expected number of lineages currently in A with a parent in B *divided by the haploid population size of A*; so, this is the rate matrix you get
after rescaling time by 2 N_A = 2e4.

> Now let N_A = 2e+4, N_B = 1e+4 and m_BIT = 4e-4, then the rate of leaving A is M_AB_BIT = 2 N_A m_BIT = 16 and M_BA_BIT = 8. I would have thought the rate matrix is then 
> ```
>  AA  BB  AB  C   
>                  
>  AA  .   0   32  0.5
>                  
>  BB  0   .   16  1
>                  
>  AB  16  8   .   0
>                  
>  C   0   0   0   0
> ```
> 
> But this does not fit msprime’s rates (middle plot), instead what fits it is the following matrix: 
> ```
>  AA  BB  AB  C   
>                  
>  AA  .   0   16  0.5
>                  
>  BB  0   .   16  1
>                  
>  AB  8   8   .   0
>                  
>  C   0   0   0   0
> ```

So, I think that the second matrix is correct (happily agreeing with
msprime). This is because the backwards-in-time migration rates have
not changed: m_BIT is still declared to be 4e-4, and you're still just
scaling time by 2e4 (as evidenced by the rates in the "coalescence"
column), so there's nothing to make the AA->AB and BB->AB rates
different.  The reason this was confusing was because if you want
M_AB_BIT to be 2 N_A m_BIT then you've got to rescale *all* the rates
by 2 N_A = 4e4 (in which case you'd get the msprime matrix times two).

> This leads me to my initial question: why does increasing the population size of A not increase the expected number of lineages who (BIT) have parents in B? Or equivalently FIT, why does increasing the population size of A not increase the expected number of lineages who migrate to B?

I think the answer is "because we said it didn't" - this
parameteriziation controls population sizes and
backwards-migration-rates-of-lineages completely separately (as
opposed to the forwards-time parameterization, where changing N_A with
forwards-time migration rate fixed would affect the backwards-time
migration rate).

Incidentally, this sort of mix up is one reason I prefer not to work
with the "coalescent scaling" - i.e., keep everything in real units
and not multiply time by 2N.

**Comment by petrelharp** [comment]
This stuff is confusing!
