### ISSUE TITLE
Variable recombination maps e.g. per population

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime#2017]
At the end of the chat with @davidrasm yesterday he brought up an interesting suggestion which was to be able to change the recombination map as well as the demography during a simulation.

It should be possible to hack this is we want to change the recombination map over time by stopping a simulation, changing the map, then restarting from the roots of the previous simulation. But I think it would require msprime changes to allow different populations to have different maps, which was one idea that @davidrasm put forward.

Even more difficult (and maybe logically meaningless for a backwards simulator?), but also nice would be to change the map on a lineage-specific basis. I dan't really know how to do this, or even quite what it means.

Pinging @benjeffery as he was in on the conversation too

**Comment by grahamgower** [comment]
Conceptually, its not hard to imagine having two distinct lineages with two distinct recombination maps, and also permitting those maps to change over time (using the approach you suggest). But what happens when those lineages exchange migrants?

**Comment by hyanwong** [comment]
If it's in populations, then the migrant takes the map of the population it is in. If it is for a "lineage", then I assume we mean a lineage at a particular point in the genome, or something? I haven't thought is through properly, TBH.

**Comment by jeromekelleher** [comment]
I think there's an existing issue discussing this, good to link these together if we could.

**Comment by hyanwong** [comment]
Ah, I didn't realise, sorry. I think this is https://github.com/tskit-dev/msprime/issues/1095. Is ti worth closing this issue ands moving the conversation there?

**Comment by hyanwong** [comment]
Closing this one.
