### ISSUE TITLE
Docs don't specify the units in which recombination rate is measured

### ISSUE THREAD

**Issue by alanrogers** [tskit-dev/msprime#2026]
In the old (0.x) msprime, my understanding was that the recombination_rate parameter gave the probability of recombination between sites that were 1 unit of distance apart, in the units used to specify sequence_length. This was different from Hudson's ms, in which recombination rate describes the probability of recombination between sites at either end of the sequence.

The new docs don't specify which convention is now being used.

Edit: [Elsewhere in the docs](https://tskit.dev/msprime/docs/stable/ancestry.html#sec-ancestry-discrete-genome) there is a discussion that does relate recombination_rate to sequence_length. However, I also find that discussion confusing. It says that 1-exp(-r) is the expected number of recombinations per unit time and per unit map length. Do you mean the number of cross-over events? If so, this should be rewritten in terms of Haldane's mapping formula, because the recombination rate is the probability that the number of crossovers is odd. If recombinations really are a thing you can count, wouldn't 1-exp(-r) be the probability of at least 1 event rather than the expected number of events?

**Comment by molpopgen** [comment]
Related to #2025. 

Yes, the units are missing.

**Comment by molpopgen** [comment]
It's the expected number of actual events rather than hypothetical observable events (e.g., odd numbers between region ends).

**Comment by alanrogers** [comment]
Sounds like the number of crossovers. I don't see how 1-exp(-r) can be the mean. For very large r, you'd expect a large number of crossover events. But this formula goes to 1 as r goes to infty.

**Comment by molpopgen** [comment]
Yes, I think the discussion is confusing as well.  (See the other issue.) I'm not sure who wrote that section, but we can figure them out and ping them to help clear up the confusion.

**Comment by alanrogers** [comment]
Here's how I would reason it. Let r represent the probability of a crossover between 2 adjacent nucleotides in 1 generation. The number of crossovers in t generations is Poisson(r*t). In a sequence with n nucleotide sites, there are n-1 adjacent pairs, for each of which the number of crossovers is Poisson(r*t). The total number of crossovers across the sequence is the sum of these Poisson r.v.s, which is Poisson(r*t*(n-1)), which has mean r*t*(n-1).

**Comment by molpopgen** [comment]
> 

Yes, I believe this is what that `Note` section should say.

**Comment by petrelharp** [comment]
Right: the units are crossovers per unit length per unit time.

**Comment by jeromekelleher** [comment]
:point_up:

**Comment by alanrogers** [comment]
So what is 1-exp(-r)? I don't see how it can be the mean number of crossovers per unit time between sites that are 1 unit of map distance apart. Is it possible that you mean that (1-exp(2r))/2 is the probability (per generation) of recombination between two sites that are 1 unit of map distance apart? This is Haldane's mapping function, which goes to 1/2 as r goes to infinity.

**Comment by alanrogers** [comment]
Recombination rate should not be linear in the length of the chromosome. That was one of the early discoveries in the history of genetics. I suspect the correct expression is r(d) = (1 - exp(-2cd))/2, where r(d) is the recombination rate between sites that are d base pairs apart, and c is the crossover rate between adjacent base pairs. I'm sure that the msprime code is correct, because it agrees with other simulators and with theoretical expectations. But I'm suspicious of this bit of the documentation.

**Comment by molpopgen** [comment]
> Recombination rate should not be a linear function of physical distance between loci. That was one of the early discoveries in the history of genetics. I suspect the correct expression is r(d) = (1 - exp(-2cd))/2, where r(d) is the recombination rate between sites that are d base pairs apart, and c is the crossover rate between adjacent base pairs. I'm sure that the msprime code is correct, because it agrees with other simulators and with theoretical expectations. But I'm suspicious of this bit of the documentation.

I addressed this [here](https://github.com/tskit-dev/msprime/issues/2026#issuecomment-1086964034).

**Comment by petrelharp** [comment]
Ok, so after reminding myself how the code works (see e.g. [here](https://github.com/tskit-dev/msprime/blob/main/lib/msprime.c#L2409))... what happens is that recombinations happen, in continuous time, as a Poisson process in time with rate equal to the recombination rate. If the genome is discrete, then this is just saying that each 'link' between adjacent positions has recombinations hitting it at rate equal to the recombination rate. So, I don't think that note about `1 - exp(-r)` is correct for the Hudson model, although I think it *does* apply [to the DTWF](https://github.com/tskit-dev/msprime/blob/main/lib/msprime.c#L2106). @apragsdale - you wrote that note, do you remember what it applies to? (the "note" is the one [here](https://github.com/tskit-dev/msprime/issues/2026#issuecomment-1090255187))

**Comment by apragsdale** [comment]
To be honest, I have no clue what that note is getting at. That note existed before I added the Multiple Chromosomes docs, and the diff just shows that I moved the note "out of the way".

> So, I don't think that note about `1 - exp(-r)` is correct for the Hudson model, although I think it _does_ apply [to the DTWF](https://github.com/tskit-dev/msprime/blob/main/lib/msprime.c#L2106).

I'm not sure how the inner workings of DTWF works when drawing recombinations. Does DTWF apply a crossover between adjacent base pairs in a given generation if a drawn poisson rv is nonzero (and not just odd)? That would make the `1-exp(-r)` make sense to me..

**Comment by petrelharp** [comment]
Ah, I see, thanks. I think we should definitely remove that note from that position in the documentation, but maybe add it somewhere referring to the DTWF. I think we need @jeromekelleher's confirmation on this, though.

**Comment by alanrogers** [comment]
I'm trying to follow along in the code. Does "DTWF" stand for "Discrete-Time Wright-Fisher"?

If recombination events happen as a Poisson process in time, is 1 - exp(-r) the probability of at least one event in a unit of time?

**Comment by jeromekelleher** [comment]
DTWF does stand for [Discrete Time WF](https://tskit.dev/msprime/docs/latest/api.html#msprime.DiscreteTimeWrightFisher)

I don't remember when that note got added, and it's been moved around so much that it's hard to dig out the git history. How about we just remove it, if it's causing confusion? (I'm pretty fuzzy on what it means also)

**Comment by alanrogers** [comment]
Discrete-time Wright-Fisher?

**Comment by petrelharp** [comment]
> Discrete-time Wright-Fisher?

Yes.
