### ISSUE TITLE
generator output with `num_replicates > 1` confuses `sim_mutations`

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/msprime#2030]
Over in #2029 someone tried to translate over their previous workflow, applying `sim_mutations` to the output of `sim_ancestry`, obtaining "`AttributeError: 'generator' object has no attribute 'tables'`".

I guess that `sim_mutations( )` applied to a tree sequence generator could return a generator of tree sequences (mutated ones). This seems a bit tricky, and maybe not worth the bother - but then is `num_replicates` argument still useful?

**Comment by benjeffery** [comment]
Rather than change the API or get in a tangle of polymorphic returns I think detecting an (not ts duck type and is iterable) in sim_mutations and giving a friendly error might be the easiest way to round off this rough edge?

**Comment by jeromekelleher** [comment]
I've actually proposed this already in #1786, and I think it would be a useability win. Just not got around to implementing it.

Closing this as a dupe.
