### ISSUE TITLE
Binary wheels failing

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#2041]
Since https://github.com/tskit-dev/msprime/runs/6075809632?check_suite_focus=true

Not sure what has changed. Need to fix before 1.2 release.

**Comment by jeromekelleher** [comment]
Looks like it's still a problem and something to do with setuptools_scm. Any ideas @benjeffery?

**Comment by benjeffery** [comment]
This looks different to the issue we had over at `tsinfer` where a dirty repo due to symlink fiddling causes `setuptools_scm` to give a bad version preventing PyPI upload. Not sure what this is at all. Investigating.

**Comment by jeromekelleher** [comment]
Thought it might be something like that. No hurry, 1.2.0 probably won't land for a few weeks yet.

**Comment by jeromekelleher** [comment]
Fixed in recent CI updates.

**Comment by molpopgen** [comment]
@jeromekelleher / @benjeffery  -- is there a PR for the fixes?  I've been banging my head against this same issue in fwdpy11 for a week.  I'm unable to reproduce it locally when using the manylinux docker images, which has made it quite frustrating to track down.

**Comment by molpopgen** [comment]
> It won't recreate locally as you aren't root.

Hmmm -- why would that matter if everything is running in Docker?

Thanks for the tip!

**Comment by benjeffery** [comment]
> Hmmm -- why would that matter if everything is running in Docker?

The user inside the docker container is root - I'm not sure why but it screws up git.

**Comment by molpopgen** [comment]
> > Hmmm -- why would that matter if everything is running in Docker?
> 
> The user inside the docker container is root - I'm not sure why but it screws up git.

Yes, that is true when I'm running my pipeline locally -- I am using a Dockerfile that doesn't specify another user.  Hence the confusion/frustration tracking this down.
