### ISSUE TITLE
Add pyodide package

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/msprime#2053]
To enable usage in-browser.

**Comment by benjeffery** [comment]
https://github.com/pyodide/pyodide/pull/2548

**Comment by grahamgower** [comment]
I'm curious, do you have use cases in mind for this?

**Comment by jeromekelleher** [comment]
Education mainly. Ultimately we hope to run msprime/tskit workshops directly from the browser, without any need for JupyterHub etc. Performance is totally good enough for this.

**Comment by benjeffery** [comment]
> I'm curious, do you have use cases in mind for this?

This lets any javascript browser app use msprime as a library, so for example you could have a web app where you had a box that had a `demes` model in, and as you edit the model a load of plots/analysis update in real-time. Would give people a great way to get a handle on how the demographic model influences different metrics.

**Comment by jeromekelleher** [comment]
That should already be possible (although loading up a tree sequence from a URL is a bit of a faff and we need a nice recipe for it).

**Comment by molpopgen** [comment]
> That should already be possible (although loading up a tree sequence from a URL is a bit of a faff and we need a nice recipe for it).

Yeah, I've tried and given up.  But my JS skills are weak.

**Comment by benjeffery** [comment]
Merged at pyodide.

**Comment by molpopgen** [comment]
Exciting!

**Comment by jeromekelleher** [comment]
That's pretty nuts - msprime in the browser is probably faster than any other simulator for most things then.

**Comment by grahamgower** [comment]
How's the memory use compare?

**Comment by benjeffery** [comment]
Browser (memory footprint of the tabin chrome dev tools) - after `import msprime`: 269M, after simulation: 1,667M
Native - after `import msprime`: 28M, after simulation: 1,000M.
