### ISSUE TITLE
Rework build to use the `build` module.

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/msprime#2055]
Similarly to tskit, this would allow us to remove the numpy import and other hacks in `setup.py`.
Once this is done the numpy install step can be removed in the pyodide `meta.yaml`.

**Comment by benjeffery** [comment]
Turns out I misunderstood the requirements and the pyodide change isn't needed. However this is still worth doing.

**Comment by benjeffery** [comment]
This is done

**Comment by jeromekelleher** [comment]
Can we close then?
