### ISSUE TITLE
Problem with manylinux wheels

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#2057]
Looks like we've only uploaded one manylinux wheel to pypi for 1.2 (
msprime-1.2.0-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl)

Any idea what's happened @benjeffery?

https://pypi.org/project/msprime/1.2.0/#files

**Comment by benjeffery** [comment]
Fixed in #2058. Was a silly mistake in the wheel script, that went unnoticed as the test was installing from PyPI if the wheel had failed to build.

**Comment by benjeffery** [comment]
I've manually pushed the wheels for 1.2.0 to PyPI.
