### ISSUE TITLE
Review and document default params for microsat models

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#2074]
In #2071 we added default parameters for all the new microsat models. This is convenient, but may be a bad idea as users might assume that this is *the* microsat model.

What was the reasoning for the various defaults that you chose @andrewkern?

**Comment by andrewkern** [comment]
> What was the reasoning for the various defaults that you chose @andrewkern?

hopefully the final doc strings that got merged lay this out sufficiently?

**Comment by jeromekelleher** [comment]
There's a few changes I'd like to make, where we're hard-coding values into the signature. I'll make a quick PR with the updates now.
