### ISSUE TITLE
More details on defaults for TPM

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#2075]
We set p and m to some values estimated by Sainudiin et al, but it's not obvious to me where these values come from. Need more detail on this.

**Comment by andrewkern** [comment]
We could say something like:

Sainudiin et al (2004) estimated model parameters using 644 dinucleotide repeat loci identified as orthologous in human and chimpanzee genomes using maximum likelihood. TPM parameter estimates of `p` and `m` are taken from those MLEs.

is that what you are looking for @jeromekelleher?

**Comment by jeromekelleher** [comment]
Just a reference to which Table they come from would be enough. I was having trouble tracking the figures down quickly - we just want to make it easy for users to trace back to exactly what bit of the paper we're pulling these numbers from.

More fundamentally though - should we be putting in defaults for humans here? Do people use these models for nonhumans too? We don't put in defaults for particular organisms anywhere else in the API, so unless this model is *only* for humans, I wonder if we should just leave them unparametrised and instead give these values in some examples?

**Comment by andrewkern** [comment]
closed with #2080
