### ISSUE TITLE
Justify default values for lo and hi

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#2078]
Not obvious where these came from. In particular, why 2 and not 1 (or zero) for lo?

I've put a placeholder into the MicrosatMutationModel class.

**Comment by jeromekelleher** [comment]
Sound reasonable to me - we just need to document these choices. People will assume that the defaults are the Right Choice.

**Comment by andrewkern** [comment]
going to close this out now that #2080

**Comment by jeromekelleher** [comment]
See #2086 for discussion on changing lo to 1.
