### ISSUE TITLE
Update docs on simulating multiple chromosomes

### ISSUE THREAD

**Issue by apragsdale** [tskit-dev/msprime#2082]
There was some discussion (#2081) about simulating multiple chromosomes when you have a known fixed pedigree. The [simulating multiple chromosomes](https://tskit.dev/msprime/docs/stable/ancestry.html#multiple-chromosomes) section of the docs were written before the fixed pedigree model was released, and the discussion in #2081 I think reveals some common confusions that users might have about the best approach for simulating whole genomes. A second issue was that it also wasn't clear how to handle NaN flanking regions in recombination map when you attempt to stitch chromosomes together.

Proposed doc updates

1. Split the "Example" in the multiple chromosomes section into two examples: a new section on simulating with a pedigree, and then the existing example of simulating when the pedigree is unavailable
2. In the existing example that stitches chromosome maps together, discuss how to handle flanking regions of NaN, and a caution to discard those regions afterward. I think the suggested approach should be to set those regions to 0 rate, and then use `delete_intervals()` to remove trees in those regions.

I'd be happy to open a PR with these proposed updates.

**Comment by jeromekelleher** [comment]
That would be fabulous, thanks @apragsdale!
