### ISSUE TITLE
Issue importing msprime into Python

### ISSUE THREAD

**Issue by asadrh8** [tskit-dev/msprime#2091]
Hello!

I've installed msprime using pip, but am met with the following error when I attempt to import it into JupyterLab.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/msprime/__init__.py", line 28, in <module>
    from msprime._msprime import (
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/msprime/_msprime.cpython-310-darwin.so, 2): Library not loaded: @rpath/libgsl.25.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/msprime/_msprime.cpython-310-darwin.so
  Reason: image not found

I've also attempted installing it with conda, activating a conda environment, and am met with the same error. I'm really unsure of what's going on haha.

Thank you!
Asad

**Comment by jeromekelleher** [comment]
Hi @asadrh8 :wave:

It's odd you should get the same error when using conda. Can you try installing msprime into a fresh conda environment (see [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands)) and let us know how you get on?

**Comment by asadrh8** [comment]
I ended up with the same error. I'm really unsure of what's going on given that the installation always run smoothly. Is it perhaps a python compatibility issue? I'm running python 3.10.4.

**Comment by asadrh8** [comment]
Just to update, I reverted to python 3.9.12 and am no longer experiencing the error. Everything is working fine!

**Comment by molpopgen** [comment]
This is macOS?  It'd be nice to confirm this.  What macOS version are you on?  I can try to replicate next week on a machine running Monterey.

**Comment by asadrh8** [comment]
I'm on macOS Mojave, 10.14.6!

**Comment by molpopgen** [comment]
Thanks.  I just updated a machine to that.  It looks to me like you installed stuff into system libraries?  I'm basing that on the paths.  That may be part of the issues.

**Comment by jeromekelleher** [comment]
@asadrh8 do you still have this problem? Can you check if installing msprime into its own environment using conda solves the problem (see #2093 for help on doing this)?

**Comment by molpopgen** [comment]
I didn't get around to firing up my Mac yet.  It isn't my daily driver and I am easily distracted!

**Comment by jeromekelleher** [comment]
I'm going to close this as there's no updates after a few months - we can reopen if it's still a live issue.
