### ISSUE TITLE
Unable to run msprime after installling on Windows via conda; get error with msprime._msprime not being found.

### ISSUE THREAD

**Issue by HadiKhan-dev** [tskit-dev/msprime#2093]
I recently tried to install msprime on Windows via conda with the command

`conda install msprime -c conda-forge`

and the installation itself worked fine. However when I try to run `msp --version` in CMD (or Powershell) I get the error:

`
Traceback (most recent call last):

  File "C:\Users\HadiKhan\anaconda3\Scripts\msp-script.py", line 6, in <module>
    from msprime.cli import msp_main

  File "C:\Users\HadiKhan\anaconda3\lib\site-packages\msprime\__init__.py", line 28, in <module>
    from msprime._msprime import (

ImportError: DLL load failed while importing _msprime: The specified module could not be found.
`

I'm getting a similar issue when I `import msprime` in Python, giving the error:

`
  File ~\anaconda3\Lib\site-packages\msprime\__init__.py:28 in <module>
    from msprime._msprime import (

  File ~\anaconda3\lib\site-packages\msprime\__init__.py:28 in <module>
    from msprime._msprime import (

ImportError: DLL load failed while importing _msprime: The specified module could not be found.
`

Please let me know how to fix as I'm not able to use msprime at all at the moment.

**Comment by jeromekelleher** [comment]
Thanks very much for the report @HadiKhan-dev, this is very helpful. Would you mind providing a little more information please?

```
conda info -a
```

If possible, could you install msprime into it's own environment please, and paste in the output of the installation here?

```
conda create -n msprime-test msprime
```

Possibly related to #2091.

**Comment by HadiKhan-dev** [comment]
Here is the output of the `conda info -a` command:

`
(base) PS C:\Users\HadiKhan> conda info -a

     active environment : base
    active env location : C:\Users\HadiKhan\anaconda3
            shell level : 1
       user config file : C:\Users\HadiKhan\.condarc
 populated config files :
          conda version : 4.13.0
    conda-build version : 3.21.8
         python version : 3.9.12.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\HadiKhan\anaconda3  (writable)
      conda av data dir : C:\Users\HadiKhan\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\HadiKhan\anaconda3\pkgs
                          C:\Users\HadiKhan\.conda\pkgs
                          C:\Users\HadiKhan\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\HadiKhan\anaconda3\envs
                          C:\Users\HadiKhan\.conda\envs
                          C:\Users\HadiKhan\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.13.0 requests/2.27.1 CPython/3.9.12 Windows/10 Windows/10.0.22000
          administrator : False
             netrc file : None
           offline mode : False

# conda environments:
#
base                  *  C:\Users\HadiKhan\anaconda3

sys.version: 3.9.12 (main, Apr  4 2022, 05:22:27) [MS...
sys.prefix: C:\Users\HadiKhan\anaconda3
sys.executable: C:\Users\HadiKhan\anaconda3\python.exe
conda location: C:\Users\HadiKhan\anaconda3\lib\site-packages\conda
conda-build: C:\Users\HadiKhan\anaconda3\Scripts\conda-build.exe
conda-content-trust: C:\Users\HadiKhan\anaconda3\Scripts\conda-content-trust.exe
conda-convert: C:\Users\HadiKhan\anaconda3\Scripts\conda-convert.exe
conda-debug: C:\Users\HadiKhan\anaconda3\Scripts\conda-debug.exe
conda-develop: C:\Users\HadiKhan\anaconda3\Scripts\conda-develop.exe
conda-env: C:\Users\HadiKhan\anaconda3\Scripts\conda-env.exe
conda-index: C:\Users\HadiKhan\anaconda3\Scripts\conda-index.exe
conda-inspect: C:\Users\HadiKhan\anaconda3\Scripts\conda-inspect.exe
conda-metapackage: C:\Users\HadiKhan\anaconda3\Scripts\conda-metapackage.exe
conda-pack: C:\Users\HadiKhan\anaconda3\Scripts\conda-pack.exe
conda-render: C:\Users\HadiKhan\anaconda3\Scripts\conda-render.exe
conda-repo: C:\Users\HadiKhan\anaconda3\Scripts\conda-repo.exe
conda-server: C:\Users\HadiKhan\anaconda3\Scripts\conda-server.exe
conda-skeleton: C:\Users\HadiKhan\anaconda3\Scripts\conda-skeleton.exe
conda-token: C:\Users\HadiKhan\anaconda3\Scripts\conda-token.exe
conda-verify: C:\Users\HadiKhan\anaconda3\Scripts\conda-verify.exe
user site dirs:

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: base
CONDA_EXE: C:\Users\HadiKhan\anaconda3\Scripts\conda.exe
CONDA_PREFIX: C:\Users\HadiKhan\anaconda3
CONDA_PROMPT_MODIFIER: (base)
CONDA_PYTHON_EXE: C:\Users\HadiKhan\anaconda3\python.exe
CONDA_ROOT: C:\Users\HadiKhan\anaconda3
CONDA_SHLVL: 1
CURL_CA_BUNDLE: <not set>
HOMEPATH: \Users\HadiKhan
PATH: C:\Users\HadiKhan\anaconda3;C:\Users\HadiKhan\anaconda3\Library\mingw-w64\bin;C:\Users\HadiKhan\anaconda3\Library\usr\bin;C:\Users\HadiKhan\anaconda3\Library\bin;C:\Users\HadiKhan\anaconda3\Scripts;C:\Users\HadiKhan\anaconda3\bin;C:\Users\HadiKhan\anaconda3;C:\Users\HadiKhan\anaconda3\Library\mingw-w64\bin;C:\Users\HadiKhan\anaconda3\Library\usr\bin;C:\Users\HadiKhan\anaconda3\Library\bin;C:\Users\HadiKhan\anaconda3\Scripts;C:\Users\HadiKhan\anaconda3\bin;C:\Users\HadiKhan\anaconda3\condabin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\HashiCorp\Vagrant\bin;C:\Program Files\PuTTY;C:\Program Files\dotnet;C:\Program Files\PowerShell\7;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\HadiKhan\AppData\Local\Microsoft\WindowsApps;.
PSMODULEPATH: C:\Users\HadiKhan\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>
VBOX_MSI_INSTALL_PATH: C:\Program Files\Oracle\VirtualBox\

`


Interestingly msprime did work when I created it's own environment:

`

(base) PS C:\Users\HadiKhan> conda create -n msprime-test msprime -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\HadiKhan\anaconda3\envs\msprime-test

  added / updated specs:
    - msprime


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    attrs-21.4.0               |     pyhd8ed1ab_0          49 KB  conda-forge
    bzip2-1.0.8                |       h8ffe710_4         149 KB  conda-forge
    ca-certificates-2022.6.15  |       h5b45459_0         188 KB  conda-forge
    gsl-2.7                    |       hdfb1a43_0         1.7 MB  conda-forge
    importlib-metadata-4.11.4  |  py310h5588dad_0          34 KB  conda-forge
    importlib_resources-5.9.0  |     pyhd8ed1ab_0          28 KB  conda-forge
    intel-openmp-2022.1.0      |    h57928b3_3787         3.7 MB  conda-forge
    jsonschema-4.7.2           |     pyhd8ed1ab_0          63 KB  conda-forge
    libblas-3.9.0              |     15_win64_mkl         5.6 MB  conda-forge
    libcblas-3.9.0             |     15_win64_mkl         5.6 MB  conda-forge
    libffi-3.4.2               |       h8ffe710_5          41 KB  conda-forge
    liblapack-3.9.0            |     15_win64_mkl         5.6 MB  conda-forge
    libzlib-1.2.12             |       h8ffe710_2          68 KB  conda-forge
    mkl-2022.1.0               |     h6a75c08_874       182.7 MB  conda-forge
    msprime-1.2.0              |  py310h72e48cd_0         350 KB  conda-forge
    numpy-1.23.1               |  py310h8a5b91a_0         6.3 MB  conda-forge
    openssl-3.0.5              |       h8ffe710_0         7.6 MB  conda-forge
    pip-22.2                   |     pyhd8ed1ab_0         1.5 MB  conda-forge
    pyparsing-3.0.9            |     pyhd8ed1ab_0          79 KB  conda-forge
    pyrsistent-0.18.1          |  py310he2412df_1          86 KB  conda-forge
    python-3.10.5              |hcf16a7b_0_cpython        16.2 MB  conda-forge
    python_abi-3.10            |          2_cp310           4 KB  conda-forge
    ruamel.yaml-0.17.21        |  py310he2412df_1         171 KB  conda-forge
    ruamel.yaml.clib-0.2.6     |  py310he2412df_1         112 KB  conda-forge
    setuptools-63.2.0          |  py310h5588dad_0         1.4 MB  conda-forge
    sqlite-3.39.2              |       h8ffe710_0         1.3 MB  conda-forge
    tbb-2021.5.0               |       h2d74725_1         148 KB  conda-forge
    tk-8.6.12                  |       h8ffe710_0         3.5 MB  conda-forge
    tskit-0.5.1                |  py310h2873277_0         500 KB  conda-forge
    tzdata-2022a               |       h191b570_0         121 KB  conda-forge
    ucrt-10.0.20348.0          |       h57928b3_0         1.2 MB  conda-forge
    vc-14.2                    |       hb210afc_6          13 KB  conda-forge
    vs2015_runtime-14.29.30037 |       h902a5da_6         1.3 MB  conda-forge
    wheel-0.37.1               |     pyhd8ed1ab_0          31 KB  conda-forge
    xz-5.2.5                   |       h62dcd97_1         211 KB  conda-forge
    zipp-3.8.0                 |     pyhd8ed1ab_0          12 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       247.5 MB

The following NEW packages will be INSTALLED:

  attrs              conda-forge/noarch::attrs-21.4.0-pyhd8ed1ab_0
  bzip2              conda-forge/win-64::bzip2-1.0.8-h8ffe710_4
  ca-certificates    conda-forge/win-64::ca-certificates-2022.6.15-h5b45459_0
  demes              conda-forge/noarch::demes-0.2.2-pyhd8ed1ab_0
  gsl                conda-forge/win-64::gsl-2.7-hdfb1a43_0
  importlib-metadata conda-forge/win-64::importlib-metadata-4.11.4-py310h5588dad_0
  importlib_resourc~ conda-forge/noarch::importlib_resources-5.9.0-pyhd8ed1ab_0
  intel-openmp       conda-forge/win-64::intel-openmp-2022.1.0-h57928b3_3787
  jsonschema         conda-forge/noarch::jsonschema-4.7.2-pyhd8ed1ab_0
  libblas            conda-forge/win-64::libblas-3.9.0-15_win64_mkl
  libcblas           conda-forge/win-64::libcblas-3.9.0-15_win64_mkl
  libffi             conda-forge/win-64::libffi-3.4.2-h8ffe710_5
  liblapack          conda-forge/win-64::liblapack-3.9.0-15_win64_mkl
  libzlib            conda-forge/win-64::libzlib-1.2.12-h8ffe710_2
  mkl                conda-forge/win-64::mkl-2022.1.0-h6a75c08_874
  msprime            conda-forge/win-64::msprime-1.2.0-py310h72e48cd_0
  numpy              conda-forge/win-64::numpy-1.23.1-py310h8a5b91a_0
  openssl            conda-forge/win-64::openssl-3.0.5-h8ffe710_0
  pip                conda-forge/noarch::pip-22.2-pyhd8ed1ab_0
  pyparsing          conda-forge/noarch::pyparsing-3.0.9-pyhd8ed1ab_0
  pyrsistent         conda-forge/win-64::pyrsistent-0.18.1-py310he2412df_1
  python             conda-forge/win-64::python-3.10.5-hcf16a7b_0_cpython
  python_abi         conda-forge/win-64::python_abi-3.10-2_cp310
  ruamel.yaml        conda-forge/win-64::ruamel.yaml-0.17.21-py310he2412df_1
  ruamel.yaml.clib   conda-forge/win-64::ruamel.yaml.clib-0.2.6-py310he2412df_1
  setuptools         conda-forge/win-64::setuptools-63.2.0-py310h5588dad_0
  sqlite             conda-forge/win-64::sqlite-3.39.2-h8ffe710_0
  svgwrite           conda-forge/noarch::svgwrite-1.4.3-pyhd8ed1ab_0
  tbb                conda-forge/win-64::tbb-2021.5.0-h2d74725_1
  tk                 conda-forge/win-64::tk-8.6.12-h8ffe710_0
  tskit              conda-forge/win-64::tskit-0.5.1-py310h2873277_0
  tzdata             conda-forge/noarch::tzdata-2022a-h191b570_0
  ucrt               conda-forge/win-64::ucrt-10.0.20348.0-h57928b3_0
  vc                 conda-forge/win-64::vc-14.2-hb210afc_6
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.29.30037-h902a5da_6
  wheel              conda-forge/noarch::wheel-0.37.1-pyhd8ed1ab_0
  xz                 conda-forge/win-64::xz-5.2.5-h62dcd97_1
  zipp               conda-forge/noarch::zipp-3.8.0-pyhd8ed1ab_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
tk-8.6.12            | 3.5 MB    | ############################################################################ | 100%
zipp-3.8.0           | 12 KB     | ############################################################################ | 100%
tskit-0.5.1          | 500 KB    | ############################################################################ | 100%
importlib_resources- | 28 KB     | ############################################################################ | 100%
jsonschema-4.7.2     | 63 KB     | ############################################################################ | 100%
python_abi-3.10      | 4 KB      | ############################################################################ | 100%
numpy-1.23.1         | 6.3 MB    | ############################################################################ | 100%
vc-14.2              | 13 KB     | ############################################################################ | 100%
intel-openmp-2022.1. | 3.7 MB    | ############################################################################ | 100%
python-3.10.5        | 16.2 MB   | ############################################################################ | 100%
ruamel.yaml.clib-0.2 | 112 KB    | ############################################################################ | 100%
ucrt-10.0.20348.0    | 1.2 MB    | ############################################################################ | 100%
sqlite-3.39.2        | 1.3 MB    | ############################################################################ | 100%
tbb-2021.5.0         | 148 KB    | ############################################################################ | 100%
libcblas-3.9.0       | 5.6 MB    | ############################################################################ | 100%
libffi-3.4.2         | 41 KB     | ############################################################################ | 100%
setuptools-63.2.0    | 1.4 MB    | ############################################################################ | 100%
libblas-3.9.0        | 5.6 MB    | ############################################################################ | 100%
xz-5.2.5             | 211 KB    | ############################################################################ | 100%
bzip2-1.0.8          | 149 KB    | ############################################################################ | 100%
importlib-metadata-4 | 34 KB     | ############################################################################ | 100%
tzdata-2022a         | 121 KB    | ############################################################################ | 100%
ca-certificates-2022 | 188 KB    | ############################################################################ | 100%
pyrsistent-0.18.1    | 86 KB     | ############################################################################ | 100%
libzlib-1.2.12       | 68 KB     | ############################################################################ | 100%
ruamel.yaml-0.17.21  | 171 KB    | ############################################################################ | 100%
attrs-21.4.0         | 49 KB     | ############################################################################ | 100%
mkl-2022.1.0         | 182.7 MB  | ############################################################################ | 100%
liblapack-3.9.0      | 5.6 MB    | ############################################################################ | 100%
msprime-1.2.0        | 350 KB    | ############################################################################ | 100%
openssl-3.0.5        | 7.6 MB    | ############################################################################ | 100%
pyparsing-3.0.9      | 79 KB     | ############################################################################ | 100%
pip-22.2             | 1.5 MB    | ############################################################################ | 100%
vs2015_runtime-14.29 | 1.3 MB    | ############################################################################ | 100%
wheel-0.37.1         | 31 KB     | ############################################################################ | 100%
gsl-2.7              | 1.7 MB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate msprime-test
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) PS C:\Users\HadiKhan> conda activate msprime-test

(msprime-test) PS C:\Users\HadiKhan> msp
usage: msp [-h] [-V] {ancestry,mutations,simulate} ...
msp: error: the following arguments are required: subcommand

`

I'm not sure why it's working in its own environment but not in the base environment. msprime was literally the first package I installed after a fresh installation of anaconda from source, from what I understand both the base environment and the new msprime-test environment should have the exact same packages...

**Comment by jeromekelleher** [comment]
That's really helpful, thanks @HadiKhan-dev!

Given msprime works in its own environment I'm inclined to think it's some weird conda problem rather than something specific to msprime's packages. What do you think?

**Comment by grahamgower** [comment]
For posterity, here are things that conda users should be aware of (independent of msprime):
* Never install software into the base environment. The base can be used for installing/upgrading `conda` (and `mamba`), but avoid using it for anything else. Create a new  environment for each separate tool/project. This is what the [conda docs recommend](https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html#managing-environments), although they don't explain why. Mysterious breakages like observed in this thread are why.
* Conda environments are not adequately isolated. User-installed python packages (`pip install --user`) and user-installed R packages take precedence over the packages installed in a conda environment. Sadly, the conda devs have known about this since 2013 and have failed to fix it. https://github.com/conda/conda/issues/448
So, don't use `pip install --user` unless you're willing to debug conda conflicts.
* These days, `pip install` will automatically install in `--user` mode if it doesn't have write permission to the default installation path. This means users can indadvertantly install packages locally that will interfere with conda environments (due to the previous point).

**Comment by HadiKhan-dev** [comment]
Yes, after reading the replies from Jerome and Graham I agree it seems to be a conda issue rather than an msprime one and I'm able to use msprime now via its own environment. Happy to have this issue closed

**Comment by jeromekelleher** [comment]
Sounds good @HadiKhan-dev - I've created a new issue (#2095) to update our documentation accordingly (maybe integrating some of @grahamgower's wisdom above).
