### ISSUE TITLE
Create names for individuals in SampleSet

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime#2105]
Should we provide an easy way to allocate names for the individuals generated in a SampleSet? E.g.

```
samples = [
    msprime.SampleSet(["Ada", "Bob", "Cat"], population="pop_1", ploidy=2, time=0),    
]
```

Or, since I don't think we define a standard "name" field in the individual metadata, like we do for populations, we could take a python dict (or JSON string) for the individual metadata:

```
samples = [
    msprime.SampleSet([{"name":nm} for nm in ["Ada", "Bob", "Cat"]], population="pop_1", ploidy=2, time=0),    
]
```

**Comment by jeromekelleher** [comment]
Metadata is a can of worms and I don't want to get into it unless there's a clear use-case. What's the application?

**Comment by hyanwong** [comment]
Well, I'm doing some simulations, with multiple historical individuals at a set of timepoints. It seems potentially fragile to identify those individuals by node id, as that could change e.g. after inference (especially if we are messing about by inferring without historical individuals, then adding them later, etc). I think of the metadata values in individuals and nodes as a way of keeping track of them even after simplification, inference, etc. Also, some sort of user-generated identifier could be useful when e.g. outputting to VCF. But maybe not worth it unless others want this capability.

When generating a VCF, I assume that the individual names are auto generated, but that leads to relabelling after simplification:

```
ts = msprime.sim_mutations(msprime.sim_ancestry(2, sequence_length=100, random_seed=1), rate=1e-2, random_seed=1)
print(ts.as_vcf())
print(ts.simplify([2,3], filter_sites=False).as_vcf())  # What was labelled as tsk_1 is now labelled as tsk_0
```

That could be avoided if it were possible to add names to the individuals when simulating (and if those were used in the VCF file).

It's not that important to me, however. It just seemed like a useful thing to suggest to people who want to keep track of the exact individuals that they are simulating.

**Comment by jeromekelleher** [comment]
It would be nice to have individual names coming through in the VCF, but it really is a can of worms when you start adding metadata to a table that previously didn't have it so I'd rather not open it up unless other people want it.
