### ISSUE TITLE
Get population from Demography object by name

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime#2106]
I think it might be helpful to be able to get the population definitions from a Demography object by the name of the population. E.g.

```
class Demography:
    def get_populalation(self, name):
        for p in self.populations:
            if p.name == name:
                return p
        return None

demography = msprime.Demography.island_model([1000] * 3, 1e-5)
demography.get_population("pop_1")
```

**Comment by jeromekelleher** [comment]
This is already implemented, isn't it? See [here](https://tskit.dev/msprime/docs/latest/demography.html#demography-objects) for docs.

**Comment by hyanwong** [comment]
Oh, so it is, sorry! Since you can get a list of populations out of a demography object by using `demography.populations()`, I was assume that it followed the `tskit` syntax of `demography.population(0)` rather than `demography[0]`.

I'll close this, but I am wondering whether `demography.population[0]` is a bit more obvious, especially if the demography class ends up containing more complicated objects.

**Comment by jeromekelleher** [comment]
Not a lot of motivation to change this now, but happy to look at a concrete suggestion.
