### ISSUE TITLE
segmentation fault when trying to run msprime.log_arg_likelihood()

### ISSUE THREAD

**Issue by savitakartik** [tskit-dev/msprime#2107]
```
import tskit
import msprime
import random

random.seed(6)
nreps = 20
ne = [10, 1e2, 1e3, 1e4, 3e4, 5e4, 7e4, 1e5]

for i in range(nreps):
        ifile = "slim_msp_rep_" + str(i+1) + ".trees"
        ts = tskit.load(ifile)
        for j in range(len(ne)):
                print(msprime.log_arg_likelihood(ts, recombination_rate = 0, Ne = ne[j]))
```
This code results in a Segmentation fault more often than not. The tree sequences are from a single-locus SLiM model without recombination, followed by recapitation of the deep past with msprime. I use a random seed of 6 with SLiM and msprime. 
I'm not sure how to reproduce the error as the code runs fine for the same tree sequence on occasion.

**Comment by jeromekelleher** [comment]
Thanks for the bug report @savitakartik.

It looks like this will fail for a specific tree sequence file that you have stored - could you narrow it down to one file that definitely does result in a segfault, at least some of the time, please?

The file shouldn't be too big, so hopefully you can just attach it here.

**Comment by JereKoskela** [comment]
This is speculation without seeing the details, but since part of the tree comes from SLiM I'm guessing this will have something to do with simultaneous mergers. I wouldn't be surprised if those could cause the way the likelihood calculation traverses nodes and edges to go haywire. The likelihood is only really valid for tree sequences which are output by the Hudson coalescent with recombination algorithm; for anything else we should expect things to break. Even if the code runs, the output won't be very meaningful.

**Comment by jeromekelleher** [comment]
That's true - still, we shouldn't segfault, so I'd like to get to the bottom of this.

**Comment by savitakartik** [comment]
This one, for example, for Ne=10, 1000, 10000
[slim_msp_rep_7.zip](https://github.com/tskit-dev/msprime/files/9754276/slim_msp_rep_7.zip)

**Comment by jeromekelleher** [comment]
Hmm, I can't reproduce. I've run this code:
```python
import msprime
import tskit
import tqdm

ts = tskit.load("slim_msp_rep_7.trees")
print(ts)

for _ in tqdm.tqdm(range(1000)):
    ll = msprime.log_arg_likelihood(ts, recombination_rate = 0, Ne=1000)
print(ll)
```

Are you running this on the BMRC cluster? What version of msprime/Python etc?

**Comment by savitakartik** [comment]
Sorry, wrong file - could you try this file but without the tqdm module, although I don't know why it would make a difference. I get a segmentation fault with:

```
import msprime
import tskit

ts = tskit.load("slim_rep_7.trees")
print(ts)

for i in range(1000):
        ll = msprime.log_arg_likelihood(ts, recombination_rate = 0, Ne=1000)
        print(i, ll)
```
but when I import tqdm (e.g. your code above), it works fine.

I'm using Python 3.10.5, msprime 1.2.0, tskit 0.5.2 on the BMRC cluster.
[slim_rep_7.zip](https://github.com/tskit-dev/msprime/files/9757050/slim_rep_7.zip)

**Comment by JereKoskela** [comment]
I think it would be cleanest to return an error when the tree isn't binary, since any number we return won't really mean much. Is there an easy, existing way to check that @jeromekelleher?

**Comment by jeromekelleher** [comment]
Something like this in the Python code is probably best:
```python
for tree in ts.trees():
     if np.any(tree.num_children_array > 2):
          raise ValueError(...)
```
Although should probably check for unary nodes etc as well.

**Comment by JereKoskela** [comment]
@jeromekelleher, any idea why `python3 -m pytest` would insist that `Tree` object has no attribute `num_children_array`?

Running `git submodule update --init --recursive`, then `python -m pip install -r requirements/development.txt` and `make` in the project root all complete without errors, and I'm parallel with the latest version of the main msprime repo.

**Comment by benjeffery** [comment]
@JereKoskela what version of tskit are you using? Pip won't upgrade it unless asked and the dev requirements might need a pin.
`python -m pip install --upgrade tskit`

**Comment by JereKoskela** [comment]
Upgrading tskit did the job. I had naively assumed reinstalling requirements would do that. Thanks @benjeffery!

**Comment by benjeffery** [comment]
Sounds like we need a pin. Will raise an issue!

**Comment by GertjanBisschop** [comment]
Small detail. The implemented check will also flag a polytomy when a tree has multiple roots. `tree.num_children_array[-1]` tracks the number of children of the virtual root. Will post a pr with a more informative error message in that particular case.

**Comment by jeromekelleher** [comment]
Did we update the changelong in #2232?

**Comment by GertjanBisschop** [comment]
The changelog update for the bugfix was done in #2227.
