### ISSUE TITLE
update SLiM script for verification.py

### ISSUE THREAD

**Issue by GertjanBisschop** [tskit-dev/msprime#2126]
The current SLiM scripts in `verification.py` throw up a few errors when run with SLiM 4.0 (default installed version is the latest version of SLiM). For example, the concept of time/generations has been modified slightly, `sim.generation` can no longer be called to track time.

The version of SLiM used for statistical tests needs to specified explicitly and the scripts require some minor tweaks if we go with version 4.

**Comment by jeromekelleher** [comment]
There's a [makefile](https://github.com/tskit-dev/msprime/blob/main/data/Makefile) to download and compile SLiM, so perhaps we should just stick a particular version on that download (something < 4) and make sure that the verification.py will always use that?

**Comment by GertjanBisschop** [comment]
Yup. Just for completeness. Had a little look, the actual modifications are minor.
Explicitly add `1 early()` to the event populating the simulation. And replace `sim.generation` with `sim.cycle`.

**Comment by jeromekelleher** [comment]
Great, thanks. I don't mind which direction we go.

**Comment by GertjanBisschop** [comment]
Solved in #2315 .
