### ISSUE TITLE
Documentation for simulating with unary nodes

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#2135]
Once we've thought through the proper API for simulating with extra unary nodes in the output (#2132) we should add a short section in the docs explaining what's going on with examples.

**Comment by GertjanBisschop** [comment]
Also, review the current docstrings both for the `additional_nodes` flag as well as the `coalescing_segments_only` flag.

**Comment by GertjanBisschop** [comment]
Solved in #2185.
