### ISSUE TITLE
Documentation for "transition_matrix" of a mutation model

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime#2140]
When looking at the transition_matrix discussion in the msprime docs that [discuss mutation](https://tskit.dev/msprime/docs/stable/mutations.html#matrix-mutation-models), I think it is reasonable to describe the transition matrix as describing the probabilities that, if a mutation occurs, that mutation will result in a change to each of the states. The rate then describes the probability of mutations occurring over time. Would it be helpful to emphasise that in the docs? I can make a minor wording PR. 

Note that it is (confusingly, I think) different from the P(t) “transition matrix” used e.g. in the[ wikipedia article on substitution models](https://en.wikipedia.org/wiki/Substitution_model#The_mathematics_of_substitution_models) 

> The entry in the ith column and the jth row, Pij(t), is the probability, after time t, that there is a base j at a given position, conditional on there being a base i in that position at time 0

P(t) is also described as a “transition probability matrix” e.g. in [the RevBayes docs](https://revbayes.github.io/tutorials/ctmc/), so I think clearing up the terminological differences here might be helpful. It's presumably too late to call the msprime `transition_matrix` by another name, like the `mutation_matrix`, I presume? Maybe this was discussed when setting up the mutation model API?

**Comment by hyanwong** [comment]
> So, go for it if you think it helps?

I think it does, but you are right that it's a very minor tweak.

>  I don't think we considered the terminology conflict you mention

I think we can just note that there is another meaning, and that should be enough to flag up to people to be a little careful with terminology.

**Comment by petrelharp** [comment]
There's a good discussion of these issues [here](https://tskit.dev/msprime/docs/latest/mutations.html#sec-mutations-matrix-mutation-theory) (including calculation of P(t)), so any clarification might link to that.
