### ISSUE TITLE
SMC with record_full_arg produces discontinuous nodes

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime#2146]
I'm not what "SMC" means for a full ARG, so I'm not sure if this is expected, but I thought it worth noting:

```python
ts = msprime.sim_ancestry(
    4,
    sequence_length=1e4,
    recombination_rate=1e-5,
    record_full_arg=True,
    random_seed=14,
    model="SMC",
)
ts.draw_svg(style=".n19 > .sym {fill:red}")
```

![image](https://user-images.githubusercontent.com/4699014/206855816-46d973df-9b2b-442c-8804-e87ed9e7fd60.png)

**Comment by jeromekelleher** [comment]
Ah, that's because 19 is above the local root. Another reason for making snipping out fully-coalesced bits optional @GertjanBisschop?

I don't think this is particularly unexpected though.

**Comment by hyanwong** [comment]
> Ah, that's because 19 is above the local root in the middle tree. 

Yes indeed. I wonder if this is a reason to continue the full_arg even after local coalescence (until all the trees have met their own local coalescent.

> Another reason for making snipping out fully-coalesced bits optional @GertjanBisschop?
> 
> I don't think this is particularly unexpected though.

No, I guess not, but it's an edge case in the SMC model that people might not have thought about.

**Comment by jeromekelleher** [comment]
I don't think this is an actionable issue, so closing.

**Comment by hyanwong** [comment]
Possibly worth moving to a discussion. Or maybe it's easily searchable enough here. There's som complexity in what SMC actually means, which might be worth a forum for others to add to / search for.
