### ISSUE TITLE
add Software Heritage badges to repo README file

### ISSUE THREAD

**Issue by castedo** [tskit-dev/msprime#2147]
This is a proposal for adding Software Heritage badges to tskit and msprime (and perhaps other) repo README files.

Here's info about Software Heritage badges:
https://www.softwareheritage.org/2020/01/13/the-swh-badges-are-here/

I'm happy to create a PRs if this is considered an improvement.

I think Software Heritage is a great resource for the research community and am happy to write more about why it is so awesome.

**Comment by jeromekelleher** [comment]
Sure, SGTM!

**Comment by jeromekelleher** [comment]
Closed in #2151
