### ISSUE TITLE
Building msprime from source results in ImportError: DLL load failed

### ISSUE THREAD

**Issue by General-Solution** [tskit-dev/msprime#2150]
When I built the latest version of msprime using `pip install .`, it successfully compiles but results in the following error when importing:
```
  File "D:\miniconda3\lib\site-packages\msprime\__init__.py", line 28, in <module>
    from msprime._msprime import (
ImportError: DLL load failed while importing _msprime: The specified module could not be found.
```
This happens in the base conda environment, in a fresh conda environment, and when not using a conda environment. Replacing `_msprime.pyd` with the old version of it allows the module to be imported again but the new functionalities are not there.

**Comment by benjeffery** [comment]
@General-Solution Thanks for the report, is this the same issue as https://github.com/tskit-dev/msprime/discussions/2142 and does anything there help?

**Comment by benjeffery** [comment]
If I read you're issue right you're actually trying to build from source under windows? When you `pip install .` does it build the wheel successfully? You should see output something like this:
```
Building wheels for collected packages: msprime
  Building wheel for msprime (pyproject.toml) ... done
  Created wheel for msprime: filename=msprime-1.2.1.dev23+g6ff59683-cp310-cp310-linux_x86_64.whl size=939077 sha256=c3570f01ce587a910f83f9783b59926b76021bcebaf6e62779dfce2d54a90094
  Stored in directory: /tmp/pip-ephem-wheel-cache-6yhyc6re/wheels/f9/a6/19/a29fa8b956b467979765170614c9beb1eb546dc05e618b0bb4
```
(This is from linux as I don't have easy access to a windows machine).

**Comment by General-Solution** [comment]
Hello,

No, it isn't the same issue as #2142. Msprime imports well when installed with conda, it is only after building with `pip install .` It does build the wheel successfully, it only throws an error when I try to import.

**Comment by benjeffery** [comment]
Is the location of the DLL in `sys.path`?

**Comment by jeromekelleher** [comment]
I'm not sure ``pip install .``  will build a local copy for development here - can you try ``python3 setup.py build_ext --inplace`` please?

(I know this isn't the current best practice, but I'm not sure how it's done properly on windows)

**Comment by General-Solution** [comment]
Using `python setup.py build_ext --inplace` still results in the error. The DLL is in sys.path (it is in `miniconda3\Lib\site-packages\msprime` and I also tried copying it to `miniconda3\Lib\site-packages` and `miniconda3\DLLs`.

**Comment by benjeffery** [comment]
Ok, this is odd! I'm assuming you've checked that the python you're actually running is the one you expect by printing out `sys.path` at the start of the script you're running? Sometimes `pip` ends up using a different python to the one you would expect.

**Comment by General-Solution** [comment]
Do you mean at the start of the script that's trying to import msprime? It seems to be in the right place. If you mean that it was built with the same version of python that's running it, I'm running python 3.9.15, and also tried running it with 3.10.1 and 3.11.0, as well building it with each of these.

**Comment by General-Solution** [comment]
I'm wondering if it could have anything to do with this: I had to copy my `gsl` folder into the `lib` folder for it to find the gsl headers, and I had to copy `tskit_lwt_interface.h` into the `msprime` folder, in order for it to build correctly. Is it possible that this caused problems?

**Comment by General-Solution** [comment]
I appear to have fixed the error by inputting `$env:CONDA_DLL_SEARCH_MODIFICATION_ENABLE=1` into the terminal before running my program. This appears to be related to this issue: conda/conda#10897. However, I don't know how this explains it not working when I tried to run it outside of a conda environment.

**Comment by benjeffery** [comment]
Great! I've never heard of that conda flag so glad you found it. I'll close this issue for now.
