### ISSUE TITLE
Coalescence rate trajectory, more than two lineages

### ISSUE THREAD

**Issue by trevorcousins** [tskit-dev/msprime#2163]
Hi, 

I have a question regarding the coalescence_rate_trajectory functionality. 

If I simulate a history with 2 lineages (ploidy=2, num_samples=1), then get the coalescence rate with `debug.coalescence_rate_trajectory(time_array,{"A": 2})`, then I am satisfied. If I simulate with more samples and do `debug.coalescence_rate_trajectory(time_array,{"A": 3})` then the coalescence rate msprime gives me is exactly the same as `debug.coalescence_rate_trajectory(time_array,{"A": 2})`. This is counter to my expectation. 

Quick bit of theory then an example. In a panmictic population of constant size, sampling 2 lineages, the density function for time till first coalecsence is f=exp(-t), thus the distribution is F=1-exp(-t), then the coalescence rate is CR = f/(1-F) = 1, and effective population size (Ne) is taken as Ne=1/CR = 1. If we sample 3 lineages, then the density function for time till first coalescence is f=3*exp(-3t), so F=1-exp(-3t), so CR = 3, so Ne=1/3. Thus it is suprising to me that `debug.coalescence_rate_trajectory(time_array,{"A": 2}) = debug.coalescence_rate_trajectory(time_array,{"A": 3})` . 

As a minimal example to demonstrate this, I do the following: a) simulate a constant population with N=2e+04, size with ploidy=2,samples=2, b) record the tree sequence, c) discretise time into windows, and round the continuous times from the tree sequence into these windows, d) choose three random pairs of lineages, e) calculate their empirical coalescence (note 1) rate from the discrete tree sequence. I get this, which looks good: 
 
![image](https://user-images.githubusercontent.com/58950900/228601944-65425c80-3f51-432e-a8b8-5ff977bd0fa5.png)
(noise because of short sequence length)

If I do the same as above, but instead choose three arbirtrary lineages and calculate their empirical coalescence rate (note 2), then indeed the CR is 3 times higher so Ne is three times lower:
![image](https://user-images.githubusercontent.com/58950900/228602897-2f393f8b-952b-4df5-90a1-ea970ab843af.png)

Where as from the simulation, choosing 2 or 3 lineages looks the same:
`R2, _ = debug_p2_s2.coalescence_rate_trajectory(T_gens,{"A": 2}) `
`R3, _ = debug_p2_s2.coalescence_rate_trajectory(T_gens,{"A": 3})` 

![image](https://user-images.githubusercontent.com/58950900/228603764-0c9af654-6491-4916-866c-47f80a1836d7.png)

Am i misundertsanding the coalescence_rate_trajectory ? I appreciate that in each case it correctly gets N=2e+04, but if there are e.g. three lineages this is not what I expect. I also wonder if this is a related issue: https://github.com/tskit-dev/msprime/issues/1771

Thanks, 

(note 1) calculate empirical estimate of the density f, essentially with a histogram, from which F then CR then Ne follow simply.
(note 2) Same as above, but look for first coalescence event of three lineages

Trevor

**Comment by nspope** [comment]
Hi Trevor, IIRC `coalescence_rate_trajectory` does not calculate coalescence rates of higher order than pairs (which is not trivial when there is population structure, I think). Instead it calculates the average of pairwise rates, over all possible pairs from the requested sample configuration. For example,
```python
import msprime
import numpy as np

model = msprime.Demography.island_model([20000, 10000], migration_rate=1e-5)
steps = np.linspace(0, 40000, 10) 

AA = model.debug().coalescence_rate_trajectory(steps, lineages={"pop_0" : 2}) 
AB = model.debug().coalescence_rate_trajectory(steps, lineages={"pop_0" : 1, "pop_1": 1}) 
AAB = model.debug().coalescence_rate_trajectory(steps, lineages={"pop_0" : 2, "pop_1": 1}) 

AAB_num = (AA[0]*AA[1] + 2*AB[0]*AB[1])/3
AAB_den = (AA[1] + 2*AB[1])/3
np.allclose(AAB_num/AAB_den, AAB[0]) # True
np.allclose(AAB_den, AAB[1]) # True
```

If you're specifically interested in calculating trio coalescence rates under a multipopulation model, I have the CTMP implemented at github.com/nspope/coaldecoder, would be happy to share an example if that's helpful.

cheers
Nate

**Comment by trevorcousins** [comment]
Hi Nate, 

> coalescence_rate_trajectory does not calculate coalescence rates of higher order than pairs, which is not trivial when there is population structure
I agree. 

I would be interested in your CTMP, thanks! If I remember ProbGen correctly in coaldecoder you are thinking about a N-island model with a migration rate per generation. In addition to N-island models I am thinking about pulse events, which are not as amenable to the CTMP I believe. 

Note, I think as an extension you could get >2 lineages into the `coalescence_rate_trajectory` functionality , by doing what I did (estimate density, from which you calculate CR). Of course though you would need a clever smoothing procedure to remove the noise, which will obviously be prohibitive in short sequences. 

Trevor

**Comment by nspope** [comment]
>  In addition to N-island models I am thinking about pulse events, which are not as amenable to the CTMP I believe.

Maybe I'm not understanding what you mean, but the CTMP framework does handle pulse events -- I omitted those from the talk, to save on time, but it's just another linear operator at the start of each (arbitrarily delineated) epoch. Basically for population mergers, you'd migrate all lineages from A to B and set migration rates into A (backward in time) to 0. Of course, this generalizes to arbitrary admixture proportions. I'll shoot you example over email.

The other thing to keep in mind (when doing empirical calculations) is that you need to weight by span correctly -- in general, the "marginal" process won't have the same expectation as the process with recombination on a finite sequence, because coalescence time and tract length are correlated (so certain parts of the time distribution will be overrepresented, relative to the marginal process). When testing this stuff out, it's often easier just to simulate iid trees.

`TreeSequence.coalescence_time_distribution` implements empirical estimators that should be quite efficient (with large tree sequences) and does the span-weighting thing correctly -- but right now it is limited to trios and pairs (I'll extend to higher-order topologies soon).

**Comment by trevorcousins** [comment]
> the CTMP framework does handle pulse events

Oh, great!

> you need to weight by span correctly

Yes, I think I accounted for that in the plots above. 

I'll look into TreeSequence.coalescence_time_distribution too. Thanks again!

**Comment by petrelharp** [comment]
Would #2164 clear this up?
