### ISSUE TITLE
Problem with Demography Debugger output

### ISSUE THREAD

**Issue by helmutsimon** [tskit-dev/msprime#2204]
In the example output below, end population size is shown as 0. Shouldn't it be approx. 99000?
Example code is given below.

1.2.0
DemographyDebugger
╠════════════════════════════════╗
║ Epoch[0]: [0, inf) generations ║
╠════════════════════════════════╝
╟    Populations (total=1 active=1)
║    ┌────────────────────────────────────────┐
║    │       │      start│   end│growth_rate  │
║    ├────────────────────────────────────────┤
║    │  pop_0│   100000.0│   0.0│ 0.01        │
║    └────────────────────────────────────────┘

`import msprime

print(msprime.__version__)

demography = msprime.Demography()
demography.add_population(initial_size=100000, growth_rate=0.01) 
demographic_hist = demography.debug()
print(demographic_hist)`

**Comment by petrelharp** [comment]
Well, somewhat confusingly, what that shows is that a population that has been growing at rate 0.01 per generation, and today has a size of 100,000, had a size of 0 infinitely many generations in the past. That's correct, I believe.

Notice that the time period ("epoch") is "[0, inf)"; so the "end" refers to the population size at time `inf` (infinity) generations in the past; referring to the [documentation on growth rate](https://tskit.dev/msprime/docs/latest/demography.html#growth-rate), a positive growth rate means that it's been getting bigger, so is smaller further back in time.

I think that should clear this up? Re-open if I'm missing something.

**Comment by helmutsimon** [comment]
Yes, sorry, I completely misunderstood growth_rate
