### ISSUE TITLE
Documentation for replicate_index

### ISSUE THREAD

**Issue by daikitag** [tskit-dev/msprime#2210]
The `replicate_index` input in `sim_ancestry` function https://github.com/tskit-dev/msprime/blob/main/msprime/ancestry.py#L1100 is used repeatedly in various functions, but it is not documented in the docstring or the msprime documentation, and its usage is unclear. It might be better to document it or remove from the input.

**Comment by jeromekelleher** [comment]
I'm not sure why we didn't document that @daikitag, and I'm honestly not sure whether it's really supported or not. We may have decided it wasn't worth the trouble of documenting.

**Comment by daikitag** [comment]
I think it might be better to simply remove the argument from the `sim_ancestry` function, but what do you think about it? Since it is used in various functions, we can put `replicate_index=None` inside the function for now, and fix the other functions in the future release.

**Comment by jeromekelleher** [comment]
I'm reluctant to change things like this without a good motivation. Let's have a look tomorrow to see if we can figure out why it's there.
