### ISSUE TITLE
draw_pedigree documentation

### ISSUE THREAD

**Issue by daikitag** [tskit-dev/msprime#2211]
I find the pedigree documentation to be extremely helpful, but `nx` and `plt` can be confusing here, as they are not imported inside the documentation page https://github.com/tskit-dev/msprime/blob/main/docs/pedigrees.md?plain=1#L329.
Would it be possible for you to add
`from matplotlib import pyplot as plt` and `import networkx as nx` in that code example?

**Comment by jeromekelleher** [comment]
Sure - PR welcome @daikitag!

**Comment by daikitag** [comment]
I opened up a PR in https://github.com/tskit-dev/msprime/pull/2214

**Comment by GertjanBisschop** [comment]
Solved in #2214.
