### ISSUE TITLE
Island model - migration rate definition 

### ISSUE THREAD

**Issue by JaneeshBansal** [tskit-dev/msprime#2223]
Hi,

I have been simulating an island model in msprime and was wondering how the migration rate is defined. I understand that the documentation states "The migration rate between each pair of populations". 

But does this include the chance of migrating back into the same deme? For example, if I have set a migration rate "m" and there are "d" demes is the total migration rate **dm** or **(d-1)m**.

Thank you!
Janeesh

**Comment by petrelharp** [comment]
The total rate is `(d-1) * m` -- "migration" events that leave the lineage in the same deme wouldn't affect genealogies (and are of uncertain interpretation anyhow), so msprime does not simulate them.
