### ISSUE TITLE
1.3.0 Release

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#2226]
We have almost completed the 1.3.0 milestone: https://github.com/tskit-dev/msprime/milestone/22

I think the remaining issues are trivial, so should be able to close of quite quickly.

Creating this issue to track miscellaneous stuff we need to do before tagging:

- [x] Run full statistical test suite
- [x] Check release notes 
- [x] Check new features are fully documented
- [x] Tag and release!
- [x] Make a quick news item for tskit.dev showcasing additional nodes API

Have I missed anything? @GertjanBisschop, I think you can ping @benjeffery once we've closed off all these and he can then kick off the release.

**Comment by GertjanBisschop** [comment]
pinging @benjeffery. ready for release.

**Comment by benjeffery** [comment]
woop woop! Will try to roll it out today.
