### ISSUE TITLE
MacOS ARM wheels packages broken

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#2285]
Getting this error when I run on ARM mac in upstream CI:
```
Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/msprime/__init__.py:28: in <module>
27
    from msprime._msprime import (
28
E   ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/msprime/_msprime.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_gsl_rng_default'
```

It looks like this is basically a duplicate of https://github.com/brentp/cyvcf2/issues/305

We should probably push out a release with the numpy < 2 version out ASAP anyway, so good to get this sorted.

I guess the question is whether we should try to tag the current code, or we do a quick maintenance release from a branch which backports the minimal packaging changes to the last release? I feel like there's a good few changes under the hood after happening, and it's a bit premature to release the smc_k code (even as undocumented). What do you think @GertjanBisschop?

**Comment by GertjanBisschop** [comment]
Agreed @jeromekelleher. It would be good to give the smc_k code some more time for any potential bugs to pop up.

The `binary wheels` action has been broken since #2277. Error due to `delocate` package not being able to deal with different parameter values for different architectures (`arm64`, `x86_64`). Are these two separate issues?

**Comment by jeromekelleher** [comment]
I think it's probably the same issue. Should be an easy fix with new macos-14 runner.

**Comment by jeromekelleher** [comment]
Assuming this is fixed in recent release
