### ISSUE TITLE
Python 3.12 wheels

### ISSUE THREAD

**Issue by fcooper8472** [tskit-dev/msprime#2288]
Would it be straightforward to upload Python 3.12 wheels to PyPI?

Thanks

**Comment by hyanwong** [comment]
I understand that it's there in https://github.com/tskit-dev/msprime/pull/2286, so will be done in the next week or so?

**Comment by benjeffery** [comment]
Yes, just trying to sort out the universal wheels for osx-arm64 and x86.

**Comment by benjeffery** [comment]
Done in #2286
