### ISSUE TITLE
Multiple model simulation is not accurately capturing demography model

### ISSUE THREAD

**Issue by daikitag** [tskit-dev/msprime#2293]
I am now conducting simulation with demographic model in `demes` with discrete WF model and standard coalescent model.
I performed two simulations:

- msprime simulation with multiple model
- Conducting two `msprime.sim_ancestry` simulations, where the first one is using discrete WF with `duration` and the second one is using standard coalescent with `initial_state`

The simulation results are not matching, and this might be due to the fact that the multiple model simulation is not accurately detecting population size in demography model. The demes demography file is attached to this issue as `demography_sample.json`, and the sample codes are attached below:

[demography_sample.json](https://github.com/user-attachments/files/16233679/demography_sample.json)

```python
import demes
import msprime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm

# Function to return the summary statistics of tree sequence data
def ts_stats(ts_iter):
    df = pd.DataFrame()
    for ts in ts_iter:
        pop_sizes = np.unique(ts.nodes_population, return_counts = True)[1]
        t_mrca = np.zeros(ts.num_trees)
        for tree in ts.trees():
            t_mrca[tree.index] = tree.time(tree.roots[0])
        tree_df = pd.DataFrame({
            "Num_Edge": ts.num_edges,
            "Num_Node": ts.num_nodes,
            "Num_Tree": ts.num_trees,
            "T_MRCA_MEAN": np.mean(t_mrca),
        }, index=[0])
        df = pd.concat([df, tree_df], ignore_index = True)

    return df

# Set msprime demography object by using demes
graph = demes.load("demography_sample.json")
demography = msprime.Demography.from_demes(graph)

ancestral_pop_time = 103
seq_length = 1e5
recom_rate = 1e-8
sample = {"YRI": 100, "CEU": 100}
num_rep = 100

model=[
    msprime.DiscreteTimeWrightFisher(duration=ancestral_pop_time),
    msprime.StandardCoalescent(),
]
msprime_dtwf_hudson_ts_iter = msprime.sim_ancestry(
    sample, demography=demography, sequence_length=seq_length,
    recombination_rate=recom_rate, num_replicates=num_rep, model=model
)

msprime_dtwf_hudson_df = ts_stats(msprime_dtwf_hudson_ts_iter)

def msprime_manual_iter(ts_iter, demography):
    for ts in ts_iter:
        ts = msprime.sim_ancestry(initial_state = ts, demography=demography)
        yield ts

msprime_dtwf_ts_iter = msprime.sim_ancestry(
    sample, demography=demography, sequence_length=seq_length,
    recombination_rate=recom_rate, end_time = ancestral_pop_time, num_replicates=num_rep,
    model="dtwf"
)

msprime_manual_iter_df = ts_stats(msprime_manual_iter(msprime_dtwf_ts_iter, demography=demography))

# plotting function to compare two dataframe
def qqplot_stat(df1, df2, df1_name, df2_name):
    fig, axs = plt.subplots(2, 2, figsize=(10,8))
    fig.tight_layout(pad=5.0)
    sm.qqplot_2samples(df1["Num_Edge"], df2["Num_Edge"], line="45", ax=axs[0,0],
                      xlabel=df1_name, ylabel=df2_name)
    axs[0,0].set_title("Number of Edges")
    sm.qqplot_2samples(df1["Num_Node"], df2["Num_Node"], line="45", ax=axs[0,1],
                      xlabel=df1_name, ylabel=df2_name)
    axs[0,1].set_title("Number of Nodes")
    sm.qqplot_2samples(df1["Num_Tree"], df2["Num_Tree"], line="45", ax=axs[1,0],
                      xlabel=df1_name, ylabel=df2_name)
    axs[1,0].set_title("Number of Trees")
    sm.qqplot_2samples(df1["T_MRCA_MEAN"], df2["T_MRCA_MEAN"], line="45", ax=axs[1,1],
                      xlabel=df1_name, ylabel=df2_name)
    axs[1,1].set_title("Mean of T_MRCA")
    plt.show()

qqplot_stat(df1=msprime_dtwf_hudson_df, df2=msprime_manual_iter_df, df1_name="Multiple Model", df2_name="Manual Recapitate")

```

**Comment by daikitag** [comment]
The generated QQ-plots are attached to this comment:
![image](https://github.com/user-attachments/assets/b8d6023f-2b8a-46e9-9326-6470cad7516a)

**Comment by GertjanBisschop** [comment]
Thanks @daikitag. Do I see this correctly that you did not provide a recombination rate to your `msprime_manual_iter()` function?

**Comment by jeromekelleher** [comment]
Ahhhh, well spotted @GertjanBisschop! @daikitag, does this fix the problem?

**Comment by daikitag** [comment]
@GertjanBisschop Thank you for your feedback. I forgot to addd the recombination rate to the `msprime_manual_iter()` function, and after adding it to the function,

```
def msprime_manual_iter(ts_iter, demography):
    for ts in ts_iter:
        ts = msprime.sim_ancestry(initial_state = ts, demography=demography, recombination_rate=1e-8)
        yield ts
```

the recapitated tree sequence had similar TMRCA pattern, but with slightly different number of edges and nodes.

![image](https://github.com/user-attachments/assets/3445498e-1730-4a27-af51-35de326f14a6)

The issue existed in my original problem as well even after adding the recombination rate to `recapitate` function, and I'm wondering if this is a bug or an issue with my codes.

**Comment by GertjanBisschop** [comment]
I think you might have to add in a simplification step after completing `msprime_manual_iter` as the initial state will contain additional nodes representing the state of the simulator at `end_time`.

**Comment by daikitag** [comment]
Thank you very much for your help @GertjanBisschop ! That solved the problem completely.
