### ISSUE TITLE
Simulate more common SNPs

### ISSUE THREAD

**Issue by Chonghao98** [tskit-dev/msprime#2323]
Hi there,

Thanks for your great work. I have a question on how to simulate more common SNPs (e.g. MAF > 5%). I found that the output vcf file has many rare SNPs and few common SNPs, which can be attributed to the neutral mutations. I would like to know whether there are some effective ways to generate more common SNPs. I tried to use pyslim to add selection, but I found that it was difficult to complete the SLiM script for my simulation. Hopefully there is an alternative way.

Best,
Chonghao

**Comment by gregorgorjanc** [comment]
I assume you want an ascertained SNP array with more SNPs at higher frequencies.

@hannesbecher has recently done something similar in our lab.

**Comment by Chonghao98** [comment]
I wonder whether you could provide more details?

**Comment by hannesbecher** [comment]
Sure, we were recently looking into generating data as you would see it in microarray SNP genotyping. Our solution was to run a normal msprime simulation with `sim_ancestry` and `sim_mutations`. In a second step, we selected high-frequency alleles and tried to bias against SNP-dense areas to get an even coverage. We did that by assigning weights to each SNP according to its allele frequency and local SNP density. Then we sampled SNPs at random (with these weights), and we discarded all unsampled SNPs. Does that make sense?

**Comment by Chonghao98** [comment]
Thanks for your resnpose. If I understand correctly, you are filtering out SNPs with lower frequencies, so the proportion of common SNPs increase. My question is about increase the number of common SNPs instead of the proportion. For example, if the output vcf from msprime has 10,000 SNPs for a 10Mb region, with 300 common SNPs and 9700 rare SNPs, I would like to take some ways to increase the number of common SNPs (e.g. increase it to 5000 common SNPs, and I can allow the total number of SNPs increase as well, but the length of the region and mutation rate should remain the same).  I wonder whether there are some ways to achieve this.

**Comment by hannesbecher** [comment]
In a panmictic population, the number of SNPs is a function of the mutation rate and population size (see Watterson's famous 1975 paper). So, you could increase the population size or you could run a simulation with multiple somewhat diverged populations (which would increase the effective population size).

**Comment by Chonghao98** [comment]
I see. Thank you very much.
