### ISSUE TITLE
Update documentation code snippets to use Sphinx doctest

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#240]
Code snippets in the documentation and their results are currently cut and pasted into the source. This is bad for lots of reasons.

We should port the docs to use the Sphinx [doctest extension](http://www.sphinx-doc.org/en/stable/ext/doctest.html), so that all the code snippets are run and tested when the docs are built. I would probably be good to also use the [Spinx IPython directive](http://ipython.org/ipython-doc/rel-0.13.2/development/ipython_directive.html) for things like the tutorial.

Major hat-tip to @molpopgen for suggesting this over in #239!

**Comment by molpopgen** [comment]
Happy to help.  I'm going to start playing with the API a bit more in the coming week or so.

**Comment by molpopgen** [comment]
Curiously, not using Mock results in some formatting getting treated as errors.  But the manual does print out the NodeTable now, which is cool.

Of course, this now required having msprime compiled on RTD.  Perhaps a separate branch is needed to get that working?  On a related note, the _msprime C module is placed into the project root, but must be in msprime/ in order for the docs to build w/o using Mock.

**Comment by jeromekelleher** [comment]
> Of course, this now required having msprime compiled on RTD. Perhaps a separate branch is needed to get that working? On a related note, the _msprime C module is placed into the project root after a "build_ext -i", but it must be in msprime/ in order for the docs to build w/o using Mock.

OK, I'll have a go at getting the RTD stuff working in another PR.

**Comment by jeromekelleher** [comment]
I spent a couple of hours fiddling with using conda on RTD, and unfortunately I don't think it's going to work without a fair amount of effort. There seems to be an upstream bug in the interaction between various parts of sphinx and the sphinx-argparse module I'm using to document the CLIs. When running through conda, I get:
```
Running Sphinx v1.6.3
making output directory...
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/msprime/conda/conda-rtd/lib/python2.7/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/msprime/conda/conda-rtd/lib/python2.7/site-packages/sphinx/application.py", line 196, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/msprime/conda/conda-rtd/lib/python2.7/site-packages/sphinx/application.py", line 456, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/msprime/conda/conda-rtd/lib/python2.7/site-packages/sphinx/registry.py", line 199, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
ExtensionError: Could not import extension sphinxarg.ext (exception: cannot import name Parser)

Extension error:
Could not import extension sphinxarg.ext (exception: cannot import name Parser)
```
I've tried pinning the version of CommonMark in pip, but it doesn't seem to help. (I think this package is pulled in somewhere else in RTD's setup and this is overriding it or something).

https://github.com/rtfd/recommonmark/issues/24

Anyway, the short version is that I don't think I'll be able to get conda working without breaking other stuff and putting in a lot more time than I'm willing to spend on this right now. 

I think it's probably better to resurrect this issue in a couple of months when hopefully the underlying issues will be resolved on RTD.

**Comment by jeromekelleher** [comment]
Closing this due to lack of action. We can reopen if anyone wants to work on it.
