### ISSUE TITLE
Method to compute `parent` column in `MutationTable`

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/msprime#286]
Write a function that does this.  Maybe two of them, one sideways and one backwards, for comparison.

Once this is written, we may also want to add  flags to `load_tables` to:
 - verify the parent column if present, and
 - compute the `parent` column on the fly, for sources where this is not already easily available.

**Comment by petrelharp** [comment]
It turns out we need to do this *now*, cc @bhaller.

**Comment by jeromekelleher** [comment]
This is done in ``table_collection_compute_mutation_parents``.
