### ISSUE TITLE
Add notebook friendly output to DemographyDebugger

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#385]
The output of the DemographyDebugger is currently text based. It would be nice to update this to render something in HTML (or something else) so that it works well in a Jupyter notebook. The information is straightforward to access, as the Demography debugger class has a ``epochs`` attribute, which contains all the information required.

**Comment by gtsambos** [comment]
Continuing the conversation had via email with @marianne-aspbury, and in [this pull request](https://github.com/tskit-dev/msprime/pull/791/files), it would be cool to have some HTML of the phylogenetic tree describing the simulated demography. We might need to think a bit about how to represent admixture between the populations, though.

(I don't have time for this right now, but adding these comments here in case I/someone else wants to revisit them later)

**Comment by jeromekelleher** [comment]
As a first step we'd settle for some HTML output for the migration matrix, rates etc and something that renders nicely in the notebook. 

Rendering the model is a whole other can of worms - I was talking to @apragsdale about this yesterday. He's working on a generic way of describing these models as a graph.
