### ISSUE TITLE
Add IndividualTable to model polyploid individuals

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#386]
As discussed in #380, there are issues with us not explicitly handling ploidy properly, and letting the user be responsible for knowing what pair (or more) of nodes corresponds to a particular individuals. I can imagine in future when we want to deal with more sophisticated algorithms and stats that are ploidy away (or just defined only for diploids), then we'll need some mechanism for handling it.

So, I suggest we add an IndividualTable, which would initially just consist of a metadata column. We then add an ``individual`` column to the node table so that we can assign nodes to individuals. This should be easy enough to manage through the simplification process.

Any thoughts @petrelharp, @molpopgen, @ashander?

**Comment by petrelharp** [comment]
Good idea; but I am a bit loathe to add more optional columns.  Alternatively, we could have some `node` columns in the `individual` table; this would then be easy to update with the (old node) -> (new node) mapping that simplify provides. Somehow it seems nicer to have an optional table than an optional column in a required table?

**Comment by jeromekelleher** [comment]
Are you suggesting that we have (e.g.) ``node1``, and ``node2`` as columns in the ``Individual`` table to store diploids?

**Comment by petrelharp** [comment]
Yes, exactly.

**Comment by ashander** [comment]
Good idea to have the IndividualTable. I agree with Peter --- if it's
possible to not have the NodeTable "know about" the individuals that seems
cleaner.

**Comment by jeromekelleher** [comment]
I'm not keen on this... what happens when someone wants to work with octoploid strawberrys, or haplodiploid wasps? I guess we could have a ragged column, but these are such a pain to manage.

We're consistently managing these one-to-many relationships using back-references now, which I think is good (nice and normalised). I.e., mutations have references to their sites, and mutations have references to their nodes. I'd need convincing!

**Comment by petrelharp** [comment]
Well, we could deal with haplodiploids by recording the NULL_NODE in those columns.  Are you thinking the 'individual' column would be optional?  If so, would it be less trouble to deal with an optional column there than to deal with a table that might have 8 columns?

Either seems OK to me, though.

**Comment by jeromekelleher** [comment]
I'd think of it as optional in the same way that ``mutation.parent`` is optional, or ``node.population`` is. (Really, population is referring to a table that we haven't created yet...) It's filled with -1s by default, so we don't have to worry about it when it doesn't matter. It would be substantially less trouble to add a single optional column to node (following this pattern) that the other options, I think.

**Comment by molpopgen** [comment]
The more I think about this, the more ambivalent I become.   One one hand, there's utility in having such a table/Table.  On the other, feature-creep may set in with `msprime` trying to do everything  for everyone.

Alternatively, imagine a (hopefully near) future where we've written up some docs on guidelines for generating node/edge data during forward-time simulations.  With the correct sorting of both ancestral and modern samples (one of the key things we need to document), I know that the `i-th` individual with ploidy `P` corresponds to nodes `[P*i,P*i+P)`, assuming that I'm generating offspring in a sane way in my forward sim (another thing to document!!)   Given that, if my node meta-data for samples is a generation plus the population size in that generation, I immediately know to which individual each node belongs.  (Perhaps I should maintain such a `list` or `dict` of `(time,N)` tuples separately, and thus only need to track generation as the metadata??) Given proper sorting of node IDs in sample lists, I should then be able to book-keep my own `dict` keyed on generation containing `list`s of metadata for each sample in that generation and be able to retrieve the correct data upon demand.

I'd argue that the above scheme wouldn't be hard, and suggesting it in the docs may help avoid adding further tables and columns to the Tables API.  In fact, having written the above, I find myself less keen on the whole idea of an `Individual`, but I acknowledge that there may exist `Individual`-level algorithms that may be nice to have in place.

**Comment by jeromekelleher** [comment]
Fair points @molpopgen. I would add though that representing real data is explicitly on the roadmap (and indeed, my main focus). I've made some tree sequences for 1000 Genomes data. How does someone who downloads one of these files know which samples correspond to NA12878? 

I agree we should be wary of feature creep, but not being able to specify concretely and unambiguously which two chromosomes make a sample seems like a gap to me. If we leave it up to convention, then, well, we all know what happens (Bioinformatics is rich with examples...).

**Comment by molpopgen** [comment]
Representing real data is a good motivation for this feature, as the workarounds one could use in a simulation don't exist.

I guess this comes down to deciding if everything that will be in `tskit` should also be in `msprime`?

**Comment by petrelharp** [comment]
Also re: @molpopgen - I think that we lose that information about ancestors after we simplify; so that adding in individuals somehow gives us the (arguably not very useful) information about when two coalescences happen on homologous chromosomes of the same individual.

**Comment by molpopgen** [comment]
> I think that we lose that information about ancestors after we simplify; so that adding in individuals somehow gives us the (arguably not very useful) information about when two coalescences happen on homologous chromosomes of the same individual.

Shouldn't this info be preserved due to sorting the samples?  Unless I've misunderstood something, it looks like samples are input into the "output node table" in the order of their ID.

**Comment by molpopgen** [comment]
@petrelharp -- I'm speaking specifically about the case where we are tracking ancestral samples.  Losing information about Individual ID due to coalescence is fine, as we're not going to try to associate meta-data to that node in most (all?) applications that I can envision.

**Comment by jeromekelleher** [comment]
> I guess this comes down to deciding if everything that will be in tskit should also be in msprime

I don't think we'd bother with this in msprime, and would just leave the ``IndividualTable`` empty and the ``node.individual`` column null. Perhaps sometime in the future someone will want to implement a proper diploid coalescent model in msprime, and then we would start using these fields.

**Comment by petrelharp** [comment]
@molpopgen - the information that the ancestral IDs are adjacent would be preserved, but the parity might not be.  If you're tracking ancestors, then sure, you can do the bookkeeping; I was talking about untracked ancestors... which we probably would not care about, I agree.

**Comment by petrelharp** [comment]
This would be nice to have in the SLiM implementation; we're currently putting this info (twice) into the metadata field for nodes. cc @bhaller

**Comment by jeromekelleher** [comment]
This isn't a simple change, it would take a fair bit of effort and thinking through of the consequences. I think we'd need to schedule a call to talk things through before taking this one on @petrelharp.

I think we do need it though, in the long run.

**Comment by petrelharp** [comment]
Agree: later.

**Comment by jeromekelleher** [comment]
Closed in #472.
