### ISSUE TITLE
Review tutorial structure

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#401]
Once the simulation tutorial chapter has been published and can be linked to, we need to go through the existing tutorial. It may be best to remove the tutorial entirely, and just have a series of links to Howto documents, built in another repo.

**Comment by cdquinto** [comment]
As a new user, I think that having a short tutorial like the one proposed here: https://github.com/tskit-dev/msprime/issues/995 , should be in the main documentation.

**Comment by jeromekelleher** [comment]
Closing this as we're moving all tutorial content to https://github.com/tskit-dev/tutorials
