### ISSUE TITLE
Add more statistical checks for DTWF with recombination

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#440]
Add more checks to verification.py checking various regimes with recombination (and perhaps more statistics?). We want to be sure that the basic DTWF gives the same results as the coalescent when N is reasonably large and n << N.

**Comment by DomNelson** [comment]
Fixed pending scaling issue mentioned in #439. For example (more checks written but without demography):

num_trees:
![num_trees](https://user-images.githubusercontent.com/8810687/41997769-f79cf270-7a26-11e8-8ca1-5a43d31b08f9.png)

tmrca_mean
![tmrca_mean](https://user-images.githubusercontent.com/8810687/41997773-f9b06830-7a26-11e8-80c0-4a8b895f6e51.png)

**Comment by jeromekelleher** [comment]
Excellent!  Looks good @DomNelson, let's get these checks into a PR.

**Comment by DomNelson** [comment]
Can close - PR #599

**Comment by jeromekelleher** [comment]
Done, thanks.
