### ISSUE TITLE
Unit tests for ModelChangeEvent

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#444]
Write some tests for the ModelChangeEvent to make sure model changes work OK. Should be robust to many different changes. Need to check how it interacts with other models also.

**Comment by DomNelson** [comment]
Deprecated - can close

**Comment by jeromekelleher** [comment]
I'm not sure we should get rid of the model change event --- we learned from hooking up with SLiM that there's quite a bit of subtlety in combining simulations. Are you using ModelChangeEvents or partial simulation of the DTWF + ``simulate_from`` in your combined sims? Ideally we'd use ``simulate_from`` I guess, but we do have to be certain that we're simulating the correct models, so would need statistical tests and some unit tests.

**Comment by jeromekelleher** [comment]
One of the reasons we might prefer to use the ModelChangeEvent is that using ``simulate_from`` involves round-tripping all coordinates through the recombination map, which can cause real problems. For this reason I think we should keep it, and put using ``max_time`` on the back burner (see #564 for more detail). If we use the ``ModelChangeEvent`` we don't have to worry about these messy details, and it's a bit more convenient for users in any case.

**Comment by jeromekelleher** [comment]
We have decent test coverage on this now. Closing.
