### ISSUE TITLE
Add tests for unique positions in simplify_tables

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#454]
#453 added a check to simplify to require unique positions, but no tests. Add some tests to verify the behaviour.

Also, if we can check this in sort_tables cheaply, I think we should and raise an error.

**Comment by jeromekelleher** [comment]
I can't remember if we decided this was desireable behaviour or not @petrelharp. I think we decided that simplify should let duplicate positions through? If so, we need to update the code to allow it and this issue is irrelevant.

**Comment by petrelharp** [comment]
In SLiM we are deduplicating sites before simplifying. If duplicate sites would pass through simplify, then we would not have to do this step until output, which would be nice but I suspect not a big deal. We do have to sort before deduplicating sites, though, which would be broken if we checked for this in sort_tables.
