### ISSUE TITLE
Remove MAX_ALLELES=255 restriction

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#466]
This is currently an artificial restriction which causes issues in certain extreme cases. 

Note that we don't need to *efficiently* handle very large numbers of alleles; the current algorithm which is efficient for small numbers of alleles is perfectly fine.

cc @bhaller

**Comment by bhaller** [comment]
Yes, this sounds right.  Fixing this is not at all a priority, but it is conceivable that a user trying to do something weird in SLiM might run into it.  Mostly, fixing it will just make a couple of tests in my test suite go from red to green.  :->
