### ISSUE TITLE
provide method to add individual tables to output

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/msprime#474]
This is dependent on getting IndividualTables (e.g. #472), obviously, but to have a placeholder...

I think we will want:

1. a method of a tree sequence that adds an individual table; you can pass it a list of tuples of sample nodes to be the individuals; or else by default it will pick pairs randomly within populations.

... and maaaybe we also want to

2. make `individuals` an argument to `msprime.simulate( )` so that then `sample_size` would be *diploid* sample size, and an individual table would be produced

**Comment by jeromekelleher** [comment]
What's your thinking on this @petrelharp, does it belong here or in tskit? I think we should update msprime to output individuals all right, but it's not a trivial change to make. (Probably there's some more complex simulation scenarious in the pipeline in which individuals will definitely be needed.)

**Comment by petrelharp** [comment]
I was thinking of it as an msprime thing, because it's a function necessary sometimes for msprime output. But it'd probably be useful in other situations, so it could go either way.

I was imagining this to be a trivial 'pair up nodes randomly' function, so maybe that should be in tskit, so no-one thinks that msprime is actually doing diploid simulation.

**Comment by jeromekelleher** [comment]
> I was imagining this to be a trivial 'pair up nodes randomly' function, so maybe that should be in tskit, so no-one thinks that msprime is actually doing diploid simulation.

I'm keen to keep any semblance of 'simulation' out of tskit to avoid bloat, so I think it'd be better to have a function ``msprime.whatever`` instead. By making it a post-processing function on a tree sequence I think it'd be pretty clear that we're not doing a proper diploid simulation.

**Comment by petrelharp** [comment]
Given that we have put in the ability to control VCF output via specifying individuals, this would be a useful thing to put in. How about either:

- `msprime.label_individuals(ts, individuals=[[0,1], [2,3], ... ], individual_names=['ind0', 'ind1', ...])` which returns a new tree sequence
- or another argument to `PopulationConfiguration` and to `simulate`,which is `individual_names` (and I guess also `ploidy`)?

**Comment by jeromekelleher** [comment]
Yes, something to think about as we're also adding support for individuals through a specified pedigree @DomNelson, @ivan-krukov

**Comment by jeromekelleher** [comment]
Closing in favour of #1170.
