### ISSUE TITLE
Add UUID to file format.

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#479]
Add a UUID to each tree sequence file so that it is uniquely identifiable. This is to facilitate provenance information, where we want to track the history of a given file through other files.

A randomly generated uuid4 is most appropriate.

**Comment by jeromekelleher** [comment]
Use  https://github.com/rxi/uuid4

**Comment by petrelharp** [comment]
Proposal:

1. this UUID lives with the table colleciton (which a tree sequence has one of)

2. whenever the table collection is written out to file,
    a. the UUID is wrtten to a new line in the provenance table
    b. the UUID of the table collection is updated with a new one
    c. then all this is written to file

2. as such the UUID of a table collection is interpreted as "the UUID of the file that was most recently sync'ed with this table collection" - i.e., the file it was loaded from, or the last one it was saved to.

**Comment by petrelharp** [comment]
We don't need to change the UUID every time the tables are modified, therefore.  And we *also* shouldn't change it when the tables are copied (since that most recent file is still the same for both copies).

**Comment by jeromekelleher** [comment]
Sounds like a good plan.

For the moment, though, we might simplify this down to:

1. When writing a file, if the table collection doesn't have a UUID, make a new one and write it to the file in the "uuid" field.

This will ensure at least that every file has a UUID. We can worry about the exact update rules later.

I'm inclined to push the provenance stuff up higher levels. We need to define a schema for provenance information, which the source UUID is going to be one aspect.

**Comment by petrelharp** [comment]
OK, but I'm going to vote for not having a standard for *every* provenance entry: we'll want to record stuff in there for SLiM that wouldn't appear in other places.

**Comment by jeromekelleher** [comment]
> OK, but I'm going to vote for not having a standard for every provenance entry: we'll want to record stuff in there for SLiM that wouldn't appear in other places.

I totally agree with this. The idea of the schema would be to give some high-level structure to the records, but people could put whatever they want in there apart from that. It'll be a very permissive approach, with just enough structure to make the records machine-parseable and usable.
