### ISSUE TITLE
Add MSP_INDIVIDUAL_ALIVE flag to the individual flags?

### ISSUE THREAD

**Issue by bhaller** [tskit-dev/msprime#484]
Hi all.  When loading in a .trees file, SLiM needs to know which individuals are ancestral (and thus do not need to be instantiated in the simulation, except as ancestral nodes in the trees) and which individuals are presently alive (and thus get instantiated as live individuals going forward).  Right now, we just assume that every individual in the Individuals table is alive.  However, it seems likely that some users of .trees files might want to have entries in the Individuals table for some (or all) ancestral individuals, too, to preserve information about them in metadata entries etc.  Such users, if they wanted to open their .trees file in SLiM, would have to remove all of the not-alive individuals from the table first, to avoid confusing SLiM.  This suggests to me that it would be useful to have a flag defined, perhaps called MSP_INDIVIDUAL_ALIVE, that would indicate which individuals in the table should still be considered to be alive for such practical purposes.  I don't think there would be any requirement that people set this flag one way or the other, unless they intend to load their file into SLiM (or other forward sims; this seems like a general issue that, e.g., fwdpp would also face @molpopgen).  But if they do want to set it, it's there; and it lets them load their .trees file into SLiM without having to prune out some of their data first.  (The "is_sample" stuff does not fit this bill because one can place ancestral/dead nodes in the sample, of course.)
Peter suggests instead having a flag that is private to SLiM; but this seems to me to be more hidden, less documented, less interchangeable, etc.  (Also, it isn't clear to me exactly how SLiM could define a private flag; if we decided to just designate a particular bit in the flags field as being "SLIM_ALIVE" or whatever, that would then create bugs and general chaos if tskit ever decided to add a meaning for that same bit.  Unless there is a range of bits in the flags field designated specifically as being reserved for third-party use, we really couldn't do this; we'd have to put it in metadata instead, which seems much more complicated than just defining the flag globally in tskit.)
Thoughts?

**Comment by jeromekelleher** [comment]
I agree with your thoughts on interchangability as a general principle @bhaller. In this, I wonder if it might be simpler to adopt the convention that all nodes with time 0 are alive and should be in the simulation? It seems logical enough.

**Comment by bhaller** [comment]
With overlapping generations and individuals that can live for different and (somewhat) arbitrary lengths of time, that doesn't work, does it?

**Comment by jeromekelleher** [comment]
> With overlapping generations and individuals that can live for different and (somewhat) arbitrary lengths of time, that doesn't work, does it?

Hmmm yes, that's true. OK, I'm happy to go with the consensus among the forward simulator authors on this one. @petrelharp, @molpopgen, what do we think? Should we define an ALIVE flag for individuals which is used to initialise forward simulations from a tree sequence? Seems sensible to me.

**Comment by molpopgen** [comment]
Well, fwdpp handles all of this completely differently, and fwdpy11 does one better via the pickling mechanism.  The data exchange would automatically rebuild all individuals + trees without needing to have a flag for who is alive vs not.  This wouldn't apply for some other simulator attempting to read in the data, but that's not what we're going for here.

As in tskit-dev/msprime#482, I'm leaning towards thinking of this as metadata.  However, this starts to address the issue of what bugs me about the IndividualTable (tskit-dev/msprime#472), and perhaps some of what I'm about to say belongs there.  The table is really a PartialIndividualTable--the code @petrelharp linked to in tskit-dev/msprime#472, which referred to individuals using indexes in the node table (the first thing I really didn't like, as it breaks the concept of how non-Node tables refer to Node Tables, but not vice-versa) means that the table contains individuals that are neither currently alive nor are tracked ancestral samples.  Thus, many individuals in the IndividualTable are represented by a single node that is a coalescent event, and are therefore partial.  When I originally brought up the issue of metadata redundancy for individuals way back when, I clearly didn't think through the implications of how partial individuals complicate the solution :). To me, it seems cleaner to build an IndividualTable at the end of a simulation (or whenever output of trees to an output format is desired), and you can have an ANCIENT flag where the non-zero value means an ancient sample, and the zero value mean an extant sample.

**Comment by bhaller** [comment]
> To me, it seems cleaner to build an IndividualTable at the end of a simulation (or whenever output of trees to an output format is desired)

This is what SLiM does now.  Yes, an individuals table maintained while running would be a bit odd, agreed.

> and you can have an ANCIENT flag where the non-zero value means an ancient sample, and the zero value mean an extant sample.

This is the proposed `MSP_INDIVIDUAL_ALIVE` flag, more or less.

**Comment by jeromekelleher** [comment]
OK, sounds like ALIVE isn't too controversial, and serves a purpose which we can clearly document. Seems good to me.

Responding to another point from @molpopgen:

> The table is really a PartialIndividualTable--the code @petrelharp linked to in tskit-dev/msprime#472, which referred to individuals using indexes in the node table (the first thing I really didn't like, as it breaks the concept of how non-Node tables refer to Node Tables, but not vice-versa) means that the table contains individuals that are neither currently alive nor are tracked ancestral samples. Thus, many individuals in the IndividualTable are represented by a single node that is a coalescent event, and are therefore partial. 

I think it's a strength that we can have individuals that have zero, one or many nodes referring to them. We might want to remember some ancestral individuals, even though they left no descendants in the present. It makes things very flexible, as we can capture mixed ploidy as well as the more boring human two nodes referring to a single individual. Hopefully it's flexible enough to capture the crazy stuff that happens in cancer cells too.

We can add a flag to simplify also to clear out any individuals that have zero nodes, which is easy and efficient to do.

**Comment by petrelharp** [comment]
I'm fine with doing it either way, but: the `ALIVE` flag is, I think, something that is only useful for telling simulators how to recover from a given state, and so maybe should be specific to simulators. For this sort of thing, I think we need

- a specified part of `flag` space for applications to use, so that e.g. SLiM can make up and set its own flags without worrying about conflicting with future `MSP_` flags.  Maybe: above 1024?

But, if we *do* want to have an `ALIVE` flag, I think we also need to add another bit of data: to what time does being "alive" refer to? In SLiM we're recording time in units of "time before the start of the simulation", so time 0 is definately not the time that "alive" refers to; and we store that time in metadata. So, the `ALIVE` flag is one that would only make sense with that additional bit of context, so I think we should put either neither or both in the standard.

Why doesn't alive-ness apply to real data?  Most real data is heterogenous, taken at different times, so I wouldn't expect all individuals to be alive, even if none of them are "ancient". I think it's fine to put in useful things for simulators that doesn't apply to real data, but I'd like to make sure it's general across most simulators (especially as they can store their own data in other ways).

**Comment by jeromekelleher** [comment]
> a specified part of flag space for applications to use, so that e.g. SLiM can make up and set its own flags without worrying about conflicting with future MSP_ flags. Maybe: above 1024?

We've got 32 bits, so 22 seems like a lot to reserve for application use. Maybe just the top 8 (bits 24 and above) would do? Or the top 16 also seems fine, I doubt we'll ever use more than this in tskit.

**Comment by bhaller** [comment]
From the SLiM perspective I don't have a terribly strong opinion regarding whether ALIVE should be a public tskit flag or a private flag.  To me it feels like a shared, and therefore public, concept, but I see @petrelharp's points too.  I've said my piece on that and I'm happy for Jerome to decide since he knows the broader usage of this stuff better than I.

As far as how to divvy up the bits, if the plan is to keep tskit fairly minimal and push off most biological weirdness and edge cases onto the particular users of tskit (as seems to be the consensus with, e.g., having tskit know only "male", "female", and "hermaphrodite" and leaving the rest to be defined in a package-specific manner), then it might make sense to give more bits to the other packages and fewer to tskit; so the top 16, at least.  Of course now would be the right time to increase flags fields to 64 bits, if we wanted more headroom, at least in the tables that we expect to have relatively few rows.  Might sound silly now, but who knows what the future holds...

**Comment by petrelharp** [comment]
In #482 we decided that individual flags would be for internal tskit use, so I am closing this until/unless we revist that discussion.
