### ISSUE TITLE
newick() output should (optionally) allow root to be specified, if multiple roots exist

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime#487]
In the case of a ts.tree with multiple roots, we should probably output multiple trees, each terminated by a semicolon.

**Comment by jeromekelleher** [comment]
I agree with this, but I think we need to consider what downstream tools will do with such inputs? Do you have any idea what libraries like biopython and R toolkits will do with this input @hyanwong? Is the idea of a tree with multiple roots something that people consider in the newick-based toolchain?

**Comment by jeromekelleher** [comment]
Yes, this is the best strategy I think. Users can then twiddle the output as they like. If ``root`` is None, revert to the current semantics (raising an error if more than one root), and otherwise return the newick tree rooted at that node.

**Comment by hyanwong** [comment]
Seems reasonable to me.
