### ISSUE TITLE
Documentation confuses SparseTree.get_num_samples() and SparseTree.num_samples()

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime#491]
Both are mentioned, at http://msprime.readthedocs.io/en/stable/api.html#msprime.TreeSequence.trees and http://msprime.readthedocs.io/en/stable/api.html#msprime.SparseTree.num_samples - presumably only one should be used.

**Comment by jeromekelleher** [comment]
Yes, it should all the ``num_samples`` form. PR welcome!

**Comment by hyanwong** [comment]
Right, will make a few other (trivial) doc corrections too. I guess I just edit the doc files in `/msprime/docs/*.rst`?

**Comment by jeromekelleher** [comment]
> Right, will make a few other (trivial) doc corrections too. I guess I just edit the doc files in /msprime/docs/*.rst?

Yep, or the docstrings for the function in question.

**Comment by jeromekelleher** [comment]
Closed in #548.
