### ISSUE TITLE
Add text input for Individuals, Populations, Migrations, Provenances

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#498]
We can't round trip a table collection through text without them, and we'll definitely need at least individuals and Populations  for doing decent testing.

**Comment by petrelharp** [comment]
Also: Individuals and Populations are not printed when printing a TableCollection.

**Comment by jeromekelleher** [comment]
Closed in #555. Migrations are handled in #389.

**Comment by gtsambos** [comment]
I'm currently trying to use this functionality to set up some tests, but am getting some errors. Do you know what might be going wrong for me here?

https://gist.github.com/gtsambos/d20f85954fd9325b94af548e7eda7051
