### ISSUE TITLE
load_tables should accept TableCollection as parameter

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#499]
I suggest changing ``load_tables`` as follows:

```python
def load_tables(tables=None, nodes=None, edges=None, ..., sequence_length):
    # stuff
```
The default way to use ``load_tables`` will be 
```python
ts = msprime.load_tables(tables)
```
which seems like what we'd want. We can also support existing code by looking at the keyword arguments and accepting **either** a TableCollection in ``tables``, or a bunch of other tables in the old keywords. This will be **mostly** backwards compatible with old code. Where it will break old code is if people we using the pattern

```python
ts = msprime.load_tables(nodes, edges)
```
rather than
```python
ts = msprime.load_tables(nodes=nodes, edges=edges)
```
It's unfortunate, but I don't see any other way of doing it without making the API clumsier in the long term. Since it's a pretty recent API with a fairly niche usage, I think it's OK.

@petrelharp, @molpopgen, what do you think?

**Comment by petrelharp** [comment]
Looks good.
