### ISSUE TITLE
Deprecate simplify_tables and sort_tables

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#500]
These have been replace by ``TableCollection.simplify`` and ``TableCollection.sort``. The question is, do we quietly 'undocument' the old functions and mark them as deprecated in the code, or do we keep them in the documentation, marking them as deprecated?

I would be in favour of undocumenting them --- I doubt many people are using them.

@petrelharp, @molpopgen, what do you think?

**Comment by petrelharp** [comment]
Undocument; or document as deprecated, to be removed in the future.

**Comment by jeromekelleher** [comment]
Also document the TableCollection object and the new interfaces based on this.
