### ISSUE TITLE
Update simplify to remove unreferenced individuals

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#501]
Simplify should have an option of removing individuals that are not referenced by any nodes. I think this should be the default behaviour, and keeping these individuals should require a boolean flag be provided. This should be analogous to the existing ``filter_zero_mutation_sites``. Call it ``filter_zero_node_individuals``?

What do you think @petrelharp

**Comment by petrelharp** [comment]
yes, perfect.
