### ISSUE TITLE
Add time interval to mutate()

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#508]
Based on idea from @molpopgen. See also #507.

It is useful to specify a time interval over which mutations are generated. This should include an upper and lower bound. One way we could parameterise this is:
```python
def mutate(ts,..., interval=None...):
     if interval is None:
          interval =  None, None
     start, end = interval
     if start is None:
        start = 0
     if end is None:
         end = sys.float.max  # whatever the notation for DBL_MAX is
     # Now generate mutations between from time start to end
```

Or we could have
```python
def mutate(ts,..., start=None, end=None,...):
      if start is None:
        start = 0
     if end is None:
         end = sys.float.max  # whatever the notation for DBL_MAX is
     # Now generate mutations between from time start to end
```

``start`` and ``end`` don't feel like quite the right names for the parameter though. ``interval`` is also a bad idea as this is used for trees to denote the genomic range they cover. Any better ideas would be very welcome!

**Comment by hyanwong** [comment]
`time_interval` or `timespan` might be better?

**Comment by molpopgen** [comment]
@hyanwong makes a good suggestion.  Other possibilities include `epoch`, `era`, etc.

**Comment by jeromekelleher** [comment]
For symmetry with the rest of the API (see #541), these should be called ``start_time`` and ``end_time``, and be half open (started included, end excluded).
