### ISSUE TITLE
Interface for making mutations SLiM compatible

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#509]
From @bhaller in #507 

> We will eventually want to be able to open a .trees file with overlaid mutations back up in SLiM, to run further simulation on it, I think; to do that the overlaid mutations will need to get the appropriate metadata added to them, which I believe @petrelharp has a plan for...? That SLiMification process would also involve rounding off site positions to integers and merging mutations at the same site into stacked mutations with the appropriate stacked derived state, so it will be a bit of an adventure to do right.

**Comment by petrelharp** [comment]
I had imagined the tools for dealing with SLiM data being a separate package, but it need not be if others are interested.  Would you like it all in one place, @jeromekelleher?

**Comment by petrelharp** [comment]
> It could start out as utilities needed for dealing with metadata like this and eventually provide a Python interface to SLiM. 

Maybe! But not by me. =)

**Comment by jeromekelleher** [comment]
> I think a separate package, but under tskit-dev is the way to go.

Agreed.

>> It could start out as utilities needed for dealing with metadata like this and eventually provide a Python interface to SLiM.
> Maybe! But not by me. =)

Haha! If it used an existing installation of SLiM and just ran simulations by ``subprocess.call`` with tempfiles it would be pretty simple to do though (not that I'm volunteering!).

OK, going to close this one here so. We can discuss the tskit-dev/??SLiM?? repo elsewhere.
