### ISSUE TITLE
tree_sequence_init_individuals doesn't use conitiguity

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#527]
We can do the initialisation more efficiently using the fact that individuals are contiguous.

**Comment by petrelharp** [comment]
I didn't think we were going to guarantee this, actually?

**Comment by jeromekelleher** [comment]
We are currently testing that all nodes for a given individual are contiguous [here](https://github.com/tskit-dev/msprime/blob/master/lib/tree_sequence.c#L465). What's to be gained from not requiring that all the nodes for a given individual are contiguous? We're not saying that they have to be in any particular order, just contiguous.

**Comment by petrelharp** [comment]
Why, so we are: mostly, I just misremembered about this.

I don't see a particular problem with this. Only: if we do require this, then the `add_individuals` method (that adds an individual table to a tree sequence without one) will have to reorder the tables, rather than only adding an individual table.

**Comment by jeromekelleher** [comment]
> I don't see a particular problem with this. Only: if we do require this, then the add_individuals method (that adds an individual table to a tree sequence without one) will have to reorder the tables, rather than only adding an individual table.

I think the advantages outweigh this... hopefully most table collections will come complete with individuals set already, so this sort of post-hoc surgery won't be necessary.

**Comment by jeromekelleher** [comment]
Certainly, msprime should start adding proper individual tables in the next release...

**Comment by jeromekelleher** [comment]
#567 resolves this by getting rid of the contiguity requirement.
