### ISSUE TITLE
Distinction between nodes and individuals not clear

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#529]
The docs for nodes and individuals need another pass; it's still not clear to me what a node is... Is it a gamete? (This is mentioned somewhere).

We need to get this clear I think and make sure it's consistent through the docs. We'll have confused users otherwise...

**Comment by petrelharp** [comment]
Yes, it is, but I hesitate to say that, since it will be confusing.

How about we refer to nodes as "chromosomes" mostly, but I'll write an paragraph explaining what they actually are, in the more-than-one-chromosome case.

**Comment by jeromekelleher** [comment]
Sounds good to me @petrelharp, whatever you think.

**Comment by petrelharp** [comment]
I went with "nodes" mostly, but then "genomes" for explanatory purposes; and put a paragraph explaining in.

**Comment by jeromekelleher** [comment]
Closed in #548.
