### ISSUE TITLE
Installation issues via pip: no _msprime.TableCollection() function available

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime#552]
When I install msprime using

`pip3 install --user --upgrade msprime`

I then get:

```
>>> import msprime
>>> ts = msprime.TableCollection()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yan/.local/lib/python3.4/site-packages/msprime-0.6.1.dev4+ngdc17d5e-py3.4-linux-x86_64.egg/msprime/tables.py", line 1382, in __init__
    ll_tables = _msprime.TableCollection(
AttributeError: 'module' object has no attribute 'TableCollection'
```

This doesn't happen if I run the python3 interpreter from within the msprime directory, so I suspect the pip3 installation is missing up the installation of the msprime C library somehow. Or it could just be me.

**Comment by jeromekelleher** [comment]
Looks like you have some odd versions lying around which is confusing things (see version 0.6.1.dev4+ngdc17d5e above). If you clear out the version in ``/home/yan/.local/lib/python3.4/site-packages/`` and run ``pip install msprime`` it should work fine.

**Comment by jeromekelleher** [comment]
FYI, it's better to use ``python3 -m pip`` rather than ``pip3``, as this ensures that you're updating the Python installation that you think you are.
