### ISSUE TITLE
Provenance schema

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#556]
We need some sort of structure for the provenance data that we are recording. I suggest we create a simple JSON schema for this, so that we can document the format and validate it. There is a basic outline at the moment, which covers things like the software environment quite well, but is poor for capturing the actual command/function that was run. Currently we have:
```json
{
  "version": "0.6.0b1",
  "environment": {
    "os": {
      "version": "#50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018",
      "node": "powderfinger",
      "release": "4.13.0-45-generic",
      "system": "Linux",
      "machine": "x86_64"
    },
    "python": {
      "implementation": "CPython",
      "version": [
        "3",
        "5",
        "2"
      ]
    },
    "libraries": {
      "kastore": {
        "version": [
          0,
          1,
          0
        ]
      },
      "gsl": {
        "version": [
          2,
          1
        ]
      }
    }
  },
  "command": "simulate",
  "parameters": {
    "TODO": "encode simulation parameters"
  },
  "software": "msprime"
}
```

The  ``command`` and ``parameters`` bit is weak I think, and doesn't generalise very well between CLI and API invocations.

With SLiM now outputting tree sequence files I think it's important we nail this down reasonably well so that we can document the expected structure.

Some principles:

1. The schema should document a **top-level** structure that specifies just enough to be useful. Users are entirely free to put whatever extra stuff they like into the provenance documents.  Hopefully the top-level structure will make it obvious where the stuff that they want to add should go.
2. The schema should provide structure sufficient to make it possible to fully reproduce a particular simulation/tree sequence inference. The schema is not responsible for this though, it's up to the client programs to ensure that they are providing enough information.
3. The schema structure for specifying commands and parameters used should generalise across API and CLI invocations (i.e., having a ``command_line`` attribute somewhere is no good, as this doesn't work for API invocations).

Pinging @molpopgen, @bhaller, @petrelharp, @ashander, @DomNelson, @hyanwong for input.

See also https://github.com/tskit-dev/tsinfer/issues/29

**Comment by jeromekelleher** [comment]
> Looks good to me. I vote for the other stuff being allowed at the top level, not (necessarily) shoved into some required toplevel category.

Sure, people can stuff whatever they like wherever so long as it doesn't clash with the defined usage.

Is there a reason for not including the full SLiM program in there, btw? I would have thought this was the obvious thing to do.

**Comment by bhaller** [comment]
> Sure, people can stuff whatever they like wherever so long as it doesn't clash with the defined usage.

So if I understand correctly, SLiM's provenance would not be required to change as a result of this proposal, correct?  Nothing about it "clashes with the defined usage", correct?

> Is there a reason for not including the full SLiM program in there, btw? I would have thought this was the obvious thing to do.

What do you mean by "the full SLiM program"?

**Comment by jeromekelleher** [comment]
> So if I understand correctly, SLiM's provenance would not be required to change as a result of this proposal, correct? Nothing about it "clashes with the defined usage", correct?

That's true. It would be better if we could agree on things like ``software`` or ``program`` though. In the long run, this will be a lot more useful if we can get some basic things agreed on and standardise. It doesn't really matter if the existing provenance documents don't match the schema, which I would imagine we'll want to version anyway.

> What do you mean by "the full SLiM program"?

OK, my terminology was wrong here. I mean the Eidos script that defines the simulation. Since the goal is reproducability here, why not add the full  (JSON escaped) script to the provenance? 

The ultimate goal here is: the user finds a file in 5 years time and they want to reproduce the simulation that produced it. They should be able to know (a) what the software package was, and what version; (b) what the execution environment was (what OS, version, etc), and the versions of any important linked libraries; (c) what the exact parameters used were.

**Comment by bhaller** [comment]
> It would be better if we could agree on things like software or program though. In the long run, this will be a lot more useful if we can get some basic things agreed on and standardise.

Agreed.  I guess msprime is already using "software" and SLiM is using "program"?  Well, there's no big obstacle to having SLiM write out exactly the same thing for "software", I suppose.  The "program" key can be deprecated and eventually omitted.

> OK, my terminology was wrong here. I mean the Eidos script that defines the simulation. Since the goal is reproducability here, why not add the full (JSON escaped) script to the provenance?

Hmm.  In general, I think this is not really possible, because the script can source other arbitrary scripts in the filesystem, etc. – you could include the main script, but that provides no guarantee that that script will actually run and produce the same results as the original run, because of external dependencies.  Might still be worth considering, though.

> The ultimate goal here is: the user finds a file in 5 years time and they want to reproduce the simulation that produced it.

Needless to say, this was not on our radar at all when we designed the present SLiM provenance info.  :->  But it's a nice goal.

**Comment by jeromekelleher** [comment]
Define basic schema and documentation for 0.6.1
