### ISSUE TITLE
Add ploidy argument to simulate and allocate individuals

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#557]
It's becoming increasingly clear that the current approach of sort-of being diploid isn't great. Perhaps we should add a ``ploidy`` argument to ``simulate`` so that we can try to fix this. Here's one possible way forward.

- Add an argument ``ploidy`` which defaults to None. If it is None, have the same behaviour as now: time is scaled as 4Ne and no individuals are allocated. 
- If ``ploidy`` is not None, scale time appropriately and allocate individuals sequentially among the samples. The total number of samples must be divisible by ``ploidy``, or an error is raised.

Hopefully this will keep backwards compatibility so that all existing code will still work as expected, while also providing a less confusing path forward. It would be nice to set ``ploidy`` to 2 by default, but I don't see how we can deal with allocating individuals in the case where the number of samples is odd. 

Any thoughts @petrelharp, @molpopgen? 

See also #548, #529

**Comment by molpopgen** [comment]
For odd-numbered samples:

The final nodes are random w.r.to genealogical relationship.  In ms/msprime, one make 'diploids' simply by pairing up adjacent rows in the output matrix.  Thus, for odd-numbered sample sizes and even ploidy, you could simulate one extra lineage that is not output?  However, this scheme means that the error condition you outline above is undesirable.

It may be useful to avoid setting the ploidy to two by default.  As-is, it is straightforward for a user to simulate haploids, etc., with the current machinery by simply scaling their input parameters appropriately.

**Comment by petrelharp** [comment]
Partly, I think this is an unavoidably confusing issue. We can't completely remove the burden of thinking through things carefully from the user.  

A `ploidy` argument does seem like a good way to ask msprime to give you diploids, etcetera. But, with the `ploidy` argument, it would be natural if everything referring to samples refered to polyploid samples (thus avoiding the odd-numbers problem).  This would be a major change, which we probably want to avoid.

I don't understand what you mean by "time scaling" - which time scaling? Do you mean that `ploidy` is a factor that the provided Ne is multiplied by?

**Comment by jeromekelleher** [comment]
> A ploidy argument does seem like a good way to ask msprime to give you diploids, etcetera. But, with the ploidy argument, it would be natural if everything referring to samples refered to polyploid samples (thus avoiding the odd-numbers problem). This would be a major change, which we probably want to avoid.

I agree it would have been better for samples to be polyploid, but it's too late to change that now I think.

> I don't understand what you mean by "time scaling" - which time scaling? Do you mean that ploidy is a factor that the provided Ne is multiplied by?

Yes -- currently we multiple by 4Ne, which is ploidy * 2 Ne. If ploidy was 1, then we'd scale by 2Ne, and wouldn't have to do this confusing Ne=1/2 business when comparing with theory. Or have I missed the point somewhere along the line?

**Comment by petrelharp** [comment]
> Yes -- currently we multiple by 4Ne, which is ploidy * 2 Ne. If ploidy was 1, then we'd scale by 2Ne, and wouldn't have to do this confusing Ne=1/2 business when comparing with theory. Or have I missed the point somewhere along the line?

I think this just adds another layer of possible confusion. The theory isn't even all consistent on whether Ne is diploid or not, anyhow.

**Comment by jeromekelleher** [comment]
This has been closed by the ``sim_ancestry`` function
