### ISSUE TITLE
Add TreeSequence.metadata?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#563]
It seems it might be useful to have a top-level metadata value associated with a TreeSequence object itself. Basically each TreeSequence has a ``.metadata`` attribute which returns a bytes object (in the same way as would happen for a node, etc). This gives somewhere to store information which helps you understand the tree sequence itself, and is stored in the file.

I guess we also add this to the TableCollection object, and we follow the same rules about data access (read only for the TreeSequence; if you want to modify it, output the TableCollection and edit there).

The reason I thought of this is that I feel that SLiM is slightly abusing the idea of provenance at the moment by storing things which help a client interpret the tree sequence in there, rather than documenting where the tree sequence came from.

Any thoughts @petrelharp, @bhaller? It's easy to implement and we can add it in for the next release. We can make it an optional field in the file, so we won't need to bump the file format major version.

**Comment by petrelharp** [comment]
That would be very nice; my only concern is if more than one program wants to store stuff there, they could overwrite each other's info.

And, it is a slight abuse of provenance, maybe, but that information really is legitimately part of the provenance, because it is information about how the tree sequence was produced. I kinda think it is OK?

On the other hand, it would be nice to have somewhere to store `sequence_length`.

**Comment by bhaller** [comment]
Hmm.  I *think* I would say that we should just keep things the way they are.  I don't see any problem with storing the info in the provenance, really, and in some ways it's actually good; it says "at the time that this provenance entry was written out by program X, here is the additional program-specific info that was associated with it".  Tying those two things together actually seems better to me.  And it is nice that the provenance info is in JSON; that makes it simpler.  If this SLiM-specific info were being put into metadata instead, SLiM would (a) have to walk through the metadata and try to interpret each metadata block as a SLiM metadata block, which could be problematic if another app happens to write out a block that looks the same, and (b) would have to assume that the last metadata entry matched the last provenance, or something.  The current scheme seems simpler and better, really.  Sorry, thinking/typing fast, I only have a minute with internet.  But that's my hot take.

**Comment by petrelharp** [comment]
If `sequence_length` doesn't go there, then I totally vote for keeping as-is, I think.

**Comment by jeromekelleher** [comment]
OK, cool, let's shelve the idea so. Thanks for the feedback @petrelharp and @bhaller.
