### ISSUE TITLE
Debugger prints incorrect demography

### ISSUE THREAD

**Issue by apragsdale** [tskit-dev/msprime#568]
When simulating exponentially growing populations, events that occur between the start and end times of the exponential epoch reset the population sizes to the initial size. So if a population's size changes from N_0 to N_1, any event that occurs between T_0 and T_1 will reset the population size to N_0, and the size at T_1 is no longer N_1.

This appears to just be an issue with the debugger, as the resulting simulated data look to be correct for the scripted (not printed) models.

A working example is included here (.py files can't be attached..?) - should be able to see it in the printed output. Thanks!

[admix_example.py.gz](https://github.com/tskit-dev/msprime/files/2274828/admix_example.py.gz)

**Comment by apragsdale** [comment]
import sys, os
import numpy as np
import msprime
import copy, time, math

def demo_model_2pops(ns=(10,10), L=1e6, r=2e-8, u=2e-8, debugger=False, ts=False):
    """ simple split model with two populations, bottleneck+growth in each """ 
    n1,n2 = ns
    N_A = 1e4
    # population sizes at time of split
    N1_0 = 1e3
    N2_0 = 2e3
    # event times
    generation_time=29
    T_merge = 40e3 / generation_time
    # growth rates
    r1 = 0.005
    r2 = 0.002
    # original population sizes
    N1 = N1_0 / math.exp(-r1 * T_merge)
    N2 = N2_0 / math.exp(-r2 * T_merge)

    population_configurations = [
        msprime.PopulationConfiguration(sample_size=n1, initial_size=N1, growth_rate=r1),
        msprime.PopulationConfiguration(sample_size=n2, initial_size=N2, growth_rate=r2)
    ]
    
    demographic_events = [
        # no admixture in this model, just two exponentially growing populations that split some time ago 
        # populations 1 and 2 merge together, set migration rates to 0
        msprime.MassMigration(
            time = T_merge, source = 1, destination = 0, proportion = 1.0),
        msprime.MigrationRateChange(
            time = T_merge, rate=0),
        # update pop size and growth rate to have ancestral size
        msprime.PopulationParametersChange(
            time = T_merge, initial_size = N_A, growth_rate = 0, population_id = 0)
    ]
    
    # to see the debugger history, set debugger to True
    if debugger == True:
        dp = msprime.DemographyDebugger(
            population_configurations=population_configurations,
            migration_matrix=migration_matrix,
            demographic_events=demographic_events)
        dp.print_history()
    
    # to simulate under this demography, set ts to True
    if ts == True:
        tree_sequence = msprime.simulate(
            population_configurations=population_configurations,
            length=L,
            mutation_rate=u,
            recombination_rate=r,
            migration_matrix=migration_matrix,
            demographic_events=demographic_events)
        return tree_sequence

def demo_model_admix(ns=(10,10,10), L=1e6, r=2e-8, u=2e-8, debugger=False, ts=False):
    n1,n2,n3 = ns
    N_A = 1e4
    # population sizes at time of split
    N1_0 = 1e3
    N2_0 = 2e3
    N_ADM = 5e3
    f_ADM = 0.25 # f_adm of lineages come from pop1, 1-f_adm from pop2
    # event times
    generation_time=29
    T_ADM = 5e3 / generation_time
    T_merge = 40e3 / generation_time
    # growth rates
    r1 = 0.005
    r2 = 0.002
    # original population sizes
    N1 = N1_0 / math.exp(-r1 * T_merge)
    N2 = N2_0 / math.exp(-r2 * T_merge)

    population_configurations = [
        msprime.PopulationConfiguration(sample_size=n1, initial_size=N1, growth_rate=r1),
        msprime.PopulationConfiguration(sample_size=n2, initial_size=N2, growth_rate=r2),
        msprime.PopulationConfiguration(sample_size=n3, initial_size=N_ADM)
    ]
    
    demographic_events = [
        # admixture event, send proportion f_adm of lineages to pop1, rest to pop2
        msprime.MassMigration(
            time = T_ADM, source = 2, destination = 0, proportion = f_ADM),
        msprime.MassMigration(
            time = T_ADM, source = 2, destination = 1, proportion = 1.0),
        
        # populations 1 and 2 merge together, set migration rates to 0
        msprime.MassMigration(
            time = T_merge, source = 1, destination = 0, proportion = 1.0),
        msprime.MigrationRateChange(
            time = T_merge, rate=0),
        # update pop size and growth rate to have ancestral size
        msprime.PopulationParametersChange(
            time = T_merge, initial_size = N_A, growth_rate = 0, population_id = 0)
    ]
    
    # to see the debugger history, set debugger to True
    if debugger == True:
        dp = msprime.DemographyDebugger(
            population_configurations=population_configurations,
            migration_matrix=migration_matrix,
            demographic_events=demographic_events)
        dp.print_history()
    
    if ts == True:
        tree_sequence = msprime.simulate(
            population_configurations=population_configurations,
            length=L,
            mutation_rate=u,
            recombination_rate=r,
            migration_matrix=migration_matrix,
            demographic_events=demographic_events)
        return tree_sequence

if __name__ == "__main__":
    print "Model without admixture...\n\n"
    tree_seq = demo_model_2pops(debugger=True)
    print "\n\n\nModel with admixture...\n\n"
    tree_seq_admix = demo_model_admix(debugger=True)

**Comment by apragsdale** [comment]
import sys, os
import numpy as np
import msprime
import copy, time, math

def demo_model_2pops(ns=(10,10), L=1e6, r=2e-8, u=2e-8, debugger=False, ts=False):
    """ simple split model with two populations, bottleneck+growth in each """ 
    n1,n2 = ns
    N_A = 1e4
    # population sizes at time of split
    N1_0 = 1e3
    N2_0 = 2e3
    # event times
    generation_time=29
    T_merge = 40e3 / generation_time
    # growth rates
    r1 = 0.005
    r2 = 0.002
    # original population sizes
    N1 = N1_0 / math.exp(-r1 * T_merge)
    N2 = N2_0 / math.exp(-r2 * T_merge)

    population_configurations = [
        msprime.PopulationConfiguration(sample_size=n1, initial_size=N1, growth_rate=r1),
        msprime.PopulationConfiguration(sample_size=n2, initial_size=N2, growth_rate=r2)
    ]
    
    demographic_events = [
        # no admixture in this model, just two exponentially growing populations that split some time ago 
        # populations 1 and 2 merge together, set migration rates to 0
        msprime.MassMigration(
            time = T_merge, source = 1, destination = 0, proportion = 1.0),
        msprime.MigrationRateChange(
            time = T_merge, rate=0),
        # update pop size and growth rate to have ancestral size
        msprime.PopulationParametersChange(
            time = T_merge, initial_size = N_A, growth_rate = 0, population_id = 0)
    ]
    
    # to see the debugger history, set debugger to True
    if debugger == True:
        dp = msprime.DemographyDebugger(
            population_configurations=population_configurations,
            migration_matrix=migration_matrix,
            demographic_events=demographic_events)
        dp.print_history()
    
    # to simulate under this demography, set ts to True
    if ts == True:
        tree_sequence = msprime.simulate(
            population_configurations=population_configurations,
            length=L,
            mutation_rate=u,
            recombination_rate=r,
            migration_matrix=migration_matrix,
            demographic_events=demographic_events)
        return tree_sequence

def demo_model_admix(ns=(10,10,10), L=1e6, r=2e-8, u=2e-8, debugger=False, ts=False):
    n1,n2,n3 = ns
    N_A = 1e4
    # population sizes at time of split
    N1_0 = 1e3
    N2_0 = 2e3
    N_ADM = 5e3
    f_ADM = 0.25 # f_adm of lineages come from pop1, 1-f_adm from pop2
    # event times
    generation_time=29
    T_ADM = 5e3 / generation_time
    T_merge = 40e3 / generation_time
    # growth rates
    r1 = 0.005
    r2 = 0.002
    # original population sizes
    N1 = N1_0 / math.exp(-r1 * T_merge)
    N2 = N2_0 / math.exp(-r2 * T_merge)

    population_configurations = [
        msprime.PopulationConfiguration(sample_size=n1, initial_size=N1, growth_rate=r1),
        msprime.PopulationConfiguration(sample_size=n2, initial_size=N2, growth_rate=r2),
        msprime.PopulationConfiguration(sample_size=n3, initial_size=N_ADM)
    ]
    
    demographic_events = [
        # admixture event, send proportion f_adm of lineages to pop1, rest to pop2
        msprime.MassMigration(
            time = T_ADM, source = 2, destination = 0, proportion = f_ADM),
        msprime.MassMigration(
            time = T_ADM, source = 2, destination = 1, proportion = 1.0),
        
        # populations 1 and 2 merge together, set migration rates to 0
        msprime.MassMigration(
            time = T_merge, source = 1, destination = 0, proportion = 1.0),
        msprime.MigrationRateChange(
            time = T_merge, rate=0),
        # update pop size and growth rate to have ancestral size
        msprime.PopulationParametersChange(
            time = T_merge, initial_size = N_A, growth_rate = 0, population_id = 0)
    ]
    
    # to see the debugger history, set debugger to True
    if debugger == True:
        dp = msprime.DemographyDebugger(
            population_configurations=population_configurations,
            migration_matrix=migration_matrix,
            demographic_events=demographic_events)
        dp.print_history()
    
    if ts == True:
        tree_sequence = msprime.simulate(
            population_configurations=population_configurations,
            length=L,
            mutation_rate=u,
            recombination_rate=r,
            migration_matrix=migration_matrix,
            demographic_events=demographic_events)
        return tree_sequence

if __name__ == "__main__":
    print "Model without admixture...\n\n"
    tree_seq = demo_model_2pops(debugger=True)
    print "\n\n\nModel with admixture...\n\n"
    tree_seq_admix = demo_model_admix(debugger=True)

**Comment by jeromekelleher** [comment]
Thanks for the report @apragsdale, we'll try and get this one sorted out for the next release.

**Comment by jeromekelleher** [comment]
Can you walk me through an example of what's going wrong here please @apragsdale? I've had a look at the output your code is producing, but I can't see anything wrong. It'd be helpful if you could paste in the debug output, and point out where the problem is.

**Comment by apragsdale** [comment]
Hi Jerome - it looks like this was an issue with version 0.4.0, and the problem doesn't replicate on newer versions (0.5.0 for example). Thanks for taking the time to check in any case.
