### ISSUE TITLE
Provide recipe for simulation using threads

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#59]
Splitting replicate simulations over the available processors is a common and important application. We should provide an example of how to do this in the docs.

**Comment by molpopgen** [comment]
Yes please!

**Comment by jeromekelleher** [comment]
This is a bit of a can of worms, unfortunately. The problem is that the TreeSequence object is mutable, which makes guaranteeing safety with many threads accessing the same underlying C struct very difficult. By releasing the GIL at the critical points needed for good simulation performance, we open up all sorts of possibilities for nasty things to happen.

The way to make this happen cleanly in the future may be to make the TreeSequence fully immutable, so that we don't have to worry about pointers changing in between invocations. The only place that we currently allow mutability is through ``set_mutations``, so the answer might be to change the semantics from setting the mutations to returning a new tree sequence with the same topology and a different set of mutations.

There are higher priorities at the moment though, so I'm going to have to kick this can down the road. In the short term, using the ``multiprocessing`` module will give very convenient parallelism across multiple processes (which is better if you are doing any processing of the results in Python in any case).

**Comment by molpopgen** [comment]
Using multiprocessing is probably fine for most use cases, so that's
great.  I'll play with it.

By mutability, do you mean global, static, or what? (A link to the relevant
lines of .c files is probably enough to answer.)  Depending on the details,
it may be possible to use compiler pragmas to give thread-safety.  The
issue is that that approach may undo the work you've done in adding Windows
support.

**Comment by jeromekelleher** [comment]
> By mutability, do you mean global, static, or what? (A link to the relevant lines of .c files is probably enough to answer.) 

Basically mutability of the object itself. At the moment there is a reference count on the TreeSequence object (or  equivalently, ``tree_sequence_t`` struct) which needs to be incremented and decremented when we create and destroy trees that reference it. When ``set_mutations`` is called, this count is checked, and if non-zero an error raised. I've tried various ways of protecting the reference count, but nothing works cleanly. I think c11 atomics would do the trick, but it's not worth the portability hassles IMO (as you point out). 

The more I think about it the more full immutability makes sense, it just gets rid of all this awkwardness and gives a real definition of identity for a tree sequence as well.

**Comment by ashander** [comment]
Semi-related question: what factors drove your initial decision to make the TreeSequence object mutable

**Comment by molpopgen** [comment]
On Tue, Nov 8, 2016 at 12:44 PM Jerome Kelleher <notifications@github.com>
wrote:

> By mutability, do you mean global, static, or what? (A link to the
> relevant lines of .c files is probably enough to answer.)
>
> Basically mutability of the object itself. At the moment there is a
> reference count on the TreeSequence object (or equivalently,
> tree_sequence_t struct) which needs to be incremented and decremented
> when we create and destroy trees that reference it. When set_mutations is
> called, this count is checked, and if non-zero an error raised. I've tried
> various ways of protecting the reference count, but nothing works cleanly.
> I think c11 atomics would do the trick, but it's not worth the portability
> hassles IMO (as you point out).
>

I see.  Looking at the code, it seems that you are reference counting the
objects "manually"?

OpenMP may be more portable in the near-term than any c11 stuff, since it
is widely available. It supports atomic operations via compiler directives:
http://stackoverflow.com/questions/14016026/openmp-and-pragma-omp-atomic

The more I think about it the more full immutability makes sense, it just
> gets rid of all this awkwardness and gives a real definition of identity
> for a tree sequence as well.
>
Yes, this is probably true.  But I have what may be a naive question:  if
you're running different simulations in different threads, isn't there a
different tree allocated per thread?  The lack of thread safety that I see
(again, based on just a cursory look) appears to only be an issue if > 1
thread try to touch the same tree.

**Comment by jeromekelleher** [comment]
> Semi-related question: what factors drove your initial decision to make the TreeSequence object mutable

It is useful to be able to set the mutations on a tree sequence 'by hand' @ashander, for example, when you want to create some specially crafted mutational patterns for testing, or if you want to filter out the low-frequency mutations, and so on. However, these use cases can be met by providing an API for copying with a given set of mutations, which would make the object fully immutable.

**Comment by jeromekelleher** [comment]
> I see.  Looking at the code, it seems that you are reference counting the objects "manually"?

Yeah, it's a hack @molpopgen . I'm not reference counting for garbage collection or anything like that, it's just to make sure that this 
```
tree = next(tree_sequence.trees())
tree_sequence.set_mutations([])
tree_muts = list(tree.mutations())
```
raises an error rather than segfaults. Each tree object is intimately linked with the parent tree sequence for memory and performance reasons, and so yanking out a bunch of pointers is very dangerous. The reference counting approach works fine in a single thread, but gets hairy across multiple threads.

Good idea on OpenMP, I didn't know they provided atomics. I think the simpler answer long-term is to make the TreeSequence fully immutable so we can have efficient read-only semantics from lots of threads.

> Yes, this is probably true.  But I have what may be a naive question:  if
you're running different simulations in different threads, isn't there a
different tree allocated per thread?  The lack of thread safety that I see
(again, based on just a cursory look) appears to only be an issue if > 1
thread try to touch the same tree.

This is absolutely true (and impressive code sleuthing!). In the nominal case where we're doing lots of replicate simulations in different threads we're just creating lots of thread private TreeSequences, and these problems never happen. Unfortunately, by unblocking the GIL at the points needed for good performance, I can't stop multiple threads accessing the same TreeSequence, which is where things get dodgy. I can't _guarantee_  the safety of Python code under the current semi-mutable model.

**Comment by molpopgen** [comment]
I think I have a better understanding now.  That is tricky.  The only other thing that comes to mind is to have things like "tree" be something equivalent Cython extension types that hold a pointer to the underlying C type.  That would give a Pythonic API while also being robust to those sorts of quirky use situations.

**Comment by jeromekelleher** [comment]
This is how it works @molpopgen --- in _msprimemodule.c (which defines low-level Python interface), the [SparseTree class](https://github.com/jeromekelleher/msprime/blob/master/_msprimemodule.c#L64) keeps a pointer to a  [sparse_tree_t struct](https://github.com/jeromekelleher/msprime/blob/master/lib/msprime.h#L305), which is the corresponding C 'object'. This one object is used to represent every tree in the sequence, and is updated to change its state to represent the next tree. This means there are no mallocs between tree transitions, and the time required to move from one tree to the next is constant.

Once the parent TreeSequence is immutable, then we can be sure that Python's reference counting will keep all the relevant objects alive for the right amounts of time and that all pointers are valid. The problem occurs when the TreeSequence is mutable via ``set_mutations``, then we can't be sure that the pointers that SparseTree instances hold to the mutations are valid. This will go away once we make TreeSequence immutable, and everything will be nice and simple.

**Comment by molpopgen** [comment]
Ok--now I get it.  I've never worked with C/Python directly.  I've only done stuff via Cython.

Once trees are immutable, is there a way to keep functionality like set_mutations alive?  Seems like that stuff would be useful, but there's always this safety/flexibility tradeoff.

**Comment by jeromekelleher** [comment]
> Once trees are immutable, is there a way to keep functionality like set_mutations alive? Seems like that stuff would be useful, but there's always this safety/flexibility tradeoff.

Yeah, I think the right thing to do is offer copy semantics --- give me a new tree sequence with exactly the same toplogy as the current one, and optionally with a different set of mutations.

**Comment by hyanwong** [comment]
This issue is very old, and nor tree sequences are immutable, so it should (I think) be trivial to stick an example in the docs for running multiple parallel instances of mutate() on the same tree sequence. I suggest that we should also recommend using branch length stats as an alternative, if the point of replication is to reduce statistical variance in some metric. As I think it's trivial to close this issue, can we add the msprime 1.0 milestone to this, @jeromekelleher ?

**Comment by jeromekelleher** [comment]
I don't think it's that trivial @hyanwong because of the GIL, actually getting stuff to run in parallel in threads isn't that easy. I think we can just close the issue though, as everything we've said above is out of date.
