### ISSUE TITLE
big overallocation in node_table_expand_metadata?

### ISSUE THREAD

**Issue by bhaller** [tskit-dev/msprime#606]
Hi @jeromekelleher.  I *think* I have a bug for you, although I'm inexperienced in this code base.  In `node_table_expand_metadata()`, you do:
```
ret = expand_column((void **) &self->metadata, new_size, sizeof(char *));
```
That should be `sizeof(char)`, shouldn't it?  I'm pretty sure that what I'm seeing in my profiling tool is that the node table's metadata column is taking exactly eight times as much memory as it ought to.  :-O

@petrelharp, this bug, if it is a bug, exists in SLiM's copy of the code as well.  :-O

**Comment by jeromekelleher** [comment]
Yes indeed; superb catch @bhaller! Thanks a million for this.
