### ISSUE TITLE
Calculate likelihood of observed pattern of variants, given a tree sequence

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime#613]
_From @hyanwong on November 10, 2017 13:31_

This might be more of an msprime issue, but Rob has suggested that it would be nice to be able to calculate the likelihoods of a set of haploid sequences, conditioned on the TS. It should be easy to do this for a tree sequence with branch lengths. But it should also be possible to do with the topology only (relevant for tsinfer)

_Copied from original issue: mcveanlab/treeseq-inference#43_

**Comment by jeromekelleher** [comment]
This is dependent on assumed models and a lot of other things, so I think it's out of scope here. Tacking this would involve another repo I think.
