### ISSUE TITLE
Advice about memory use when generating large samples

### ISSUE THREAD

**Issue by gdurif** [tskit-dev/msprime#614]
Hi, I have a question about memory (and cpu) use.

For an experiment, I would like to generate large samples (at least dozens and at best hundreds of individuals) for a region of the size of a small human chromosome (tens of thousands of SNPs).

Is there any trick to reduce memory consumption ?

My problem is that generating large samples is memory consuming (the following example exceed 32 GB with 45 individuals, i.e. `sample_size=15). I have access to machines with larger memory (~200GB) but I don't know if that would be sufficient. Numerous and large trees occupy a lot of memory but maybe I am doing something not efficiently, or maybe there is some way to improve my code ?

I use this simple model where a population A splits into two populations A and B, and population  C is the result of a recent admixture event between A and B:
```
A, B, C = 0, 1, 2

Ne = 5000
sample_size = 1

population_configurations = [
    msprime.PopulationConfiguration(sample_size=sample_size, initial_size=Ne),
    msprime.PopulationConfiguration(sample_size=sample_size, initial_size=Ne),
    msprime.PopulationConfiguration(sample_size=sample_size, initial_size=Ne)
]

demographic_events = [
    msprime.MassMigration(
        # 60 % of C merge to A
        time=15,
        source=C, destination=B, proportion=0.6),
    msprime.MassMigration(
        # 40 % of C merge to A
        time=15,
        source=C, destination=A, proportion=0.4),
    msprime.MassMigration(
        # B merge to A
        time=5000,
        source=B, destination=A, proportion=1)
]

ts = msprime.simulate(
        length=50e3, mutation_rate=2e-8,
        recombination_rate=2e-8,
        population_configurations = population_configurations,
        demographic_events = demographic_events,
        random_seed=30)
```

In addition, I have seen that you were considering multi-thread computing when generating more than one replicate. Is there any multi-core mechanism when simulating a single replicate ?

Thanks in advance (and thanks again for all your amazing work),
Best

**Comment by jeromekelleher** [comment]
This is a good question @gdurif, but I think it's more suited to the [mailing list](
https://groups.google.com/forum/#!forum/msprime-users) rather than an issue. Would you mind reposting it there please?

I'm surprised this example uses so much memory...

**Comment by gdurif** [comment]
Sorry, yes I will repost it there.
