### ISSUE TITLE
Simulate local ancestry

### ISSUE THREAD

**Issue by MrLocuace** [tskit-dev/msprime#621]
Hello, I would like to ask you a question and I'd be very grateful if you could help me.

I have SNP info of an admixed population A with 3 ancestral populations (B,C,D). Using local ancestry inference methods, a 0,1 or 2 (from B,C and D, respectively) is assigned to each allele of each SNP in A. This is an example of an admixed population of 2 diploid individuals having 2 SNPs, and their corresponding local ancestry:

IND  SNP1 SNP2
indv1 0 1
indv1 0 2
indv2 0 1
indv2 1 1

On the other hand, I simulated genotypes using ms, including admixture events. I'd like to compare my real vs simulated genotypes. Is there any way of simulating this kind of local ancestry data with msprime? Do you have any suggestion?

Thank you very much
All the best,
Luc

**Comment by petrelharp** [comment]
The only way I know of to do this using msprime would be to use the
undocumented argument to the `simulate()` function that lets you run a
simulation for a given amount of time (not all the way to coalescence):

https://github.com/tskit-dev/msprime/blob/master/msprime/simulations.py#L266
So, if admixture occurred T units of time ago you could just simulate back
T units of time and determine local ancestry. If you needed completely
coalesced trees, you could fill those out using the `from_ts` argument to
simulate( ) on the resulting tree sequence, described here:

https://msprime.readthedocs.io/en/stable/api.html#initialising-simulations-from-a-tree-sequence

**Comment by MrLocuace** [comment]
Thank you very much. I'll try that
