### ISSUE TITLE
AttributeError: module 'msprime' has no attribute 'simulate'

### ISSUE THREAD

**Issue by alanrogers** [tskit-dev/msprime#622]
stschiff had this same problem last March, but the fix that worked for him then isn't working for me now, so I thought I'd open a new issue.

I've installed msprime version 0.6.1 on a Mac using pip3. Initial efforts to do this failed because the C compiler could not find file "hdf5.h".  I fixed that with "brew install hdf5", then re-installed like this:

  pip3 install --force-reinstall --ignore-installed --no-binary :all: msprime==0.6.1

The command-line test (mspms 10 1 -T) works fine. But this fails:

$ python3
Python 3.7.0 (default, Oct 20 2018, 16:53:21) 
[Clang 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import msprime
>>> ts = msprime.simulate(sample_size=10, Ne=1000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'msprime' has no attribute 'simulate

**Comment by jeromekelleher** [comment]
Thanks for letting me know @alanrogers.

> I've installed msprime version 0.6.1 on a Mac using pip3. Initial efforts to do this failed because the C compiler could not find file "hdf5.h". I fixed that with "brew install hdf5", then re-installed like this:

This is weird because we got rid of hdf5 a while back, which shouldn't be needed at all now (except for indirectly through h5py). There must be another version of msprime lying about the place somewhere or something...

Can you try:
```
$ python3 -m pip install --force-reinstall msprime
```
and paste the full output in here please?

**Comment by alanrogers** [comment]
I just did as you suggested, and now it works. The pip output is below. Thanks, Alan

[jacana ~]$ python3 -m pip install --force-reinstall msprime
Collecting msprime
Collecting h5py (from msprime)
Using cached 
Collecting six (from msprime)
Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting numpy>=1.7.0 (from msprime)
  Downloading https://files.pythonhosted.org/packages/f9/64/f47c172c2d2ee8907b5918ff7af7e52207f6bf4a57983e4474fcda728112/numpy-1.15.2-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (24.5MB)
    100% |████████████████████████████████| 24.5MB 315kB/s 
Collecting svgwrite (from msprime)
  Using cached https://files.pythonhosted.org/packages/9f/27/a29fc710b5fc4dc8031d55e903c1352a194df4014dccf8b507049dd754e6/svgwrite-1.1.12-py2.py3-none-any.whl
Collecting jsonschema (from msprime)
  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting pyparsing>=2.0.1 (from svgwrite->msprime)
  Using cached https://files.pythonhosted.org/packages/2b/4a/f06b45ab9690d4c37641ec776f7ad691974f4cf6943a73267475b05cbfca/pyparsing-2.2.2-py2.py3-none-any.whl
Installing collected packages: six, numpy, h5py, pyparsing, svgwrite, jsonschema, msprime
  Found existing installation: six 1.11.0
    Uninstalling six-1.11.0:
      Successfully uninstalled six-1.11.0
  Found existing installation: numpy 1.15.2
    Uninstalling numpy-1.15.2:
      Successfully uninstalled numpy-1.15.2
  Found existing installation: h5py 2.8.0
    Uninstalling h5py-2.8.0:
      Successfully uninstalled h5py-2.8.0
  Found existing installation: pyparsing 2.2.2
    Uninstalling pyparsing-2.2.2:
      Successfully uninstalled pyparsing-2.2.2
  Found existing installation: svgwrite 1.1.12
    Uninstalling svgwrite-1.1.12:
      Successfully uninstalled svgwrite-1.1.12
  Found existing installation: jsonschema 2.6.0
    Uninstalling jsonschema-2.6.0:
      Successfully uninstalled jsonschema-2.6.0
  Found existing installation: msprime 0.6.1
    Uninstalling msprime-0.6.1:
      Successfully uninstalled msprime-0.6.1
Successfully installed h5py-2.8.0 jsonschema-2.6.0 msprime-0.6.1 numpy-1.15.2 pyparsing-2.2.2 six-1.11.0 svgwrite-1.1.12

**Comment by alanrogers** [comment]
I just realized what caused this problem. I had named a file in my directory "msprime.py" (to distinguish it from scrm.py). So my "import msprime" command was importing the local file by mistake.

Sorry to have raised this issue.

**Comment by jeromekelleher** [comment]
No problem @alanrogers, glad you sorted it out!
