### ISSUE TITLE
mspms: error: argument --random-seeds/-seeds: expected 3 arguments

### ISSUE THREAD

**Issue by MrLocuace** [tskit-dev/msprime#623]
Dear Jerome,
I am tying to run a ms script that starts like this:

    mspms 500 2 -s 1 -I 5 2 100 100 100 100 100

When I run it I get:

    mspms: error: argument --random-seeds/-seeds: expected 3 arguments

When I do:

    mspms 500 2 -s 1 -I 5 2 100 100 100 100 100  -seeds 123 456 789

or 

    mspms -seeds 123 456 789 500 2 -s 1 -I 5 2 100 100 100 100 100

I get the same message.

May I ask you how and where in the script do I need to specify the seed?

Also, in the documentation it says:

_The implementation of the -es option is limited, and has restrictions on how it may be combined with other options._

May I ask you where can I find a description of these restrictions

Thanks very much
All the best,
Luc

**Comment by MrLocuace** [comment]
You are right Peter, that is exactly what I wanted to do. Thank you for your help.

**Comment by MrLocuace** [comment]
Hello @petrelharp , I have a very naive question. I have a ms script and I want to convert the output genotypes to vcf format. ms cannot do it, so I decided to use msprime. I do not want to translate the whole ms script into msprime code. What is the easiest way to achieve this? "Plugging in" the ms code in msp or mspms?. From the documentation it looks like mspms is better suited to do this task, but maybe I am wrong. Thanks very much

**Comment by petrelharp** [comment]
`mspms` and `msp` are just different interfaces to the same code. The `msp`
command-line interface is mostly the same as `ms` (but beware of
differences in scaling: see the documentation). So, it should be easy to
convert over your script (although I saw your other issue...). I exerpt
here from the help to `msp`:
```
peter@skua:~/projects/space/isolation_by_coalescence$ msp -h
usage: msp [-h] [-V]

{simulate,vcf,nodes,edges,sites,mutations,provenances,haplotypes,variants,macs,newick,upgrade}
           ...

Command line interface for msprime.

positional arguments:

{simulate,vcf,nodes,edges,sites,mutations,provenances,haplotypes,variants,macs,newick,upgrade}
    simulate            Run the simulation
    vcf                 Write the tree sequence out in VCF format.
```
... so that looks easy to do. On the other hand, if you output the result
in tree sequence format by some other method, then it is just a few lines
of python to convert it to VCF.

**Comment by jeromekelleher** [comment]
Hi @MrLocuace. The mspms inferface is intended to be an ms-compatible interface to the msprime code that implements a subset of ms's functionality to support existing applications. Things that aren't currently implemented (like parts of the ``-es`` options) are unlikely to be implemented unless someone volunteers to do the work, as I'm afraid supporting this interface is a long way down our priority list.

>> The implementation of the -es option is limited, and has restrictions on how it may be combined with other options.
> May I ask you where can I find a description of these restrictions

The source code is the best place to look for this I'm afraid:

https://github.com/tskit-dev/msprime/blob/master/msprime/cli.py#L313

mspms should raise an error when options are combined in an unsupported way, and this function will be called in those circumstances.

See also 
```
$ mspms --help
```
which lists the options and gives details.

It looks like the original problem has been resolved (with seeds), so I'm going to close this issue.

**Comment by MrLocuace** [comment]
Thank you very much for your help !
All the best,
Luc
