### ISSUE TITLE
mspms: error: Cannot currently use the -es and -ema options together. 

### ISSUE THREAD

**Issue by MrLocuace** [tskit-dev/msprime#624]
Hello, I am trying to reproduce a ms script using mspms. The script includes -ema and -es options. When I run the script with mspms I get:

    mspms: error: Cannot currently use the -es and -ema options together. Please open an issue on GitHub if this functionality is important to you.

Do you have any suggestion?

Thanks very much
Best,
Luc

**Comment by jeromekelleher** [comment]
The simplest option here I'm afraid is to translate your model into msprime Python code; If I recall correctly, supporting these options together will be quite tricky in mspms. If you'd like to help us add support for this though please do get in touch off-line.
