### ISSUE TITLE
GSL error handler clobbering

### ISSUE THREAD

**Issue by molpopgen** [tskit-dev/msprime#632]
In lib/msprime.c, msp_alloc sets the GSL error handler to "off" with every call.  The effect of this behavior is to undo the error handler of any other package running in the same memory space.  I noticed this when unit tests started suddenly failing in molpopgen/fwdpy11#142.  The cause was having msprime and fwdpy11 both listed as top-level imports.

Not sure what the best approach to fixing this is.

**Comment by jeromekelleher** [comment]
I think a module level function in the ``_msprime`` C module which allows us to turn on and off the GSL error handling stuff. Will sort out for next release.

**Comment by molpopgen** [comment]
By turn off, do you mean disable, or to save and then restore the error handler?

**Comment by jeromekelleher** [comment]
Just turn off ``msprime``'s messing with the handler entirely, so it never gets touched. Anything else would be too complicated I think. The handler can only ever get invoked in obscure cases when we're doing numerical integration in the Lambda coalescent models, so there's no point in doing anything too elaborate.

So, in your case, you could do something like
```
import msprime

msprime.gsl_error_handling(False)
```
which would ensure that the handler never gets messed with. Would this work for you?

**Comment by molpopgen** [comment]
And otherwise, GSL error handling would be untouched, meaning that whatever error handler is enabled would be respected?  If so, that works.

**Comment by jeromekelleher** [comment]
> And otherwise, GSL error handling would be untouched, meaning that whatever error handler is enabled would be respected? If so, that works.

Yeah. I'll change it so that the error handler setting is done once only. On import, we'll save the current GSL error handler and set the custom msprime one. If a function is called though, we can reset the error handler back to what it was previously. This should sort it out I think.
