### ISSUE TITLE
Remove GSL dependency?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#639]
GSL is causing a lot of problems in upstream packaging. Investigate removing the dependency and instead compiling the bits we need locally.

Windows support will probably be the trickiest thing.

**Comment by jeromekelleher** [comment]
Had a go at this over in #640 and gave up after getting bogged down in trying to extract out the bits of GSL that we're using. If we were only using the random number generator and random distributions, I think it'd be pretty straightforward to just compile in the bits we need. However, we're also using some special functions and it's very hard to extract out anything without having to basically compile in *all* of the special functions, which then touch other parts of the library and so on.

So, unless we get rid of the non-Hudson models in msprime I think we're stuck with having GSL as a dependency.

FYI @molpopgen.

**Comment by petrelharp** [comment]
If this is a big enough deal we could implement those special functions ourselves. (i.e., find the appropriate old fortran code to copy)

**Comment by jeromekelleher** [comment]
I've ended up spending more than a day fiddling with it at this point, I don't think there's a good solution. The GSL breaks up its special function implementations into lots of cases, which ends up reaching out into lots of other special functions to handle the particular regimes. People have though hard about these things, and there's no point in duplicating/using worse, potentially buggy implementations.

Some of the special functions are being reached into for implementing the random distributions, which we definitely want. 

GSL is a pretty well behaved dependency in any case. It's just conda-forge is in a mess at the moment and I was seeing if I could work around it.

**Comment by molpopgen** [comment]
I think that the openblas issue with GSL on conda-forge should be opened as
an issue, and/or a member of that project should submit a PR to fix it.
The current recipe maintainer has hidden the dependency on openblas on the
grounds that GSL's blas implementation is "slow".  But, replacing it with
an OpenMP-based blas causes other side-effects and the method used to link
to openblas is not the one that the GSL authors recommend.
__
Kevin Thornton
Associate Professor
Ecology and Evolutionary Biology
UC Irvine
www.molpopgen.org
github.com/molpopgen
github.com/ThorntonLab

**Comment by jeromekelleher** [comment]
I've been working on this [here](https://github.com/conda-forge/gsl-feedstock/issues/34) @molpopgen. I'm not sure it's an issue with gslcblas vs openblas, it's some obscure combination of compiler toolchain/platform/conda-build mucking things up.

**Comment by molpopgen** [comment]
What a mess.
__
Kevin Thornton
Associate Professor
Ecology and Evolutionary Biology
UC Irvine
www.molpopgen.org
github.com/molpopgen
github.com/ThorntonLab
