### ISSUE TITLE
Implement basic single sweep model in C

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#645]
Implement the minimal working code for sweeps in C. Needs:

1. Implemented using the [development CLI](https://msprime.readthedocs.io/en/stable/development.html#development-cli), ensuring that there's no memory leaks or access violations with valgrind.
2. Some tests in ``simulation_tests.c`` that exercise all new code paths (except for memory errors, etc).

**Comment by andrewkern** [comment]
hey @jeromekelleher i'm just checking out this "TODO" feature list and saw this open. if we merge my PR will it satisfy the test requirements or is there a different test suite?

**Comment by jeromekelleher** [comment]
Closed in #744.
