### ISSUE TITLE
Statistical tests for single_sweeps

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#647]
Once the basic infrastructure for sweeps we need to get some statistical tests in place in [verification.py](https://github.com/tskit-dev/msprime/blob/master/verification.py). Ideally, we'll add some basic infrastructure for comparing with discoal and add a bunch of checks comparing distributions.

**Comment by andrewkern** [comment]
just trying to go through the TODO list... working on this with this [PR](https://github.com/tskit-dev/msprime/pull/756)

**Comment by andrewkern** [comment]
okay @jeromekelleher want to finish this up in the next few weeks (finally). what sorts of statistical tests do we want to get in to `verification.py`? Right now we have the following
```
 # Simple discoal tests
    verifier.add_discoal_instance(
        "discoal-simple-ex",
        "15 1000 100 -t 5.0")
    verifier.add_discoal_instance(
        "discoal-size-change1",
        "15 1000 100 -t 10.0 -en 0.1 0 2.0")
    verifier.add_discoal_instance(
        "discoal-size-change2",
        "15 1000 100 -t 10.0 -en 0.1 0 0.1")
    verifier.add_discoal_instance(
        "discoal-size-change3",
        "50 1000 100 -t 10.0 -en 0.01 0 0.01")
    verifier.add_discoal_instance(
        "discoal-size-change4",
        "50 1000 100 -t 10.0 -en 0.01 0 0.5 -en 0.05 0 1.0")
```

presumably i should do some single sweep tests with no population size change? anything more?

trying to recall exactly where we left this and what we need to do next to get it production ready. most of the nuts and bolts code is merged already I believe.

**Comment by andrewkern** [comment]
okay @jeromekelleher want to finish this up in the next few weeks (finally). what sorts of statistical tests do we want to get in to `verification.py`? Right now we have the following
```
 # Simple discoal tests
    verifier.add_discoal_instance(
        "discoal-simple-ex",
        "15 1000 100 -t 5.0")
    verifier.add_discoal_instance(
        "discoal-size-change1",
        "15 1000 100 -t 10.0 -en 0.1 0 2.0")
    verifier.add_discoal_instance(
        "discoal-size-change2",
        "15 1000 100 -t 10.0 -en 0.1 0 0.1")
    verifier.add_discoal_instance(
        "discoal-size-change3",
        "50 1000 100 -t 10.0 -en 0.01 0 0.01")
    verifier.add_discoal_instance(
        "discoal-size-change4",
        "50 1000 100 -t 10.0 -en 0.01 0 0.5 -en 0.05 0 1.0")
```

presumably i should do some single sweep tests with no population size change? anything more?

trying to recall exactly where we left this and what we need to do next to get it production ready. most of the nuts and bolts code is merged already I believe.

**Comment by jeromekelleher** [comment]
I think we just want a mixture of representative tests @andrewkern, that will exercise the different things we've implemented. You're a better judge of what that needs to be than me I think.

**Comment by jeromekelleher** [comment]
@andrewkern, do you think we can close this issue now? Are you happy with the stats test coverage we have on the existing sweep models?

**Comment by andrewkern** [comment]
yup we are all set for now. closing.
