### ISSUE TITLE
linker errors for tskit and lib

### ISSUE THREAD

**Issue by andrewkern** [tskit-dev/msprime#657]
hey jerome- i'm trying to make the lib directory to get the development CLI up and going and am getting a linker error. looks like tskit is now a required library:

gcc -g -O2 -Ikastore/c -std=c99 -pedantic -Werror -Wall -W -Wmissing-prototypes -Wstrict-prototypes -Wconversion -Wshadow -Wpointer-arith -Wcast-align -Wcast-qual -Wwrite-strings -Wnested-externs -fshort-enums -fno-common -Dinline=  -std=c99 -pedantic -Werror -Wall -W -Wmissing-prototypes -Wstrict-prototypes -Wconversion -Wshadow -Wpointer-arith -Wcast-align -Wcast-qual -Wwrite-strings -Wnested-externs -fshort-enums -fno-common -Dinline=  -o main main.c msprime.o fenwick.o object_heap.o recomb_map.o mutgen.o avl.o util.o  argtable3.o -lgsl -lgslcblas -lm -Ltskit -ltskit -lconfig
ld: library not found for -ltskit
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [main] Error 1`

i did the natural thing and went to try to build tskit in lib/tskit and got a whole slew of duplicate symbols:
gcc -I../kastore/c -std=c99 -Wall -g old_tests.c tsk_core.o tsk_tables.o tsk_trees.o tsk_genotypes.o tsk_convert.o tsk_stats.o kastore.o -lm -lcunit -lgsl -lgslcblas
duplicate symbol ___sputc in:
    tsk_core.o
    tsk_tables.o

etc.

how should I be building this to get my dev CLI going? I was following the docs but I think your coding has outpaced them!!! thanks for all your help.

**Comment by jeromekelleher** [comment]
Sorry about this @andrewkern, unfortunately your hitting the code base at a time when it's going through a major transition (pulling tskit out of msprime). You're right the documentation is out of date.

What you need to do to build the developement CLI is first build tskit and then build the CLI:
```
$ cd lib/tskit
$ make
$ cd ..
$ make 
```
This should leave you with a working ``./main`` program.

However, I'm guessing that you're working on a mac, which is going to cause problems when working on the C code here I'm afraid. The Makefile I have here is only tested on (Debian/Ubuntu) Linux. I don't have access to a Mac, and the last time I tried to help someone get it working it on a Mac it ended up being a bit of a rabbit hole and I gave up.

The simplest thing to do might be to develop on a Linux machine I'm afraid. Either on a server you have access to or using linux VM on your laptop?

**Comment by andrewkern** [comment]
yep. I'll switch machines that I am developing on.
