### ISSUE TITLE
Bad edge interval when simulating multiple chromosomes

### ISSUE THREAD

**Issue by DomNelson** [tskit-dev/msprime#664]
Possibly relates to #278 
Originally tested on commit 72f5005ac91f23cd7a46805bf63cbd92a056c638

When using recombination hotspots to unlink different chromosomes, I occasionally get the error: `Bad edge interval where right <= left`. Recombination map was specified using positions/rates similar to 
```
0 1e-08
99999999 0.5
100000000 1e-08
199999999 0.5
200000000 1e-08
299999999 0
```
and using `recombination_map = msprime.RecombinationMap(positions, rates)`. Maybe also related to `num_loci` as in #278?

When updating to 0f2a86c49013e78193ff03e54f4c2cb7bc3a507a, these errors become `_msprime.LibraryError: Unknown error`. More recent versions I had trouble importing `kastore` so I haven't tested them yet. It does look like it's the same error though - at least the same random seeds give errors in both versions. 

I wrote a little script for finding these errors: https://github.com/DomNelson/wf_coalescent/blob/master/scripts/test_multiple_chroms.py

Using the default parameters and running I few times, I got errors in the Hudson model at random seeds
```
19116959
875432464
413146442
282020767
``` 

and in the DTWF model at 
```
568229549
586898785
240190228
219888652
```

**Comment by jeromekelleher** [comment]
So I think this is the same problem as #278. Basically, the recombination rate is so high we end up converting two different discrete loci to the same double value, resulting in a bad edge.

The answer is to explicitly use a discrete coordinate map, as shown in #278.

**Comment by jeromekelleher** [comment]
Can we close this issue @DomNelson?

**Comment by DomNelson** [comment]
Yep sounds good. I thought I'd seen the problem when using a discrete map so I wanted to double check. I've done it now though and it all looks good. I'd possibly missed the proper `num_loci` by +- 1.
