### ISSUE TITLE
Convert _msprimemodule.c to use numpy C API where possible

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#666]
A lot of the code in _msprimemodule.c is concerned with parsing input. We can streamline this and make it much more efficient by using numpy instead. For example, functions like ``convert_integer_list``, ``convert_float_list`` etc can all be changed.  We can also probably update ``parse_samples`` to use numpy record array without losing backwards compatability.

The RecombinationMap class in particular should be updated, as this would be far simpler if we used numpy.

**Comment by jeromekelleher** [comment]
See also #902

**Comment by grahamgower** [comment]
You can assign this and #902 to me.

**Comment by jeromekelleher** [comment]
Done! Thanks @grahamgower .

**Comment by jeromekelleher** [comment]
I think this is basically done now. The one thing I spotted in the code was the ``migration_matrix`` argument to simulate could be changed to a 2D array, which would probably help us shed some code. Would you like to take this on @grahamgower. I'm happy to do it.

Should be done after #946

**Comment by grahamgower** [comment]
I remember looking at it and thinking that the current `Simulator_parse_migration_matrix()` wouldn't be simplified much, so it wouldn't be worth the effort unless 2d numpy arrays were also returned from `Simulator_get_migration_matrix()`. But this will likely result in considerable breakage. I'll leave this one to you --- hopefully you've got a better handle on the scope of the breakage.

**Comment by jeromekelleher** [comment]
Will do, ta.
