### ISSUE TITLE
Keep/kill the msp CLI?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#671]
~The ``msp`` CLI will remain where it is, but a different CLI will be developed for ``tskit`` which may be more useful. Add some comments in the source to the effect that the code is kept for compatibility purposes, but no longer under development (see ``python -m tskit`` for more up-to-date versions).~

There seems to be little point to the msp CLI and I doubt anyone uses it. Can we kill it as part of the 1.0 breakage?

**Comment by jeromekelleher** [comment]
Need to have CLI working in tskit first: https://github.com/tskit-dev/tskit/issues/80

**Comment by jeromekelleher** [comment]
We could consider dropping this for 1.0.

**Comment by jeromekelleher** [comment]
The tskit CLI should have all the features we need, and we can remove anything in the msp CLI that's duplicated. This will allow us to shed a fair bit of code.

We could remove the msp CLI altogether: it's not feature rich, and it's pretty redundant now we have stdpopsim.

**Comment by jeromekelleher** [comment]
Hmmm, twitter say [keep msp simulate](https://twitter.com/jeromekelleher/status/1225056414990839808). Oh well.

**Comment by andrewkern** [comment]
only 24 votes however

**Comment by molpopgen** [comment]
Mark me down as "never used it".

**Comment by jeromekelleher** [comment]
I think we can keep ``msp simulate`` and kill off the rest of the commads (which have moved into tskit) for 1.0. It's not a big maintenance burden, and even if only a handful of people are using then there's no point in screwing them over.

**Comment by winni2k** [comment]
Mark me down as "stdpopsim doesn't do what I need it to do and therefore msp works nicely". Not sure if that means we should still kill it and force me to contribute my weird models to stdpopsim...

**Comment by jeromekelleher** [comment]
The decision is to keep the msp CLI, but to get rid of the extra commands left-over from pre-tskit days.

See #1120 for details.
