### ISSUE TITLE
Compilation failure: 'tsk_tables.h' file not found

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime#689]
On current master, on OS X (although I'm guessing it doesn't matter) I get:

```
python3 setup.py build_ext --inplace
running build_ext
building '_msprime' extension
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -UNDEBUG -Ilib -Ilib/tskit/c -Ilib/tskit/c/kastore/c -I/usr/local/Cellar/gsl/2.5/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/include/python3.7m -I/usr/local/lib/python3.7/site-packages/numpy/core/include -c _msprimemodule.c -o build/temp.macosx-10.14-x86_64-3.7/_msprimemodule.o -std=c99
In file included from _msprimemodule.c:32:
lib/msprime.h:34:10: fatal error: 'tsk_tables.h' file not found
#include "tsk_tables.h"
1 error generated.
error: command 'clang' failed with exit status 1
make: *** [ext3] Error 1
```

**Comment by jeromekelleher** [comment]
This is a gotcha that's probably going to hit a few people, so thanks for opening the issue. It's because of the missing git submodule. Run: 
```
$ git submodule update --init --recursive
```
If it's all setup properly you should see
```
$ git submodule status --recursive 
 bb5f4f4475c477374a85fc0deb66b65a0972a2a3 tskit (0.1.2)
 a6599e9d58332e5f46da4869b814babaaf86afc1 tskit/c/kastore (c_0.1.0)
```

See  the [developer docs](https://msprime.readthedocs.io/en/latest/development.html) for some more info.

**Comment by hyanwong** [comment]
Ah, thanks. I've just changed my makefile (for the ancestral-inference-testing repo shared with Simon et al) to  use `git clone --recurse-submodules`.

**Comment by hyanwong** [comment]
A more informative error message might help here - not sue how easy that is using `make`.

**Comment by jeromekelleher** [comment]
> Ah, thanks. I've just changed my makefile (for the ancestral-inference-testing repo shared with Simon et al) to use git clone --recurse-submodules.

This should be using a released version of msprime --- there's no reason to track git (and no guarantee at all that the head of git doesn't contain bugs).

> A more informative error message might help here - not sure how easy that is using make.

There's not much we can do about that. But, it's only developers who'll see it so I think it's fine.
