### ISSUE TITLE
Latent trees in the SMC' model 

### ISSUE THREAD

**Issue by ismael2395** [tskit-dev/msprime#691]
Hello, 

I was testing the SMC' model and I found some disagreement with what I was expecting, but it might be that I'm understanding the output of `msprime`. Under the SMC' model I think it's possible that when a recombination event occurs the genealogy before the recombination and after are exactly the same (invisible transition). I was running the following code: 
```
tree_sequence = msprime.simulate(sample_size=5, Ne=1, 
                                 length=1, recombination_rate=450, model='smc_prime', random_seed = 1)

#are there any latent? 
prev_times = None 
for i,tree in enumerate(tree_sequence.trees()):
    times = [] 
    for node in tree.nodes(): 
        times.append(tree.time(node))
    times.sort() 
    if times == prev_times: 
        print('latent! \n')
    prev_times = times 
```

but I do not get any invisible transitions (all coalescent times exactly the same). Could it be that `msprime` reports recombination events only if the tree changes? Is there a way to report all recombination events in that case? Thanks in advance!

**Comment by jeromekelleher** [comment]
This is a difference between ms and msprime. In msprime we always squash together any identical adjacent trees, as this is nearly always what you want to happen. The only time you don't want this to happen is when you're counting recombination events, in which case you'll get significantly fewer events that expected (this is a problem in the full coalescent as well as the SMC).

To get the correct count of recombination events you have to use an undocumented API, unfortunately:
```python
rng = msprime.RandomGenerator(random_seed)
sim = msprime.simulator_factory(10, random_generator=rng, # other args as usual)
sim.run()
print("recomb events = ", sim.num_recombination_events)
print("Common ancesto events = ", sim.num_common_ancestor_events)
tree_sequence = sim.get_tree_sequence() # If you need to get the tree sequence
```

This is a bit awkward, but is the API I've used for verifying that the numbers of recombination events we get match between simulators and fit Hudson's formulae.

Another option is the to use the 'full ARG' code that's currently [in development](https://github.com/tskit-dev/msprime/pull/665). This will contain all recombination events and will not squash together identical trees (indeed, will contain nodes corresponding to the recombination events themselves).

Does this help?

**Comment by ismael2395** [comment]
Thanks for your response @jeromekelleher ! This is helpful. 

It would be nice for my application to get all the recombination events and not squash together identical trees, is there a way to obtain this already with the code that is in development or should I wait for the release?  Thanks again!

**Comment by jeromekelleher** [comment]
> It would be nice for my application to also get all the recombination events and not squash together identical trees, is there a way to obtain this already with the code that is in development or should I wait for the merge? Thanks again!

Best to wait for the merge I think. I'll try and get it done in the next couple of days.

**Comment by ismael2395** [comment]
Thanks @jeromekelleher!  I will wait for the merge then

**Comment by jeromekelleher** [comment]
OK, the PR has been merged. Would you mind trying out the ``record_full_arg`` option please @ismael2395? If it does what you need, please close this issue.

**Comment by ismael2395** [comment]
Thanks @jeromekelleher !  This is perfect!
