### ISSUE TITLE
Add migration events to full ARG recording

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#692]
#665 added the ability to record all recombination and common ancestor events via the ``record_full_arg`` option. We should also be able to do this for migration events (already implemented in ``algorithms.py`` prototype).

We should implement this fully and test to make sure that the output agrees with the migration records that we also optionally store (the tricky bit).

@JereKoskela, is this something you'd be interested in taking on?

**Comment by JereKoskela** [comment]
I'd be happy to take this on, but need to clear something up: The same functionality as that in the `algorithms.py` prototype is already in `msp_move_individual` in the likelihood_evaluation branch (lines 1082 - 1091 of `msprime.c`). Do you just mean taking on the additional testing, or is there something more to implement that I've missed?

**Comment by jeromekelleher** [comment]
Yeah, the implementation is trivial, it's just a case of testing to make sure it interacts with ``store_migrations`` correctly and documenting the relationship between the two. This would be done [here](https://github.com/tskit-dev/msprime/blob/master/tests/test_demography.py#L939)

**Comment by JereKoskela** [comment]
Ok, I've written a test into the `TestMigrationRecords` class, and spotted two minor issues with the `store_full_arg` implementation while I was at it. I'll start a PR so you can have a look @jeromekelleher.

**Comment by jeromekelleher** [comment]
Close in #699.
