### ISSUE TITLE
0.6.2 conda-forge linux package broken:  undefined symbol: cblas_dasum 

### ISSUE THREAD

**Issue by alimanfoo** [tskit-dev/msprime#694]
Installing 0.6.2 from conda-forge on linux, then importing msprime, I get:

```
>>> import msprime
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aliman/github/malariagen/vector-ops/binder/deps/conda/envs/vector-ops/lib/python3.6/site-packages/msprime/__init__.py", line 26, in <module>
    from _msprime import FORWARD  # NOQA
ImportError: /home/aliman/github/malariagen/vector-ops/binder/deps/conda/envs/vector-ops/lib/python3.6/site-packages/../../libgsl.so.23: undefined symbol: cblas_dasum
```

Here's exactly what's installed:

```
$ conda list | grep msprime
msprime                   0.6.2            py36hf3f1cc3_0    conda-forge
```

**Comment by alimanfoo** [comment]
Also applies to 0.6.1. Guessing it's something to do with recent compiler migration.

**Comment by jeromekelleher** [comment]
Our of interest, have you updated your conda envs to the new gcc7 infrastructure? I'm guessing you're seeing it on CI, so it should all be fine..

**Comment by alimanfoo** [comment]
> Thanks @alimanfoo, but, **sigh**, this again. GSL and BLAS has been a consistent headache in conda-forge for the past six months. In this [issue](https://github.com/conda-forge/gsl-feedstock/issues/34) we had problems with OSX and [here](https://github.com/tskit-dev/msprime/issues/629) for problems other have had with msprime on Linux.

Oof. 

> There's two solutions:
> 
> 1. Use conda to install openblas. This should fix up the missing symbols on GSL.

I thought it was already installed (via numpy). E.g., extract of `conda list`:

```
blas                      1.0                    openblas  
libopenblas               0.3.3                h5a2b251_3  
gsl                       2.4                  h14c3975_4  
```

Are there some openblas/gsl packages I should be specifically installing?

> 2. Install GSL from apt if you're on linux and install msprime using pip. This is probably the more dependable solution, I'm afraid.

Thanks, yep this definitely works on linux. I need to support some mac users though.

> Our of interest, have you updated your conda envs to the new gcc7 infrastructure? I'm guessing you're seeing it on CI, so it should all be fine..

Yes seeing it on CI on a completely fresh conda installation. Just reinstalled locally from scratch too and get the same.

**Comment by jeromekelleher** [comment]
Hmmm, this is a bit different then. Thanks @alimanfoo, looking into it now.

**Comment by jeromekelleher** [comment]
Closing in favour of https://github.com/conda-forge/msprime-feedstock/issues/20
