### ISSUE TITLE
Squash deprecation warning for python 3.8

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime#695]
I guess the warning below is trivial to correct:

`/usr/local/lib/python3.7/site-packages/msprime/simulations.py:590: 
    DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working`

**Comment by jeromekelleher** [comment]
Not obvious to me what's triggering the warning here. Can you take a look at the line of code involved please?

**Comment by jeromekelleher** [comment]
OK, easy fix other than dealing with Python 2. Might be better to remove the check entirely, probably doesn't help all that much.
