### ISSUE TITLE
main.c moved?

### ISSUE THREAD

**Issue by andrewkern** [tskit-dev/msprime#708]
working my way through the developer documentation and I've hit a snag-- according to the RTD info I'm supposed to run `make` in the `lib` directory. Looking at that `Makefile` and the rest of the documentation, it looks like there should be a file called `main.c` that will compile down for use as the development CLI. `main.c` seems to be missing from `lib` now however.... any help? tagging @petrelharp if he comes up for air this afternoon

**Comment by jeromekelleher** [comment]
This has changed all right, but  the documentation should be updated [here](https://msprime.readthedocs.io/en/latest/development.html#c-library). Perhaps you're looking at the ``stable`` version of the documentation rather than ``latest``?

**Comment by andrewkern** [comment]
yup I was looking at `stable` and not `latest`. Working my way through the `latest` for a clean build and am running in to another problem with `meson`. In particular the docs say to initialize the build dir with `meson build` but I am now getting the following error:

```
$ meson build

ERROR: Neither directory contains a build file meson.build.
```

mind you I'm trying to do this on a mac laptop so I can code on a flight, so that might explain _some_ of this weirdness, but this issue seems straight forward, no?

**Comment by jeromekelleher** [comment]
Are you in the lib directory?

**Comment by andrewkern** [comment]
ha. no. is there a simple enough way for me to edit to docs as I go? there wasn't a note to be in lib

**Comment by jeromekelleher** [comment]
Maybe edit the rst files on GitHub and make PRS from there? Look in docs, development.rst or something like that.
