### ISSUE TITLE
add genomic interval argument to mutate()

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/msprime#710]
It is useful to be able to mutate different regions of the genome at different rates. To allow this, we could either:

1. add a `left` and `right` parameter to `msprime.mutate()`, or
2. add something like a `MutationRateMap` class, with breakpoints and rates

I guess I'm leaning towards the second option.

This is maybe orthogonal to other efforts to better mutations in #553.

**Comment by jeromekelleher** [comment]
Sounds good @petrelharp, and I think there's a desire for this from the PopSim perspective as well. I think it's orthogonal to #553.

I think we should do the ``MutationMap`` option, parameterised in the same way as the ``RecombinationMap``. I can see two ways of implementing it for infinite sites mutations:

1. Create an AVL tree of the breakpoints mapping to mutation rates. Then, for each edge, find the correct rate for the left hand side and then iterate over the map as needed. Easy to do, and O(num edges * log(size of mutation map). In practise, probably quite fast unless there's very large maps.
2. Use the table collection indexes to iterate of the edges from left-to-right, keeping track of the position in the mutation rate map. A bit more complex to do (probably using something like the [overlapping_segments](https://github.com/tskit-dev/tskit/blob/master/python/tests/simplify.py#L37) iterator), but very efficient.

**Comment by petrelharp** [comment]
Sounds good about the `MutationMap`.  In (2) wouldn't we still need to do something like the AVL tree, because we'd still have to apply different rates along the edge? I think (1) sounds better. 

On second thought, it's *not* totally orthogonal to #553, because we might need to put down the mutations in order by time, not by left end of the edge.

**Comment by jeromekelleher** [comment]
> Sounds good about the MutationMap. In (2) wouldn't we still need to do something like the AVL tree, because we'd still have to apply different rates along the edge? I think (1) sounds better.

Probably (1) is simpler and would be efficient enough in all but the cases where we have a large mutation map and a lot of long edges (so, the large sample size case). Having to iterate over the whole map hundreds of thousands of times would add up though. In (2) we're co-iterating over the map and edges, so it would have to be more efficient.

> On second thought, it's not totally orthogonal to #553, because we might need to put down the mutations in order by time, not by left end of the edge.

I think we'd probably end up with a different code path for doing non-infinite sites mutations anyway, so we'd probably just do that on the mutation map from the start if/when we get around to it.

**Comment by petrelharp** [comment]
also ping @carjed who just volunteered to do this! <3 <3
