### ISSUE TITLE
nothing happens in terminal zero-recomb segments

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/msprime#715]
It looks like if the last segments of chromosome have zero recombination rate, then the chromosome *functionally* acts as if it ended before those segments, although the `sequence_length` attribute is still correct.

Here is a MWE (modified from @jradrion's in #704):
```
import msprime
recomb_map = msprime.RecombinationMap(positions = [0, 100, 200, 300], 
             rates = [0.01, 0.00, 0.0, 0.0])

ts=msprime.simulate(
        sample_size=50,
        Ne=100,
        mutation_rate=0.01,
        recombination_map=recomb_map)

print("Recombination_map.get_positions():", recomb_map.get_positions())
print("Sequence length:", ts.sequence_length)
print("Rightmost edge end:", max(ts.tables.edges.right))
print("Rightmost SNP:", ts.site(ts.num_sites - 1).position)
```
Even though `sequence_length` is (correctly) 300, the end of the rightmost edge and the position of the rightmost SNP are both 100.

And, I think I know what the problem is.
1. There aren't any mutations on the righthand end because no edges extend that far, and mutations are added to the edges.
2. The edges don't actually extend to the end because (I'm guessing) when we map physical position -> discrete genetic map -> back to physical positions it's taking the end of the chromosome (300) to 100.

Indeed, that's what it's doing:
```
>>> recomb_map.genetic_to_physical(recomb_map.physical_to_genetic(300))
100.0
```

**Comment by petrelharp** [comment]
This happens in general, that any point in a zero recombination region gets mapped to the left-hand end of that region by physical -> genetic -> physical, even points on the right-hand end of that region:
```
recomb_map = msprime.RecombinationMap(positions = [0, 100, 200, 300, 400], 
                  \rates = [0.01, 0.0, 0.1, 0.0, 0.0])
[(u, recomb_map.genetic_to_physical(recomb_map.physical_to_genetic(u))) 
         for u in [0.0, 99, 100, 199, 200, 299, 300, 399, 400]]

# [(0.0, 0.0), (99, 99.0), (100, 100.0), (199, 100.0), (200, 100.0), (299, 299.0), (300, 300.0), (399, 300.0), (400, 300.0)]
```
In this example the region `[100,200]` has no recombination, so the point 200 gets mapped back to 100.

This basic fact is not a bug: you can't invert a piecewise constant function on the regions where it's flat: since `physical_to_genetic` takes the whole region `[100,200]` to a single point in genetic space, when we invert that map we've got to pick a single point in that region to map it back to; we've chosen the left end point. And, this is the right answer, for every case except this one, when there's a zero-recombination region at the end of the chromosome.

But, this is clearly a bug, unless we want to exclude the possibility of zero-recombination bits on the ends of chromosomes. I guess that somewhere just needs a check for this?  I'm surprised this hasn't come up yet? @jeromekelleher did you think about this at some point?

**Comment by jeromekelleher** [comment]
> But, this is clearly a bug, unless we want to exclude the possibility of zero-recombination bits on the ends of chromosomes. I guess that somewhere just needs a check for this? I'm surprised this hasn't come up yet? @jeromekelleher did you think about this at some point?

I agree with everything you're saying @petrelharp, and no, I didn't think of this (or at least if I did, I've forgotten about it). I guess the answer is special-casing the last interval? I don't like the idea of forcing a nonzero last (real) rate, this seems like it will cause problems for people.
