### ISSUE TITLE
Recombination events that do not create trees in SMC' model 

### ISSUE THREAD

**Issue by ismael2395** [tskit-dev/msprime#717]
Hi! 

I had a question about a type of recombination event that I see sometimes when I simulate the `smc_prime` model like: 

```
ts = msprime.simulate(sample_size=3, Ne=1, length=1, recombination_rate=1, 
                      model='smc_prime', random_seed= 14034, record_full_arg=True)
```

which produces the node table: 

```
id	flags	population	individual	time	metadata
0	1	0	-1	0.00000000000000	
1	1	0	-1	0.00000000000000	
2	1	0	-1	0.00000000000000	
3	131072	0	-1	0.00568042553659	
4	131072	0	-1	0.00568042553659	
5	131072	0	-1	0.30858780379419	
6	131072	0	-1	0.30858780379419	
7	0	0	-1	0.41635693895254	
8	0	0	-1	0.56402443996819	
9	131072	0	-1	0.61740892100997	
10	131072	0	-1	0.61740892100997	
11	0	0	-1	0.89128387287791	
12	0	0	-1	0.95193112819696	
```

but only 3 trees: 

<img width="141" alt="image" src="https://user-images.githubusercontent.com/11745764/53705649-deb3c900-3dda-11e9-8229-553dd06f0e87.png">

This means that one of the three recombination events shown in the table does not create a new tree. Could you help me understand what type of recombination event is this in the ARG? (my hypothesis is that this is a recombination event that coalesces with non-ancestral material?) and do you think this should be allowed in the `smc_prime` model? Thank you in advance!

**Comment by petrelharp** [comment]
How can you tell from the node table there were three recombination events?
Did you mean to include the edge table?

**Comment by ismael2395** [comment]
Oh, at least how I understand it now, the flag 131072 indicates a node where a recombination happened so for any recombination we get two nodes with the flag 131072 that have the same time (one node for each tree produced in the recombination). But this simulation makes me think that sometimes a new tree is not produced when a new recombination happens and I'm trying to understand what this looks like in the ARG.

**Comment by jeromekelleher** [comment]
> How can you tell from the node table there were three recombination events?

This is the new [record_full_arg](https://msprime.readthedocs.io/en/latest/tutorial.html#recording-the-full-arg) feature @petrelharp, which records all ARG events using extra nodes and gives the type of these nodes using flags.

**Comment by jeromekelleher** [comment]
I'm not quite sure what happened here @ismael2395; can you paste in the edge table as well please? (I tried rerunning your simulation, but I get a different output for that seed. I guess you're on a mac?)

**Comment by ismael2395** [comment]
yes that's right I am on a mac, here is the edge table: 

<img width="514" alt="image" src="https://user-images.githubusercontent.com/11745764/53747421-13b23100-3e58-11e9-917a-9fe62d366d68.png">

**Comment by jeromekelleher** [comment]
It looks to me like the recombination event for nodes 9 and 10 fell in non-ancestral material, and then a common ancestor event joined them back up again. I'm finding it difficult to get my head around it without being able to reproduce it locally though. Would you mind pasting in the text representation of the nodes and edges here so that I can create the tree sequence myself please @ismael2395?

**Comment by ismael2395** [comment]
Thanks @jeromekelleher I can do that, do you mean something like `str(ts.tables.nodes` and `str(ts.tables.edges)` ? 

nodes: 
```
id\tflags\tpopulation\tindividual\ttime\tmetadata\n0\t1\t0\t-1\t0.00000000000000\t\n1\t1\t0\t-1\t0.00000000000000\t\n2\t1\t0\t-1\t0.00000000000000\t\n3\t131072\t0\t-1\t0.00568042553659\t\n4\t131072\t0\t-1\t0.00568042553659\t\n5\t131072\t0\t-1\t0.30858780379419\t\n6\t131072\t0\t-1\t0.30858780379419\t\n7\t0\t0\t-1\t0.41635693895254\t\n8\t0\t0\t-1\t0.56402443996819\t\n9\t131072\t0\t-1\t0.61740892100997\t\n10\t131072\t0\t-1\t0.61740892100997\t\n11\t0\t0\t-1\t0.89128387287791\t\n12\t0\t0\t-1\t0.95193112819696\t
```

edges: 
```
'id\tleft\t\tright\t\tparent\tchild\n0\t0.00000000\t0.62321306\t3\t2\n1\t0.62321306\t1.00000000\t4\t2\n2\t0.00000000\t0.21106476\t5\t1\n3\t0.21106476\t1.00000000\t6\t1\n4\t0.00000000\t0.62321306\t7\t3\n5\t0.21106476\t1.00000000\t7\t6\n6\t0.00000000\t1.00000000\t8\t0\n7\t0.00000000\t1.00000000\t8\t7\n8\t0.00000000\t0.21106476\t9\t8\n9\t0.62321306\t1.00000000\t10\t8\n10\t0.00000000\t0.21106476\t11\t5\n11\t0.00000000\t0.21106476\t11\t9\n12\t0.62321306\t1.00000000\t12\t4\n13\t0.62321306\t1.00000000\t12\t10'
```

or how would you like me to produce the text representation?

**Comment by jeromekelleher** [comment]
Sorry, I wasn't clear here @ismael2395. I just want the edge table you've pasted in above as text rather than an image so that I can copy and paste it. Or, if you could email me the tree sequence file this would save a bit of time.

**Comment by ismael2395** [comment]
Ah I see. Thanks Jerome, here is the tree sequence file (created using `ts.dump`), are you able to access it? 
https://www.dropbox.com/s/zhgtdpy6y9f02xb/ts1?dl=0

I am also copying the edge table just in case: 

```
id	left		right		parent	child
0	0.00000000	0.62321306	3	2
1	0.62321306	1.00000000	4	2
2	0.00000000	0.21106476	5	1
3	0.21106476	1.00000000	6	1
4	0.00000000	0.62321306	7	3
5	0.21106476	1.00000000	7	6
6	0.00000000	1.00000000	8	0
7	0.00000000	1.00000000	8	7
8	0.00000000	0.21106476	9	8
9	0.62321306	1.00000000	10	8
10	0.00000000	0.21106476	11	5
11	0.00000000	0.21106476	11	9
12	0.62321306	1.00000000	12	4
13	0.62321306	1.00000000	12	10
```

**Comment by jeromekelleher** [comment]
OK, I've finally figured out what happened here @ismael2395. Basically, the middle tree coalesced quite a long time before the two outer trees. After this had coalesced a recombination even fell in this already-coalesced segment. The two flanking trees then coalesced independently in nodes 11 and 12. 

So yeah, you can't assume a 1-1 mapping between recombination events and the number of trees, even in the SMC.

**Comment by ismael2395** [comment]
Thanks so much @jeromekelleher  that makes sense.
