### ISSUE TITLE
Visualizing the full arg with msprime (feature request?) 

### ISSUE THREAD

**Issue by ismael2395** [tskit-dev/msprime#723]
Hello, 

Me and @airam-blancas were wondering if it was possible to visualize the full ARG (all at the same time) using `msprime`? From looking through the documentation we believe this is not possible at the moment. An example of what would be good to see is something like what appears in figure 1 of Marjoram and Wall (2006): 

<img width="578" alt="image" src="https://user-images.githubusercontent.com/11745764/54382992-550fc100-464e-11e9-8d3d-8b1271da6eac.png">

In that case, is this a feature that is planned for future versions of `msprime` or do you think this is a feature that would be helpful more broadly? Thanks in advance!

**Comment by jeromekelleher** [comment]
This isn't something that's on our radar I'm afraid @ismael2395. I'm not a huge fan of ARG visualisations in the first place (they never do anything other than confuse me more), so it's not something I'm going to spend time on, if I'm honest. I'm happy to provide pointers if someone else wants to code it up though.

**Comment by ismael2395** [comment]
Thanks Jerome for your quick response. I agree with your sentiment about ARG visualizations, so I will close down this issue for now ( I also don't have intentions of coding it up).
