### ISSUE TITLE
python-jsonschema-objects 0.3.5 has requirement jsonschema~=2.3, but you'll have jsonschema 3.0.1 which is incompatible.

### ISSUE THREAD

**Issue by andrewkern** [tskit-dev/msprime#725]
got this warning on a fresh install of msprime requirements. this was using python 3.7.2 and pip 19.0.3

**Comment by jeromekelleher** [comment]
Hmm, thanks @andrewkern. Looks like we might need to pin the version of jsonschema until the requirement is updated upstream (https://github.com/cwacek/python-jsonschema-objects/issues/154).

In the meantime, it looks like it's harmless for our purposes.

**Comment by jeromekelleher** [comment]
Should be fixed with the latest release of jsonschema-objects.
