### ISSUE TITLE
file format for saving replicates

### ISSUE THREAD

**Issue by agladstein** [tskit-dev/msprime#730]
I'm doing 100 replicates of 100kb sims (mu = 1.2e-8 and rho = 1e-8) and I'd like to save the 100 replicates to one file. Is there a way to do this using the .trees table format?

since I'm now doing smaller sims with mu = rho, I wanted to check again if the .trees format would be more efficient than numpy arrays.

**Comment by agladstein** [comment]
So, if I simulate 100 replicates of 100kb (mu = 1.2e-8 and rho = 1e-8), 100 times, and print each tree with `tree_sequence.simplify().dump()`, I get a directory of 770M. If I zip the .trees replicates, then it's 625M.
If I convert each replicate to a numpy array with `genotype_matrix()`, and then put each replicate in a numpy ndarray and print with `np.savez_compressed()`, I get a directory of 56M.

**Comment by andrewkern** [comment]
just gonna weigh in here quickly, i'm sure @jeromekelleher will have more insightful comments-- why store .trees files with mutations? those can be added later.

**Comment by agladstein** [comment]
That is a good question... I remember I talked about that with @jeromekelleher, but now I forget why we decided it was a better idea to add the mutations first...
Well, I'm doing multiple analyses on the same simulated dataset... so could I record a seed and use that seed to add on the mutations for each analysis?

Creating the trees takes the most time right? And adding the mutations will add a memory burden, but not computational time?

**Comment by andrewkern** [comment]
this is exactly what we have been doing. save tree sequences w/o mutations. then record a seed (or not) and add mutations on the fly. months ago @jgallowa07 did some benchmarking of the whole process. i forget how it shakes out exactly, but yes adding mutations to existing tree sequences is very fast.

**Comment by agladstein** [comment]
hmm... saving the .trees files without the mutations gives me a directory of size 673M, so still about 10x more disk space than just compressed numpy arrays.

**Comment by jeromekelleher** [comment]
The short answer is 'no' @agladstein, there's no way to save multiple replicates in one file. In principle we could, there just doesn't seem to be much point as you're not going to save any significant disc space by doing it.

The benefits of saving things as tree sequences don't kick in until you have quite a large sample size, so if numpy is smaller and does what you need then I'd just use numpy. (I'd consider using [zarr](https://zarr.readthedocs.io/en/stable/) though, it's excellent and lets you save metadata in there. If you want you can store your 100 replicates in the same zarr file).
