### ISSUE TITLE
store_full_arg incompatible with msp_move_individual

### ISSUE THREAD

**Issue by andrewkern** [tskit-dev/msprime#743]
sorry to raise a crappy, poorly explored issue, however it looks like `store_full_arg=1` creates a bug in `msp_move_individual`. the issue that i'm seeing is that the call to `msp_store_arg_edges` on line 1086 is returning a non-zero value. 

not sure why, haven't poked around at all, but wanted to note this issue before i forgot.

**Comment by jeromekelleher** [comment]
Probably we should just disallow ``record_full_arg`` on anything except the standard coalescent --- if anyone wants it they can open an issue requesting.

**Comment by jeromekelleher** [comment]
Closed in #738.
