### ISSUE TITLE
Trouble installing msprime

### ISSUE THREAD

**Issue by sackmana** [tskit-dev/msprime#746]
I have been attempting to install msprime on a mac, following the instructions in the msprime documentation. When trying to install with pip, I get the error:

  Could not fetch URL https://pypi.python.org/simple/msprime/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping

Any idea what I am doing wrong? 
Thanks,
Andrew Sackman

**Comment by jeromekelleher** [comment]
Looks like you need to upgrade pip (see [this issue](https://github.com/pypa/pip/issues/5236)). See also the stackoverflow thread [here](https://stackoverflow.com/questions/49748063/pip-install-fails-for-every-package-could-not-find-a-version-that-satisfies/49748494#49748494)
