### ISSUE TITLE
Bottlenecks in DTWF

### ISSUE THREAD

**Issue by DomNelson** [tskit-dev/msprime#747]
Running into time travel errors with bottlenecks in DTWF - looks like this was hidden by small pop sizes in the tests. Basically any event which calls `msp_merge_ancestors()` can potentially create a child node with the same time as the parent node (if called before parent selection) or a parent node with the same time as the child nodes (if called after).

Are bottleneck events strictly necessary in the DTWF, or would they be equivalent to population size changes? The simple bottleneck maybe couldn't be done this way, but they might have to be treated as a special case in Wright-Fisher sims and be done within the DTWF parent selection step. The only other thing I can think of at the moment is jiggling node times a bit, but I'm not sure that's a great solution.

**Comment by DomNelson** [comment]
Another thought, if simple bottlenecks are not urgently needed, is to wait until pedigrees are supported and outsource them to the pedigree-creation step

**Comment by DomNelson** [comment]
OK my mistake - these were never meant to be used outside of the Hudson model anyway. Fixed by a small tweak to the tests

**Comment by jeromekelleher** [comment]
I'm happy to rule out bottlenecks in the DTWF, but we do need to have some sort of sensible error message if we do (I'm going to get a lot of emails asking about Time Travel errors otherwise!). Any ideas?

**Comment by DomNelson** [comment]
Hah dang it I had even written one before I noticed there was already a `MSP_ERR_BAD_MODEL` thrown, but either I'm crazy or it was removed in the merge. Adding something now
