### ISSUE TITLE
Issues importing msprime in Python 2.7

### ISSUE THREAD

**Issue by sackmana** [tskit-dev/msprime#748]
I recently installed msprime with pip. When I import msprime in Python 2.7, I get the error message:

>>> import msprime
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "msprime/__init__.py", line 50, in <module>
    from msprime.simulations import *
  File "msprime/simulations.py", line 1316
    growth_rate_field_width=growth_rate_field_width), end=sep_str,
                                                         ^
Any idea what's going on? Thanks.

**Comment by jeromekelleher** [comment]
Msprime (and tskit) which it relies on are removing support for Python 2.7, following the lead of large projects like numpy etc. If you want to use msprime with Python 2.7 in the future, you are best off installing version 0.6.2, which should continue to work for the foreseeable future:
```
python -m pip install msprime==0.6.2
```
