### ISSUE TITLE
Demographic events in DTWF with non-integer times

### ISSUE THREAD

**Issue by DomNelson** [tskit-dev/msprime#750]
@jeromekelleher I don't think we can have DTWF demographic events at non-integer times without a bit more work, since the demographic events set the internal simulation time, and right now we're only set up to do one event per generation.

So if we have events at `time=0.5` and `time=0.6`, the first will take effect, followed by a generation of recombination and parent-chosing, and set the internal time to `0.5`, half a generation behind the 'true' simulation state. Similarly after the next event another full generation will have passed but simulation time will only show `0.6`.

```
if (self->next_demographic_event != NULL) {                
    if (self->next_demographic_event->time <= self->time) {
        ret = msp_apply_demographic_events(self);          
        if (ret != 0) {                                    
            goto out;                                      
        }                                                  
    }                                                      
}                                                          
free(node_trees);               
node_trees = NULL;              
                                
ret = msp_dtwf_generation(self);
if (ret != 0) {                 
    goto out;                   
}                               

```

If we want to allow non-integer times, we could have something like

```
while (self->next_demographic_event->time <= self->time) {
    ret = msp_apply_demographic_events(self);          
    if (ret != 0) {                                    
        goto out;                                      
    }
}
```
then maybe
```
self->time = ceil(self->time)
```
so that nodes at least will always have integer times. What do you think?

**Comment by jeromekelleher** [comment]
This sounds like a good plan. A quick comment giving the rationale for applying ``self->time = ceil(self->time)`` would be good though, as it's not immediately obvious why we'd do this.
