### ISSUE TITLE
pip install failure

### ISSUE THREAD

**Issue by luciansmith** [tskit-dev/msprime#755]
I'm attempting to install msprime on a shared machine with --user, but am getting errors.  

The relevant error seems to be:

_msprimemodule.c: In function ‘msprime_get_gsl_version’:
_msprimemodule.c:3967: error: ‘GSL_MAJOR_VERSION’ undeclared (first use in this function)
_msprimemodule.c:3967: error: (Each undeclared identifier is reported only once
_msprimemodule.c:3967: error: for each function it appears in.)
_msprimemodule.c:3967: error: ‘GSL_MINOR_VERSION’ undeclared (first use in this function)
error: command 'gcc' failed with exit status 1

Here's the full output, using --verbose:

-------------
[lpsmith@grid-head2 bin]$ ./pip install --user msprime --verbose
Created temporary directory: /tmp/pip-ephem-wheel-cache-6egz1w7k
Created temporary directory: /tmp/pip-req-tracker-01cjynza
Created requirements tracker '/tmp/pip-req-tracker-01cjynza'
Created temporary directory: /tmp/pip-install-mtc0m6up
Collecting msprime
  1 location(s) to search for versions of msprime:
  * https://pypi.org/simple/msprime/
  Getting page https://pypi.org/simple/msprime/
  Looking up "https://pypi.org/simple/msprime/" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/msprime/ HTTP/1.1" 304 0
  Analyzing links from page https://pypi.org/simple/msprime/
    Found link https://files.pythonhosted.org/packages/ec/83/c2f4df4a3c89ab2eaaffc5fbcfd57ec3583b1bde3e5847671a36c02a9935/msprime-0.1.0a2.tar.gz#sha256=28d6bdd1f2df00eac91b26dbf9373a9f151b455688b90d0bcdd6db838b2230cf (from https://pypi.org/simple/msprime/), version: 0.1.0a2
    Found link https://files.pythonhosted.org/packages/86/93/22e522ea96c70726759a3ab0fcc1603a719f029e4099429fd65231f5bd54/msprime-0.1.1a1.tar.gz#sha256=8f0c778de83e51380fef0f720d8f5e5094136517fd4fbe4e857ff05af57436e7 (from https://pypi.org/simple/msprime/), version: 0.1.1a1
    Found link https://files.pythonhosted.org/packages/a1/71/d9b9101513b0ff191f31b60e0fee63a02d609f3b9d7b9cba225fd93ef006/msprime-0.1.1a2.tar.gz#sha256=af592d8510789fcfe0e48b132fe720e48fcd552cfb828a909e13a1f0feb380d6 (from https://pypi.org/simple/msprime/), version: 0.1.1a2
    Found link https://files.pythonhosted.org/packages/5f/42/d4f619d0f59f9dc8ed4670543b4a6e4ae5a9a73ac0aa5fc12e102f696481/msprime-0.1.1a3.tar.gz#sha256=e16f5f0a05118b0f01648f1785228a033330a6aaa48e976460a890ac7c00fe08 (from https://pypi.org/simple/msprime/), version: 0.1.1a3
    Found link https://files.pythonhosted.org/packages/db/46/74c99f22fbbf07a8423f88ce23ba8fe6e4043359de88f26cad72585fd748/msprime-0.1.1a4.tar.gz#sha256=23b886a39d2a3d3bf3c746dfc0cf7691d2bf0acda055570a03d37d408ffcdf4e (from https://pypi.org/simple/msprime/), version: 0.1.1a4
    Found link https://files.pythonhosted.org/packages/ae/d4/f639d2744f9a6cc764247cccc50baf4f9e41405e671655db3f76b4ad81ca/msprime-0.1.1a5.tar.gz#sha256=e40cb1ebd989ef78e6204de2e1873eeed55adcf50bd0ccfe02a8a108ecab7be6 (from https://pypi.org/simple/msprime/), version: 0.1.1a5
    Found link https://files.pythonhosted.org/packages/69/42/5bfde8d65d8bebc8728480a32a1fc1157bd2e7d05635c8ca46c0c74a2848/msprime-0.1.1.tar.gz#sha256=a2107ba4c6d9940d8467572d5bc1c942c6c73b74cc68d185dfa506e1fc17abba (from https://pypi.org/simple/msprime/), version: 0.1.1
    Found link https://files.pythonhosted.org/packages/10/72/b40195d353017c28fd84903d3e6e8e3be8088339b8bb51185bb77d5cad60/msprime-0.1.2a2.tar.gz#sha256=9c8f9ae6ffa6f3deeabee8b9e6e8f2e6df69fa109f77adae1eeebef3e3e44fdf (from https://pypi.org/simple/msprime/), version: 0.1.2a2
    Found link https://files.pythonhosted.org/packages/c5/88/501104e353f42f8158280443b4827978211cc4647f63531cf29db5c3bc01/msprime-0.1.2.tar.gz#sha256=737ce0ef337fbf520873af320f707909d295d4c3a7c25479d66c53709bd9e583 (from https://pypi.org/simple/msprime/), version: 0.1.2
    Found link https://files.pythonhosted.org/packages/c3/e9/a042480b2861940f454410a095e040ffd8c7322e6c15bea3db8de478c546/msprime-0.1.3.tar.gz#sha256=56b221e6b98c35e0da82a941c9cbbeadf0e6082ac6cdbb5eefed51799f358ea6 (from https://pypi.org/simple/msprime/), version: 0.1.3
    Found link https://files.pythonhosted.org/packages/a7/35/f1a0eff4d7dd079c0b9e7a64a961db25a603c452ac1074c054a1a7dacd37/msprime-0.1.4.tar.gz#sha256=1dbb2b6915007a364112233e2bec93762b709e42225d5fab1cdd118a82afe758 (from https://pypi.org/simple/msprime/), version: 0.1.4
    Found link https://files.pythonhosted.org/packages/c9/0b/b8147b318e9ab84740bc76084791437b4a69969333d6fb713458974375ed/msprime-0.1.5a1.tar.gz#sha256=848e14eefcfd3a6d235d5ab35dbba7f41123782182627a7ee87ce7738bdfa9bd (from https://pypi.org/simple/msprime/), version: 0.1.5a1
    Found link https://files.pythonhosted.org/packages/41/c2/7848e88ec3937f949a8b04c72cb4dfe33129738ed4fc77996f49039d2789/msprime-0.1.5a2.tar.gz#sha256=b76c601b6d04b4471d7042639e8f391c63bb365dc84d9b64dde58b9cfbd76151 (from https://pypi.org/simple/msprime/), version: 0.1.5a2
    Found link https://files.pythonhosted.org/packages/f6/99/40a19bc08797c73ccdcb0768cbdc4eed2073dd5ea944a97435dc0d717086/msprime-0.1.5.tar.gz#sha256=82b33baf90c49a6716c120eeaba08ac4e728bc36948794bfbec2e3a2e609c0a4 (from https://pypi.org/simple/msprime/), version: 0.1.5
    Found link https://files.pythonhosted.org/packages/8c/b0/f8c92930dcc941a2f5287feb724c850ce13caf833fc146a519947e56e7a0/msprime-0.1.6a2.tar.gz#sha256=d7adfdfb6bba38832456015870f9aef6a43befbc7b56b7ab9c8e9be8e30a1504 (from https://pypi.org/simple/msprime/), version: 0.1.6a2
    Found link https://files.pythonhosted.org/packages/e3/6a/58ba1a0ebb98c9329327ed9caa10577c5a2a3380d1d5eb298f6f84b1a37e/msprime-0.1.6a3.tar.gz#sha256=137273055153825e0a4470ef310e34f06fa15e9699834f6216f6548c870fb975 (from https://pypi.org/simple/msprime/), version: 0.1.6a3
    Found link https://files.pythonhosted.org/packages/07/a5/fea8a2b7494accf9dff68e6e0bb89ef716a239764159083e48bc57a95ed6/msprime-0.1.6.tar.gz#sha256=c0aaf2e44c9fd3d17ee9e1bae0898f2b962c5ebe3b0e90d5057de9900dad7fa8 (from https://pypi.org/simple/msprime/), version: 0.1.6
    Found link https://files.pythonhosted.org/packages/fb/a2/456cec8e181dfd69beee02ca3c9f862bc574e7e346915ba378b5c6301e3c/msprime-0.1.7.tar.gz#sha256=51e4682b7df7ace636643a61c35ca5cef70eccb19c43664debf7164649cdbdc4 (from https://pypi.org/simple/msprime/), version: 0.1.7
    Found link https://files.pythonhosted.org/packages/69/11/cf35d8d0396f83102aae124b4f216c2f3fc0868f2fbd2caecd315a310713/msprime-0.1.8.tar.gz#sha256=00a1cbe65bb51f5c6ccb15439ad3d52f8ea16a05572289d02cbaf2e4c9073f33 (from https://pypi.org/simple/msprime/), version: 0.1.8
    Found link https://files.pythonhosted.org/packages/1a/ce/2444d7a5f1e69caaffcb1f37035480989565a46b93e3d7fda8bfb3b67b48/msprime-0.1.9.tar.gz#sha256=0bb97b2649687d4888f1571e1c3912f396d90941003b8f8f3833be7a21671dde (from https://pypi.org/simple/msprime/), version: 0.1.9
    Found link https://files.pythonhosted.org/packages/ff/7c/4e0a934bcb8578912dff9f0b19f7e250bb20470147bb5fd6101fc7ac874d/msprime-0.1.10.tar.gz#sha256=56e5c2adc0d8bbc4419d0561b11ceb832534ad0e06befbb0a97b5de4982a9efb (from https://pypi.org/simple/msprime/), version: 0.1.10
    Found link https://files.pythonhosted.org/packages/af/77/28348cb6aa6caa9a0550d141fc14c4795ebe7a714307cc258b79b2fb9615/msprime-0.2.0.tar.gz#sha256=9d98a8a767291541b6466abb6131b44c997d5eb9616c19058668f0fc55545dde (from https://pypi.org/simple/msprime/), version: 0.2.0
    Found link https://files.pythonhosted.org/packages/ef/99/a636d843e67c7d3b40902f8f1d12d1952555e56c25286cce71a1089e82b4/msprime-0.3.0.tar.gz#sha256=e359da26ecb86ebc07fec307cbeb4caf633b9d73848a93d94dc811c8709b7182 (from https://pypi.org/simple/msprime/), version: 0.3.0
    Found link https://files.pythonhosted.org/packages/83/ef/e00a8456d1467acef995f83095f99b6bfb3f93fa6af25bad4a6b163607bd/msprime-0.3.1.tar.gz#sha256=4f700e5d691c55365f0789f52700ed09032aec5a83fd4540134ba4fa067f5245 (from https://pypi.org/simple/msprime/), version: 0.3.1
    Found link https://files.pythonhosted.org/packages/8b/26/e0c2bdfab77d8d7113d9b2121f29d4da69eec213dbaf7de74dc8dfe5cf8c/msprime-0.3.2.tar.gz#sha256=cded9b26c56ec49111681c344560116a52066321da8354ad82158083cb617430 (from https://pypi.org/simple/msprime/), version: 0.3.2
    Found link https://files.pythonhosted.org/packages/db/65/7010c12c8594b6a36b7b6bb7f108cce17003b45d676aafb3f275c7cd598a/msprime-0.4.0.tar.gz#sha256=8c4fb6128ebf0c79da0b508a53fa89d300108fe52fe66529506d4f99e7c1e5ed (from https://pypi.org/simple/msprime/), version: 0.4.0
    Found link https://files.pythonhosted.org/packages/ad/6a/654eb0a9ea113ac313db7eaf603c8e8f81f09c682c7bdb2589d134844e58/msprime-0.5.0b1.tar.gz#sha256=09fbae95d61820797cfd8f1e27cc86ac358f8354f3995a6e50920d3ed8a76448 (from https://pypi.org/simple/msprime/), version: 0.5.0b1
    Found link https://files.pythonhosted.org/packages/16/37/57468f3b6e1c1c1617099959ef12115e3de920ad6d6e98105e41d083441c/msprime-0.5.0b2.tar.gz#sha256=5cf78da4c27669d3980d86861cbcdb67ee3ead56d94206e52bc7e0b208b276d9 (from https://pypi.org/simple/msprime/), version: 0.5.0b2
    Found link https://files.pythonhosted.org/packages/9c/cd/31c5eba41f9d3b934967f3a22ac468ff9e2697b90378f6d57cb0bc9a88b8/msprime-0.5.0.tar.gz#sha256=e1ad0392608f23a66f2192bd052d161fb507aaaa85af5ae4bdd50504ef9b4fa7 (from https://pypi.org/simple/msprime/), version: 0.5.0
    Found link https://files.pythonhosted.org/packages/54/da/923e8a59842f5352095f10273afadce50da857578331e5ad8aa5d4c0eb8c/msprime-0.6.0b1.tar.gz#sha256=ed3114654c881654ab9e97e59ace4f10e3da5c6a3608b8f1ccf0259e21242e83 (from https://pypi.org/simple/msprime/), version: 0.6.0b1
    Found link https://files.pythonhosted.org/packages/28/1f/f959f278ce5c49cc7dba699a99ee93f2a4e3589c1b2bc135cf47439be394/msprime-0.6.0b2.tar.gz#sha256=912ded0aa75d1460f83690d474675cd366355304c5924ed41c06c68f5afb4c57 (from https://pypi.org/simple/msprime/), version: 0.6.0b2
    Found link https://files.pythonhosted.org/packages/07/0f/4a35d2af6d9721bff2bbe7888509c06c2450328b22287e70b5f627f1940f/msprime-0.6.0.tar.gz#sha256=38037540d2ba90533110522bac3e8a4c8311cdd03310ec8d1aa7fa43a7e15874 (from https://pypi.org/simple/msprime/), version: 0.6.0
    Found link https://files.pythonhosted.org/packages/43/b3/194690d20f18613ea3b08bea3866464c049a9959c1762a21105db53ce195/msprime-0.6.1.tar.gz#sha256=974c7dac8e30436fab6f1e19d2e0767ff20626893c49bbcc8e0d087ea54b6e3a (from https://pypi.org/simple/msprime/), version: 0.6.1
    Found link https://files.pythonhosted.org/packages/d7/9a/8912404c12ae0b1e651cac80351b284ba0eddce2ebdf490ed82394e766a2/msprime-0.6.2.tar.gz#sha256=05914b4f6cfffd34076b013699f1d39e0fbe892f6f9a5b9831961b9639baadbf (from https://pypi.org/simple/msprime/), version: 0.6.2
    Found link https://files.pythonhosted.org/packages/ea/72/492a013741b7f92234f431d088339eb2e1c9eda176e6c2043e8e9440c277/msprime-0.7.0a1.tar.gz#sha256=85acb7a397b2e964ca841dc2807884880163489f82918b745fab047451b9c80f (from https://pypi.org/simple/msprime/), version: 0.7.0a1
    Found link https://files.pythonhosted.org/packages/51/bc/cd0d661ae86c36b1360c6863eecef7483561d37024e61c5d4b131b6c7a80/msprime-0.7.0.tar.gz#sha256=38d6849c164cd0ba23dad8fb2e18b84f177030b8658716df9bbaeb4d26981206 (from https://pypi.org/simple/msprime/), version: 0.7.0
  Using version 0.7.0 (newest of versions: 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.2.0, 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.7.0)
  Created temporary directory: /tmp/pip-unpack-2jto9yq4
  Looking up "https://files.pythonhosted.org/packages/51/bc/cd0d661ae86c36b1360c6863eecef7483561d37024e61c5d4b131b6c7a80/msprime-0.7.0.tar.gz" in the cache
  Current age based on date: 5228
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 5228
  Using cached https://files.pythonhosted.org/packages/51/bc/cd0d661ae86c36b1360c6863eecef7483561d37024e61c5d4b131b6c7a80/msprime-0.7.0.tar.gz
  Downloading from URL https://files.pythonhosted.org/packages/51/bc/cd0d661ae86c36b1360c6863eecef7483561d37024e61c5d4b131b6c7a80/msprime-0.7.0.tar.gz#sha256=38d6849c164cd0ba23dad8fb2e18b84f177030b8658716df9bbaeb4d26981206 (from https://pypi.org/simple/msprime/)
  Added msprime from https://files.pythonhosted.org/packages/51/bc/cd0d661ae86c36b1360c6863eecef7483561d37024e61c5d4b131b6c7a80/msprime-0.7.0.tar.gz#sha256=38d6849c164cd0ba23dad8fb2e18b84f177030b8658716df9bbaeb4d26981206 to build tracker '/tmp/pip-req-tracker-01cjynza'
    Running setup.py (path:/tmp/pip-install-mtc0m6up/msprime/setup.py) egg_info for package msprime
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/msprime.egg-info
    writing pip-egg-info/msprime.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/msprime.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/msprime.egg-info/entry_points.txt
    writing requirements to pip-egg-info/msprime.egg-info/requires.txt
    writing top-level names to pip-egg-info/msprime.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/msprime.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/msprime.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'README.txt'
    writing manifest file 'pip-egg-info/msprime.egg-info/SOURCES.txt'
  Source in /tmp/pip-install-mtc0m6up/msprime has version 0.7.0, which satisfies requirement msprime from https://files.pythonhosted.org/packages/51/bc/cd0d661ae86c36b1360c6863eecef7483561d37024e61c5d4b131b6c7a80/msprime-0.7.0.tar.gz#sha256=38d6849c164cd0ba23dad8fb2e18b84f177030b8658716df9bbaeb4d26981206
  Removed msprime from https://files.pythonhosted.org/packages/51/bc/cd0d661ae86c36b1360c6863eecef7483561d37024e61c5d4b131b6c7a80/msprime-0.7.0.tar.gz#sha256=38d6849c164cd0ba23dad8fb2e18b84f177030b8658716df9bbaeb4d26981206 from build tracker '/tmp/pip-req-tracker-01cjynza'
Requirement already satisfied: numpy>=1.7 in /net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/lib/python3.6/site-packages (from msprime) (1.16.2)
Requirement already satisfied: tskit in /net/gs/vol1/home/lpsmith/.local/lib/python3.6/site-packages (from msprime) (0.1.5)
Requirement already satisfied: jsonschema in /net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/lib/python3.6/site-packages (from tskit->msprime) (3.0.1)
Requirement already satisfied: svgwrite in /net/gs/vol1/home/lpsmith/.local/lib/python3.6/site-packages (from tskit->msprime) (1.2.1)
Requirement already satisfied: h5py in /net/gs/vol1/home/lpsmith/.local/lib/python3.6/site-packages (from tskit->msprime) (2.9.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/lib/python3.6/site-packages (from jsonschema->tskit->msprime) (0.14.11)
Requirement already satisfied: six>=1.11.0 in /net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/lib/python3.6/site-packages (from jsonschema->tskit->msprime) (1.12.0)
Requirement already satisfied: attrs>=17.4.0 in /net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/lib/python3.6/site-packages (from jsonschema->tskit->msprime) (19.1.0)
Requirement already satisfied: setuptools in /net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/lib/python3.6/site-packages (from jsonschema->tskit->msprime) (40.8.0)
Requirement already satisfied: pyparsing>=2.0.1 in /net/gs/vol1/home/lpsmith/.local/lib/python3.6/site-packages (from svgwrite->tskit->msprime) (2.4.0)
Building wheels for collected packages: msprime
  Created temporary directory: /tmp/pip-wheel-95ljogm4
  Building wheel for msprime (setup.py) ...   Destination directory: /tmp/pip-wheel-95ljogm4
  Running command /net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-mtc0m6up/msprime/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-95ljogm4 --python-tag cp36
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/msprime
  copying msprime/exceptions.py -> build/lib.linux-x86_64-3.6/msprime
  copying msprime/provenance.py -> build/lib.linux-x86_64-3.6/msprime
  copying msprime/_version.py -> build/lib.linux-x86_64-3.6/msprime
  copying msprime/cli.py -> build/lib.linux-x86_64-3.6/msprime
  copying msprime/__init__.py -> build/lib.linux-x86_64-3.6/msprime
  copying msprime/mutations.py -> build/lib.linux-x86_64-3.6/msprime
  copying msprime/simulations.py -> build/lib.linux-x86_64-3.6/msprime
  running egg_info
  writing msprime.egg-info/PKG-INFO
  writing dependency_links to msprime.egg-info/dependency_links.txt
  writing entry points to msprime.egg-info/entry_points.txt
  writing requirements to msprime.egg-info/requires.txt
  writing top-level names to msprime.egg-info/top_level.txt
  reading manifest file 'msprime.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'README.txt'
  writing manifest file 'msprime.egg-info/SOURCES.txt'
  running build_ext
  building '_msprime' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/lib
  creating build/temp.linux-x86_64-3.6/lib/subprojects
  creating build/temp.linux-x86_64-3.6/lib/subprojects/tskit
  creating build/temp.linux-x86_64-3.6/lib/subprojects/tskit/tskit
  creating build/temp.linux-x86_64-3.6/lib/subprojects/kastore
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/include/python3.6m -I/net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/include/ -fPIC -UNDEBUG -Ilib -Ilib/subprojects/tskit -Ilib/subprojects/tskit/tskit -Ilib/subprojects/kastore -I/usr/include -I/net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/include/python3.6m -I/net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/lib/python3.6/site-packages/numpy/core/include -c _msprimemodule.c -o build/temp.linux-x86_64-3.6/_msprimemodule.o -std=c99
  _msprimemodule.c: In function ‘table_read_offset_array’:
  _msprimemodule.c:372: warning: comparison between signed and unsigned integer expressions
  _msprimemodule.c: In function ‘msprime_get_gsl_version’:
  _msprimemodule.c:3967: error: ‘GSL_MAJOR_VERSION’ undeclared (first use in this function)
  _msprimemodule.c:3967: error: (Each undeclared identifier is reported only once
  _msprimemodule.c:3967: error: for each function it appears in.)
  _msprimemodule.c:3967: error: ‘GSL_MINOR_VERSION’ undeclared (first use in this function)
  error: command 'gcc' failed with exit status 1
error
  Failed building wheel for msprime
  Running setup.py clean for msprime
  Running command /net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-mtc0m6up/msprime/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all
  running clean
  removing 'build/temp.linux-x86_64-3.6' (and everything under it)
  removing 'build/lib.linux-x86_64-3.6' (and everything under it)
  'build/bdist.linux-x86_64' does not exist -- can't clean it
  'build/scripts-3.6' does not exist -- can't clean it
  removing 'build'
Failed to build msprime
Installing collected packages: msprime
  Created temporary directory: /tmp/pip-record-gfvp39r7
  Running setup.py install for msprime ...     Running command /net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-mtc0m6up/msprime/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-gfvp39r7/install-record.txt --single-version-externally-managed --compile --user --prefix=
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/msprime
    copying msprime/exceptions.py -> build/lib.linux-x86_64-3.6/msprime
    copying msprime/provenance.py -> build/lib.linux-x86_64-3.6/msprime
    copying msprime/_version.py -> build/lib.linux-x86_64-3.6/msprime
    copying msprime/cli.py -> build/lib.linux-x86_64-3.6/msprime
    copying msprime/__init__.py -> build/lib.linux-x86_64-3.6/msprime
    copying msprime/mutations.py -> build/lib.linux-x86_64-3.6/msprime
    copying msprime/simulations.py -> build/lib.linux-x86_64-3.6/msprime
    running egg_info
    writing msprime.egg-info/PKG-INFO
    writing dependency_links to msprime.egg-info/dependency_links.txt
    writing entry points to msprime.egg-info/entry_points.txt
    writing requirements to msprime.egg-info/requires.txt
    writing top-level names to msprime.egg-info/top_level.txt
    reading manifest file 'msprime.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'README.txt'
    writing manifest file 'msprime.egg-info/SOURCES.txt'
    running build_ext
    building '_msprime' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/lib
    creating build/temp.linux-x86_64-3.6/lib/subprojects
    creating build/temp.linux-x86_64-3.6/lib/subprojects/tskit
    creating build/temp.linux-x86_64-3.6/lib/subprojects/tskit/tskit
    creating build/temp.linux-x86_64-3.6/lib/subprojects/kastore
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/include/python3.6m -I/net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/include/ -fPIC -UNDEBUG -Ilib -Ilib/subprojects/tskit -Ilib/subprojects/tskit/tskit -Ilib/subprojects/kastore -I/usr/include -I/net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/include/python3.6m -I/net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/lib/python3.6/site-packages/numpy/core/include -c _msprimemodule.c -o build/temp.linux-x86_64-3.6/_msprimemodule.o -std=c99
    _msprimemodule.c: In function ‘table_read_offset_array’:
    _msprimemodule.c:372: warning: comparison between signed and unsigned integer expressions
    _msprimemodule.c: In function ‘msprime_get_gsl_version’:
    _msprimemodule.c:3967: error: ‘GSL_MAJOR_VERSION’ undeclared (first use in this function)
    _msprimemodule.c:3967: error: (Each undeclared identifier is reported only once
    _msprimemodule.c:3967: error: for each function it appears in.)
    _msprimemodule.c:3967: error: ‘GSL_MINOR_VERSION’ undeclared (first use in this function)
    error: command 'gcc' failed with exit status 1
error
Cleaning up...
  Removing source in /tmp/pip-install-mtc0m6up/msprime
Removed build tracker '/tmp/pip-req-tracker-01cjynza'
Command "/net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-mtc0m6up/msprime/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-gfvp39r7/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-mtc0m6up/msprime/
Exception information:
Traceback (most recent call last):
  File "/net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 393, in run
    use_user_site=options.use_user_site,
  File "/net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 57, in install_given_reqs
    **kwargs
  File "/net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 945, in install
    spinner=spinner,
  File "/net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 761, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/net/gs/vol3/software/modules-sw/python/3.6.4/Linux/RHEL6/x86_64/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-mtc0m6up/msprime/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-gfvp39r7/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-mtc0m6up/msprime/
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
-------------

(I have indeed installed pip 19.1.1 locally, but running that version doesn't actually use the locally installed libraries, for some reason.  It doesn't seem like this is the issue, however.)

**Comment by jeromekelleher** [comment]
It looks like the compiler can't find the GSL libraries. It looks like this is being built in a shared environment with lots of packages, so you'll probably need to set some compiler flags when calling pip to do this. See the example [here](https://msprime.readthedocs.io/en/latest/installation.html#freebsd-10-0) for doing something similar using CFLAGS and LDFLAGS.

If installing GSL using system packages is an option, then ``yum install gsl-devel`` should do the trick.

**Comment by luciansmith** [comment]
Installing the GSL module (in this environment, everything is module-driven) did the trick!  It might be nice if pip could tell the user 'hey, you need GSL' first, but I'll go ahead and close the issue.

(Also, 'pip install --user gsl' did not work.)
