### ISSUE TITLE
Clear up confusion about Ne

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#766]
An early version of #754 had some documentation trying to clear up what Ne means for the various models, and how it interacts with the individual population sizes. This [thread](https://github.com/tskit-dev/msprime/pull/754#discussion_r287438943) shows a basic disagreement.

**Comment by molpopgen** [comment]
I was just wrestling with this bit of the docs for that thing I'm writing. Happy to help rework the docs--ping me if you want input.

**Comment by jeromekelleher** [comment]
That would be very helpful, thanks @molpopgen.

**Comment by jeromekelleher** [comment]
Pushing this back to the next milestone, as we want to get a bugfix release out now ASAP.
