### ISSUE TITLE
DTWF statistical tests falling over

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#767]
Many of the statistical tests for the DTWF are falling over with exceptions being thrown - I had to put in a try/except into get them to run. @DomNelson, can you go through these please and delete any tests you think aren't relevant, and fix any that you think are?

**Comment by DomNelson** [comment]
Yikes, ok I'll try to find out what's happening. I've been running them myself and only seeing problems with the random tests, which I've been trying to fix.

**Comment by jeromekelleher** [comment]
OK, thanks. I'm cutting a beta release of the code now so that people can start using it, and we can push out the full 0.7.1 release once we've ironed out the details in the stats tests (next week, I guess?).

They're taking a *long* time to run now - could you add an option to the CLI where we say ``--extended`` or something when we want to run all the tests, but by default just run a representative sample of them?

**Comment by DomNelson** [comment]
Ya you're right they're unreasonably long to run now. I'll see which might be useful to keep as part of an extended set of tests, and will probably just remove some that aren't adding much value at the moment - a few checks vs. SLiM for example which we know don't fit because of haploid/diploid model differences.

**Comment by jeromekelleher** [comment]
Great, thanks. Just released the beta btw: hooray, nearly there!

**Comment by DomNelson** [comment]
Woohoo!!

**Comment by DomNelson** [comment]
I've had trouble replicating these failures - can you give a bit more info? I did see errors about `population_size` not being specified, but that was fixed by a fresh build. I'll get the other changes into a PR.

**Comment by jeromekelleher** [comment]
I added in a ``try: except`` around the runner so that other tests would run. You'll see some errors in the output where tests have fallen over.

**Comment by DomNelson** [comment]
Ok I did see a few zero pop size errors - if those were the issue they're addressed by PR #769

**Comment by jeromekelleher** [comment]
Looks like these are sorted in #769 all right, will close once it's merged.
