### ISSUE TITLE
Assertion `self->next_demographic_event->time == self->time' failed when running DTWF with non-integer time

### ISSUE THREAD

**Issue by mkanai** [tskit-dev/msprime#778]
Hi, thank you all so much for providing a novel implementation of DTWF.

I was running [this script](https://github.com/DomNelson/ancestry_pipeline/blob/master/simulate_prs.py) with `model = 'dtwf'` and encountered the following error. 

```
python: lib/msprime.c:2842: msp_run_dtwf: Assertion `self->next_demographic_event->time == self->time' failed.
Aborted (core dumped)
```

I think this is related to #750 but couldn't find any clues in [lib/msprime.c:2842](https://github.com/tskit-dev/msprime/blob/master/lib/msprime.c#L2842). Would you mind looking into this? Thanks!

**Comment by jeromekelleher** [comment]
Thanks for the report @mkanai. I just tried to run this script using Python 3.6, but it failed with a syntax error. What version of Python are you using? It's possible that you're using Python 2, in which case you're working with an older, unreleased version of the DTWF code (which probably has lots of bugs).

**Comment by mkanai** [comment]
Thanks so much @jeromekelleher for taking a look! I was trying to write [a minimum reproducible example](https://gist.github.com/mkanai/5001934013eff6de4e93e6038796027b), and indeed you are right -- my python environment was somehow messed up. `python test_dtwf.py` and `python -c 'import msprime; print(msprime.__version__)'` showed different msprime versions.

I re-configured my python environment and the issue is solved. Thanks again for your help!

**Comment by jeromekelleher** [comment]
No problem @mkanai, happy it worked out well!
