### ISSUE TITLE
admixture model in demographic history

### ISSUE THREAD

**Issue by panjha** [tskit-dev/msprime#780]
Hello I want to simulate the admixture model as the parameter file shown in given paper
( https://doi.org/10.1371/journal.pgen.1000695) table 2 and figure 3 for American population. I am able to generate the 4 population and the fourth population is splitting from Asian however i am not able to get the given admixture proportion in 4th population in my admixture run. I have a question how i provide the admixture in demographic events to get the admixture proportion in msprime. I am new to msprime so i tried similar way as example given in msprime for Out-of-Africa model. Thanks.

**The parameters used are given below:**
N_A = 7300
N_B = 2100
N_AF = 12300
N_EU0 = 1500
N_AS0 = 590
N_MX0 = 800
Times are provided in years, so we convert into generations.
generation_time = 25
T_AF = 220e3 / generation_time
T_B = 140e3 / generation_time
T_EU_AS = 26.4e3 / generation_time
T_MX = 21.6e3 / generation_time
We need to work out the starting (diploid) population sizes based on
the growth rates provided for these two populations
r_EU = 0.0023
r_AS = 0.0037
r_MX = 0.005
N_EU = N_EU0 / math.exp(-r_EU * T_EU_AS)
N_AS = N_AS0 / math.exp(-r_AS * T_EU_AS)
N_MX = N_MX0 / math.exp(-r_MX * T_EU_AS)
Migration rates during the various epochs.
m_AF_B = 25e-5
m_AF_EU = 3e-5
m_AF_AS = 1.9e-5
m_EU_AS = 13.5e-5
m_AS_MX = 1.7e-5
Population IDs correspond to their indexes in the population
configuration array. Therefore, we have 0=YRI, 1=CEU, 2=CHB and 3=MXL
initially.
p = [
	msprime.PopulationConfiguration(
		sample_size=100, initial_size=N_AF),
	msprime.PopulationConfiguration(
		sample_size=100, initial_size=N_EU, growth_rate=r_EU),
	msprime.PopulationConfiguration(
		sample_size=100, initial_size=N_AS, growth_rate=r_AS),
	msprime.PopulationConfiguration(
		sample_size=100, initial_size=N_MX, growth_rate=r_MX),
]
m = [
	[      0,	m_AF_EU,	m_AF_AS,	      0],
	[m_AF_EU,	      0,	m_EU_AS,	      0],
	[m_AF_AS,	m_EU_AS,	      0,	      0],
	[0,	              0,	      0,           0],
]
d = [
	# Admixture event for MXL with rate changes at T_MX
	msprime.MassMigration(
	    time=T_MX, source=3, destination=1, proportion=2.0/4.17),
	msprime.MassMigration(
	    time=T_MX, source=3, destination=2, proportion=1.0),
	# CEU and CHB merge into B with rate changes at T_EU_AS
	msprime.MassMigration(
	    time=T_EU_AS, source=2, destination=1, proportion=1.0),
	msprime.MigrationRateChange(time=T_EU_AS, rate=0),
	msprime.MigrationRateChange(
	    time=T_EU_AS, rate=m_AF_B, matrix_index=(0, 1)),
	msprime.MigrationRateChange(
	    time=T_EU_AS, rate=m_AF_B, matrix_index=(1, 0)),
	msprime.PopulationParametersChange(
	    time=T_EU_AS, initial_size=N_B, growth_rate=0, population_id=1),
	# Population B merges into YRI at T_B
	msprime.MassMigration(
	    time=T_B, source=1, destination=0, proportion=1.0),
	# Size changes to N_A at T_AF
	msprime.PopulationParametersChange(
	    time=T_AF, initial_size=N_A, population_id=0)
]

Output options used:
tree_sequence = msprime.simulate(length=10000000, recombination_rate=2e-8, mutation_rate=2e-8, population_configurations=p, migration_matrix=m, demographic_events=d)

**Comment by petrelharp** [comment]
Hello! Could you explain a bit more what the problem is? Thanks for
providing the code, but could you say (a) what happened when you ran it,
and (b) what you expected to happen (that was different from what actually
happened)?

**Comment by panjha** [comment]
As you can see in code, the demographic event i am trying to recapitulate is European admixture in MXL at time T_MX from source 1 (EUR) to source 3 (MXL) and the admixture proportion i defined is 2.0/4.17 (that will be nearly 48%). But when i generated a 10 mb of test data for this model. I used this simulated data to understand whether i got the admixture in source 3 population. For this I ran ADMIXTURE analysis but i was not able to find the admixture in source 3. Could please tell me what i am doing wrong or do i need to put some other parameter in the model. Thank you.

**Comment by jeromekelleher** [comment]
Thanks for using msprime @panjha, and welcome to the community! This issue tracker is for reporting bugs or requesting new features in msprime. If you'd like some help in setting up and debugging your demographic model, I'd suggest posting to the [msprime users mailing list](https://groups.google.com/forum/#!forum/msprime-users).
