### ISSUE TITLE
Very rarely, waiting time until coalesence = 0. What to do?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#783]
In very, very, very rare cases msprime can generate a zero waiting time until the next coalescent event, resulting in an error being thrown. This script for example, does it:

```python
import msprime as msp

def ancient_sample_test(
        num_modern=1000, anc_pop = 0, anc_num = 1, anc_time = 200, split_time_anc = 400,
        Ne0 = 10000, Ne1 = 10000, length = 1000):
    samples = [msp.Sample(population = 0, time = 0)]*num_modern
    samples.extend([msp.Sample(population = anc_pop, time = anc_time)]*(2*anc_num))
    pop_config = [msp.PopulationConfiguration(initial_size = Ne0), msp.PopulationConfiguration(initial_size = Ne1)]
    divergence = [msp.MassMigration(time = split_time_anc, source = 1, destination = 0, proportion = 1.0)]
    seed = 94320219
    sims = msp.simulate(
        samples=samples,Ne=Ne0,population_configurations=pop_config,
        demographic_events=divergence, length=length,
        random_seed=seed)

if __name__ == "__main__":
    num_ind = 10
    ancient_sample_test(
        num_modern=100,anc_pop=0,anc_num=num_ind,Ne0=3000,Ne1=3000,anc_time=5419,split_time_anc=5919,length=500)
```

we get 
```
  File "ancient_genotypes_simulation.py", line 19, in <module>
    num_modern=100,anc_pop=0,anc_num=num_ind,Ne0=3000,Ne1=3000,anc_time=5419,split_time_anc=5919,length=500)
  File "ancient_genotypes_simulation.py", line 14, in ancient_sample_test
    random_seed=seed)
  File "/home/jk/work/github/msprime/msprime/simulations.py", line 485, in simulate
    sim, mutation_generator, 1, provenance_dict, end_time))
  File "/home/jk/work/github/msprime/msprime/simulations.py", line 163, in _replicate_generator
    sim.run(end_time)
  File "/home/jk/work/github/msprime/msprime/simulations.py", line 704, in run
    self.ll_sim.run(end_time)
_msprime.LibraryError: The simulation model supplied resulted in a parent node having a time value <= to its child. This can occur either as a result of multiple bottlenecks happening at the same time or because of numerical imprecision with very small population sizes.
```

What happens is, [this line](https://github.com/tskit-dev/msprime/blob/master/lib/msprime.c#L2484) returns exactly zero and so the minimum time until the next event is 0 and naturally enough this gets chosen as the next event. But, we end up with a zero branch length, which tskit won't allow.

We could put in some cludge where we have 1e-200 or something as the time if ``t_wait`` is exactly zero, but I don't think this is a good idea. We can easily get to a case where branch lengths become too short for double precision when growth rates are specified, and it's much better that the simulation ends with an error than the user getting back a bunch of completed trees with miniscule branch lengths.

So; I don't really know how to handle this!

Thanks to David Lawrie for the script and reporting the problem. Pinging @molpopgen for thoughts.

**Comment by jeromekelleher** [comment]
Also, I should say it's really annoying for users when this happens in the middle of a gazillion replicates, so we really should do *something*.

**Comment by molpopgen** [comment]
cc @dl42

**Comment by molpopgen** [comment]
Is one of these functions the solution: https://en.cppreference.com/w/c/numeric/math/nextafter

```c
if(next_event_time == 0.)
{
    /* unclear that this is the right one... :) */
    current_time = nextafter(current_time, INFINITY);
}
else
{ 
    current_time += next_event_time;
}
```

**Comment by molpopgen** [comment]
Maybe my last suggestion over/under-thought it--what about a while(next_time == 0.) { next_time = ... } ?

**Comment by petrelharp** [comment]
Well, I think the two options suggested so far:

1. return epsilon instead of zero (as `nextafter( )` would do), or
2. resample if zero

would be reasonable. But I think your worry about that is that people won't get errors with models that have unreasonably high coalescence rates (or something)? The only way around *that* I can think of is to count how many times the "if zero" condition has occurred, and error if it happens more than once, or twice, or something. But, there's other ways to catch wierd situations like this, using e.g. the demography debugger (could even use the coalescence rate calculations we have now).

Hm: note that option (2) is the same as conditioning on the waiting time being greater than epsilon. Since the time 'til the next event is exponential, this is equivalent to adding espilon to *every* event. This seems like it might add up to something non-neglegible, and I like option (1) better.

**Comment by molpopgen** [comment]
> Hm: note that option (2) is the same as conditioning on the waiting time being greater than epsilon. Since the time 'til the next event is exponential, this is equivalent to adding espilon to _every_ event. This seems like it might add up to something non-neglegible, and I like option (1) better

Yes, this is the worry.  This suggestion is not numerically rigorous.

**Comment by molpopgen** [comment]
> and I like option (1) better.

I do, too, but it'd take some homework (for me) to be convinced that `i + nextafter(i, INFINITY) -i != 0.0` for all (reasonable?) `i`. There are devils in the details here.

**Comment by molpopgen** [comment]
> Hm: note that option (2) is the same as conditioning on the waiting time being greater than epsilon. Since the time 'til the next event is exponential, this is equivalent to adding espilon to _every_ event. This seems like it might add up to something non-neglegible, and I like option (1) better.

Actually, both approaches do this (because both add a small value i.f.f. the next time is zero).  The difference is that the epsilons are different.  For the `nextafter` approach, the magnitude of the epsilon will depend on the `Ne` parameter of the simulation.

**Comment by DL42** [comment]
So I generally would go with option 1 or 2. But I think Peter's idea of counting has given me a related idea which I'm not sure is good or not. If this is happens during the course of a simulation, continue to throw an error.

For multiple simulation replicates, I'm assuming msprime takes the user supplied seed and then uses that to set the RNG to generate unique seeds for each replicate? If so, if a simulation replicate fails for this reason, then log its occurrence and generate a new seed to assign to that replicate and run the whole simulation over again. If it never happens agains over any of the replicates, the user gets a warning about its occurrence, but that in the end, everything ran okay explaining what you did and why. That way it isn't silent but the user still gets their simulations. 

If, on the other hand, multiple simulations start coming back with the same error, then over some threshold (based on absolute count or proportion of replicates) you re-raise the error to the user level and stop running. If there is only one simulation replicate, re-raise that error to the user level and explain in the error message that if the demographic model is not one that is expected to produce such errors, that it is likely a very rare zero-branch length event and choosing a different random number seed should solve the issue. Or maybe throw a warning and automatically re-run with a different seed generated from that user-chosen seed. 

Maybe this behavior could even be settable by the user - some flag that says throw warning and re-run, set the threshold to x, or always send back an error no matter what - and, as Peter said, adding a warning in the demography debugger if the demography model is potentially problematic which could be informative of how to set the flag. 

I'm not sure that I prefer this over the standard options 1 or 2, but I thought it might be at least interesting enough of an idea to propose it.

**Comment by jeromekelleher** [comment]
There's a lot to be said for @DL42's idea - we leave the low-level C code as it is, catch the error at the Python level and discard replicates that throw the problem with a warning. If we discard two consecutive replicates (or maybe more than, say, max(2, 0.01 * num_replicates)), we throw an error.

This way should be statistically safe and keep the user sufficiently warned that something funky is happening when we have tiny population sizes.

Thanks for the input here everyone!

**Comment by petrelharp** [comment]
> Actually, both approaches do this (because both add a small value i.f.f. the next time is zero). The difference is that the epsilons are different. For the nextafter approach, the magnitude of the epsilon will depend on the Ne parameter of the simulation.

I meant one of those options to add an epsilon *every* time, which sounds sensible because it's just conditioning on being at least epsilon. But, might actually add up to something non-neglegible.

**Comment by petrelharp** [comment]
It would be nice to not slow things down for the sake of a once-in-a-very-long-time situation.

**Comment by jeromekelleher** [comment]
> It would be nice to not slow things down for the sake of a once-in-a-very-long-time situation.

I don't think it'd slow things down much. We'd just be wrapping a try/except around the ``simulator.run`` and any extra code would happen in the failure case of this. So, the only overhead would be a try/except, which is probably negligible.

**Comment by molpopgen** [comment]
Overall, i would vote for a fix that doesn't involve exception handling.  There's a bug here, and my view is that the correct fix would be numeric one.

For the record, this is what `ms` does:

```c
		   while( ( rdum = ran1() )  == .0 )
               ;
`

That's lines 212-213 of `stree.c`.  He does that for all waiting time generation.

**Comment by petrelharp** [comment]
> We'd just be wrapping a try/except around the simulator.run 

I meant the C fix.

> Overall, i would vote for a fix that doesn't involve exception handling

I agree with Kevin, unless this slows things down more than, say, 5%.

**Comment by molpopgen** [comment]
> I meant one of those options to add an epsilon _every_ time, which sounds sensible because it's just conditioning on being at least epsilon. But, might actually add up to something non-neglegible.

Gotcha.  in general, though, this approach fails because a correct epsilon cannot be chosen:

```c
#include <stdio.h>
#include <assert.h>

int main(int argc, char * argv[])
{
    double epsilon = 1e-100;
    double x = 1.;
    x+=epsilon;
    assert(x-1. != 0.);
}
```

The above assertion fails because the only value that would work for epsilon is DBL_EPSILON, which is defined as the next value larger than 1.0.

**Comment by jeromekelleher** [comment]
The ms solution is seems like the sensible thing to do to me - just rejection sample if we get zero (perhaps event as a wrapper around gsl_ran_exponential). What we could do to catch the "your population size is ridiculously small" situation is put in a threshold where we throw an error if it goes below it. If your population size is < 10^-20 or something it's almost sure an error.

**Comment by petrelharp** [comment]
> If your population size is < 10^-20 or something it's almost sure an error.

If it's got lineages in, sure. Although checking this sort of thing seems like maybe a can of worms we don't want to get into.

**Comment by molpopgen** [comment]
> The ms solution is seems like the sensible thing to do to me - just rejection sample if we get zero (perhaps event as a wrapper around gsl_ran_exponential).

It seems that times to the next recombination event may come up zero with some frequency too?  For large regions, the total recombination rate in the sample is quite high, much like the probability of coalescence in a really small pop.

**Comment by jeromekelleher** [comment]
> If it's got lineages in, sure. Although checking this sort of thing seems like maybe a can of worms we don't want to get into.

Ack, yes, we don't want to stop people having zero population sizes for stuff that isn't active in the simulation. That's messy. 

If we don't do something, very small population sizes will result in rejection sampling on gsl_ran_exponential forever, so the simulation won't finish. Users also won't be able to use CTRL-C to kill the simulation because this is handled by the Python interpreter (that's what [this line](https://github.com/tskit-dev/msprime/blob/master/_msprimemodule.c#L3793) is about.) That would really trip people up.

**Comment by molpopgen** [comment]
> very small population sizes will result in rejection sampling on gsl_ran_exponential forever,

This may lead to preferring an approach using the C99 machinery?

**Comment by jeromekelleher** [comment]
> It seems that times to the next recombination event may come up zero with some frequency too? For large regions, the total recombination rate in the sample is quite high, much like the probability of coalescence in a really small pop.

This probably doesn't do any harm, I think, except in the case where we're recording the full ARG. The event happens and it has it's effect.

**Comment by jeromekelleher** [comment]
> This may lead to preferring an approach using the C99 machinery?

What difference would this make?

**Comment by molpopgen** [comment]
There is no while loop.

**Comment by molpopgen** [comment]
> What difference would this make?

No while loop.

**Comment by jeromekelleher** [comment]
>> What difference would this make?

> No while loop.

I'm missing something here: what C99 machinery are you talking about?

**Comment by molpopgen** [comment]
> I'm missing something here: what C99 machinery are you talking about?

`nextafter`:

```c
#include <math.h>
#include <assert.h>
#include <stdio.h>

double exponential_deviate()
{
    return 0.;
}

int main(int argc, char *argv[])
{
    double total_time=0., check=0.;
    double next_time;
    int i;

    for(i = 0;i<10;++i)
    {
        next_time=exponential_deviate();
        if(next_time==0.)
        {
            next_time=nextafter(total_time, INFINITY) - total_time;
            assert(next_time!=0.);
        }
        total_time+=next_time;
    }
    assert(total_time!=0.);
    printf("%.20e\n", total_time);
    for(i=0;i<10;++i)
    {
        check = nextafter(check,INFINITY);
    }
    assert(total_time==check);
}
```

**Comment by molpopgen** [comment]
One note: the `nextforward` stuff is incompatible with flags like `-ffast-math`.

**Comment by jeromekelleher** [comment]
Ahhhhh! Sorry, totally missed  this.

**Comment by molpopgen** [comment]
No problem.  This is the most pedantic way to handle the issue, as it is the only way to reconsider a zero waiting time as the "smallest thing to add" to the current total time.  No guarantees that this works for Windows builds, tho--I understand that C99 support there may be incomplete?

**Comment by DL42** [comment]
Does this nextafter solution also fix the multiple recurring bottleneck problem? I mean in the sense that getting a next_time of 0 is never an error anymore? Or if this happens too many times during a simulation is this is still a problem?

If Jerome uses -ffast-math for compilation and this prevents compilation with that flag, is this solution then faster or slower than a while loop in the cases we want to prevent - i.e. the ultra-rare cases? The while loop could still have a counter that throws an error if it happens too often. The nextafter solution never errors out ... although to the first question, if this is a fix for even those demographic cases that were problematic before, then that is even better.

**Comment by DL42** [comment]
> Overall, i would vote for a fix that doesn't involve exception handling. There's a bug here, and my view is that the correct fix would be numeric one.
> 
> For the record, this is what `ms` does:
> 
> ```c
> 		   while( ( rdum = ran1() )  == .0 )
>                ;
> `
> 
> That's lines 212-213 of `stree.c`.  He does that for all waiting time generation.
> ```


So I agree that this or the nextafter solution is probably the better way to handle this. However, in this instance, the error handling on the python end is basically doing the same thing as the while loop, but on the python end - i.e. if we run into the problem, redo the simulation until it isn't a problem, which is basically the approach the while loop takes as well. The advantage of doing it on the python end is that you don't slow down the normal C execution of a simulation that doesn't experience a problem and exception handling in python is not that much worse than normal execution - the try block takes less time than an if statement to execute and the catch block is slower, but C++ orders of magnitude slower. Finally, if you keep running into this issue, you can easily re-raise the exception to the user stating something is seriously wrong with the simulation setup.

**Comment by molpopgen** [comment]
My preference for a non-exception solution is that try/catch is a workaround for a bug rather than a fix for it, creating a bit of a  "code smell".  I'll guess that the performance impact of a C-side fix is unnoticeable.

**Comment by DL42** [comment]
> My preference for a non-exception solution is that try/catch is a workaround for a bug rather than a fix for it, creating a bit of a "code smell". I'll guess that the performance impact of a C-side fix is unnoticeable.

I see what you are saying, but I guess I would counter that, philosophically, both the while loop and the try/catch are really the same work around, just in different pieces of the code. The while loop in the C code is probably just as good if not better than the try/catch block in the circumstance I experienced as there the random event happened once and then never again. Rerunning a single random number draw would be incredibly fast - basically no performance hit at all and no error handling needed. And in the python try-catch solution there would actually be a slightly bigger performance loss. It goes to a catch block which runs another while loop where the whole simulation replicate is repeated - same effect in the end, but much slower. 

Where it gets tricky is that the while loop on the C-end getting stuck during a pathological demographic scenario. A while-loop in the Python catch statement could also get stuck, but it is easier to keep track of both for a particular replicate and across replicates how many times this error has been thrown and that it needs to be re-raised to the user. 

The nextafter solution suffers from none of these issues and if it gives sensible results for the pathological demographic scenarios then suddenly there is no error at all to ever report. I don't know if Jerome compiles with -ffast-math. My own experience is that for some programs it makes a huge difference, for others, none at all. If the performance hit is big, it may also be possible to move the needed pieces of code with nextafter function into their own compilation unit so that all other code is compiled with -ffast-math. 

So for me in terms of solutions listed so far, I would rank them as follows:

1) nextafter if it behaves nicely
2) try-catch with while loop in the catch on python side
3) while loop in C code

**Comment by jeromekelleher** [comment]
I'll give nextafter a go. I don't compile with any particular flags (msprime is mostly shuffling memory around, so they don't make any real difference), so not being able to use -ffastmath is fine. Windows is a concern though - C99 support has been an issue at times. We can try it out though and see what happens.

**Comment by molpopgen** [comment]
> I'll give nextafter a go. I don't compile with any particular flags (msprime is mostly shuffling memory around, so they don't make any real difference), so not being able to use -ffastmath is fine. Windows is a concern though - C99 support has been an issue at times. We can try it out though and see what happens.

Sounds good.  No sane person uses ffast-math for scientific code.  I was just pointing out that this is one of the many things that that flag breaks.
