### ISSUE TITLE
MassMigration unexpected behavior

### ISSUE THREAD

**Issue by agladstein** [tskit-dev/msprime#784]
Problem: MassMigration seems to not behave the same as ms's -ej

I was attempting to simulate a two population split model, with no gene flow, and constant population size in both populations.

```
A, B = 0, 1
population_configurations = [
    msprime.PopulationConfiguration(sample_size=int(sample_size/2), initial_size=NA),
    msprime.PopulationConfiguration(sample_size=int(sample_size/2), initial_size=NB)
]
demographic_events = [
    msprime.MassMigration(time=td, source=A, destination=B, proportion=1.0),
]
tree = msprime.simulate(population_configurations=population_configurations,
                        demographic_events=demographic_events,
                        length=L,
                        recombination_rate=r,
                        mutation_rate=u,
                        random_seed=seed,
                        num_replicates=locus_replicates)
```
I ran this 10,000 times, randomly picking `NA` and `NB` from [1000, 40000], and `td` from [100, 3499.99].
I expected that on average population genetic statistics calculated on pop A and pop B would be equal. However, on average stats on A and B differed. For example pi and the number of private alleles are different:
![Screen Shot 2019-07-05 at 4 41 00 PM](https://user-images.githubusercontent.com/26617086/61017822-94cb8880-a362-11e9-99d6-950675387376.png)
![Screen Shot 2019-07-05 at 4 45 40 PM](https://user-images.githubusercontent.com/26617086/61017842-a1e87780-a362-11e9-9c3c-25fd64754035.png)

When I ran the same simulations (mutation rate = u/10) with ms, the stats were on average equal between A and B.
```
ms sample_size 1 -t theta -r rho L -I 2 sample_size/2 sample_size/2 -n 1 NA -n 2 NB -ej td 1 2
```
![Screen Shot 2019-07-05 at 4 37 57 PM](https://user-images.githubusercontent.com/26617086/61018206-fc360800-a363-11e9-987e-05ff6abe1a30.png)
![Screen Shot 2019-07-05 at 4 45 15 PM](https://user-images.githubusercontent.com/26617086/61018247-1c65c700-a364-11e9-972c-e9a09349083b.png)

I got the behavior I wanted with msprime by explicitly including an ancestral population that both pop A and pop B diverge from.
```
A, B = 1, 2
population_configurations = [
    msprime.PopulationConfiguration(sample_size=0, initial_size=N0),
    msprime.PopulationConfiguration(sample_size=int(sample_size/2), initial_size=NA),
    msprime.PopulationConfiguration(sample_size=int(sample_size/2), initial_size=NB)
    ]
demographic_events = [
	msprime.MassMigration(time=td, source=A, destination=0, proportion=1.0),
	msprime.MassMigration(time=td, source=B, destination=0, proportion=1.0)
    ]
tree = msprime.simulate(population_configurations=population_configurations,
                        demographic_events=demographic_events,
                        length=L,
                        recombination_rate=r,
                        mutation_rate=u,
                        random_seed=seed,
                        num_replicates=locus_replicates)
 ```
![Screen Shot 2019-07-10 at 3 30 28 PM](https://user-images.githubusercontent.com/26617086/61018499-145a5700-a365-11e9-9d10-f12137d4dea7.png)

This may be an msprime feature, but it was unexpected behavior for me since the documentation says, "This event class generalises the population split (`-ej`) and admixture (`-es`) events from ms."
Or am I misunderstanding something?

**Comment by jeromekelleher** [comment]
This is odd all right. 

There is a semantic difference in the 2 pop and 3 pop case here for the msprime code, as you're also setting the ancestral population size to N0 in the three population case.

I don't see any reason why the stats would differ in the two cases for the first example though. Would you mind making a MWE script to reproduce and post it here please @agladstein?

**Comment by gtsambos** [comment]
The discrepancy between `ms` and `msprime` is something to think about, but to me it sortof makes sense that there would be diversity differences in the 2 pop case? At the time of the MassMigration, the diversity of in the 'new' population that splits off should be a subset of the diversity in the founder population at that time, right?

Also, what sample sizes are you simulating @agladstein? I think this is a case where the limitations of the coalescent model assumptions would make a difference. You're keeping Ne constant for all pops the whole way through - which would never be the case irl unless you had an infinite population size. (If some people are migrating out of a population and there are no new migrants in, the migration should be accompanied by a decrease in Ne for the founder population).

**Comment by agladstein** [comment]
@jeromekelleher here is a notebook to reproduce it. But.... when I made this notebook to reproduce the problem, it seems like ms is also producing uneven stats in pops A and B. I'm pretty confused...
Either way, seems that using an explicit ancestral population with msprime produces the effect I want.

https://gist.github.com/agladstein/0c37901929fc922e512d35698958f6b0

@gtsambos sample sizes were 50. Possibly, I'm not sure about that...

**Comment by gtsambos** [comment]
![image](https://user-images.githubusercontent.com/17755074/61085682-c9a21300-a428-11e9-9df3-fd00f50e50c0.png)

Here a rough sketch of two pops, equal numbers of samples in each, and pop1 is created by a mass migration from pop0. But the migrants into pop1 are more closely related to those in the right part of the pop0 tree than to those in the left part - ie. at the time of divergence, pop1 will only have represent a subsample of all diversity present in pop0. And if there's a difference in diversity at the time of divergence, that difference will persist until the present day if Ne is constant the whole way through.

This is quite likely to happen - the only way it wouldn't is if the migrants coalesce with the pop0 ancestors before any of the pop0 ancestors coalesce with each other.

(Basically, I think this is expected, though kindof counterintuitive behaviour)

**Comment by jeromekelleher** [comment]
OK, given @gtsambos's argument above and that ms is doing the same thing as msprime, I think this is expected behaviour. Can you close this issue if you're happy with this please @agladstein?

**Comment by gtsambos** [comment]
> the only way it wouldn't is if the each migrant coalesces with a different pop0 ancestor before any of the pop0 ancestors coalesce with each other.

I think this particular statement might not be quite right -- Maybe an easier way to understand the difference in diversity is that the MRCA of the pop0 samples is older as the MRCA of the pop1 samples. (And MRCA(pop0) is always guaranteed to be >= MRCA(pop1), because of the fact that pop0 has founded pop1).

**Comment by agladstein** [comment]
@gtsambos I'm still thinking about your argument...
@jeromekelleher yes, given that ms seems to producing the same results, I can close it. But, I good to have this issue in the record for anyone else potentially stumbling on that.

**Comment by petrelharp** [comment]
Looking at your code, @agladstein, I think I can explain? Aren't you choosing the population sizes for A and B randomly and separately? And, we'd only expect these quantities to be equal if their pop sizes are the same?

**Comment by gtsambos** [comment]
> @gtsambos I'm still thinking about your argument...

I'll try to explain a bit more.

The amount of diversity in a sample is due to the number of mutations in its history. In coalescent theory, the expected number of mutations on any edge/branch is directly proportional to its length. So the diversity in a subsample, say those from pop0, should reflect the total lengths of all the edges in the tree for pop0 samples. 

In your two pop simulation, you've set up a a scenario where the root of the tree representing your pop1 sample history is guaranteed to be younger than (or at most, the same age as) the root of the tree representing your pop0 sample history. 

This means that the total sum of branch lengths in the pop1 tree sequence will on average be smaller than the total sum of branch lengths in the pop0 tree sequence, and it will have accumulated fewer mutations on average.

**Comment by agladstein** [comment]
@petrelharp this is true, but I am sampling randomly from the same distribution for A and B, and did this 10,000 times. So, on average I was expecting them to be the same.

**Comment by petrelharp** [comment]
> @petrelharp this is true, but I am sampling randomly from the same distribution for A and B, and did this 10,000 times. So, on average I was expecting them to be the same.

That sounds plausible, but a better check would be if they were always the same.

I'm not following the argument that this is expected, btw: at the time they merge, all lineages still present should be exchangeable, and in particular, everything should be symmetric wrt population identity.

**Comment by jeromekelleher** [comment]
I'm not entirely following the argument that they should be different either, tbh, but if the results from ms are the same then I'm happy that this expected behaviour...

**Comment by agladstein** [comment]
I agree with @petrelharp. 
The simplest way I see it, if Ne is constant (or on average the same over sims) your two subpopulations have same Ne before pop1 diverges from pop0, therefore diversity stats should be the same in the two subpops.
