### ISSUE TITLE
Why is gene conversion rate multiplied by recombination rate?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#786]
In algorithms.py, in [this line](https://github.com/tskit-dev/msprime/blob/master/algorithms.py#L1492) we muliply the gene conversion rate by the recombination rate. Why do we do this? Wouldn't it be simpler to just specify the gene conversion rate by itself rather than as a function of the recombination rate? (This may be what ms does, but msprime tries to avoid compound parameters where possible).

pinging @fbaumdicker

**Comment by jeromekelleher** [comment]
Ooops, my bad, I see this is within simulate. Closing.

**Comment by fbaumdicker** [comment]
But you are right, I am mimicking the parameter behavior of ms within simulate.
