### ISSUE TITLE
[Question] Write .trees from mspms rather than ms-like output 

### ISSUE THREAD

**Issue by Chris1221** [tskit-dev/msprime#790]
I've been using the `ms` drop in CLI, and I appreciate you guys including this feature. However, I was wondering if it is currently possible to, rather than writing `ms`-like output to `stdout`, instead save the intermediate tree sequence file. For full context, I am trying to plug in legacy `ms` simulations to the `stdpopsim` analysis workflow. I have the commands, and would love to be able to directly input that to the workflow by writing out a `.trees` file and going from there. If this is not something that can be done, or would be supported, my apologies! 

Chris

**Comment by jeromekelleher** [comment]
I'm not keen on adding this @Chris1221, as it'll be a support headache in the future I think. The problem is that everything is scaled differently in ms, and documenting how the intermediate ts is scaled will be tricky and confusing. Sorry.

**Comment by Chris1221** [comment]
Fair enough, thanks anyway @jeromekelleher. 👌
