### ISSUE TITLE
Add functionality to track number of lineages over time

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#792]
It's useful to be able to examine the state of the simulation at various times in the past. We already have functionality of this in the low-level module, we just need to provide some plumbing in the high-level API to enable it (see [here](https://github.com/tskit-dev/msprime/blob/master/tests/test_lowlevel.py#L363) for an example of the ``get_ancestors`` function in use). We could add a ``ancestors`` property to the high-level Simulator object, so we'd do things like:

```python
sim = msprime.simulator_factory(...)

times = np.logspace(...)
num_ancestors = np.zeros(...)
for j, t in enumerate(times):
     sim.run(t)
     num_ancestors[j] = len(sim.ancestors)
```

If we're just interested in the number of ancestors we can add a ``num_ancestors`` property as well that skips building all the intermediate lists and stuff.

@DomNelson, looks like this is something you need?

**Comment by DomNelson** [comment]
Definitely this would be good to have, much better than the hack I'm using to extract it now. I've just been looking at `num_ancestors` but I can see how `ancestors` could be useful too - say in the future in pedigree sims to track segment paths?

**Comment by jeromekelleher** [comment]
> Definitely this would be good to have, much better than the hack I'm using to extract it now. I've just been looking at num_ancestors but I can see how ancestors could be useful too - say in the future in pedigree sims to track segment paths?

Yeah, I think both will be useful. Do you see how it fits together? Happy to implement it?

**Comment by DomNelson** [comment]
Yep I can take a crack at it, as long as it's not urgent.

**Comment by jeromekelleher** [comment]
Yeah, no hurry - you're the main user I think!

**Comment by jeromekelleher** [comment]
Going to close this due to inactivity. We can reopen if anyone is interested (it's not hard to implement).
