### ISSUE TITLE
Simulations with recombination map slow

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#798]
It looks like simulations that use a recombination map are much slower than those that don't. It appears that ``recomb_map_genetic_to_phys`` is getting called a **lot**. This is a pretty serious performance issue, so we should resolve it. There should be no reason that recombination map simulations are any slower, as in principle all the remapping should be done at the end.

**Comment by petrelharp** [comment]
If this is a chance to provide compatibility with discrete-site models, that'd be great.

**Comment by jeromekelleher** [comment]
I doubt it, but I'll keep it in mind!

**Comment by andrewkern** [comment]
i wonder if this is partially responsible for the very long runtimes of the drosophila model in stdpopsim
