### ISSUE TITLE
Mac instructions for making the Makefile

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/msprime#801]
On machines that compile with clang (eg. Macs by default), just typing `make` produces errors, but `make ext3` works. This note should be added to the developer documentation.
<img width="506" alt="Screen Shot 2019-08-23 at 1 34 09 pm" src="https://user-images.githubusercontent.com/17755074/63592993-d3cc3b00-c5aa-11e9-8545-cefc50553744.png">

**Comment by jeromekelleher** [comment]
Closed in #805.
