### ISSUE TITLE
Outputting fasta files from tree sequences

### ISSUE THREAD

**Issue by marianne-aspbury** [tskit-dev/msprime#802]
This is a pretty basic file format to output, I have something that works for me but I don't know how to integrate it within tskit, and that'd be nice to do so noting it here for the future. (I'm also happy to do this, but with some direction). 
This is what I'm doing for my personal use at the moment:

```
# the actual haplotype strings
haps = []
for i in ts.haplotypes():
    haps.append(i)

# The ">ID" parts of the fasta format. Don't know what best info to include is, 
# I'm just using sample index and the population because that's relevant for me. 
# Possibly people could choose what to include for ID strings in a fasta output function call
sequence_IDs = []
for i in range(len(haps)):
    sequence_IDs.append(f'sample_{ts.samples()[i]}_pop_{ts.node(i).population}')

# saving the file
with open('Sim_fasta_file.txt', 'w') as f:
    for i in range(len(haps)):
        f.write(f'>{sequence_IDs[i]}\n{haps[i]}\n') 
```

**Comment by petrelharp** [comment]
Very nice. I'm curious, what do you need a fasta of just the variant sites for? We would like to add support for [reference sequences](https://github.com/tskit-dev/tskit/issues/146) but have not.

And, hm: this should really be over in tskit (which deals with tree sequence manipulations), not msprime (which simulates them). Mind moving this over there?

**Comment by marianne-aspbury** [comment]
Oops! I meant to put this on tskit.... Thanks... 
We're using some phylogeny inference software that needs fasta files as input. We're actually making a fasta file that included all the sites, not just the variant ones, since we're making a table that includes the invariant sites as well.

**Comment by marianne-aspbury** [comment]
Kamino closed and cloned this issue to [tskit-dev/tskit](https://github.com/tskit-dev/tskit/issues/338)
