### ISSUE TITLE
meson build instructions on Mac OS X

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/msprime#804]
see emotional rollercoaster [here](https://github.com/tskit-dev/msprime/pull/799). Edit documentation for developers to suggest this for Mac OS C users.

**Comment by gtsambos** [comment]
@jeromekelleher, would it be going too far to explicitly recommend that Mac users compile with `gcc` instead of `clang`? I don't have much understanding of the differences between different compilers and I wasn't haven't problems with `clang` on my laptop, but perhaps that was just lucky. And perhaps it might make it easier for you/others to help troubleshoot if we are all compiling things with the same compiler?

**Comment by jeromekelleher** [comment]
I don't really have an opinion on this stuff I'm afraid @gtsambos --- I'm happy to go with what OSX users think in terms of recommendations for development. Ordinary users should be using conda I think, so choice of compiler isn't going to make any difference.

**Comment by molpopgen** [comment]
I made a comment on this in the PR (#805).  It is still actually possible to `conda install gcc` on OS X?  I just tried on my mac laptop (Sierra, latest miniconda).  The command fails at the "solving environment" step.

When you are referring to `gcc` on your mac, what is the path of that compiler?  `which gcc` will tell you that?  I think the answer will be `/usr/bin/gcc`?  If so, that is the xcode clang.  You can see that in your comments in #799.  The output of `gcc --version` is referring to clang, and not to any actual `gcc` version.

**Comment by gtsambos** [comment]
Hi @molpopgen, sorry, somehow I missed this amongst a flurry of other stuff last week. You're right, it's in `/usr/bin/gcc`. And yeah, I'm pretty sure I got my version of (what I thought was...) clang via Xcode, so that would make sense. I've just updated the PR - are there any changes to that text that you would suggest?

**Comment by gtsambos** [comment]
ps. I'm on a slightly later version of OS X - Mojave. 

>  It is still actually possible to conda install gcc on OS X? I just tried on my mac laptop (Sierra, latest miniconda) 

Will try this later (need to be careful to ensure I don't break things that are currently working for me!)

**Comment by molpopgen** [comment]
> Will try this later (need to be careful to ensure I don't break things that are currently working for me!)

I wouldn't try too hard!  Attempting to `conda install gcc` on OS X with the "latest" miniconda causes the system to go into a long process where it tries to back-calculate how far it needs to downgrade in order to make your request work.  I killed it after about 5 minutes.

The OS X version itself won't matter--all the 'conda stuff is built against Xcode SDK9, which is an even earlier version.  (That early SDK is why it is so hard to get the new compilers working locally.)

**Comment by molpopgen** [comment]
>  are there any changes to that text that you would suggest?

I made a comment in the PR--take a look there.

**Comment by jeromekelleher** [comment]
I think we can close this now @gtsambos?
