### ISSUE TITLE
error loading msprime after recent conda install of tskit/msprime 

### ISSUE THREAD

**Issue by mcneney** [tskit-dev/msprime#807]
I recently removed and reinstalled tskit and msprime using conda. I get the following error when trying to import msprime:

MacBook-Air:~ mcneney$ python3
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import msprime
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mcneney/miniconda3/lib/python3.7/site-packages/msprime/__init__.py", line 24, in <module>
    import tskit
  File "/Users/mcneney/miniconda3/lib/python3.7/site-packages/tskit/__init__.py", line 25, in <module>
    MISSING_DATA = _tskit.MISSING_DATA
AttributeError: module '_tskit' has no attribute 'MISSING_DATA'

**Comment by mcneney** [comment]
I should add that msprime installs fine with pip.

**Comment by petrelharp** [comment]
Sounds like you've got an old version of tskit. Make sure you've actually uninstalled msprime and tskit, and reinstall them; if you still have issues please post just how you've done this.

**Comment by mcneney** [comment]
Thanks.  I uninstall/reinstall msprime and tskit in my base conda environment with:

conda uninstall msprime
conda install msprime

As an alternative, I create a new conda environment and install msprime/tskit into it:

conda create -n test
conda activate test
conda install msprime

and get the same error. I see now that the error has nothing to do with msprime. I can replicate the problem by installing tskit into a 

Brad

**Comment by mcneney** [comment]
sorry, end of message should have read 
  ... the base conda environment or a new test environment.

**Comment by petrelharp** [comment]
Hm; I've just done this and it worked fine for me. Perhaps some others more used to conda can help?

**Comment by mcneney** [comment]
OK, thanks. I wouldn't be surprised if it's something to do with my computer/installation. I'll continue to investigate. -b

**Comment by mcneney** [comment]
I'm going to close this issue and re-open under tskit where it belongs.
