### ISSUE TITLE
Revamp of tutorial in the docs, especially the 'demography' section?

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/msprime#808]
At the moment, the [Demography section](https://msprime.readthedocs.io/en/stable/tutorial.html#demography) isn't particularly helpful - there's one big example (with lots of relatively complicated stuff going on), rather than a step-by-step explanation of what different types of demographic events are and what they do. I think it would be more helpful to flesh this out by porting over material from, say, [here](https://github.com/DRL/SMBE-SGE-2019/blob/master/Session_1/2.Introduction_to_msprime.ipynb). 

I'm happy to take this on but it's a not a small change, so not right now.

**Comment by petrelharp** [comment]
Awesome. It'd probably be good to post an outline of what you're thinking here before you jump into it.

**Comment by jeromekelleher** [comment]
Yes, this would be superb, thanks @gtsambos!

**Comment by molpopgen** [comment]
It may be handy to roll #766 into this?

**Comment by gtsambos** [comment]
> It may be handy to roll #766 into this?

Yup, absolutely, feel free to ping things like this in here.

> Awesome. It'd probably be good to post an outline of what you're thinking here before you jump into it.

Yup, will do. I won't have time to think about this properly for a few weeks but will defs let you know before I jump into any significant changes!

As a related (but possibly separate) idea, I was thinking the other day that it could be useful to set up a site/gallery (or a [living book?](https://jupyter.org/jupyter-book/intro.html)) that holds some longer code snippets showing analyses done with tskit and msprime, sort of like the 'recipes' in the SLiM manual.

**Comment by jeromekelleher** [comment]
> As a related (but possibly separate) idea, I was thinking the other day that it could be useful to set up a site/gallery (or a living book?) that holds some longer code snippets showing analyses done with tskit and msprime, sort of like the 'recipes' in the SLiM manual.

This is a bit more ambitious, and related to the [tutorials](https://github.com/tskit-dev/tutorials) we started on a while back (rendered website [here](https://tskit-dev.github.io/tutorials/)). We found that converting the jupyter notebooks to HTML and the review process (in particular) for the notebooks was really tedious. Perhaps the living book thing works better?

Revamping the current tutorial a bit would be a real help though, and I don't think we need to change the toolchain for doing that.

**Comment by molpopgen** [comment]
For the SVG images in bookdown, I use a Makefile that converts svg to 300dpi png via ImageMagick.  It isn't much of a compromise, as the whole thing is built via `make` anyways.

**Comment by agladstein** [comment]
I wouldn't mind helping with this (especially reviewing).

**Comment by molpopgen** [comment]
Thanks @agladstein.

i think the short-term marching orders are for someone (probably me?) to evaluate JupyterBook and then do a liftover of the current tskit tutorials from notebook to markdown formats. (That should just be a notebook convert op....?)

**Comment by molpopgen** [comment]
After some monkeying around with the code for the "demo" book:

* Code blocks in markdown files do not appear to be executed
* Executed notebooks get included, and their output is shown.

So, this is cool on one hand.  But it seems that the problems we've had so far still exist: changes to the content are hard to review, and the version tracking via github is very difficult. (The notebooks are bit binary blobs, and so they don't `diff` well.)

in other words, it doesn't let us get rid of the `.ipynb` files that currently exist in the tskit tutorials.  What it does allow is for a more automated way to build the web version that is superior to the Makefile we currently have.

The major plus of the Rmd system is that the `knitr` step executes code blocks in the markdown.  This means we can review code, and we "know" (via conda envs) that the outputs are current because we could have something like Circle Ci execute them.

**Comment by agladstein** [comment]
You can use ReviewNB for viewing diffs. 
https://www.reviewnb.com/

But, I'm pro `knitr` anyways.

**Comment by molpopgen** [comment]
IIRC, we looked into ReviewNB for the tutorials. It had just come out around then.  It solves one problem, but not the other, which is repo bloat.

**Comment by gtsambos** [comment]
hullo again everyone 👋 just trying to make a more concrete plan for this docs revamp now.

>  It'd probably be good to post an outline of what you're thinking here before you jump into it.

As a first pass, I was thinking of adding the following structure to the current Demography section:

**Demography**
- Population structure
  - see [here](https://github.com/DRL/SMBE-SGE-2019/blob/master/Session_1/2.Introduction_to_msprime.ipynb)
- Migrations
  - see [here](https://github.com/DRL/SMBE-SGE-2019/blob/master/Session_1/2.Introduction_to_msprime.ipynb)
- Population size and growth rates
  - see [here](https://github.com/DRL/SMBE-SGE-2019/blob/master/Session_1/2.Introduction_to_msprime.ipynb)
- Census events
  - Already in the master doc [here](https://github.com/tskit-dev/msprime/blob/master/docs/tutorial.rst#census-events).
- Demography Debugger
  - Already in the docs
- An example: OoA
  - Already in the docs

The section on [census events](https://github.com/tskit-dev/msprime/blob/master/docs/tutorial.rst#census-events) that I wrote a bit earlier shows you the level of detail that I am hoping will be in each of these other sections.

Thoughts, feelings, comments?

@jeromekelleher, could you please assign this issue to the Docs project?

**Comment by jeromekelleher** [comment]
This looks like an excellent plan @gtsambos, thanks!

**Comment by agladstein** [comment]
That sounds good to me.

**Comment by agladstein** [comment]
So, have we decided what format to have the tutorials in?

**Comment by molpopgen** [comment]
I'd vote for Rmd input to md via a Makefile executing knitr.  Some hints for the yml are [here](https://stackoverflow.com/questions/31914161/how-to-convert-rmd-into-md-in-r-studio).  I don't like the notebooks for GitHub, and the tools to look at their diffs still don't solve the repo bloat problems.  I can show how to get svg images in--you can have the Makefile convert to png using ImageMagick.

**Comment by jeromekelleher** [comment]
I don't think we need to do a technology change here for the local tutorial --- hadn't we agreed to keep it as it is, and look into the other stuff for the more specialised tutorials that get hosted externally?

**Comment by molpopgen** [comment]
Oops, my bad.  Yes, you're right and I got my wires crossed

**Comment by agladstein** [comment]
So, basic tutorials will just be in restructured text on read the docs?

**Comment by molpopgen** [comment]
> So, basic tutorials will just be in restructured text on read the docs?

Yep.  In practice, anything else is really hard on RTD.

**Comment by jeromekelleher** [comment]
Closed in #945
