### ISSUE TITLE
Statistic tests for GC

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#823]
Update the ``verification.py`` to add tests comparing to ms. These will look something like

```
   verifier.add_ms_instance(
        "gc-simple"
        "10 -g 1 1 [or something] [+ mutations]"
```

Scenarious:

1. Gene conversion, no recombintion
2. GC + recombination
3. Different track lengths
4. more

**Comment by jeromekelleher** [comment]
Depends on #824

**Comment by fbaumdicker** [comment]
We have now various comparisons to ms and a comparison to theoretical results from Wiuf and Hein. Everything looks good to me.

**Comment by fbaumdicker** [comment]
After the change to physical coordinates, the verification results are still fine in #896.
So from my side, this issue can be closed.

**Comment by jeromekelleher** [comment]
OK, let's close after #896

**Comment by jeromekelleher** [comment]
This is pretty well covered now.
