### ISSUE TITLE
Feature request: a 'stop_at_time' argument into simulate?

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/msprime#826]
I'm wondering how difficult it would be to add an argument into `msprime.simulate()` that stops the simulation at a given point in time and returns the tree sequence corresponding to this (partial) genomic history going back to this point.

Was wondering how difficult implementing this would be (I'm thinking you could re-use a lot of the existing `census_time` code to 'snip' the trees at this stop time).

The application I'm thinking of is doing hybrid DTWF simulations where the most recent history is simulated with a DTWF model going back to some time point. The partial tree sequence resulting from this simulation could then be into msprime again via the `from_ts` argument, enabling the older genomic history to be simulated with a quicker coalescent model.

**Comment by jeromekelleher** [comment]
It's already in there:

> end_time (float) – If specified, terminate the simulation at the specified time. In the returned tree sequence, all rootward paths from samples with time < end_time will end in a node with one child with time equal to end_time. Sample nodes with time >= end_time will also be present in the output tree sequence. If not specified or None, run the simulation until all samples have an MRCA at all positions in the genome.
