### ISSUE TITLE
Name not spelled correctly in google results for RTD

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#827]
![msPrime](https://user-images.githubusercontent.com/2664569/68471487-3fbb5880-0216-11ea-9566-23f7df7abfa1.png)

The project name must be spelled "msPrime" (ugh) somewhere in the RTD configuration.

**Comment by petrelharp** [comment]
Maybe, but I can't find it anywhere on readthedocs or in the repo. I do get that google result also, but only if I google, specifically, "msprime readthedocs".  nbd?

**Comment by jeromekelleher** [comment]
OK, if it's not in the repo then let's not worry about it.
