### ISSUE TITLE
docs for migration_matrix do not define source/dest pops

### ISSUE THREAD

**Issue by grahamgower** [tskit-dev/msprime#828]
In the Python API docs, neither the `migration_matrix` parameter for `msprime.simulate()`, nor the `matrix_index` parameter of `msprime.MigrationRateChange`, suggest which dimension of the matrix corresponds to the migration source and which to the destination. Unfortunately the examples provided use symmetric migration matrices, so do not clarify this.

**Comment by petrelharp** [comment]
Good catch. I think that information is [here](https://msprime.readthedocs.io/en/stable/api.html#simulation-model):

> Population structure is modelled by specifying a fixed number of subpopulations \(d\), and a \(d \times d\) matrix \(M\) of per generation migration rates. Each element of the matrix \(M_{j,k}\) defines the fraction of population \(j\) that consists of migrants from population \(k\) in each generation. Each subpopulation has an initial absolute population size \(s\) and a per generation exponential growth rate \(\alpha\). The size of a given population at time \(t\) in the past (measured in generations) is therefore given by \(s e^{-\alpha t}\). Demographic events that occur in the history of the simulated population alter some aspect of this population configuration at a particular time in the past.

So, what if the [docs for `simulate()`](https://msprime.readthedocs.io/en/stable/api.html#msprime.simulate) said (new bit in **bold**):

> The matrix describing the rates of migration between all pairs of populations. If \(N\) populations are defined in the `population_configurations` parameter, then the migration matrix must be an \(N \times N\) matrix with 0 on the diagonal, consisting of \(N\) lists of length \(N\) or an \(N \times N\) numpy array, **with the\([j, k]\)th element giving the fraction of population \(j\) that consists of migrants from population \(k\) in each generation.**

**Comment by grahamgower** [comment]
Thanks, I clearly missed the description in the simulation model section. The change you've suggested for the `simulate()` docs seems appropriate though.
