### ISSUE TITLE
Runtime error with `model='dtwf'` and recombination if `length=` is too small.

### ISSUE THREAD

**Issue by terhorst** [tskit-dev/msprime#831]
This causes an immediate crash on version 0.7.3:

```
msp.simulate(10, Ne=1e3,
             model="dtwf", 
             mutation_rate=1e-8, 
             recombination_rate=1e-9
            )
```

The error message is:

> Assertion failed: (k > 0 && "Negative distance: Overflow in gsl_ran_exponential!"), function msp_dtwf_recombine, file lib/msprime.c, line 1279.

Switching to Hudson's algorithm, and/or setting the `length=` parameter to something large, behaves as expected.

**Comment by terhorst** [comment]
Maybe it makes sense to validate the user input and raise a (Python) runtime error if the 1 / recombination rate exceeds the range of a 64-bit integer? cf https://github.com/tskit-dev/msprime/blob/a3197efe6a3f448bafdf729c3cec04bf0692560f/lib/msprime.c#L1278

**Comment by terhorst** [comment]
Also, I don't know enough about the new simulation interface to understand why this fails for dtwf but not Hudson.

**Comment by jeromekelleher** [comment]
Thanks for the bug report @terhorst. I'm not sure there's much we can do about this model-wise (looks like we overflow ``gsl_ran_exponential``), but we should definitely raise an error here rather than asserting out. This will basically just be a case of replacing the assertion with

```c
if (k < 0) {
    ret = MSP_ERR_RECOMB_UNDERFLOW; // or something
    goto out;
}
```

@DomNelson, do you agree?

**Comment by DomNelson** [comment]
Good catch - yep agreed, raising an error sounds like the way to go

**Comment by jeromekelleher** [comment]
> Good catch - yep agreed, raising an error sounds like the way to go

Excellent. Any insights as to why this happens in DTWF and not in Hudson?

**Comment by DomNelson** [comment]
I think @terhorst is right - I'd guess scaling is the difference (and checking for similar overflow in the coalescent could verify). In the coalescent we have

https://github.com/tskit-dev/msprime/blob/a3197efe6a3f448bafdf729c3cec04bf0692560f/lib/msprime.c#L2480-L2485

but `self->recombination_rate` is rescaled by `4 * Ne` (`num_links` I guess isn't the real difference here):

https://github.com/tskit-dev/msprime/blob/a3197efe6a3f448bafdf729c3cec04bf0692560f/lib/msprime.c#L387-L391

where `generation_rate_to_model_rate` is

https://github.com/tskit-dev/msprime/blob/a3197efe6a3f448bafdf729c3cec04bf0692560f/lib/msprime.c#L4336-L4340

vs:
https://github.com/tskit-dev/msprime/blob/a3197efe6a3f448bafdf729c3cec04bf0692560f/lib/msprime.c#L4854-L4858
