### ISSUE TITLE
Math not rendering on stable RTD

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#843]
Latest works fine: https://msprime.readthedocs.io/en/latest/api.html

But stable doesn't: https://msprime.readthedocs.io/en/stable/api.html

They should be from the same commit at the moment, so I don't know what's happened here.

See also https://github.com/tskit-dev/tskit/issues/150

**Comment by petrelharp** [comment]
Looking at the source, the problem is that the latest has this line, loading mathjax:
```
        <script async="async" type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS-MML_HTMLorMML"></script>
```
but stable does not. This has got to be a rtd issue; when I build with sphinx locally this is included. Maybe forcing a rebuild of stable would fix it?

**Comment by jeromekelleher** [comment]
Just ran a rebuild now. Seems to have fixed it --- weird!
