### ISSUE TITLE
mean_recombination_rate() assumes the start of the map is position 0

### ISSUE THREAD

**Issue by grahamgower** [tskit-dev/msprime#844]
Given a genetic map like the example provided in the documentation (reproduced below), `RecombinationMap.mean_recombination_rate()` should give zero weight to the region 0-55550. Ie. it should be calculated to match `124.482178 / 100 / (183630013 - 55550)`, but current behaviour is to (effectively) calculate `124.482178 / 100 / 183630013`.

```
Chromosome  Position(bp)    Rate(cM/Mb)     Map(cM)
chr1        55550           2.981822        0.000000
chr1        82571           2.082414        0.080572
chr1        88169           2.081358        0.092229
chr1        254996          3.354927        0.439456
chr1        564598          2.887498        1.478148
...
chr1        182973428       2.512769        122.832331
chr1        183630013       0.000000        124.482178
```

**Comment by jeromekelleher** [comment]
Thanks for this @grahamgower. I confess I haven't fully digested this --- mind if we put it on the back burner till the new year?

**Comment by petrelharp** [comment]
Good catch.

**Comment by jeromekelleher** [comment]
Alternatively, should we require that genetic maps start with zero?

**Comment by grahamgower** [comment]
I'm not sure that we can require genetic maps start with zero. The hapmap files I've seen all start well away from zero. Presumably this is due to lack of information in the telomere region, not because the rate itself is zero.
