### ISSUE TITLE
Very high recombination rates result in malformed tskit output

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#846]
We found this from trying to run whole chromosome simulations for Drosophila models:

https://github.com/popsim-consortium/analysis/issues/56

It may be that it's unavoidable, but msprime should at least raise an error and not output a malformed tree sequence (it's unclear how export succeeded, in fact). We may be able to reproduce this by using a small number of loci and some extreme genetic map.

**Comment by petrelharp** [comment]
Damn. One fix would be to move to discrete space for recombination instead of this clever remapping thing.

**Comment by andrewkern** [comment]
oh boy

**Comment by jeromekelleher** [comment]
This should now be resolved in #862. Since this is very difficult to reproduce and we've fixed (what I assume is) the underlying issue, I'm going to close.
