### ISSUE TITLE
Simulation of multiple chromosomes

### ISSUE THREAD

**Issue by ivan-krukov** [tskit-dev/msprime#848]
It would be nice to add support for whole genome simulations of multiple chromosomes with explicit breaks between chromosomes (as opposed to large recombination distance). This will let us have consistent IBD and not to have to store extra information.

## The UI

I think it would be appropriate to require a list of recombination maps (as opposed to just one) if we want to simulate multiple chromosomes. Otherwise, the interface should be unchanged.

## The implementation

To begin with, in the context of Wright-Fisher simulation model, this should be relatively straightforward. We can add an extra flag to `segment_t` that indicates it as an inter-chromosomal gap. This will let us to include them in the regular chain of segments. When simulating, if we reach such gap, we switch to the other parental chromosome with probability of 1/2. 

I am not too sure how this would look in the Hudson model yet.

**Comment by petrelharp** [comment]
Chromosomes would be nice, I agree.

From the simulation point of view, there's no difference between separate chromosomes and an infinitesimal segment with recombination probability 1/2. The only difference is -as you say- on the data end. So, one approach would be to leave everything on the simulation side as-is, but extend the data format to include chromosomes, and not allow edges to cross chromosome boundaries.

I can't really think of an upside to making the simulation itself chromosome-aware? Except for allowing mixtures of sex chromosomes and autosomes in the DTWF model.

But, maybe I'm missing something?

So, here's another proposal: add another table to the underlying data structures, `chromosomes`, with columns `start` and `metadata`. And, keep working internally in the single coordinate system (which makes plotting nice anyhow), but give the option of converting to (chromosome, position) coordinates in output (somehow).

**Comment by jeromekelleher** [comment]
I agree with @petrelharp in that the actual changes required are more on the data format side than the simulation. There's a discussion on this over in https://github.com/tskit-dev/tskit/issues/176

If you're keen on following this up @ivan-krukov, perhaps we could organise a quick call?

**Comment by ivan-krukov** [comment]
I see. I need to carefully read through tskit-dev/tskit#176 to get better idea on what's happening.
My motivation for this was eventually implementing X and Y in DTWF. I see the current issue as a first step to that. I clearly have not done as much thinking on this. I would be happy to chat about this over other media.

**Comment by ivan-krukov** [comment]
In regards to chromosome-aware simulations. Is it the case that with the interchromosome distance of 0.5, we will still store a bunch of short edges which fall within the chromosome breakpoint? Taking the documentation example of [multi-chromosome sim](https://msprime.readthedocs.io/en/latest/tutorial.html#multiple-chromosomes), I get a large fraction (~20%) of events falling within this category.

More specifically:

```python
https://msprime.readthedocs.io/en/latest/tutorial.html#multiple-chromosomes
import msprime
import numpy as np

rho = 1e-8
positions = [0, 1e8-1, 1e8, 2e8-1]
rates = [rho, 0.5, rho, 0]
num_loci = int(positions[-1])

recombination_map = msprime.RecombinationMap(
    positions=positions, rates=rates, num_loci=num_loci)

sim = msprime.simulate(sample_size=100, Ne=1000, recombination_map=recombination_map, random_seed=1)

small = np.array([e for e in sim.tables.edges if (e.left >= 1e8-1 and e.right <= 1e8)])

print(len(small)/len(sim.tables.edges))
```

This seems problematic to me. The runtimes roughly decrease by 20% if I replace the 0.5 in `rates` by `rho` (in which case the fraction of "small" edges is 0).

**Comment by jeromekelleher** [comment]
Yes, this is definitely a problem, we should have a "clean break" between the chromosomes...

**Comment by jeromekelleher** [comment]
After a call with @ivan-krukov, @sgravel and @DomNelson we think the best approach is for msprime to return a list of tree sequences, one for each  chromosome, like:
```
recomb_maps = [msprime.RecombinationMap.read_hapmap(
    f"chr_{j}".txt", name=f"chr{j}") for j in range(1, 23)]
chrom_treeseqs = msprime.simulate(10, recomb_map=recomb_maps)
assert len(chrom_treeseqs) == 22
```

We might want to add some annotations/metadata to the individual tree sequences so that we know which chromsome each one is for (that's the idea of the ``name`` argument to ``read_hapmap``), but it's sufficient that they are returned in the same order. The nice thing is that we don't need any immediate upstream changes to tskit to make this work.

I guess the downside of this is that there is some redundancy in the individual tree sequences, since same node/individuals are going to appear in them. Probably not all that many though, I'm guessing. It seems quite a lot cleaner from an analysis perspective, in that finding the tree at position 10000 on chr 5 is straightforward.

Anyway, we can prototype this easily enough in the ``algorithms.py`` to see if the approach works and take it further from there later if it seems good.

**Comment by hyanwong** [comment]
I've idly been thinking about this, after reading @apragsdale 's [excellent documentation](https://github.com/tskit-dev/msprime/pull/1299) about simulating multiple chromosomes, which is something I've wanted to do for a while. I know there was previously [discussion](https://github.com/tskit-dev/tskit/issues/176) about implementing multiple chromosomes in tskit. Here's another suggestion: if we are making `ts.table.nodes` and friends a *view* into the tree sequence, could we have a multi-tree-sequence format as above, where we define a class `TreeSequenceCollection` which is a lightweight wrapper for a tuple of tree sequences, which actually *share* (in memory/on disk) the majority of the tables, apart from the edge table? If you wanted to grab one chromosome, and manipulate it, you would have to take a copy, in which case the tree sequence would be "detached" from the collection, and, if simplified, the nodes etc would no longer correspond. But as long as you operated on the collection of tree sequences, they would all stay with the same node IDs etc. We would have to implement versions of the standard manipulation methods, such as `.simplify()`, on the TreeSequenceCollection, which would have to be multi-ts aware, and leave in nodes that were referenced in one of the tree seqs in the collection but not another, etc.. But it might work, and be a way to implement separate chromosomes in msprime/tskit while retaining backwards compatibility? Im interested if @benjeffery thinks this might work or whether there's a fatal flaw in the idea.

**Comment by benjeffery** [comment]
Thanks for the suggestion @hyanwong - my main question is whether the benefits of such a scheme would be worth the added complexity compared to having a set of normal tree sequences. Also, to my mind the `chromosome` column way of doing this suggested in #176 seems more straightforward.

**Comment by hyanwong** [comment]
Thanks for the comments @benjeffery - I didn't know about the conditional numpy columns thing, so that sounds possible too. The benefit over a set of tree sequences is (1) you are guaranteed that the node IDs in the `TreeSequenceCollection` all refer to the same things in all the tree sequences: it should be impossible to make a `TreeSequenceCollection` with different node ids (and different provenances etc) - important for sample nodes, but also possibly for internal nodes if there is correlation between the tree sequences (2) space savings - probably minor, and (3) backwards compatibility - no need to make a "special" sort of TS, or adjust the current definition in any way, include extra columns, etc. You could also take an existing TS for (say chromosome 1) and "add" another one for chromosome 2, and you'd have a genome (albeit you would need to do some merging on the node tables somehow).

**Comment by hyanwong** [comment]
p.s. since tree sequences are immutable, you don't actually need to do the fancy thing about making multiple tree sequences have the same underlying node table - it's just a neat think to save storage space, and would mean that splitting a `TreeSequence` into a set of chromosomes in a `TreeSequenceCollection` wouldn't take up any more space.

**Comment by jeromekelleher** [comment]
One to consider for tskit version 1.0, but I don't think we can take this on now. It's a nice-to-have, being able to represent multiple chromosomes in the same file and all you say makes sense @hyanwong, but there's a lot of much more urgent problems we need to solve we have finite developer time.

**Comment by hyanwong** [comment]
Yes, there's no urgency in this. It just occurred to me, so I wanted to note it down somewhere, in case there was something in it.

**Comment by jeromekelleher** [comment]
I think this has been addressed pretty well now in the [documentation](https://tskit.dev/msprime/docs/latest/ancestry.html#multiple-chromosomes), so I'm going to close the issue.

Representing multiple tree sequences within a single file isn't something I see us doing for a few years.

**Comment by hyanwong** [comment]
I would actually quite like to tackle this myself, if I ever get round to trying to do pedigree reconstruction (in particular, sharing information about pedigree between chromosomes). I'm biased, of course, but I can't see any major problems with my suggestion above, and it retains backwards compatibility quite neatly. But I agree that there's no reason to keep this particular issue open - I'm just following up now too see if, (a) when I come back to this, it's the right way forward and (b) whether my suggested approach really is trivially backwards compatible, or if there are any gotchas (the only problem I can foresee is how to save a `TreeSequenceCollection`.

I imagine it as actually quite a minor piece of dev work, but I'm, probably just being optimistic.

**Comment by jeromekelleher** [comment]
I'm pretty certain it's not minor @hyanwong, and would be months of work.

**Comment by hyanwong** [comment]
Isn't it just a fancy wrapper for something like this:

```python
def to_multi_ts(ts, breaks):
    """
    return a tuple of tree sequences, one per chromosome
    (probably we would turn this into a class, and name the chromosomes)
    """
    tree_seqs = []
    for start, end in zip([0] + breaks, breaks + [ts.sequence_length]):
        tree_seqs.append(ts.keep_intervals([[start, end]])
    return tuple(tree_seqs)

def to_single_ts(multi_ts):
    """Take the tuple of tree sets and turn back into a single one"""
    # assert all the tables except edges are identical
    tables = multi_ts[0].dump_tables()
    tables.sequence_length = sum(t.sequence_length for t in multi_ts)
    pos = multi_ts[0].sequence_length
    for ts in multi_ts[1:]:
        edges = ts.tables.edges.copy()
        edges.left += pos
        edges.right += pos
        tables.edges.add_rows(edges) # this is not the right syntax
    tables.squash_edges()
    tables.sort()
    return tables.tree_sequence()
```

Any editing of the multi_ts would require you to convert it to a single ts and edit the tables. It would also need some footling around with provenance, and maybe the ability to save the multi_ts tuple. But you get the idea.
