### ISSUE TITLE
Redundant `docs/asy` make command?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime#854]
If I try ` make docs` in msprime, it calls `make figs` which is [instructed](https://github.com/tskit-dev/msprime/blob/cf8fd3c458de400a32a06aae2a1dff44496da4ae/Makefile#L17) to cd to `docs/asy`. But `docs/asy` does not exist in my local repo. Is this a left-over from an older version?

**Comment by jeromekelleher** [comment]
Yes, this is old, feel free to nuke.
