### ISSUE TITLE
Statistical tests for Dirac coalescent

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#860]
This issue is to track where we are at with statistical tests for the dirac coalescent code.

Right now it looks like we have some tests that we get the same thing as the Hudson code in a limit for the Dirac coalescent [here](https://github.com/tskit-dev/msprime/blob/master/verification.py#L2401).

What other tests can we do?

cc @eldonb and @JereKoskela

**Comment by JereKoskela** [comment]
Similarly to #859, we should check that the empirical correlation between coalescence times of 2 loci in a sample of size 2 matches the analytic formula here:

[two_locus_correlation.pdf](https://github.com/tskit-dev/msprime/files/4192201/two_locus_correlation.pdf)

In addition, we should replicate the X(p) = 0.05 and X(p) = 0.95 sections of Figure 3 in [Blath et al (2016)](https://www.sciencedirect.com/science/article/pii/S0040580916300053).

Taken together, these two tests will validate that the merger rates are what we want them to be, and the recombination rate is what we want it to be.

**Comment by eldonb** [comment]
how are we sampling the times for the Xi-coals ?  If we are using the poisson process approach of Jere by sampling uniforms, and drawing  from a Beta in the case of  the Xi-beta coal (?), we could also check that this is correct by  comparing densities of the times  to  that  obtained by  sampling times directly from the rates, we could  do this for small sample sizes  and  we should get a  very good match

**Comment by jeromekelleher** [comment]
Closed in #957 and #953
