### ISSUE TITLE
Tree decapitation

### ISSUE THREAD

**Issue by winni2k** [tskit-dev/msprime#867]
I'm not sure this is a sensible thing to do, but I would like work with a partial ("decapitated") tree that only contains the first X generations back in time. Is there a way to tell the `simulate` function to stop simulating X generations back in time?

**Comment by jeromekelleher** [comment]
Sure, this is already supported. See the ``end_time`` argument to [simulate](https://msprime.readthedocs.io/en/stable/api.html#msprime.simulate)

**Comment by winni2k** [comment]
Cheers!
