### ISSUE TITLE
[C code] Fix verify_overlaps to work on continuous coordinates

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#875]
We don't have any C level test coverage for the continuous coordinates and we should make sure that the basic mechanisms are working.

I suggest we update the verify_overlaps algorithm to use a simple linked list based approach, where we use a list of segments to count how many of the extant segments overlap with each interval. We start off with a single interval [0, L] which has 0 segments overlapping it. We then iterate through all the individuals and their segments and update this list, performing a linear search each time to find the appropriate interval, and breaking it as needed. This shouldn't be too complicated to do, and can reuse the ``msp_alloc_segment/free_segment`` infrastructure to handle the memory management (using the ``value`` field on msp_segment_t as the counter).

It'd be sensible to do this in Python in algorithms.py first, where we also have some verification logic.

How does this sounds @daniel-goldstein?

**Comment by daniel-goldstein** [comment]
Sounds good, this seems reasonable.
