### ISSUE TITLE
[stats tests] Add checks for hotspots when simulating in continuous coords

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#877]
All existing hotspot tests are in the case of discrete coords as we're comparing the msHOT. Run a test comparing breakpoint positions in msprime Hudson when we have discrete and continuous coords (should probably check in DTWF also, see #876)

**Comment by daniel-goldstein** [comment]
I've added tests for comparing simulations in continuous vs discrete coordinates [here](https://github.com/daniel-goldstein/msprime/tree/continuous-recomb-tests), but am getting some weird results, at least I think. The breakpoint distributions are mostly reasonable, although a bit asymmetrical, but the continuous case is producing far more trees than the discrete case. Here are those two plots run with the same recombination map, except for the `discrete` flag. The comparisons to msHOT look fine when running msprime as discrete or continuous, but those use the simulator and not the resulting tree sequences to get stats. Am I missing something here or should `ts.num_trees` be the same here in both cases and there's some problem? This problem also arises in the uniform case, but not so drastically, and more for DTWF than for Hudson.

![compare continuous and discrete coordinates_breakpoints](https://user-images.githubusercontent.com/24440116/74533020-7e089800-4f28-11ea-81e8-7530a1fa6980.png)
![compare continuous and discrete coordinates_num_trees](https://user-images.githubusercontent.com/24440116/74533021-7ea12e80-4f28-11ea-839a-49bc94c8c91d.png)

**Comment by jeromekelleher** [comment]
The number of trees can be less than the number of breakpoints. That's because we sometimes have events that join segments that look like (x, y), (y, z) back together, which results in the end tree getting to (x, z).

**Comment by jeromekelleher** [comment]
This is the reason we get the number of breakpoints from the simulator, because things like ms don't squash together identical trees in the output. So, the output looks fine I'd say. What's the second plot here?

**Comment by daniel-goldstein** [comment]
I see, how should squashing together trees behave in the continuous case? The second plot compares `ts.num_trees`, showing far more trees in the continuous case, maybe because endpoints are not *exactly* the same?

**Comment by jeromekelleher** [comment]
It should work just the same in the continuous case (you can check if you like: iterate over the trees and see if there's any very small gaps between trees). I think it makes sense that we'd have more trees in the continuous case, as recombinations are bound the hit the same places in the discrete case. Looks like you need to reduce the recombination rate and make the sequence length longer if you want the discrete and continuous cases to look similar.

**Comment by daniel-goldstein** [comment]
Makes sense, looks like I was just underestimating the scale here! Do you think it's useful then to see the number of trees (under more comparable parameters) or stick to breakpoint distributions?

**Comment by jeromekelleher** [comment]
Probably simpler to work with num_trees, when we're not comparing with ms or with analytical results.

**Comment by daniel-goldstein** [comment]
not sure what you mean. I was asking if I should keep both plots or just keep the breakpoint distributions. All these tests are comparing msprime to itself. Can confirm though that they align more nicely after increasing the sequence length.

**Comment by jeromekelleher** [comment]
OK good, thanks. Ignore previous comment, not sure what I was talking about there!
