### ISSUE TITLE
Update GC code to use physical coordinates

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#879]
Since #862, we're simulating internally using physical coordinates which should get rid of a lot of headaches (e.g., #851 should no longer be an issue).

However, the code needs to be reviewed carefully now to make sure bugs weren't introduced.

In particular, it looks like the GC doesn't take into account the distinction between discrete and continuous coordinates.

**Comment by fbaumdicker** [comment]
I spotted some GC related bugs/issues and will try to nail them down. In particular, the verification keywords _gene-conversion-2-tl-10_,  _gene-conversion-2-tl-100_, and _analytical_corr_same_tree_ fail atm.

**Comment by jeromekelleher** [comment]
Thanks @fbaumdicker , sorry for breaking your code!

**Comment by fbaumdicker** [comment]
The GC code needs discrete coordinates. There is no good way to define the track length of a gene conversion in continuous coordinates. A recombination map with a local low or zero recombination mass would create gene conversions that have much larger track lengths than expected.

**Comment by petrelharp** [comment]
I think you mean that GC needs physical coordinates, rather than coordinates in recombination distance?

**Comment by fbaumdicker** [comment]
Yes and no. However, the length of the gene conversion track is determined by a geometric distributed random variable at the moment. For a nonuniform recombination map, the goal is to initiate the left side of the gene conversion events proportional to the recombination rate. The track length will be independent of the local recombination rate and geometric distributed.
For a uniform recombination map the same is true unless the recombination rate is zero.

**Comment by jeromekelleher** [comment]
Sounds good @fbaumdicker, I forgot about the complexity of dealing with the case of having a zero recombination rate everywhere...

Re discrete vs continuous coordinates though, I don't see the problem. Once the coordinates are in physical space, then surely the difference is just having a geometric vs an exponential distribution for track lengths?

**Comment by fbaumdicker** [comment]
Switching to an exponential distribution should be easy, but in my opinion, it would be harder to determine the appropriate rate for the random variable determining the track length. The rate will depend on the underlying sequence length which might not be known.
