### ISSUE TITLE
[C Code] Handling of rate conversions

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#881]
In the C code we currently have a mix of methods for handling rates. Pre #862, all rates were converted from generations into model time when the model is set. Currently we don't do this for recombination, and the recombination 'masses' stored in the Fenwick tree are in generation rates, and we convert to model rate in the main loop [here](https://github.com/tskit-dev/tskit/blob/master/c/tskit/tables.c#L5649).

This is OK, but somewhat and a little inefficient maybe. It seems better to convert the recombination rates to model time along with all the other rates, but this would involve editing the recombination map, which is provided as input (and therefore we shouldn't modify it).

An easy fix would be to take a copy of the recombination map in the simulator, and to update the rates in that we we see fit. The extra memory and copy time will be negligible and it should keep things a bit simpler.

Unless some objects? @fbaumdicker, @petrelharp, @andrewkern, @daniel-goldstein?

**Comment by petrelharp** [comment]
This sounds *very* sensible. The less converting between different time scalings the better.

**Comment by jeromekelleher** [comment]
OK, let's do this then.

**Comment by daniel-goldstein** [comment]
Got this mostly wrapped up pretty simply but hit a snag. Since we cache recombination masses in the segments themselves, we would have to update all extant segments whenever we switch models mid-simulation. Is this ok?

**Comment by jeromekelleher** [comment]
Hmm, yes, I guess this can't be avoided. That's OK though, it's fine that model switching is a linear operation.
