### ISSUE TITLE
Document likelihood calculations

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#883]
We need some documentation for the likelihood calculations. A section in the API docs plus a short tutorial section showing how it works would be idea.

**Comment by JereKoskela** [comment]
Hi @jeromekelleher. I'm trying to get a draft of the API written for this, and have run into a question. Where is the output of things like `.. autofunction:: msprime.simulate()` defined? It seems to generate much more text than just, say, an argument list, and presumably all of it is not extracted automatically from the code. I presume the best way to introduce the calculations would be to document `.. autofunction:: msprime.log_arg_likelihood` and `.. autofunction:: msprime.unnormalised_log_mutation_likelihood`, but let me know if you were expecting something different.

**Comment by jeromekelleher** [comment]
The documentation is generated by [sphinx](https://www.sphinx-doc.org/en/master/), which includes things like [autofunction](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#directive-autofunction)

Probably we'll want to have some fairly terse documentation associated with the functions themselves describing the inputs and outputs and then maybe a new page like ``likelihood.rst`` in which we describe the calculations themselves and give links to the functions.

Feel free to ping me offline if you want some help with getting this set up - might be most efficient to have a quick chat rather than back-and-forthing here.

**Comment by jeromekelleher** [comment]
Closed in #932.
