### ISSUE TITLE
[sweeps] Document model change event to Hudson and test

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#884]
We need a simple way to transition to the Hudson model after a sweep has completed. This should be done with a ModelChangeEvent, but we need a way to leave the time unspecified. Using np.inf should work here.

Test this approach to make sure it works as expected.

**Comment by andrewkern** [comment]
was trying to think of a reasonable test for this. it should be that under the SweepGenicSelection() model many trees are not fully coalesced whereas if we let them then transition models to StandardCoalescent() everything. maybe we could use `Tree.num_roots` here?

**Comment by jeromekelleher** [comment]
Yep, that sounds exactly right. We need to choose the parameters so that the sweep *some* coalescing, but not too much. We should have 1 < tree.num_roots < ts.num_samples. Then rerun the same sim with the ModelChange event and tree.num_roots should be == 1.

**Comment by andrewkern** [comment]
i can work on this today. should i put such a test in verification.py or somewhere else?

**Comment by jeromekelleher** [comment]
In [this class](https://github.com/tskit-dev/msprime/blob/master/tests/test_models.py#L552), ideally. Should be quite small to keep things quick.

**Comment by andrewkern** [comment]
can you assign me to this issue so that it shows up on my queue?

**Comment by jeromekelleher** [comment]
Done
