### ISSUE TITLE
Error using default msprime.simulate settings

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/msprime#887]
Maybe this isn't supposed to work yet (close this issue if the behaviour is expected), but I got the following error when I installed the latest development version of msprime and tried to run a simple simulation:

![Screen Shot 2020-02-07 at 3 44 16 pm](https://user-images.githubusercontent.com/17755074/74001873-426a4d00-49c1-11ea-9672-c78488f5bdff.png)

**Comment by petrelharp** [comment]
Odd - it works for me. Did you remember to `make` as well as installing? Here's the version I've got:
```
>>> ts = msprime.simulate(sample_size=4)
>>> msprime.__version__
'0.7.5.dev45+ng535f0ea'
```

**Comment by jeromekelleher** [comment]
Yes, this is probably because you didn't recompile the low-level module. Try running 'make'

**Comment by gtsambos** [comment]
right 😅  sorry for the spam and thanks for the extra eyes!
