### ISSUE TITLE
[Docs] Fix recipe for multiple chromosomes

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#888]
The tutorial recipe for muliple chromosome uses num_loci. Fix.

https://msprime.readthedocs.io/en/stable/tutorial.html#multiple-chromosomes

**Comment by DomNelson** [comment]
I wonder if it's worth adding a note explaining why DTWF is preferred for multi chromosome sims, or at least a reference. It's used in the example but not mentioned beyond that.

**Comment by jeromekelleher** [comment]
This has been moved, now in the [sim_ancestry](https://tskit-dev.github.io/msprime-docs/main/ancestry.html#multiple-chromosomes) docs, under the "genome properties" heading. We should definitely point out that the DTWF is preferred for this.

@apragsdale any chance you can bring this up to date and add some text explaining the strategy?

**Comment by apragsdale** [comment]
I can have a go at it. There was some discussion over here a little while back: #1005. I'm not really up to date on recent developments and I don't have a handle on the discrete recombination map option right now, so I should first make sure I understand what the changes this year have been. But yes, I'll work on that section of the docs.

**Comment by jeromekelleher** [comment]
Ah yes, thanks @apragsdale. Closing in favour of #1005
