### ISSUE TITLE
Modernise RecombinationMap interface

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#902]
The RecombinationMap interface is clunky, using a lot of Java style 'getter' methods. Modernise this to use properties, where appropriate.

We also want to use numpy arrays natively in the low-level interface (we currently use lists). So, we should be able to use ``recomb_map.position`` to get the position array and ``recomb_map.rate``  to get the rate array (we should use the singular following the conventions in tskit).

**Comment by jeromekelleher** [comment]
Add tests for this to the TestRecombinationMap class in tests/test_highlevel.py

**Comment by jeromekelleher** [comment]
I tried to assign this to you @grahamgower, but you weren't on the list. Not sure what's up with GitHub.

**Comment by hyanwong** [comment]
The 4 line numpy code that I posted in https://github.com/tskit-dev/msprime/issues/919#issue-584423306 and which is essentially used in the unit testing basically describes the behaviour that I would expect - being able to pass in a numpy array of physical positions and get out a numpy array of genetic positions. I suspect this is likely to be a common use case (e.g. I'm passing in all the site positions from a TS)

**Comment by jeromekelleher** [comment]
See also #920 for proposal on more generic interface for rate maps. Pinging @daniel-goldstein for input here.

**Comment by daniel-goldstein** [comment]
As a final product I think this most naturally fits as a method on interval rate maps that recombination map can directly wrap. Once we can access the underlying arrays as numpy arrays we have the following in an interval rate map:
```
def position_to_cumulative_rate(input_pos):
    return np.interp(input_pos, self.position, self.cumulative)
```

which takes care of both the single value and the array of values cases.

**Comment by jeromekelleher** [comment]
Closing in favour of #1172
