### ISSUE TITLE
[Sweeps] Retune parameters in sweep test

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#910]
#906 fixed an issue in the sweeps code where recombination rates were computed in generations rather than model time. This broke [this test](https://github.com/tskit-dev/msprime/blob/master/tests/test_models.py#L649)

Retune the parameters so that we get some recombination within the sweep (it'd be nice to fully coalesce too, but I guess we can add a hudson phase at the end if needs be.)

**Comment by jeromekelleher** [comment]
@andrewkern, was this fixed in your last PR?

**Comment by andrewkern** [comment]
yup we can close this out

**Comment by jeromekelleher** [comment]
Closed in #1101
