### ISSUE TITLE
Add pepy download badge

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#916]
There's a badge provided by [pepy](https://pepy.tech/project/msprime) which gives the total number of downloads (100k apparently!). Add this to the README

**Comment by molpopgen** [comment]
Plus all of these, presumably? https://anaconda.org/conda-forge/msprime

**Comment by jeromekelleher** [comment]
Yep, we should probably add the conda badge too, that'd be nice.
