### ISSUE TITLE
Reimplement recombination_map.physical_to_genetic()

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime#919]
It would be useful to be able to provide a list of physical positions to a genetic map and obtain a list of genetic positions. In my particular case, I want the "recombination distances" between a set of physical loci to help guide inference, which I can get by using `np.diff` once I've got the genetic coords from the physical ones.

There is already a method [`RecombinationMap.physical_to_genetic()`](https://github.com/tskit-dev/msprime/blob/ed4879ad923eeb0119752f51e5f96c5e9cb9f1d2/msprime/simulations.py#L1120) but it raises a "Genetic space is no longer supported" error. I suggest we reinstate this using something like the following code:

```
def physical_to_genetic(recombination_map, input_physical_positions):
    map_pos = recombination_map.get_positions()
    map_rates = recombination_map.get_rates()
    map_genetic_positions = np.insert(np.cumsum(np.diff(map_pos) * map_rates[:-1]), 0, 0)
    return np.interp(input_physical_positions, map_pos, map_genetic_positions)
```

**Comment by hyanwong** [comment]
Other sorts of interpolation are possible, of course, but linear is the most easy to justify, I presume.

**Comment by jeromekelleher** [comment]
We want to exactly duplicate the old API and old behaviour for backwards compatability. Resurrecting the old test cases should be easy enough.

@daniel-goldstein, how much work is this do you think?

**Comment by daniel-goldstein** [comment]
I think that should be pretty simple, since it doesn't alter the map or any of its invariants. The old API just translates a given point to and from the two spaces. Would you want to bring back only these translating methods?

**Comment by jeromekelleher** [comment]
Well, we'd like to bring back the old Python methods without the C code (so, implement using numpy like above, ideally). Ideally then the old test cases could be slotted right back in.

Once that's done and committed, and more modern numpy-like API could also be added.

**Comment by hyanwong** [comment]
@awohns - you were interested in this functionality. You can use the code above, or even implement and submit as a PR before @daniel-goldstein gets to it, if you like!

**Comment by daniel-goldstein** [comment]
Sorry for the delay on this but I should have a PR up soon. The old tests were pretty out of date so currently refactoring them to not use `num_loci`

**Comment by daniel-goldstein** [comment]
@jeromekelleher Is this not the same as converting between recombination mass and position? We already have those methods in C.

**Comment by jeromekelleher** [comment]
> @jeromekelleher Is this not the same as converting between recombination mass and position? We already have those methods in C.

Yes, it probably is (but you'll know better than me at this point). It might be easier then to pass the methods all the way through?

**Comment by daniel-goldstein** [comment]
Ya I think passing the methods through is the right way to go. Especially if innards of RecombinationMap change soon we wouldn't want them to stray apart. Plus the code above recomputes what we have in C as `cumulative`
