### ISSUE TITLE
simulate with `from_ts` removes previous provenance entries

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/msprime#924]
This bug was introduced in c2bf47a2ac59f9b8281647e63d4a8414786d4431. MWE:
```
ts = msprime.simulate(10, end_time=0.2)
rts = msprime.simulate(from_ts=ts)
print("Has ", rts.num_provenances, "provenances")
```
This prints `Has  1 provenances`, but should print `Has  2 provenances`.

**Comment by petrelharp** [comment]
Looks like the problem is [here](https://github.com/tskit-dev/msprime/commit/c2bf47a2ac59f9b8281647e63d4a8414786d4431#diff-3af8c5bda4976d0bd25e9e5754497a74R792) - this comment appears to be incorrect.

**Comment by benjeffery** [comment]
This isn't a bug in how I was thinking of `from_ts` provenance. The comment could be clearer and means `ts` (and its provenance) are in `rts`'s provenance and can be found by `parse_provenance(rts)[1]['from_ts']`. 

I can see how it  also makes sense to have two `simulate` entries in a provenance, although it would then implicit that the value of `from_ts` is result of the previous provenance entry.

**Comment by petrelharp** [comment]
First off, I'm very impressed at how what's in provenance can recreate the tree sequence itself. It's very nice.

So, here's how I hit this - in pyslim, we often take a SLiM-produced tree sequence (which is usually very big, note) and *recapitate* it, which is a front-end to `msprime.simulate(from_ts=...`).

For me - or, for SLiM - to find the previous SLiM-produced provenance entry we need to have it actually in the provenances. More generally, I think it's much better, and much more in the spirit of `provenance`, to have `simulate( from_ts=...)` add a new entry onto the provenance rather than hiding previous steps inside of a sort of nesting doll structure. 

Also, I'm worried about the file size implications of keeping the whole entire previous tree sequence as text in the provenance - is that really what it does? That's going to bite an awful lot of people, I think.

**Comment by jeromekelleher** [comment]
None of this has been released so we should just roll back on the ``from_ts`` being encoded as text thing. It's really not that important to be able to round trip a simulation like this, and just having ``from_ts=something`` will do fine I'd imagine.

**Comment by benjeffery** [comment]
Yep, I'm happy with that, as long as we don't envisage methods that take two tree sequences as input? (Probably overthinking this)

**Comment by jeromekelleher** [comment]
> Yep, I'm happy with that, as long as we don't envisage methods that take two tree sequences as input? (Probably overthinking this)

No, I can't imagine there ever being two tree sequences as input.

A lot of the time the ``from_ts`` will be coming from a file, so I think we can use the ``file_uuid`` attribute. When this is undefined because we're using a tree sequence not read from a file we can use some marker value to indicate that.

Or, we could take the MD5 sum of the tables? It's a bit more work (and should be done at the tskit side ideally, I guess), but is probably the right thing to do from a provenance perspective.

**Comment by petrelharp** [comment]
The file uuid would be more useful than an md5 sum in terms of actually figuring out what the provenance said happened...

**Comment by jeromekelleher** [comment]
Most of the tree sequence is still present after we recapitate though, as we're just adding on nodes and edges IIRC (I think we don't allow mutations when ``from_ts`` is used). So, I guess in you could use dict of table offsets to describe the input tree sequence in the provenance (and the file_uuid as well, I guess, since there's no harm in it and it could be useful, as you say)?

**Comment by petrelharp** [comment]
The table offsets are a good idea but I worry there's tricky aspects we're not thinking of.  I don't mind too much exactly what we do, but I'd like to pick something and do it - Ben Haller is waiting on this to release something...

**Comment by jeromekelleher** [comment]
It doesn't really matter from SLiM's perspective though, right? As a matter of principle we're going to keep original provenance intact, it's just the exact formatting of msprime's provenance we're discussing. 

I'll have a go at the table offsets thing once I get #893 shipped away. I'll open an issue to track.

**Comment by petrelharp** [comment]
Oh yeah - SLiM doesn't care about the recapitation provenance.
