### ISSUE TITLE
Clarify documentation on population metadata with ``initial_state``

### ISSUE THREAD

**Issue by grahamgower** [tskit-dev/msprime#925]
```
>>> msprime.__version__
'0.7.5.dev95+ng022fdb2'
>>> ts = msprime.simulate(end_time=0.2, population_configurations=[msprime.PopulationConfiguration(sample_size=10, metadata="foo")])
>>> ts.population(0)
{'id': 0, 'metadata': b'"foo"'}
>>> ts2 = msprime.simulate(from_ts=ts, population_configurations=[msprime.PopulationConfiguration(metadata="bar")])
>>> ts2.population(0)
{'id': 0, 'metadata': b'"foo"'}
```

**Comment by jeromekelleher** [comment]
Hmm - should it though? It's not clear to me that a ts transforming program should clobber existing metadata. Ideally, I guess, the program should **add** to the metadata, if it needs to. However, we don't have the infrastructure in place in tskit to enable this yet.

I think we should handle this at the stdpopsim side for now, until we have decided what the right protocol is in general for passing through metadata.

(@grahamgower, would you mind linking back to the stdpopsim issue where we hit this problem please? I've lost track of where things are!)

**Comment by jeromekelleher** [comment]
Linking to https://github.com/tskit-dev/tskit/issues/57 for reference, and cc'ing @benjeffery.

**Comment by jeromekelleher** [comment]
ah, here is the stdpopsim issue: https://github.com/tskit-dev/tskit/issues/57

Please ignore the request above Graham.

**Comment by grahamgower** [comment]
> Hmm - should it though? It's not clear to me that a ts transforming program should clobber existing metadata.

Yeah, I think an argument can be made for both cases. Either way, a note in the docs is probably warranted.

**Comment by jeromekelleher** [comment]
Related to #1528 (fix should also close this)
