### ISSUE TITLE
Documentation for species tree parsing

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#931]
#893 and #929 added species tree parsing. This has a good basis for documentation, but needs some more details

- Need to have sphinx annotations for the parameters and return values. Also need to describe in detail the algorithm used to translate the species tree into population configurations and what happens in terms of which population goes where. The ordering of the populations and the use of metadata needs to described here.
- Need to add a section to api.rst for species trees, which adds autofunctions for the two parsing functions with a small discussion at the start.
- Need to add a section to the tutorial to explain. We probably want a drawing of a simple species tree here, and an explanation of what has happened. We can use some of the examples in the ``species_tree_parsing_examples.py`` file (which we should then delete from the repo).
- Add to CHANGELOG

**Comment by mmatschiner** [comment]
Sounds good, I'll work on that as soon as possible. Thanks for merging!

**Comment by mmatschiner** [comment]
I think I'm done with bullet points 1, 2, and 4, and will work on a tutorial section next.

**Comment by jeromekelleher** [comment]
That's great! Perhaps we could do a PR for what you have and get that much merged?

**Comment by mmatschiner** [comment]
I'm on the tutorial section right now, and should finish that later today or tomorrow. Should we wait that long with the PR?

**Comment by jeromekelleher** [comment]
It's up to you, probably as well to finish it up if you're that close.

**Comment by mmatschiner** [comment]
Ok, I wrote a tutorial section now. It's not short compared to other sections but it doesn't contain an example of a StarBEAST tree yet. I'm not sure if one should be added, what do you think? I'm making a pull request now, but just let me know if you also want an example with a StarBEAST tree.

**Comment by mmatschiner** [comment]
If no further example is needed, feel free  to delete file species_tree_parsing_examples.py.

**Comment by jeromekelleher** [comment]
I don't think we need an example of a StarBEAST tree, it should be pretty clear how to use it. We can delete the ``species_tree_parsing_examples.py`` file.

**Comment by jeromekelleher** [comment]
There is good API docs for this now.
