### ISSUE TITLE
Docs for finite-sites features

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/msprime#950]
In #945 (soon to be pulled in) I've made some placeholder sections in the RTD tutorial for finite sites recombination/mutation models. Someone will need to write these. I'm happy to give it a stab, but perhaps it would be better if it was done by someone who was involved in the implementation? (@daniel-goldstein? @DomNelson?) Let me know what you think.

**Comment by jeromekelleher** [comment]
This is a great idea - once @petrelharp's #946 PR is in we should make a pass at documenting and making a tutorial for this stuff. This should be pretty high up in the "fundamental features" part of the tutorial.

**Comment by jeromekelleher** [comment]
See #880 also.

**Comment by daniel-goldstein** [comment]
Not sure I know what examples would be best for the tutorial but I'm happy to take it on if we can hash out what it should look like. Maybe at the next meeting?

**Comment by petrelharp** [comment]
Excellent! Here's a list of a few things I put in a different issue (which is subsumed in this one, whoops):

-    a mutation map
-    a built-in mutation model
-    a user-defined mutation model
-    discrete or not
-    keeping or not, and when you're allowed to

A use case is: say you have an annotation of the genome and want to apply different mutation processes to different annotations (eg Jukes-Cantor here and CpG there).

**Comment by jeromekelleher** [comment]
See also #1005

**Comment by jeromekelleher** [comment]
I'm going to close this one out in favour of more focused issues based on the new docs reorganisation. Basically, the TODO placeholders in the "simulating mutations" section should cover all the above.
