### ISSUE TITLE
`test_dict_encoding.py` fails?

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/msprime#956]
On current master (58c2585bd0fbc08e9fe5d527bbc91143aecffccd), I get a bunch of errors from `test_dict_encoding.py`, for instance:
```
$ python3 -m nose tests/test_dict_encoding.py
FFF.FF................
======================================================================
FAIL: test_two_rows (tests.test_dict_encoding.TestBadLengths)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peter/projects/tskit-dev/msprime/tests/test_dict_encoding.py", line 204, in test_two_rows
    self.verify(2)
  File "/home/peter/projects/tskit-dev/msprime/tests/test_dict_encoding.py", line 201, in verify
    lwt.fromdict(d)
AssertionError: ValueError not raised
-------------------- >> begin captured logging << --------------------
msprime.simulations: DEBUG: Setting initial model {'name': 'hudson', 'reference_size': 1}
msprime.simulations: DEBUG: Running simulation until maximum: inf
--------------------- >> end captured logging << ---------------------
```

This is strange since it's passing CI tests - must be a different library somewhere? I'm on current master, submodules are updated, and I've run `make`. I'm not sure what to check - any ideas?

**Comment by jeromekelleher** [comment]
They're also passing locally for me. Have you definitely cleared out any old ``.so`` files? Try
```
rm -fR build *.so
make
```
that should force a full rebuild.

Ah, also, is there any chance you've ``pip install -e`` this or something? Try running `python -v -m nose`` and see where ``_msprime_xxx.so`` is being pulled in from.

**Comment by petrelharp** [comment]
Cleaned up and did a full rebuild; same thing; and am using the right `.so`:
```
# extension module '_msprime' loaded from '/home/peter/projects/tskit-dev/msprime/_msprime.cpython-37m-x86_64-linux-gnu.so'
```

I've checked on our cluster and the tests pass there. On the other hand, I get the same errors on a different Debian box.  Same with 0.7.4. I'll ask around if I can find anyone else this is happening to.

**Comment by jeromekelleher** [comment]
Weird - I just ran the tests on a Debian buster machine and they pass fine.
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

**Comment by petrelharp** [comment]
I'm on sid but it's a bit out of date. If I can't turn up anyone else with the problem I'll close it.

**Comment by molpopgen** [comment]
Everything passes for me on Ubuntu 19.10.  All my dependencies are pip3 installed locally for my user.  Only oddity was this warning: `GSL error: exceeded max number of iterations`

**Comment by jeromekelleher** [comment]
> Only oddity was this warning: GSL error: exceeded max number of iterations

That's expected (testing out whether some numerical integrations in Xi coalescents failed as expected, writing some messages to stderr seemed the least icky way to get some info to the user in this remote corner case. But the numerical integration is being removed now anyway.)

**Comment by petrelharp** [comment]
No-one here can reproduce it; I'll close this and will re-open if I ever figure out what's going on.

**Comment by petrelharp** [comment]
Ah-ha - this depends on the tskit version: the errors occur with `master`, but not `0.2.3`. Maybe this should be a tskit issue, since behavior there seems to have changed?

**Comment by grahamgower** [comment]
Could it be that you need to do `git submodule update` in your tskit folder?

**Comment by jeromekelleher** [comment]
Right, so the problem is that we have extra fields in the tables in tskit master. This is largely harmless, I think, but we will need to do a bit of coordinating around the release of tskit 0.2.4. See tsikt-dev/#549 for details on this.

In the meantime, the advice for devs is "don't install tskit master". If you're happy with this, can you close the issue please @petrelharp?

**Comment by petrelharp** [comment]
> Right, so the problem is that we have extra fields in the tables in tskit master. This is largely harmless, I think,

Ah, ok - that makes sense. I believe that this is harmless.

>  the advice for devs is "don't install tskit master". If you're happy with this

Hm, I'm not sure - it seems like our intention is to not break things, and we've already found another bug in tskit thanks to using master? I agree that since this seems harmless it's not a high priority.

**Comment by jeromekelleher** [comment]
> Hm, I'm not sure - it seems like our intention is to not break things, and we've already found another bug in tskit thanks to using master? I agree that since this seems harmless it's not a high priority.

I don't think there's any alternative in the short term, unless we update the tests to deal with the extra fields being both there or not. That seems like extra work to me.

**Comment by petrelharp** [comment]
> unless we update the tests to deal with the extra fields being both there or not.

Ok, fair enough - as long as we're clear that there are maybe breaking changes in tskit, which I wasn't aware of?  Is this only happening because of the shared (lwt) code between the two?

**Comment by jeromekelleher** [comment]
> Ok, fair enough - as long as we're clear that there are maybe breaking changes in tskit, which I wasn't aware of? Is this only happening because of the shared (lwt) code between the two?

No, there's no actual bugs here, everything is working as it should. What's happened is the lwt code in msprime (which is a source **copy**) of the code in tskit has gotten out of sync with the upstream code in tskit. The code is copied as this was the least bad option (as I went through elsewhere). And it's working really well - if we hadn't done this and tried to do some clever linking between msprime and the tskit C code, we'd be chasing segfaults right now.

The solution is to update the lwt code in tskit, and then when tskit 0.3 is released, copy this over to msprime and tsinfer, and state they require tskit >= 0.3. This is what's outlined in #tskit-dev/tskit#549

**Comment by petrelharp** [comment]
Great - glad we're on the same page. Sorry for the noise.
