### ISSUE TITLE
Change ``parse_species_tree`` to return Demography object.

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#958]
Currently parse_species_tree returns a tuple ``(pop_configs, demographic_events)``. The idiomatic way of calling this is 

```python
pop_configs, demographic_events =parse_species_tree()
```

This is fine, but it's possible that we'll want to return more stuff from parse_species_tree at some point, and then we'll be in a tricky situation. It seems possible that we'll return a migration matrix as well, for example.

To make this more extensible, we could turn the configuation as a namedtuple, such that the idiomatic methods is 
```python
config = parse_species_tree(...)
ts = msprime.simulate(
     samples=# something
     population_configurations=config.population_configurations,
     demographic_events=config.demographic_events)
```

This can be made even easier, with
```python
config = parse_species_tree(...)
ts = msprime.simulate(
     samples=# something
     **config._asdict())
```

The changes needed are pretty small.

Any thoughts @mmatschiner?

**Comment by benjeffery** [comment]
One thing to consider (that you mentioned on a call @jeromekelleher) is to use `attr`:
```python
@attr.s(slots=True, frozen=True, kw_only=True, auto_attribs=True)
    class _ParseSpeciesTreeReturn:
        population_configurations: List[msprime.PopulationConfiguration]
        demographic_events: List[msprime.DempgraphicEvent]
```
This gives you an immutable class that can only be init' d by keyword (to avoid ordering errors).

**Comment by jeromekelleher** [comment]
Yes, good idea @benjeffery. The downside is we don't currently depend on ``attrs``, so we'd need to pull in a dependency (but a good dependency, which we should probably start using to make the code cleaner anyway). The upside (from a user perspective) is we can use  ``config.asdict()`` rather than ``config._asdict()`` (which I know I'd forget and have to keep looking up).

Do we get some documentation for free with your nice type-hints @benjeffery?

**Comment by benjeffery** [comment]
I wanted to talk `attr` over anyway as I'm using in in the metadata branch in `tskit`. I haven't looked into the docs yet, especially for this specific case with `attr` (was planning to as part of the metadata work) but I'm hoping that we can get the docs to use the type hints wherever we use them.

**Comment by jeromekelleher** [comment]
OK, let's assume we're using ``attrs`` so. If we're already pulling it in for tskit, then there's no reason not to use it here.

**Comment by mmatschiner** [comment]
As I'm unfamiliar with `attr`, I updated to the first and simplest example given by @jeromekelleher in https://github.com/tskit-dev/msprime/issues/958#issue-603039444 . I think this example is easy to understand for users reading the tutorial. But feel free to change it to use `attr` if you prefer.

**Comment by jeromekelleher** [comment]
I can follow up with this change @mmatschiner, but let's get your excellent documentation in first. I'll ping you for a review when it's ready to make sure we're all happy with the change.

**Comment by mmatschiner** [comment]
Sounds good, thanks!

**Comment by jeromekelleher** [comment]
Also a thought I had here is that we can improve the usability by making this result object able to create samples, like
```python
config = msprime.parse_species_tree(...)
msprime.simulate(
     config.make_samples(5, 4), # Take 5 samples from population 0, 4 from pop 1
     **config.asdict())
```

**Comment by hyanwong** [comment]
It would be nice to get this change in for my Phyloseminar talk, and I think it's quite simple now that we use attrs. Should I do it, or is someone else on the case @jeromekelleher ?

**Comment by jeromekelleher** [comment]
It's in progress in #970, but got paused as I've gone through a general overhaul of demography. I'm hoping to get this done this week.

**Comment by jeromekelleher** [comment]
We should change the parse_species_tree function to be a static method of the Demography class (returning a Demography object). We should check to see if it was released to see if there's any breakage, though.
