### ISSUE TITLE
Amusing contents of pyproject.toml

### ISSUE THREAD

**Issue by molpopgen** [tskit-dev/msprime#961]
Intentional?  No such repo exists on PyPi? :)

I discovered this while trying to sleuth out how to use setuputils_scm in my own projects.

**Comment by petrelharp** [comment]
I don't see a file named `pyproject.toml` in this repository?

**Comment by molpopgen** [comment]
Aha--that's even funnier.  I was obviously goofing around at some point w/my local copy....

**Comment by jeromekelleher** [comment]
I think we need to see the contents of this file!
