### ISSUE TITLE
Documentation for Dirac and Beta coalescents

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#963]
With the final validation wrinkles for the beta and dirac models worked out, it looks like all that remains to be done is to document them.

We want

- Add a subsection/subsections to the api/simulation-models section, showing the sphinx docs. This will include a concise description of the model given in the model docstring.
- A section in tutorial/advance features giving some quick examples of these models in use.

@JereKoskela, I think you're in the best position for this?

**Comment by JereKoskela** [comment]
Yup, happy to do this, and I'll try to get it out of the way right away while I'm on a roll. Or at least to the level of an initial draft/PR. 

Two questions @jeromekelleher:

Does the model docstring just mean the `msprime.BetaCoalescent(alpha, truncation_point)` string we use to specify these models?

Is it bad practice to link to papers for details on model specification? I'll include a description directly in the docs too, but Xi-coalescents don't really lend themselves to brevity so it will necessarily be vague to some extent. I think we should at least point to the details as well, and a link would seem like a good way. The time scale of the Beta-coalescent is already a good example of this, in comparison with the one-line simplicity of the standard coalescent.

**Comment by jeromekelleher** [comment]
> Does the model docstring just mean the msprime.BetaCoalescent(alpha, truncation_point) string we use to specify these models?

It's the within-code documentation for the classes, e.g. https://github.com/tskit-dev/msprime/blob/b1d087ec1531720bcef073d4109c1075ab274775/msprime/simulations.py#L1931-L1944

You can use the DTWF as a guide for what to put in there.

Links to papers is totally fine, and quite appropriate here I think. We mainly want to emphasize how we're different to those papers and what the recombination model is.

**Comment by petrelharp** [comment]
> Links to papers is totally fine, and quite appropriate here I think

I agree, but with the caveat that often the level of detail in a paper is not quite as precise as one would like to reconstruct exactly what's being simulated/computed, so if possible try to specify precisely what's happening, with the paper mostly serving as motivation. (said another way: the docs should communicate exactly what happens to someone who's read the paper)

**Comment by jeromekelleher** [comment]
Closed in #966.
