### ISSUE TITLE
implement more mutation models

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/msprime#971]
... we have [Jukes-Cantor](https://github.com/tskit-dev/msprime/blob/8fcdee03792ad97009d2f24cf879c4c70572cc95/msprime/mutations.py#L73) but could implement many more; a good collection is implemented by [seq-gen](http://tree.bio.ed.ac.uk/software/seqgen/).

**Comment by jeromekelleher** [comment]
Superseded by more specific issues in the mutation models project.
