### ISSUE TITLE
Fix OOA example

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/msprime#981]
As described here: https://github.com/popsim-consortium/stdpopsim/pull/496 the example [in the docs](https://msprime.readthedocs.io/en/latest/tutorial.html#id1) is slightly wrong - this should be fixed and the subtle reason it was wrong should be explained.

**Comment by apragsdale** [comment]
I can have a go at fixing the model here as well. I also saw in the docs that there is a todo to include a digram of the model. Would something like this figure work here: https://github.com/apragsdale/demography/blob/master/examples/figures/gutenkunst_ooa.pdf

**Comment by jeromekelleher** [comment]
Thanks @apragsdale, that would be very helpful. An SVG version of the plot you linked to would be really helpful in the docs.

This is a serious problem though, as a bunch of papers have used the wrong version of the model. :frowning_face:

**Comment by apragsdale** [comment]
Ah, oh no. That does appear to be a more serious problem than I thought. Not sure what else to do at this point, aside from fixing it and attaching the note that is included now.. let me know if I can help with anything else with it.

**Comment by jeromekelleher** [comment]
Thanks @apragsdale, I appreciate it. I'll have a think about how to best handle this.

**Comment by petrelharp** [comment]
One check on how serious this is would be to compare theoretical coalescence time distributions for the two models on the last time period (where they might differ), using `coalescence_rate_trajectory()`.  This doesn't check how different linkage would be, though.  @apragsdale, perhaps you could calculate some of your linkage stats for the two models, and see how they differ?
