### ISSUE TITLE
no simulation happens if all samples are ancestral

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/msprime#983]
For instance:
```
ts = msprime.simulate(samples=[msprime.Sample(0, 1.0), msprime.Sample(0, 1.0)])
print(ts.tables.nodes)
# id	flags	population	individual	time	metadata
# 0	1	0	-1	1.00000000000000	
# 1	1	0	-1	1.00000000000000	
```
... so, there's no trees! Nothing has happened!  Adding a sample at time 0 gets trees.

It's a bit wierd, I know, but it'd be easy to at least check if this is going to happen and throw an error if so.

**Comment by jeromekelleher** [comment]
Should we try to detect it and handle it properly or just error?

**Comment by petrelharp** [comment]
Depends how easy handling it properly is; I haven't looked into it.

**Comment by jeromekelleher** [comment]
I don't think it'd be too bad, probably just a case of detecting the condition in C and winding the clock forward until the first sampling event. Would have to make sure that demographic events etc, are properly handled too of course.
