### ISSUE TITLE
Demographic events not interacting with multiple mergers

### ISSUE THREAD

**Issue by JereKoskela** [tskit-dev/msprime#985]
This code implements a demographic event in the Beta coalescent, and behaves strangely:
```
import msprime

n = 158
a = 1.001
gen_time = 4
N0 = 1e5
N1 = 1e4
t1 = 150 / gen_time

ts = msprime.simulate(length=2e7,
    recombination_rate=1e-8,
    mutation_rate=1e-7,
    Ne=N0,
    model=msprime.BetaCoalescent(alpha=a),
    population_configurations = [
        msprime.PopulationConfiguration(
            sample_size=n,
            initial_size=N0
        )
    ],
    demographic_events = [
        msprime.PopulationParametersChange(
            time = t1,
            initial_size = N1
        )
    ],
    num_replicates=1,
    random_seed=1)
```
Varying the value of `N0` between `N0 = 1e5`, `N0 = 1e4`, and `N0 = 1e3` results in respective runtimes of around 1 second, 4 seconds, and more than several minutes. Smaller effective population sizes should result in faster mergers, so the changes are in the wrong direction. What's more, then Beta coalescent timescale is proportional to `Ne^(alpha - 1)`, so these changes in `Ne` should hardly change anything because `(1e5)^0.001` and `(1e3)^0.001` are essentially identical.

**Comment by JereKoskela** [comment]
Come to think of it, we should probably turn off variable population size for multiple merger coalescents if that's easy to do, at least for the time being, because the interaction of variable population size and multiple mergers is not necessarily simple.

For example, a Beta-Xi-coalescent with parameter `1 < alpha < 2`, per-generation growth rate `g > 0` and time scaling `c` will experience population growth with rate `c g (alpha - 1)` on the coalescent timescale, not `c g` like a Wright-Fisher model would. The derivation of the rate is laid out in section 3 here: https://www.sciencedirect.com/science/article/abs/pii/S0025556418303523.

Migration rates between populations behave like they do in the Wright-Fisher case, even if migration rates change, so multiple populations are ok, but instantaneous population size changes will also interact with the `alpha` parameter.

I'm not immediately sure whether the Dirac-Xi-coalescent is similarly awkward.

**Comment by jeromekelleher** [comment]
Ah, good catch @JereKoskela. I think we'll need to go through the various ``change_state`` function pointers for the events, and return an error if they do something that incompatible with one of these models. Like, in ``msp_change_population_parameters`` we return an error if ``growth_rate`` != 0 and if the current model is a beta coalescent. We'll need to check this when the model starts as well, in ``msp_set_simulation_model_X``.

I'm not sure what's happening with your original problem though. The simplest thing to do is to put an ``msp_print_state`` within the ``msp_change_population_parameters`` function to see what has actually happened.

**Comment by JereKoskela** [comment]
The updates in #1059 (see also #1082) have fixed the problem I described in my post on May 3rd involving the interaction between population size, and growth, and multiple mergers. As a result, the example in the initial post above is no longer misbehaving. I suggest we close this and revisit the topic if more unexpected behaviour comes to light.
