### ISSUE TITLE
Likelihood methods missing docstring comments

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#987]
We're not getting any function documentation for e.g. https://msprime.readthedocs.io/en/latest/api.html#msprime.log_arg_likelihood

**Comment by JereKoskela** [comment]
Closed in #992

**Comment by jeromekelleher** [comment]
Just FYI @JereKoskela, this will happen automatically if you put text like

```
Closes #987
```

Either on a line in the commit message or in the PR opening text.
