### ISSUE TITLE
[Docs] Move OOA example to tutorial/demography/complete example

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#997]
We decided that the OOA example is good to keep around.

We should put a date/version number on the warning box, being precise about when the wrong version of the model was identified.

(I'd also like to have a blog-post or something about this to give people an idea of what they might expect if they *did* use the old model. We should link to this.)

**Comment by gtsambos** [comment]
also relevant to this issue from @hyanwong:

> Re: including the OOA model code, could we do some magic where we literally pull the function code for the OOA model out of stdpopsim (which we would include as a dev dependency) and bung it, formatted, into the docs? That way it is guaranteed to be QCed. I’ve just looked at [this](https://github.com/popsim-consortium/stdpopsim/blob/9997ff1466fbf03bad855578f8a4c7144bdb6d54/stdpopsim/catalog/homo_sapiens.py#L207) and it seems like we could take most of the `_ooa_3()`  function out into a sub function that returns `populations` , `population_configurations` , `migration_matrix`  and `demographic_events` , which is basically exactly the same as the code in the docs.

> `.. literalinclude:: filename` in sphinx allows a specific function from a file (in this case presumably from the stdpopsim submodule) to be taken and included from a python file, using :pyobject:

**Comment by jeromekelleher** [comment]
Yes, it's a great idea @hyanwong. What we could do simply enough is to define our OOA example in a file and then check that it's identical to the stdpopsim version (which we can import) as part of CI. We have some infrastructure in stdpopsim for comparing models. We can then literalinclude the local version in the docs, and have some faith in the fact that it's correct.
